export type CuratedGameProfile = {
  slug: string;
  searchName: string;
  shortAnswer: string;
  playPattern: string;
  goodFit: string;
  checkBeforePlay: string;
  relatedIntent: string[];
};

const PROFILES: Record<string, CuratedGameProfile> = {
  rivals: {
    slug: "rivals",
    searchName: "라이벌즈(RIVALS)",
    shortAnswer: "1대1부터 5대5까지, 먼저 5라운드를 따내는 쪽이 이기는 짧은 대전형 FPS입니다.",
    playPattern: "로비의 듀얼 패드에서 대전을 시작하고, 라운드 승리를 쌓는 흐름이 중심입니다. 플레이 중 얻는 키와 계약 보상은 장기 진행 요소로 이어집니다.",
    goodFit: "긴 성장형 RPG보다 짧게 반복되는 대전, 연승, 리더보드 경쟁을 좋아하는 이용자에게 구조가 명확합니다.",
    checkBeforePlay: "지금 플레이 인원과 최근 변화, 서버 최대 인원을 먼저 보면 매칭 규모를 가늠하기 쉽습니다. 처음에는 무기 티어보다 듀얼 패드와 5라운드 승리 구조부터 익히는 편이 빠릅니다.",
    relatedIntent: ["라이벌즈 동접", "라이벌즈 초보", "RIVALS 하는 법"],
  },
  "blox-fruits": {
    slug: "blox-fruits",
    searchName: "블록스피스(Blox Fruits)",
    shortAnswer: "검과 Blox Fruit 능력으로 캐릭터를 성장시키며 지역을 이동하고 보스를 상대하는 장기 성장형 액션 RPG입니다.",
    playPattern: "전투, 보스전, 과일 수집, 지역 탐험이 한 흐름으로 이어집니다. 과일과 상점 상태처럼 시간에 따라 달라지는 요소가 있어 누적 진행에 가깝습니다.",
    goodFit: "짧은 한 판보다 캐릭터를 오래 키우고 새 지역과 능력을 하나씩 열어 가는 플레이를 선호할 때 잘 맞습니다.",
    checkBeforePlay: "현재 플레이 인원과 최근 추이를 먼저 보고, 코드나 공략은 마지막 확인 시각이 있는 항목만 참고하는 편이 안전합니다.",
    relatedIntent: ["블록스피스 동접", "Blox Fruits 초보", "블록스피스 코드"],
  },
  "99-nights-in-the-forest": {
    slug: "99-nights-in-the-forest",
    searchName: "99 나이트 인 더 포레스트",
    shortAnswer: "친구들과 숲에 캠프를 만들고 밤을 버티는 협동 생존 게임입니다.",
    playPattern: "캠프를 함께 만들고 숲에서 생존하는 흐름이 중심입니다. 처음에는 캠프와 주변 환경을 살피고 밤을 버티는 기본 흐름부터 익히면 됩니다.",
    goodFit: "혼자 빠르게 끝내는 대전보다 친구들과 같은 공간에서 생존 상황을 같이 풀어 가는 플레이를 원할 때 맞습니다.",
    checkBeforePlay: "현재 플레이 인원과 서버 최대 인원을 먼저 확인하세요. 세부 생존 루트가 필요하면 해당 게임 공략을 함께 보는 편이 좋습니다.",
    relatedIntent: ["99 나이트 공략", "99 나이트 초보", "99 나이트 동접"],
  },
  "murder-mystery-2": {
    slug: "murder-mystery-2",
    searchName: "머더 미스터리 2(Murder Mystery 2)",
    shortAnswer: "Innocent, Sheriff, Murderer 세 역할이 서로 다른 목표로 움직이는 라운드형 추리·생존 게임입니다.",
    playPattern: "Innocent는 살아남으며 정체를 추리하고, Sheriff는 Murderer를 제압할 수 있는 무기를 맡고, Murderer는 다른 플레이어를 제거합니다.",
    goodFit: "정해진 빌드보다 역할 추리, 관찰, 짧은 라운드의 긴장감을 좋아하는 이용자에게 구조가 분명합니다.",
    checkBeforePlay: "서버 최대 인원과 현재 인원을 같이 보면 한 서버에서 느끼는 플레이 규모를 가늠하기 쉽습니다.",
    relatedIntent: ["머더 미스터리 2 역할", "MM2 초보", "Murder Mystery 2 동접"],
  },
  "dress-to-impress": {
    slug: "dress-to-impress",
    searchName: "드레스 투 임프레스(Dress To Impress)",
    shortAnswer: "주제에 맞춰 코디를 완성하고 런웨이에서 보여 준 뒤 서로 투표하는 라운드형 드레스업 게임입니다.",
    playPattern: "코디를 만들고, 런웨이에서 포즈를 사용하고, 다른 플레이어의 의상에 투표하는 순서가 기본 흐름입니다.",
    goodFit: "전투나 파밍보다 꾸미기, 주제 해석, 다른 이용자와의 평가·경쟁을 즐기고 싶을 때 잘 맞습니다.",
    checkBeforePlay: "현재 플레이 인원과 최근 업데이트 시각을 먼저 보세요. 테마가 바뀔 때마다 정답 코디가 달라질 수 있으니 그 라운드의 주제와 투표 흐름을 먼저 보는 편이 좋습니다.",
    relatedIntent: ["드레스 투 임프레스 초보", "DTI 하는 법", "Dress To Impress 동접"],
  },
  "tower-defense-simulator": {
    slug: "tower-defense-simulator",
    searchName: "타워 디펜스 시뮬레이터(TDS)",
    shortAnswer: "유닛을 배치해 몰려오는 좀비를 막고 더 강한 보스에 도전하는 협동 타워 디펜스 게임입니다.",
    playPattern: "유닛 배치와 방어가 중심이고, 진행하면서 새로운 유닛을 해제하는 장기 성장 요소가 이어집니다.",
    goodFit: "직접 조준하는 FPS보다 배치 순서와 팀 구성을 고민하는 전략형 플레이를 선호할 때 맞습니다.",
    checkBeforePlay: "처음 시작한다면 현재 플레이 인원을 본 뒤 Farm 운영과 사거리 배치, 중후반 자원 전환 순서를 함께 확인하면 흐름을 잡기 쉽습니다.",
    relatedIntent: ["TDS 초보", "타워 디펜스 시뮬레이터 공략", "TDS 동접"],
  },
  "adopt-me": {
    slug: "adopt-me",
    searchName: "입양하세요!(Adopt Me!)",
    shortAnswer: "펫을 입양하고 키우며 수집·거래하고, 집 꾸미기와 역할놀이를 함께 즐기는 소셜 게임입니다.",
    playPattern: "펫 수집과 육성, 거래, 하우징, 친구와의 역할놀이가 한 흐름 안에 묶여 있습니다.",
    goodFit: "승패가 분명한 대전보다 수집과 꾸미기, 친구와 오래 머무는 소셜 플레이를 선호할 때 맞습니다.",
    checkBeforePlay: "거래를 시작하기 전에는 원하는 펫과 교환 조건을 차분히 확인하세요. 펫 가치와 거래 시세는 계속 바뀔 수 있어 현재 게임 상황을 함께 보는 편이 좋습니다.",
    relatedIntent: ["Adopt Me 동접", "입양하세요 펫", "Adopt Me 초보"],
  },
  "grow-a-garden": {
    slug: "grow-a-garden",
    searchName: "그로우 어 가든(Grow a Garden)",
    shortAnswer: "씨앗을 사고 심은 뒤 작물을 수확해 수익을 늘리는 농장형 시뮬레이션·타이쿤 게임입니다.",
    playPattern: "씨앗 구매 → 심기 → 성장 대기 → 수확의 반복 구조이며, 접속하지 않은 동안에도 정원이 성장할 수 있습니다.",
    goodFit: "빠른 승패보다 천천히 쌓이는 성장과 다시 접속했을 때 달라진 상태를 보는 플레이를 좋아할 때 잘 맞습니다.",
    checkBeforePlay: "상점 재입고나 씨앗 상태처럼 시간에 따라 바뀌는 요소는 확인 시각과 함께 보는 편이 좋습니다.",
    relatedIntent: ["그로우 어 가든 초보", "Grow a Garden 동접", "그로우 어 가든 하는 법"],
  },
  jailbreak: {
    slug: "jailbreak",
    searchName: "제일브레이크(Jailbreak)",
    shortAnswer: "범죄자와 경찰 역할을 중심으로 강도, 체포, 차량 추격이 이어지는 오픈월드 액션 게임입니다.",
    playPattern: "범죄자는 강도를 계획하고 경찰은 이를 막고 체포하는 역할을 맡습니다. 차량 이동과 추격이 플레이 흐름의 큰 비중을 차지합니다.",
    goodFit: "정해진 짧은 라운드보다 넓은 공간에서 역할을 고르고 친구와 상황을 만들어 가는 액션을 선호할 때 맞습니다.",
    checkBeforePlay: "현재 인원과 최근 업데이트 감지 시점을 함께 보되, 실제 패치 내용은 단순 업데이트 시각 감지와 구분해서 봐야 합니다.",
    relatedIntent: ["제일브레이크 동접", "Jailbreak 초보", "제일브레이크 업데이트"],
  },
  brookhaven: {
    slug: "brookhaven",
    searchName: "브룩헤이븐(Brookhaven)",
    shortAnswer: "집과 차량을 이용하며 도시에서 자유롭게 역할놀이를 하는 소셜 RP 게임입니다.",
    playPattern: "정해진 전투 목표보다 집, 차량, 이동, 상황극처럼 이용자가 직접 놀이 상황을 만드는 자유도가 중심입니다.",
    goodFit: "경쟁이나 파밍보다 친구들과 역할을 정하고 도시 공간에서 자유롭게 노는 플레이를 원할 때 맞습니다.",
    checkBeforePlay: "한국 리전 이용 제한이 표시되면 현재 접속 가능 여부부터 확인하세요. 플레이 인원은 마지막 정상 관측 시점과 함께 보는 편이 좋습니다.",
    relatedIntent: ["브룩헤이븐 한국", "Brookhaven 동접", "브룩헤이븐 하는 법"],
  },
  "steal-an-egg": {
    slug: "steal-an-egg",
    searchName: "스틸 언 에그(Steal An Egg)",
    shortAnswer: "알을 모아 부화시키고 희귀 펫을 늘리면서 다른 플레이어의 알도 노리는 수집·약탈형 게임입니다.",
    playPattern: "알 확보 → 부화 → 펫 수집 → 수익 확보 → 러닝머신·기지 업그레이드 → 다른 플레이어의 알을 노리는 흐름이 이어집니다.",
    goodFit: "펫 수집과 기지 성장에 경쟁 플레이가 섞인 게임, 짧게 접속해도 수집 목표가 계속 남는 구조를 좋아할 때 맞습니다.",
    checkBeforePlay: "처음에는 속도와 기지 성장을 안정시키면서 어떤 알과 펫을 모을지 확인하세요. 다른 플레이어 기지를 노릴 때는 자신의 진행 상태도 함께 챙기는 편이 좋습니다.",
    relatedIntent: ["스틸 언 에그 공략", "Steal An Egg 펫", "Steal An Egg 동접"],
  },
  "jujutsu-shenanigans": {
    slug: "jujutsu-shenanigans",
    searchName: "주술 셰니건즈(Jujutsu Shenanigans)",
    shortAnswer: "근접 콤보, 대시, 방어, 스킬과 각성을 섞어 싸우는 파괴형 배틀그라운드 액션 게임입니다.",
    playPattern: "기본 공격과 1~4번 스킬을 연결하고 Q 대시로 거리를 조절하며 F 방어와 G 각성을 상황에 맞게 사용하는 전투가 중심입니다.",
    goodFit: "정해진 스테이지 공략보다 다른 플레이어와 계속 부딪치며 콤보와 이동 타이밍을 익히는 PvP를 좋아할 때 맞습니다.",
    checkBeforePlay: "처음에는 모든 기술을 외우기보다 대시·방어·기본 콤보부터 익히세요. 기절 상태에서 Q를 탈출에 쓸 수 있다는 점도 초반 교전에 도움이 됩니다.",
    relatedIntent: ["주술 셰니건즈 조작법", "Jujutsu Shenanigans 초보", "주술 셰니건즈 동접"],
  },
  "steal-a-brainrot": {
    slug: "steal-a-brainrot",
    searchName: "스틸 어 브레인롯(Steal a Brainrot)",
    shortAnswer: "Brainrot을 사고 수익을 만들면서 다른 플레이어의 Brainrot을 훔치고 Rebirth를 반복하는 타이쿤형 게임입니다.",
    playPattern: "Brainrot 구매 → 수익 생성 → 다른 플레이어에게서 훔치기 → 장비 활용 → Rebirth로 다시 성장하는 반복 구조입니다.",
    goodFit: "가만히 키우는 타이쿤보다 다른 플레이어의 자원을 노리는 경쟁과 장난 요소가 섞인 성장 게임을 원할 때 맞습니다.",
    checkBeforePlay: "초반에는 수익을 꾸준히 만들 수 있는 상태를 먼저 확보하고, 훔치기에만 집중해 자신의 성장 흐름이 끊기지 않도록 관리하는 편이 좋습니다.",
    relatedIntent: ["스틸 어 브레인롯 공략", "Steal a Brainrot 초보", "브레인롯 동접"],
  },
  "fish-it": {
    slug: "fish-it",
    searchName: "피쉬 잇(Fish It!)",
    shortAnswer: "낚시로 다양한 물고기와 변형을 모으고 친구와 함께 바다를 탐험하는 수집형 낚시 시뮬레이션 게임입니다.",
    playPattern: "입력을 눌러 낚시 힘을 모은 뒤 빠르게 입력해 물고기를 잡고, 수집을 늘리거나 배를 타고 다른 지역을 탐험하는 흐름입니다.",
    goodFit: "빠른 전투보다 반복 수집, 희귀 결과 찾기, 친구와 느긋하게 탐험하는 플레이를 오래 이어 가고 싶을 때 잘 맞습니다.",
    checkBeforePlay: "처음에는 낚시 입력 방식을 익히고 현재 지역에서 잡히는 물고기를 모으세요. 수집이 익숙해진 뒤 다른 섬과 변형을 찾아가는 편이 진행을 이해하기 쉽습니다.",
    relatedIntent: ["피쉬 잇 낚시", "Fish It 초보", "피쉬 잇 동접"],
  },
  "catalog-avatar-creator": {
    slug: "catalog-avatar-creator",
    searchName: "카탈로그 아바타 크리에이터(Catalog Avatar Creator)",
    shortAnswer: "Roblox 카탈로그 아이템을 자유롭게 착용해 보고 코디를 만들고 저장할 수 있는 아바타 꾸미기 도구형 경험입니다.",
    playPattern: "아이템 검색 → 착용 조합 확인 → 커뮤니티 코디 탐색 → 아바타 저장으로 이어지며, 마음에 드는 아이템은 게임 안에서 구매할 수도 있습니다.",
    goodFit: "게임 승패보다 Roblox 아바타 코디를 미리 시험해 보고 여러 헤어·액세서리 조합을 비교하는 데 시간을 쓰고 싶을 때 맞습니다.",
    checkBeforePlay: "구매 전에는 코디를 충분히 착용해 보고 실제 Roblox 인벤토리에 필요한 아이템인지 확인하세요. 저장 기능을 이용하면 여러 조합을 비교하기 편합니다.",
    relatedIntent: ["카탈로그 아바타 크리에이터 코디", "Catalog Avatar Creator 사용법", "아바타 크리에이터 동접"],
  },
  evade: {
    slug: "evade",
    searchName: "이베이드(Evade)",
    shortAnswer: "빠르게 이동하고 장애물을 넘으며 Nextbot에게서 살아남는 파쿠르 중심 멀티플레이 생존 게임입니다.",
    playPattern: "맵을 계속 이동하며 Nextbot과 거리를 벌리고, 상호작용·웅크리기·아이템 사용을 섞어 생존 시간을 늘리는 흐름이 중심입니다.",
    goodFit: "무기를 맞추는 전투보다 빠른 이동, 도주 경로 선택, 아슬아슬하게 추격을 피하는 플레이를 좋아할 때 잘 맞습니다.",
    checkBeforePlay: "큰 소리와 번쩍이는 화면이 나올 수 있습니다. 처음에는 E 상호작용과 C/Ctrl 웅크리기, M 메뉴 등 기본 입력부터 확인하는 편이 좋습니다.",
    relatedIntent: ["이베이드 조작법", "Evade 초보", "이베이드 동접"],
  },
  "tower-of-hell": {
    slug: "tower-of-hell",
    searchName: "타워 오브 헬(Tower of Hell)",
    shortAnswer: "체크포인트가 없는 무작위 타워형 오비를 떨어지지 않고 끝까지 올라가는 클래식 플랫폼 게임입니다.",
    playPattern: "매 라운드 달라지는 장애물을 차례로 통과해 위로 올라가며, 실수로 떨어지면 아래 구간부터 다시 도전하는 반복 구조입니다.",
    goodFit: "성장 수치보다 직접 조작 실력을 반복해서 다듬고 어려운 점프 구간을 성공했을 때의 성취감을 원하는 이용자에게 맞습니다.",
    checkBeforePlay: "체크포인트가 없으므로 초반에는 속도보다 안정적으로 구간을 통과하는 데 집중하세요. 같은 장애물에서도 카메라 각도와 이동 타이밍이 중요합니다.",
    relatedIntent: ["타워 오브 헬 공략", "Tower of Hell 초보", "타워오브헬 동접"],
  },
  "sols-rng": {
    slug: "sols-rng",
    searchName: "솔스 RNG(Sol's RNG)",
    shortAnswer: "Roll을 반복해 희귀한 오라를 모으고, 수집한 오라로 장비를 제작하며 행운을 높이는 RNG 수집 게임입니다.",
    playPattern: "Roll로 오라 획득 → 수집 결과 확인 → 오라를 활용한 장비 제작 → 포션 등으로 행운 강화 → 더 희귀한 결과 도전이 이어집니다.",
    goodFit: "조작 난도보다 확률형 수집과 희귀 결과를 오래 노리는 과정, 컬렉션을 채우는 반복 플레이를 좋아할 때 맞습니다.",
    checkBeforePlay: "처음에는 Roll과 인벤토리, 제작 흐름을 먼저 익히세요. 희귀 오라만 기다리기보다 어떤 재료가 장비 제작에 필요한지도 함께 보면 진행이 덜 막힙니다.",
    relatedIntent: ["솔스 RNG 오라", "Sol's RNG 초보", "솔 RNG 동접"],
  },
  "dandys-world": {
    slug: "dandys-world",
    searchName: "댄디스 월드(Dandy's World)",
    shortAnswer: "여러 Toon이 협력해 기계를 완료하고 Gardenview Center의 더 깊은 구역으로 내려가는 멀티플레이 생존 게임입니다.",
    playPattern: "팀 구성 → 기계 완료 → 다음 구역 이동을 반복하면서 Toon을 모으고 Trinket으로 자신의 플레이 방식을 조정하는 흐름입니다.",
    goodFit: "혼자 전투를 밀어붙이기보다 역할이 다른 캐릭터를 고르고 팀원과 목표를 나눠 진행하는 협동 생존을 좋아할 때 맞습니다.",
    checkBeforePlay: "현재 Alpha 단계라 게임이 바뀔 수 있고 번쩍이는 조명이 포함될 수 있습니다. 첫 판에서는 Toon의 능력보다 팀과 함께 기계를 완료하는 기본 목표부터 익히세요.",
    relatedIntent: ["댄디스 월드 초보", "Dandy's World 공략", "댄디스 월드 동접"],
  },
  bedwars: {
    slug: "bedwars",
    searchName: "베드워즈(BedWars)",
    shortAnswer: "팀 침대를 지키고 자원으로 장비를 강화한 뒤 상대 침대를 파괴해 모든 적을 제거하는 팀 대전 게임입니다.",
    playPattern: "자원 수집 → 장비·팀 업그레이드 → 침대 방어 → 상대 기지 공격 → 침대 파괴 후 최종 제거의 흐름으로 경기가 진행됩니다.",
    goodFit: "단순 PvP보다 자원 관리, 기지 방어, 공격 타이밍과 팀 역할 분담을 함께 고민하는 경쟁 게임을 원할 때 잘 맞습니다.",
    checkBeforePlay: "자신의 침대가 사라지면 다시 부활할 수 없습니다. 초반에는 장비 구매만 보지 말고 침대 방어와 팀 자원 상황을 함께 확인하는 편이 좋습니다.",
    relatedIntent: ["베드워즈 공략", "BedWars 초보", "베드워즈 동접"],
  },
  piggy: {
    slug: "piggy",
    searchName: "피기(Piggy)",
    shortAnswer: "Piggy를 피해 살아남으면서 맵의 아이템을 찾아 사용하고 탈출 경로와 이야기의 단서를 풀어 가는 생존 게임입니다.",
    playPattern: "주변 탐색 → 필요한 아이템 획득 → 맞는 장소에 사용 → Piggy를 피하며 탈출 조건 진행의 순서로 한 판의 목표가 이어집니다.",
    goodFit: "빠른 전투보다 추격을 피하면서 맵을 기억하고 아이템 용도를 맞춰 탈출하는 퍼즐·생존 흐름을 좋아할 때 잘 맞습니다.",
    checkBeforePlay: "처음에는 발견한 아이템을 어디에 쓰는지 기억하는 데 집중하세요. PC에서는 클릭으로 아이템을 사용하고 Ctrl로 웅크리기나 함정 배치가 가능합니다.",
    relatedIntent: ["로블록스 피기 공략", "Piggy 초보", "피기 동접"],
  },
  "welcome-to-bloxburg": {
    slug: "welcome-to-bloxburg",
    searchName: "블록스버그(Welcome to Bloxburg)",
    shortAnswer: "집을 짓고 꾸미고 직업으로 돈을 벌며 차량과 생활 스킬, 친구와의 역할놀이를 즐기는 생활형 시뮬레이션 게임입니다.",
    playPattern: "집 건축·꾸미기, 직업으로 수입 얻기, 차량 이동, 생활 스킬 성장과 친구 역할놀이를 원하는 순서대로 이어 가는 자유로운 구조입니다.",
    goodFit: "정해진 승리 조건보다 내 집과 캐릭터를 오래 꾸미고 돈을 모아 생활 공간을 확장하는 샌드박스형 플레이를 좋아할 때 맞습니다.",
    checkBeforePlay: "처음에는 직업으로 기본 수입을 만들고 필요한 집과 차량 목표를 정하면 진행이 쉬워집니다. 요리 같은 생활 스킬도 플레이하면서 함께 성장시킬 수 있습니다.",
    relatedIntent: ["블록스버그 집짓기", "Welcome to Bloxburg 초보", "블록스버그 동접"],
  },
};

export function getCuratedGameProfile(slug: string) {
  return PROFILES[slug] ?? null;
}
export function curatedGameSlugs() {
  return Object.keys(PROFILES);
}
