import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {applyCompareDecision,validateCompareDecision} from './compare-decision-integrator.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'compare-decision-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'assets'));fs.writeFileSync(path.join(root,'assets/app.js'),'console.log("base")\n');fs.writeFileSync(path.join(root,'assets/site.css'),'body{}\n');return root}
test('compare decision integrator changes only shared app/css and is idempotent',t=>{const root=fixture(t);assert.deepEqual(applyCompareDecision(root).changedFiles,['assets/app.js','assets/site.css']);const app=fs.readFileSync(path.join(root,'assets/app.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets/site.css'),'utf8');assert.match(app,/v11\.52 compare decision: start/);assert.match(css,/v11\.52 compare decision css: start/);assert.match(app,/v52VerifiedSummary/);assert.match(app,/v52VerifiedCard/);assert.match(app,/v52CompareDirectory/);assert.match(app,/v52CompareBasis/);assert.match(app,/v52CompareCaution/);assert.match(app,/v52CompareRelated/);assert.match(css,/v52-verified-summary/);assert.match(css,/data-v52-verified-card/);assert.match(css,/data-v52-compare-directory/);assert.match(css,/data-v52-compare-basis/);assert.match(css,/data-v52-caution-item/);assert.match(css,/data-v52-compare-related/);assert.deepEqual(applyCompareDecision(root).changedFiles,[]);assert.deepEqual(validateCompareDecision(root),{compareDecision:true});});
test('compare decision integrator rejects relative roots',()=>assert.throws(()=>applyCompareDecision('relative'),/absolute/));
test('v11.52 RC generation owns compare decision application',()=>{const code=fs.readFileSync(path.join(here,'run-generate-v11-52-release-candidate.mjs'),'utf8');assert.ok(code.includes("import {applyCompareDecision} from './compare-decision-integrator.mjs';"));const browser=code.indexOf('applyBrowserRegressionFix(out);'),compare=code.indexOf('applyCompareDecision(out);'),ready=code.indexOf('const compareDecisionUx=true;');assert.ok(browser>0&&compare>browser&&ready>compare);assert.ok(code.includes('compareDecisionUx:true'));});
test('v11.52 RC validation checks compare decision without repairing it',()=>{const code=fs.readFileSync(path.join(here,'run-validate-v11-52-release-candidate.mjs'),'utf8');assert.ok(code.includes("import {validateCompareDecision} from './compare-decision-integrator.mjs';"));assert.ok(code.includes('validateCompareDecision(out)'));assert.ok(!code.includes('applyCompareDecision('));assert.ok(code.includes("err.push(`compare decision assets: ${error.message}`)"));});
