import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
import {PRIORITY_BRAND_NAMES,CURATED_COMPARE_NAMES,GUIDES,TOOLS} from './content.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));
const repo=path.resolve(here,'..');
const out=path.join(repo,'docs/franchise-ssg-preview');
const BASE=(process.env.SSG_BASE_PATH ?? '/pm-lab/franchise-ssg-preview').replace(/\/$/,'');
const SITE=(process.env.SSG_SITE_URL ?? `https://5ggul.github.io${BASE}`).replace(/\/$/,'');
const PREVIEW=process.env.SSG_PREVIEW_MODE!=='false';
const today='2026-09-07';

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const won=n=>n==null?'정보 없음':`${Math.round(n).toLocaleString('ko-KR')}만원`;
const num=n=>n==null?'정보 없음':Math.round(n).toLocaleString('ko-KR');
const pct=n=>n==null||Number.isNaN(Number(n))?'정보 없음':`${Number(n).toFixed(1)}%`;
const url=p=>`${BASE}${p==='/'?'':p}`.replace(/\/+/g,'/');
const canonical=p=>`${SITE}${p==='/'?'':p}`;

async function loadClassic(file,expr){
 const code=await fs.readFile(file,'utf8');const context={console};vm.createContext(context);vm.runInContext(`${code}\n;globalThis.__EXPORT__=${expr};`,context);return context.__EXPORT__;
}
const data=await loadClassic(path.join(repo,'docs/franchise-data-preview/data-final.js'),'{categories,brands,areas,guides}');
let official={status:'MISSING',promotion:{allowPreviewOverlay:false},records:[]};
try{official=await loadClassic(path.join(repo,'docs/franchise-data-preview/official-brand-data-final.js'),'globalThis.OFFICIAL_BRAND_DATA')}catch{}
if(!PREVIEW && !(official?.promotion?.allowPreviewOverlay && official?.records?.length)) throw new Error('Production generation blocked: official snapshot is not promotion-ready.');

const categories=data.categories,allBrands=data.brands,areas=data.areas;
const byName=new Map(allBrands.map(b=>[b.name,b]));
const brands=PRIORITY_BRAND_NAMES.map(n=>byName.get(n)).filter(Boolean);
const missingPriority=PRIORITY_BRAND_NAMES.filter(n=>!byName.has(n));
if(missingPriority.length) throw new Error(`Priority brands missing: ${missingPriority.join(', ')}`);
const catBrands=slug=>brands.filter(b=>b.categorySlug===slug);
const growth=b=>b.lastStores?((b.stores-b.lastStores)/b.lastStores*100):null;
const median=a=>{const x=[...a].filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
const priorityCats=[...new Set(brands.map(b=>b.categorySlug))];
const subpageBrands=brands.slice(0,20),priorityAreas=areas.slice(0,12);
await fs.rm(out,{recursive:true,force:true});await fs.mkdir(out,{recursive:true});

function jsonLd(items){return items.map(x=>`<script type="application/ld+json">${JSON.stringify(x).replace(/<\//g,'<\\/')}</script>`).join('\n')}
function breadcrumbs(items){return {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((x,i)=>({"@type":"ListItem",position:i+1,name:x.name,item:canonical(x.path)}))}}
function faqSchema(faqs){return {"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}}
function header(){return `<header class="site-header"><div class="shell header-inner"><a class="logo" href="${url('/')}">창업데이터랩</a><nav><a href="${url('/brands/')}">브랜드</a><a href="${url('/rankings/cafe/')}">업종 정렬</a><a href="${url('/tools/')}">계산기</a><a href="${url('/guides/')}">가이드</a><a href="${url('/methodology/')}">계산 기준</a></nav><button class="nav-toggle" aria-label="메뉴 열기">메뉴</button></div></header>`}
function footer(){return `<footer class="site-footer"><div class="shell footer-grid"><div><b>창업데이터랩</b><p>공개 데이터와 사용자가 입력한 비용을 분리해 보는 프랜차이즈 비교 도구입니다.</p></div><div><a href="${url('/about/')}">서비스 소개</a><a href="${url('/sources/')}">데이터 출처</a><a href="${url('/methodology/')}">계산 기준</a><a href="${url('/disclaimer/')}">이용 전 확인사항</a></div><div><a href="${url('/privacy/')}">개인정보처리방침</a><a href="${url('/terms/')}">이용약관</a><a href="${url('/contact/')}">문의</a></div></div><div class="shell footer-note">공식 가맹본부·정부기관 사이트가 아닙니다. 계약 전 최신 정보공개서와 실제 계약조건을 확인하세요.</div></footer>`}
function layout({path:pagePath,title,description,main,schema=[]}){
 const robots=PREVIEW?'<meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><meta name="googlebot" content="noindex,nofollow,noarchive,nosnippet"><meta name="bingbot" content="noindex,nofollow,noarchive,nosnippet">':'<meta name="robots" content="index,follow">';
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">${robots}<title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical(pagePath))}"><link rel="stylesheet" href="${url('/assets/site.css')}">${jsonLd(schema)}</head><body>${PREVIEW?'<div class="preview-bar">외부 검수용 SSG 프리뷰 · 검색엔진 제외(noindex) · 합성 수치는 정식 공개 전 공식 스냅샷으로 교체</div>':''}${header()}<main id="main">${main}</main>${footer()}<script src="${url('/assets/app.js')}" defer></script></body></html>`
}
async function writePage(pagePath,html){const dir=pagePath==='/'?out:path.join(out,pagePath.replace(/^\//,'').replace(/\/$/,''));await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'index.html'),html,'utf8');}
function crumbs(items){return `<nav class="crumbs" aria-label="현재 위치">${items.map((x,i)=>i===items.length-1?`<span>${esc(x.name)}</span>`:`<a href="${url(x.path)}">${esc(x.name)}</a>`).join('<i>›</i>')}</nav>`}
function sourceBox(){return `<aside class="source-box"><b>현재 데이터 상태</b><p>이 SSG 프리뷰의 비용·점포·매출 수치는 화면과 문서 구조 검수용 합성값입니다. 정식 도메인에서는 공정거래위원회 정보공개서·공공데이터 스냅샷 검증을 통과한 값만 색인합니다.</p><p><b>누락값은 0으로 바꾸지 않습니다.</b> 값이 없으면 “정보 없음”으로 표시합니다.</p></aside>`}
function faqHtml(faqs){return `<section class="block"><h2>자주 묻는 질문</h2><div class="faq">${faqs.map(f=>`<details><summary>${esc(f.question)}</summary><p>${esc(f.answer)}</p></details>`).join('')}</div></section>`}
function card(b){return `<article class="brand-card" data-name="${esc(b.name.toLowerCase())}" data-cat="${esc(b.categorySlug)}"><a href="${url(`/brands/${b.slug}/`)}"><h3>${esc(b.name)}</h3><p>${esc(b.category)}</p><dl><div><dt>공개비용</dt><dd>${won(b.cost)}</dd></div><div><dt>가맹점</dt><dd>${num(b.stores)}개</dd></div><div><dt>전년 증감</dt><dd>${growth(b)==null?'정보 없음':`${growth(b)>=0?'+':''}${pct(growth(b))}`}</dd></div></dl></a></article>`}

const homeMain=`<section class="hero"><div class="shell"><h1>프랜차이즈 창업비용과 가맹점 현황 비교</h1><p>브랜드 공개비용과 내가 입력하는 임대보증금·권리금·월세·인건비를 섞지 않고 봅니다.</p><form class="search-form" action="${url('/brands/')}" method="get"><label for="homeSearch">브랜드 찾기</label><div><input id="homeSearch" name="q" placeholder="예: 메가MGC커피, 교촌치킨"><button>검색</button></div></form></div></section><div class="shell"><section class="block"><h2>먼저 볼 페이지</h2><div class="link-cards"><a href="${url('/brands/')}"><b>브랜드 42개</b><span>공개비용·점포·증감 확인</span></a><a href="${url('/tools/startup-cost/')}"><b>창업비용 계산기</b><span>임대·권리금·운전자금 추가</span></a><a href="${url('/guides/')}"><b>가이드 15편</b><span>정보공개서와 비용 항목 읽는 법</span></a></div></section><section class="block"><h2>주요 브랜드</h2><div class="brand-grid">${brands.slice(0,12).map(card).join('')}</div></section><section class="block"><h2>업종별 가맹점 수 정렬</h2><div class="chips">${priorityCats.map(c=>`<a href="${url(`/rankings/${c}/`)}">${esc(categories[c].name)}</a>`).join('')}</div></section>${sourceBox()}</div>`;
await writePage('/',layout({path:'/',title:'프랜차이즈 창업비용·가맹점 현황 비교 | 창업데이터랩',description:'프랜차이즈 공개 창업비용, 가맹점 수, 점포 증감과 사용자가 입력한 임대·운영비를 분리해 비교합니다.',main:homeMain,schema:[{"@context":"https://schema.org","@type":"WebSite",name:'창업데이터랩',url:canonical('/'),potentialAction:{"@type":"SearchAction",target:`${canonical('/brands/')}?q={search_term_string}`,'query-input':'required name=search_term_string'}}]}));

const brandsMain=`<div class="shell page"><div class="page-head">${crumbs([{name:'홈',path:'/'},{name:'브랜드'}])}<h1>프랜차이즈 브랜드 42개</h1><p>검색용 정식 구조를 검수하기 위해 우선 42개 브랜드만 정적 HTML로 출력했습니다. 정식 공개는 공식 데이터 검증을 통과한 브랜드만 허용합니다.</p></div><div class="filters"><label>브랜드 검색<input id="brandFilter" type="search" placeholder="브랜드명"></label><label>업종<select id="categoryFilter"><option value="all">전체</option>${priorityCats.map(c=>`<option value="${c}">${esc(categories[c].name)}</option>`).join('')}</select></label></div><div id="brandGrid" class="brand-grid">${brands.map(card).join('')}</div>${sourceBox()}</div>`;
await writePage('/brands/',layout({path:'/brands/',title:'프랜차이즈 브랜드 창업비용·가맹점 현황 목록 | 창업데이터랩',description:'프랜차이즈 브랜드의 공개 창업비용, 가맹점 수와 전년 증감을 업종별로 찾습니다.',main:brandsMain,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'브랜드',path:'/brands/'}])]}));

const brandFaq=b=>[
 {question:`${b.name} 공개 창업비용에 임대보증금이 포함되나요?`,answer:'현재 공개 브랜드 비용과 점포 임대보증금은 별도로 표시합니다. 실제 포함 범위는 최신 정보공개서와 계약조건을 확인해야 합니다.'},
 {question:`${b.name} 가맹점 수가 많으면 수익도 높은가요?`,answer:'아닙니다. 점포 수는 브랜드 규모를 보여줄 뿐 개별 점포 수익을 의미하지 않습니다.'},
 {question:`${b.name} 창업비용에서 빠질 수 있는 항목은 무엇인가요?`,answer:'임대보증금, 권리금, 일부 별도공사, 운전자금, 대출이자 등 점포별 비용은 별도로 발생할 수 있습니다.'},
 {question:`${b.name} 숫자는 어떤 기준일을 사용하나요?`,answer:'현재 SSG 프리뷰는 구조 검수용 합성값입니다. 정식 페이지에서는 공식 스냅샷의 기준연도와 수집일을 숫자 바로 옆에 표시합니다.'},
 {question:`${b.name}와 같은 업종은 어떻게 비교하나요?`,answer:'동일 기준연도의 공개비용·점포 수·증감과 업종 중앙값을 같은 표에 놓고 비교합니다.'},
 {question:'누락된 비용을 0원으로 표시하나요?',answer:'아닙니다. 정보 없음과 실제 0원은 다르므로 누락값은 “정보 없음”으로 표시합니다.'}
];
for(const b of brands){
 const peers=catBrands(b.categorySlug),medCost=median(peers.map(x=>x.cost)),medStores=median(peers.map(x=>x.stores)),faqs=brandFaq(b),yoy=growth(b);
 const main=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'브랜드',path:'/brands/'},{name:b.name}])}<article><div class="page-head"><h1>${esc(b.name)} 창업비용과 가맹점 현황</h1><p class="answer"><b>${esc(b.name)} 공개 창업비용은 ${won(b.cost)}입니다.</b> 현재 프리뷰 수치이며 임대보증금·권리금·운전자금은 별도입니다.</p></div><section class="metric-row"><div><span>공개 창업비용</span><b>${won(b.cost)}</b></div><div><span>가맹점 수</span><b>${num(b.stores)}개</b></div><div><span>전년 증감</span><b>${yoy==null?'정보 없음':`${yoy>=0?'+':''}${pct(yoy)}`}</b></div></section><section class="block"><h2>공개 창업비용 구성</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>금액</th><th>확인할 점</th></tr></thead><tbody><tr><td>가맹비</td><td>${won(b.fee)}</td><td>계약상 반환 여부 확인</td></tr><tr><td>교육비</td><td>${won(b.education)}</td><td>교육 인원·범위 확인</td></tr><tr><td>가맹 보증금</td><td>${won(b.deposit)}</td><td>임대보증금과 다름</td></tr><tr><td>인테리어</td><td>${won(b.interior)}</td><td>기준면적·별도공사 확인</td></tr><tr><td>기타</td><td>${won(b.other)}</td><td>세부 정의 확인</td></tr><tr class="strong"><td>합계</td><td>${won(b.cost)}</td><td>점포별 비용 제외</td></tr></tbody></table></div><p class="note">빠질 수 있는 항목: 임대보증금, 권리금, 별도 전기·냉난방·철거 공사, 운전자금, 대출이자.</p></section><section class="block"><h2>가맹점 수와 전년 변화</h2><div class="table-wrap"><table><tbody><tr><th>현재 가맹점</th><td>${num(b.stores)}개</td></tr><tr><th>이전 기준 가맹점</th><td>${num(b.lastStores)}개</td></tr><tr><th>단순 증감</th><td>${yoy==null?'정보 없음':`${yoy>=0?'+':''}${pct(yoy)}`}</td></tr><tr><th>신규·종료·해지</th><td>정보 없음 · 정식 공정위 스냅샷 연결 후 표시</td></tr></tbody></table></div><p class="note">가맹점 수가 많거나 증가했다고 수익성이 높다고 판단하지 않습니다.</p></section><section class="block"><h2>${esc(b.category)} 업종 중앙값과 비교</h2><p>${peers.length}개 우선 검수 브랜드 기준 공개비용 중앙값은 ${won(medCost)}, 가맹점 수 중앙값은 ${num(medStores)}개입니다.</p><div class="compare-strip"><div><span>${esc(b.name)}</span><b>${won(b.cost)}</b></div><div><span>업종 중앙값</span><b>${won(medCost)}</b></div></div></section><section class="block actions"><a class="button" href="${url(`/tools/startup-cost/?brand=${encodeURIComponent(b.slug)}`)}">내 임대조건으로 총 필요자금 계산</a>${subpageBrands.some(x=>x.slug===b.slug)?`<a href="${url(`/brands/${b.slug}/cost/`)}">창업비용만 자세히 보기</a><a href="${url(`/brands/${b.slug}/stores/`)}">점포 변화만 자세히 보기</a>`:''}</section>${faqHtml(faqs)}${sourceBox()}<p class="disclaimer">이 페이지는 투자·가맹 권유가 아니며 수익을 보장하지 않습니다. 계약 전 최신 정보공개서와 실제 계약서를 확인하세요.</p></article></div>`;
 const pagePath=`/brands/${b.slug}/`;await writePage(pagePath,layout({path:pagePath,title:`${b.name} 창업비용·가맹점 수 | 창업데이터랩`,description:`${b.name} 공개 창업비용, 가맹점 수, 전년 증감과 같은 업종 중앙값을 분리해서 확인합니다.`,main,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'브랜드',path:'/brands/'},{name:b.name,path:pagePath}]),faqSchema(faqs),{"@context":"https://schema.org","@type":"WebPage",name:`${b.name} 창업비용과 가맹점 현황`,url:canonical(pagePath),dateModified:today}]}));
}

for(const b of subpageBrands){
 const costFaq=brandFaq(b).slice(0,4),costPath=`/brands/${b.slug}/cost/`;const costMain=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'브랜드',path:'/brands/'},{name:b.name,path:`/brands/${b.slug}/`},{name:'창업비용'}])}<article><div class="page-head"><h1>${esc(b.name)} 창업비용</h1><p class="answer"><b>공개 창업비용 ${won(b.cost)}.</b> 임대보증금·권리금·운전자금은 별도입니다.</p></div><section class="block"><h2>비용 항목</h2><div class="table-wrap"><table><tbody><tr><th>가맹비</th><td>${won(b.fee)}</td></tr><tr><th>교육비</th><td>${won(b.education)}</td></tr><tr><th>가맹 보증금</th><td>${won(b.deposit)}</td></tr><tr><th>인테리어</th><td>${won(b.interior)}</td></tr><tr><th>기타</th><td>${won(b.other)}</td></tr><tr class="strong"><th>합계</th><td>${won(b.cost)}</td></tr></tbody></table></div></section><section class="block"><h2>공개값에 빠질 수 있는 비용</h2><ul><li>건물 임대보증금과 월세</li><li>권리금</li><li>철거·전기·냉난방·소방 등 별도공사</li><li>초기 운전자금과 대출이자</li></ul><a class="button" href="${url(`/tools/startup-cost/?brand=${encodeURIComponent(b.slug)}`)}">내 조건으로 다시 계산</a></section>${faqHtml(costFaq)}${sourceBox()}</article></div>`;
 await writePage(costPath,layout({path:costPath,title:`${b.name} 창업비용·가맹비·인테리어 비용 | 창업데이터랩`,description:`${b.name} 공개 창업비용을 가맹비, 교육비, 보증금, 인테리어로 나눠 봅니다. 임대·권리금은 별도입니다.`,main:costMain,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'브랜드',path:'/brands/'},{name:b.name,path:`/brands/${b.slug}/`},{name:'창업비용',path:costPath}]),faqSchema(costFaq)]}));
 const storesFaq=[{question:`${b.name} 가맹점은 몇 개인가요?`,answer:`현재 SSG 프리뷰 값은 ${num(b.stores)}개입니다. 정식 공개 전 공식 스냅샷으로 교체합니다.`},{question:`${b.name} 점포가 전년보다 늘었나요?`,answer:growth(b)==null?'비교할 이전값이 없습니다.':`프리뷰 기준 ${growth(b)>=0?'증가':'감소'} ${Math.abs(growth(b)).toFixed(1)}%입니다.`},{question:'신규점과 폐점 수는 어디서 보나요?',answer:'정식 공정위 스냅샷에 신규·종료·해지 항목이 있을 때만 표시합니다.'},{question:'점포 증가가 수익성을 뜻하나요?',answer:'아닙니다. 점포 수 변화는 브랜드 규모 변화 관찰값입니다.'}],storesPath=`/brands/${b.slug}/stores/`;const storesMain=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'브랜드',path:'/brands/'},{name:b.name,path:`/brands/${b.slug}/`},{name:'점포 현황'}])}<article><div class="page-head"><h1>${esc(b.name)} 가맹점 수와 점포 변화</h1><p class="answer"><b>가맹점 ${num(b.stores)}개, 이전 기준 ${num(b.lastStores)}개.</b> 신규·종료·해지는 공식 데이터 연결 전까지 임의 생성하지 않습니다.</p></div><section class="metric-row"><div><span>현재</span><b>${num(b.stores)}개</b></div><div><span>이전</span><b>${num(b.lastStores)}개</b></div><div><span>증감률</span><b>${growth(b)>=0?'+':''}${pct(growth(b))}</b></div></section><section class="block"><h2>점포 변화 표</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>값</th></tr></thead><tbody><tr><td>현재 가맹점</td><td>${num(b.stores)}개</td></tr><tr><td>이전 가맹점</td><td>${num(b.lastStores)}개</td></tr><tr><td>단순 증감률</td><td>${growth(b)>=0?'+':''}${pct(growth(b))}</td></tr><tr><td>신규등록</td><td>정보 없음</td></tr><tr><td>계약종료·해지</td><td>정보 없음</td></tr></tbody></table></div></section>${faqHtml(storesFaq)}${sourceBox()}</article></div>`;await writePage(storesPath,layout({path:storesPath,title:`${b.name} 가맹점 수·점포 증감 | 창업데이터랩`,description:`${b.name} 가맹점 수와 이전 기준 점포 수를 비교합니다. 신규·종료·해지 누락값은 0으로 처리하지 않습니다.`,main:storesMain,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'브랜드',path:'/brands/'},{name:b.name,path:`/brands/${b.slug}/`},{name:'점포 현황',path:storesPath}]),faqSchema(storesFaq)]}));
}

for(const c of priorityCats){const list=catBrands(c).sort((a,b)=>b.stores-a.stores);if(!list.length)continue;const pathName=`/rankings/${c}/`;const main=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'업종 정렬'}])}<div class="page-head"><h1>${esc(categories[c].name)} 프랜차이즈 가맹점 수 정렬</h1><p class="answer"><b>${list.length}개 우선 검수 브랜드를 가맹점 수로만 정렬합니다.</b> 1위가 좋은 창업이라는 뜻은 아닙니다.</p></div><div class="table-wrap"><table><thead><tr><th>순서</th><th>브랜드</th><th>가맹점</th><th>공개비용</th><th>전년 증감</th></tr></thead><tbody>${list.map((b,i)=>`<tr><td>${i+1}</td><td><a href="${url(`/brands/${b.slug}/`)}">${esc(b.name)}</a></td><td>${num(b.stores)}개</td><td>${won(b.cost)}</td><td>${growth(b)>=0?'+':''}${pct(growth(b))}</td></tr>`).join('')}</tbody></table></div>${sourceBox()}</div>`;await writePage(pathName,layout({path:pathName,title:`${categories[c].name} 프랜차이즈 가맹점 수 정렬 | 창업데이터랩`,description:`${categories[c].name} 우선 검수 브랜드를 가맹점 수, 공개비용, 전년 증감과 함께 정렬합니다. 추천 순위가 아닙니다.`,main,schema:[breadcrumbs([{name:'홈',path:'/'},{name:`${categories[c].name} 정렬`,path:pathName}])]}));}

for(const [an,bn] of CURATED_COMPARE_NAMES){const a=byName.get(an),b=byName.get(bn);if(!a||!b)continue;const cp=`/compare/${a.slug}/${b.slug}/`;const main=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'브랜드 비교'}])}<div class="page-head"><h1>${esc(a.name)} vs ${esc(b.name)} 창업비용 비교</h1><p class="answer"><b>${esc(a.name)} ${won(a.cost)}, ${esc(b.name)} ${won(b.cost)}.</b> 비용 차이와 점포 규모를 같은 표에서 보고, 임대·권리금은 별도 계산합니다.</p></div><div class="table-wrap"><table><thead><tr><th>항목</th><th>${esc(a.name)}</th><th>${esc(b.name)}</th></tr></thead><tbody><tr><td>공개 창업비용</td><td>${won(a.cost)}</td><td>${won(b.cost)}</td></tr><tr><td>가맹점</td><td>${num(a.stores)}개</td><td>${num(b.stores)}개</td></tr><tr><td>전년 증감</td><td>${growth(a)>=0?'+':''}${pct(growth(a))}</td><td>${growth(b)>=0?'+':''}${pct(growth(b))}</td></tr><tr><td>매출 관련 프리뷰값</td><td>${won(a.sales)}</td><td>${won(b.sales)}</td></tr></tbody></table></div><section class="block actions"><a class="button" href="${url(`/tools/startup-cost/?brand=${a.slug}`)}">${esc(a.name)} 내 조건 계산</a><a class="button ghost" href="${url(`/tools/startup-cost/?brand=${b.slug}`)}">${esc(b.name)} 내 조건 계산</a></section>${sourceBox()}</div>`;await writePage(cp,layout({path:cp,title:`${a.name} vs ${b.name} 창업비용 비교 | 창업데이터랩`,description:`${a.name}와 ${b.name}의 공개 창업비용, 가맹점 수, 점포 증감을 같은 기준으로 비교합니다.`,main,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'비교',path:cp}])]}));}

for(const a of priorityAreas){const c='cafe',ap=`/areas/${a.slug}/`,count=a.categoryCounts?.[c]??0,density=a.areaKm2?count/a.areaKm2:null;const main=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'지역 상권'}])}<div class="page-head"><h1>${esc(a.sido)} ${esc(a.name)} 프랜차이즈 업종 밀도</h1><p class="answer"><b>카페 프리뷰 업소 ${num(count)}곳, ${density==null?'정보 없음':`${density.toFixed(1)}곳/㎢`}.</b> 공급량만 보여주며 매출·성공확률로 해석하지 않습니다.</p></div><section class="block"><h2>업종별 업소 수</h2><div class="table-wrap"><table><thead><tr><th>업종</th><th>업소 수</th></tr></thead><tbody>${Object.entries(a.categoryCounts||{}).filter(([k])=>categories[k]).sort((x,y)=>y[1]-x[1]).slice(0,12).map(([k,v])=>`<tr><td>${esc(categories[k].name)}</td><td>${num(v)}곳</td></tr>`).join('')}</tbody></table></div></section><p class="note">브랜드의 시도별 점포 수와 이 시군구의 동일업종 업소 수는 서로 다른 지표입니다.</p>${sourceBox()}</div>`;await writePage(ap,layout({path:ap,title:`${a.sido} ${a.name} 프랜차이즈 업종 밀도 | 창업데이터랩`,description:`${a.sido} ${a.name}의 업종별 업소 수와 면적 대비 공급 밀도를 봅니다. 매출·창업 추천 점수는 제공하지 않습니다.`,main,schema:[breadcrumbs([{name:'홈',path:'/'},{name:`${a.sido} ${a.name}`,path:ap}])]}));}

const guideIndex=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'가이드'}])}<div class="page-head"><h1>프랜차이즈 창업 데이터 읽는 법 15편</h1><p>각 글은 한 질문에 답하고, 표·계산 예·빠지는 항목·출처·FAQ를 따로 둡니다.</p></div><div class="guide-list">${GUIDES.map(g=>`<article><a href="${url(`/guides/${g.slug}/`)}"><h2>${esc(g.title)}</h2><p>${esc(g.answer)}</p></a></article>`).join('')}</div></div>`;await writePage('/guides/',layout({path:'/guides/',title:'프랜차이즈 창업 가이드 15편 | 창업데이터랩',description:'정보공개서, 창업비용, 가맹점 증감, 권리금, 로열티, 손익분기와 상권 밀도를 질문별로 설명합니다.',main:guideIndex,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'가이드',path:'/guides/'}])]}));
for(const g of GUIDES){const gp=`/guides/${g.slug}/`;const main=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'가이드',path:'/guides/'},{name:g.title}])}<article class="article"><div class="page-head"><h1>${esc(g.title)}</h1><p class="answer">${esc(g.answer)}</p><p class="updated">검수 기준일 ${today}</p></div><section class="block"><h2>항목별로 보면</h2><div class="table-wrap"><table><thead><tr><th>항목</th><th>뜻</th><th>확인할 점</th></tr></thead><tbody>${g.table.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="block"><h2>계산 예</h2><p>${esc(g.example)}</p></section><section class="block"><h2>이 설명에서 빠지는 항목</h2><p>${esc(g.excluded)}</p></section>${faqHtml(g.faqs)}<section class="block"><h2>출처와 확인 순서</h2><p>정식 서비스에서는 공정거래위원회 가맹사업정보제공시스템의 최신 정보공개서와 공공데이터 스냅샷 기준연도를 함께 표시합니다. 현재 페이지 숫자 예시는 교육용 계산 예이며 특정 브랜드의 실제 수치가 아닙니다.</p><div class="actions"><a href="${url('/sources/')}">데이터 출처 보기</a><a href="${url('/tools/')}">계산기 보기</a><a href="${url('/brands/')}">브랜드 보기</a></div></section></article></div>`;await writePage(gp,layout({path:gp,title:`${g.title} | 창업데이터랩`,description:g.answer.slice(0,145),main,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'가이드',path:'/guides/'},{name:g.title,path:gp}]),faqSchema(g.faqs),{"@context":"https://schema.org","@type":"Article",headline:g.title,description:g.answer,dateModified:today,mainEntityOfPage:canonical(gp),author:{"@type":"Organization",name:'창업데이터랩'}}]}));}

const toolsIndex=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'계산기'}])}<div class="page-head"><h1>프랜차이즈 창업 계산기</h1><p>입력창만 두지 않고 계산식, 예시, 제외 항목과 FAQ를 같은 페이지에 둡니다.</p></div><div class="tool-grid">${TOOLS.map(t=>`<article><a href="${url(`/tools/${t.slug}/`)}"><h2>${esc(t.title)}</h2><p>${esc(t.answer)}</p></a></article>`).join('')}</div></div>`;await writePage('/tools/',layout({path:'/tools/',title:'프랜차이즈 창업 계산기·비교 도구 | 창업데이터랩',description:'창업비용, 손익분기, 월 고정비, 상권 밀도, 개폐업률, 업종 중앙값과 후보 조건을 계산합니다.',main:toolsIndex,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'계산기',path:'/tools/'}])]}));
function toolWidget(t){if(t.slug==='startup-cost')return `<div class="calculator" data-tool="startup-cost"><label>브랜드<select name="brand"><option value="">직접 입력</option>${brands.map(b=>`<option value="${b.slug}" data-cost="${b.cost}">${esc(b.name)} · ${won(b.cost)}</option>`).join('')}</select></label><label>브랜드 공개비용(만원)<input inputmode="numeric" name="publicCost" value="8000"></label><label>임대보증금<input inputmode="numeric" name="rentDeposit" value="3000"></label><label>권리금<input inputmode="numeric" name="keyMoney" value="1500"></label><label>추가공사·설비<input inputmode="numeric" name="extra" value="1000"></label><label>운전자금<input inputmode="numeric" name="working" value="1500"></label><output>계산 결과 <b data-result>15,000만원</b></output></div>`;if(t.slug==='break-even')return `<div class="calculator" data-tool="break-even"><label>초기투자(만원)<input inputmode="numeric" name="investment" value="14000"></label><label>월 매출<input inputmode="numeric" name="revenue" value="4500"></label><label>원가율(%)<input inputmode="decimal" name="material" value="34"></label><label>인건비<input inputmode="numeric" name="labor" value="1100"></label><label>월세·관리비<input inputmode="numeric" name="rent" value="420"></label><label>기타비용<input inputmode="numeric" name="other" value="500"></label><output>단순 회수기간 <b data-result>계산 중</b></output></div>`;if(t.slug==='open-close-rate')return `<div class="calculator" data-tool="open-close"><label>기준 점포<input name="base" value="200"></label><label>신규<input name="new" value="20"></label><label>종료<input name="end" value="12"></label><label>해지<input name="cancel" value="6"></label><output><b data-result>계산 중</b></output></div>`;return `<div class="tool-static"><p>이 프리뷰에서는 계산 구조와 검색용 문서를 먼저 검수합니다. 정식 구현에서는 입력값만 브라우저에서 다시 계산하고 설명·표·FAQ는 서버가 만든 HTML에 남습니다.</p></div>`}
for(const t of TOOLS){const tp=`/tools/${t.slug}/`;const main=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:'계산기',path:'/tools/'},{name:t.title}])}<article><div class="page-head"><h1>${esc(t.title)}</h1><p class="answer">${esc(t.answer)}</p></div>${toolWidget(t)}<section class="block"><h2>계산식</h2><p class="formula">${esc(t.formula)}</p></section><section class="block"><h2>계산 예</h2><div class="example-grid">${t.examples.map(e=>`<div><b>${esc(e[0])}</b><p>${esc(e[1])}</p></div>`).join('')}</div></section><section class="block"><h2>기본 계산에서 제외하는 항목</h2><ul>${t.excluded.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>${faqHtml(t.faqs)}<section class="block"><h2>관련 페이지</h2><div class="actions"><a href="${url('/guides/')}">가이드 보기</a><a href="${url('/brands/')}">브랜드 보기</a></div></section></article></div>`;await writePage(tp,layout({path:tp,title:`${t.title} | 창업데이터랩`,description:t.answer,main,schema:[breadcrumbs([{name:'홈',path:'/'},{name:'계산기',path:'/tools/'},{name:t.title,path:tp}]),faqSchema(t.faqs),{"@context":"https://schema.org","@type":"WebApplication",name:t.title,url:canonical(tp),applicationCategory:'BusinessApplication',operatingSystem:'Web'}]}));}

const staticPages={
 '/methodology/':['계산·데이터 처리 기준','공식 원본값, 자체 계산값, 사용자 입력을 분리합니다.',`<h2>세 종류의 숫자를 섞지 않습니다</h2><ol><li><b>공식 원본값</b> 공정위·공공데이터 스냅샷.</li><li><b>자체 계산값</b> 증감률·중앙값·밀도. 계산식을 공개합니다.</li><li><b>사용자 입력</b> 임대보증금·권리금·월세·인건비 등.</li></ol><h2>누락값 처리</h2><p>원천에 값이 없으면 0이 아니라 정보 없음으로 저장합니다.</p><h2>색인 품질 게이트</h2><p>공식 기준연도·출처·충분한 표·FAQ·내부링크가 없는 브랜드 세부 URL은 정식 사이트에서 생성하거나 색인하지 않습니다.</p>`],
 '/sources/':['데이터 출처','정식 서비스에서 사용하는 원천과 기준일을 공개합니다.',`<h2>공정거래위원회 가맹사업정보</h2><p>브랜드별 가맹점 현황, 창업금액, 지역·직영점 등 공식 공개 API·정보공개서를 우선합니다.</p><h2>소상공인시장진흥공단 상가(상권)정보</h2><p>지역·업종별 업소 수와 좌표 기반 공급량 계산에 사용합니다.</p><h2>현재 프리뷰</h2><p>공식 브랜드 스냅샷 상태: <b>${esc(official?.status||'확인 불가')}</b>. 공식값 승격 조건을 통과하지 못하면 합성 프리뷰 수치를 정식 도메인에 게시하지 않습니다.</p>`],
 '/about/':['서비스 소개','창업데이터랩이 어떤 숫자를 어떤 목적으로 보여주는지 설명합니다.',`<p>창업데이터랩은 특정 브랜드를 추천하거나 가맹계약을 중개하지 않습니다. 공개된 프랜차이즈 데이터와 사용자가 직접 입력한 점포 비용을 분리해 비교하기 위한 정보 서비스입니다.</p><h2>운영자 정보</h2><p>외부 검수용 프리뷰에서는 개인정보를 게시하지 않습니다. 정식 공개 전 운영자 또는 사업자 정보와 연락처를 실제 정보로 채우는 것을 배포 게이트로 둡니다.</p>`],
 '/disclaimer/':['이용 전 확인사항','창업비용·손익 계산을 사용할 때 반드시 확인할 한계입니다.',`<ul><li>투자·가맹 권유가 아닙니다.</li><li>공개 창업비용은 실제 총 준비자금과 다를 수 있습니다.</li><li>손익·회수기간은 사용자가 입력한 가정이 유지된다는 단순 계산입니다.</li><li>결과가 양수이거나 순위가 높아도 성공을 의미하지 않습니다.</li><li>계약 전 최신 정보공개서와 계약서를 확인하세요.</li></ul>`],
 '/privacy/':['개인정보처리방침','프리뷰와 정식 서비스의 개인정보 처리 원칙을 설명합니다.',`<p>현재 외부 검수 프리뷰는 회원가입과 서버 저장 입력폼을 운영하지 않습니다. 계산기 입력값은 브라우저 안에서 계산합니다.</p><p>정식 서비스에서 분석도구·광고·문의폼을 도입할 경우 수집 항목, 목적, 보관기간, 제3자 제공과 쿠키 사용을 실제 구성에 맞춰 갱신합니다.</p>`],
 '/terms/':['이용약관','서비스 정보의 범위와 책임 한계를 설명합니다.',`<p>사이트 자료는 공개정보의 이해와 사용자의 자체 계산을 돕기 위한 참고자료입니다. 공식 기관·가맹본부의 최종 문서를 대체하지 않습니다.</p>`],
 '/contact/':['문의·오류 제보','데이터 오류와 페이지 문제를 제보하는 경로입니다.',`<p>외부 검수 프리뷰에서는 실제 연락처를 노출하지 않습니다. 정식 도메인 공개 전 운영 이메일 또는 사업자 연락처를 채우고 오류제보 항목을 운영합니다.</p>`]
};
for(const [sp,[title,desc,body]] of Object.entries(staticPages)){const main=`<div class="shell page">${crumbs([{name:'홈',path:'/'},{name:title}])}<article class="article"><div class="page-head"><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${body}${sp==='/methodology/'||sp==='/sources/'?sourceBox():''}</article></div>`;await writePage(sp,layout({path:sp,title:`${title} | 창업데이터랩`,description:desc,main,schema:[breadcrumbs([{name:'홈',path:'/'},{name:title,path:sp}])]}));}

await fs.mkdir(path.join(out,'assets'),{recursive:true});await fs.copyFile(path.join(here,'assets/site.css'),path.join(out,'assets/site.css'));await fs.copyFile(path.join(here,'assets/app.js'),path.join(out,'assets/app.js'));
const manifest={schemaVersion:1,generatedAt:new Date().toISOString(),previewMode:PREVIEW,basePath:BASE,siteUrl:SITE,dataMode:'SYNTHETIC_STRUCTURE_PREVIEW',officialSnapshot:{status:official?.status||'UNKNOWN',allowOverlay:Boolean(official?.promotion?.allowPreviewOverlay),recordCount:official?.records?.length||0},coverage:{priorityBrands:brands.length,brandSubpages:subpageBrands.length,guides:GUIDES.length,tools:TOOLS.length,rankings:priorityCats.length,areas:priorityAreas.length,curatedCompares:CURATED_COMPARE_NAMES.length},productionGates:{officialSnapshotReady:Boolean(official?.promotion?.allowPreviewOverlay&&official?.records?.length),operatorIdentityReady:false,realContactReady:false,guidesReady:GUIDES.length>=15,hashRoutesRemoved:true,staticHtmlMain:true,noindexPreview:PREVIEW}};
await fs.writeFile(path.join(out,'route-manifest.json'),JSON.stringify(manifest,null,2)+'\n');await fs.writeFile(path.join(out,'README.txt'),`창업데이터랩 SSG 외부검수 프리뷰\n- 실제 디렉터리 URL\n- 모든 페이지 noindex\n- 초기 HTML에 본문 포함\n- 공식 Snapshot 승격 전 합성 수치는 정식 공개 금지\n`);console.log(JSON.stringify(manifest,null,2));
