import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'..'),out=path.join(root,'docs/franchise-ssg-preview'),BASE='/pm-lab/franchise-ssg-preview';
async function walk(dir){const items=await fs.readdir(dir,{withFileTypes:true});const out=[];for(const x of items){const p=path.join(dir,x.name);if(x.isDirectory())out.push(...await walk(p));else out.push(p)}return out}
async function exists(p){try{await fs.stat(p);return true}catch{return false}}
const files=await walk(out),htmls=files.filter(f=>f.endsWith('index.html'));if(htmls.length<120)throw new Error(`Too few static HTML pages: ${htmls.length}`);
const prohibited=['PUBLIC DATA','SIDE BY SIDE','DATA QUALITY','LOCAL COMMERCIAL DATA','FRANCHISE DATA SEARCH','BRAND SHORTLIST','NEXT STEP','AREA × CATEGORY × BRAND','30초 데이터 요약','핵심 인사이트','최적의 창업','지금 시작하세요'];
const titles=new Map(),broken=[];for(const f of htmls){const h=await fs.readFile(f,'utf8'),rel=path.relative(out,f);if(!h.includes('noindex,nofollow,noarchive,nosnippet'))throw new Error(`Missing noindex: ${rel}`);if(/href=["'][^"']*#\//.test(h))throw new Error(`Hash route found: ${rel}`);for(const token of prohibited)if(h.includes(token))throw new Error(`Prohibited landing copy "${token}": ${rel}`);if(h.includes('candidate-finder'))throw new Error(`Old candidate-finder slug remains: ${rel}`);const main=h.match(/<main id="main">([\s\S]*?)<\/main>/)?.[1]?.trim();if(!main||main.length<180)throw new Error(`Thin/empty initial main: ${rel}`);if(!/<h1>[^<]+<\/h1>/.test(h))throw new Error(`Missing H1: ${rel}`);if(!/rel="canonical"/.test(h))throw new Error(`Missing canonical: ${rel}`);const title=h.match(/<title>([^<]+)<\/title>/)?.[1];if(!title)throw new Error(`Missing title: ${rel}`);if(titles.has(title))throw new Error(`Duplicate title: ${title} => ${titles.get(title)}, ${rel}`);titles.set(title,rel);for(const m of h.matchAll(/href="([^"]+)"/g)){const href=m[1];if(!href.startsWith(BASE))continue;const local=href.slice(BASE.length).split('?')[0].split('#')[0]||'/';let target;if(/\.(?:css|js|json|txt)$/i.test(local))target=path.join(out,local.replace(/^\//,''));else target=local==='/'?path.join(out,'index.html'):path.join(out,local.replace(/^\//,'').replace(/\/$/,''),'index.html');if(!(await exists(target)))broken.push(`${rel} -> ${href}`)}}if(broken.length)throw new Error(`Broken internal links (${broken.length}):\n${broken.slice(0,30).join('\n')}`);
const generic=/^(?:cafe|chicken|burger|pizza|korean|snack|bakery|pub|meat|soup|japanese|chinese|salad|convenience|study|education|beauty|laundry|auto|pet)-\d{2}$/;
const manifest=JSON.parse(await fs.readFile(path.join(out,'route-manifest.json'),'utf8'));if(manifest.schemaVersion<2)throw new Error('SSG manifest schemaVersion must be 2+');if(manifest.coverage.priorityBrands!==42)throw new Error(`Expected 42 priority brands, got ${manifest.coverage.priorityBrands}`);if(manifest.coverage.descriptiveBrandSlugs!==42)throw new Error('Descriptive brand slug coverage incomplete');if(manifest.coverage.guides<15||manifest.coverage.tools<8||manifest.coverage.compareHub!==1)throw new Error('Coverage below target');for(const gate of ['hashRoutesRemoved','staticHtmlMain','noindexPreview','descriptiveBrandSlugs','compareHub','guideInternalLinks','subpageQualityRules','candidateToolRenamed'])if(!manifest.productionGates?.[gate])throw new Error(`Gate false: ${gate}`);if(manifest.productionGates.officialMetricMergeReady!==false)throw new Error('Official metric merge gate should remain false until implemented');
const brandDirs=(await fs.readdir(path.join(out,'brands'),{withFileTypes:true})).filter(x=>x.isDirectory());if(brandDirs.length!==42)throw new Error(`Expected 42 brand directories, got ${brandDirs.length}`);for(const d of brandDirs){if(generic.test(d.name))throw new Error(`Generated-number brand slug remains: ${d.name}`);const f=path.join(out,'brands',d.name,'index.html'),h=await fs.readFile(f,'utf8');for(const token of ['공개 창업비용','가맹점 수','업종 중앙값','자주 묻는 질문'])if(!h.includes(token))throw new Error(`Brand template missing ${token}: ${d.name}`)}
let subBrandCount=0,subPageCount=0;for(const d of brandDirs){const cost=await exists(path.join(out,'brands',d.name,'cost','index.html')),stores=await exists(path.join(out,'brands',d.name,'stores','index.html'));if(cost||stores){if(!(cost&&stores))throw new Error(`Partial subpage pair: ${d.name}`);subBrandCount++;subPageCount+=2;}}
if(subBrandCount!==manifest.coverage.previewSubpageBrands||subPageCount!==manifest.coverage.previewSubpagePages)throw new Error(`Subpage coverage mismatch: ${subBrandCount} brands / ${subPageCount} pages`);
const guideDirs=(await fs.readdir(path.join(out,'guides'),{withFileTypes:true})).filter(x=>x.isDirectory());if(guideDirs.length!==15)throw new Error(`Expected 15 guides, got ${guideDirs.length}`);for(const d of guideDirs){const h=await fs.readFile(path.join(out,'guides',d.name,'index.html'),'utf8');for(const token of ['"@type":"Article"','"@type":"FAQPage"','계산 예','이 설명에서 빠지는 항목','관련 브랜드','관련 도구','같이 읽기','공식 자료'])if(!h.includes(token))throw new Error(`Guide template missing ${token}: ${d.name}`)}
const toolDirs=(await fs.readdir(path.join(out,'tools'),{withFileTypes:true})).filter(x=>x.isDirectory());if(toolDirs.length!==8)throw new Error(`Expected 8 tools, got ${toolDirs.length}`);if(!(await exists(path.join(out,'tools','brand-filter','index.html')))||await exists(path.join(out,'tools','candidate-finder','index.html')))throw new Error('Brand filter rename incomplete');for(const d of toolDirs){const h=await fs.readFile(path.join(out,'tools',d.name,'index.html'),'utf8');if(!h.includes('"@type":"WebApplication"')||!h.includes('계산식')||!h.includes('계산 예')||!h.includes('자주 묻는 질문'))throw new Error(`Tool template incomplete: ${d.name}`)}
if(!(await exists(path.join(out,'compare','index.html'))))throw new Error('Missing /compare/ hub');const compareHtml=await fs.readFile(path.join(out,'compare','index.html'),'utf8');if(!compareHtml.includes('프랜차이즈 브랜드 비교'))throw new Error('Compare hub incomplete');const compareFirst=(await fs.readdir(path.join(out,'compare'),{withFileTypes:true})).filter(x=>x.isDirectory());let comparePairCount=0;for(const d of compareFirst)if(generic.test(d.name))throw new Error(`Generated-number compare slug remains: ${d.name}`);for(const d of compareFirst){const seconds=(await fs.readdir(path.join(out,'compare',d.name),{withFileTypes:true})).filter(x=>x.isDirectory());for(const s of seconds){comparePairCount++;if(generic.test(s.name))throw new Error(`Generated-number compare slug remains: ${d.name}/${s.name}`);const h=await fs.readFile(path.join(out,'compare',d.name,s.name,'index.html'),'utf8');for(const token of ['공개비용 차이','창업비용 항목별 비교','점포 규모와 변화','지역별 점포 분포 상위 5개 시도'])if(!h.includes(token))throw new Error(`Compare report missing ${token}: ${d.name}/${s.name}`)}}
const redirectPlan=JSON.parse(await fs.readFile(path.join(out,'redirect-plan.json'),'utf8'));if((redirectPlan.brands||[]).length<20)throw new Error('Redirect planning table too small');if(!(redirectPlan.tools||[]).some(x=>x.to==='/tools/brand-filter/'))throw new Error('Tool redirect plan missing');
console.log(JSON.stringify({htmlPages:htmls.length,uniqueTitles:titles.size,brokenInternalLinks:broken.length,brands:brandDirs.length,descriptiveBrandSlugs:brandDirs.length,previewSubpageBrands:subBrandCount,previewSubpagePages:subPageCount,guides:guideDirs.length,tools:toolDirs.length,comparePairs:comparePairCount,redirectBrandMappings:redirectPlan.brands.length,productionGates:manifest.productionGates,subpageQuality:manifest.subpageQuality},null,2));
