import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'..'),out=path.join(root,'docs/franchise-ssg-preview');
async function walk(dir){const items=await fs.readdir(dir,{withFileTypes:true});const out=[];for(const x of items){const p=path.join(dir,x.name);if(x.isDirectory())out.push(...await walk(p));else out.push(p)}return out}
const files=await walk(out),htmls=files.filter(f=>f.endsWith('index.html'));if(htmls.length<100)throw new Error(`Too few static HTML pages: ${htmls.length}`);
const titles=new Map();for(const f of htmls){const h=await fs.readFile(f,'utf8');const rel=path.relative(out,f);if(!h.includes('noindex,nofollow,noarchive,nosnippet'))throw new Error(`Missing noindex: ${rel}`);if(/href=["'][^"']*#\//.test(h))throw new Error(`Hash route found: ${rel}`);const main=h.match(/<main id="main">([\s\S]*?)<\/main>/)?.[1]?.trim();if(!main||main.length<180)throw new Error(`Thin/empty initial main: ${rel}`);if(!/<h1>[^<]+<\/h1>/.test(h))throw new Error(`Missing H1: ${rel}`);if(!/rel="canonical"/.test(h))throw new Error(`Missing canonical: ${rel}`);const title=h.match(/<title>([^<]+)<\/title>/)?.[1];if(!title)throw new Error(`Missing title: ${rel}`);if(titles.has(title))throw new Error(`Duplicate title: ${title} => ${titles.get(title)}, ${rel}`);titles.set(title,rel)}
const manifest=JSON.parse(await fs.readFile(path.join(out,'route-manifest.json'),'utf8'));if(manifest.coverage.priorityBrands<42)throw new Error('Priority brand coverage below 42');if(manifest.coverage.guides<15)throw new Error('Guide coverage below 15');if(manifest.coverage.brandSubpages<20)throw new Error('Brand subpage coverage below 20');if(!manifest.productionGates.hashRoutesRemoved||!manifest.productionGates.staticHtmlMain||!manifest.productionGates.noindexPreview)throw new Error('SSG preview gates invalid');
const brandDirs=(await fs.readdir(path.join(out,'brands'),{withFileTypes:true})).filter(x=>x.isDirectory());if(brandDirs.length<42)throw new Error(`Brand directories below 42: ${brandDirs.length}`);
for(const d of brandDirs){const f=path.join(out,'brands',d.name,'index.html');const h=await fs.readFile(f,'utf8');for(const token of ['공개 창업비용','가맹점 수','업종 중앙값','자주 묻는 질문','현재 데이터 상태'])if(!h.includes(token))throw new Error(`Brand template missing ${token}: ${d.name}`)}
const guideDirs=(await fs.readdir(path.join(out,'guides'),{withFileTypes:true})).filter(x=>x.isDirectory());if(guideDirs.length!==15)throw new Error(`Expected 15 guides, got ${guideDirs.length}`);for(const d of guideDirs){const h=await fs.readFile(path.join(out,'guides',d.name,'index.html'),'utf8');if(!h.includes('"@type":"Article"')||!h.includes('"@type":"FAQPage"')||!h.includes('계산 예')||!h.includes('이 설명에서 빠지는 항목'))throw new Error(`Guide template incomplete: ${d.name}`)}
const toolDirs=(await fs.readdir(path.join(out,'tools'),{withFileTypes:true})).filter(x=>x.isDirectory());if(toolDirs.length<8)throw new Error(`Expected 8 tools, got ${toolDirs.length}`);for(const d of toolDirs){const h=await fs.readFile(path.join(out,'tools',d.name,'index.html'),'utf8');if(!h.includes('"@type":"WebApplication"')||!h.includes('계산식')||!h.includes('계산 예')||!h.includes('자주 묻는 질문'))throw new Error(`Tool template incomplete: ${d.name}`)}
console.log(JSON.stringify({htmlPages:htmls.length,brands:brandDirs.length,guides:guideDirs.length,tools:toolDirs.length,officialSnapshot:manifest.officialSnapshot,productionGates:manifest.productionGates},null,2));
