import { CANONICAL_STATUSES } from '../core.js';
const IATA=/^[A-Z0-9]{3}$/;
const FLIGHT=/^[A-Z0-9]{2,3}\d{1,4}[A-Z]?$/;
export function normalizeFlightNumber(value){const v=String(value||'').toUpperCase().replace(/\s+/g,'');if(!FLIGHT.test(v))throw new Error('INVALID_FLIGHT_NUMBER');return v}
function normalizeIata(v){const x=String(v||'').toUpperCase();if(!IATA.test(x))throw new Error('INVALID_IATA');return x}
function normalizeLimit(v,max=200){const n=Number(v??50);if(!Number.isInteger(n)||n<1)return 50;return Math.min(n,max)}
export function flightSearchSpec({query,serviceDate,limit=20}){const q=normalizeFlightNumber(query);return{sql:`SELECT DISTINCT f.* FROM flight_current f LEFT JOIN flight_codeshares c ON c.flight_instance_id=f.flight_instance_id WHERE f.service_date=?1 AND (f.flight_number=?2 OR f.operating_flight_number=?2 OR f.master_flight_number=?2 OR c.marketing_flight_number=?2) ORDER BY COALESCE(f.scheduled_departure,f.scheduled_arrival) LIMIT ?3`,params:[serviceDate,q,normalizeLimit(limit,50)]}}
export function airportBoardSpec({iata,serviceDate,direction='DEPARTURE',status=null,limit=100}){const airport=normalizeIata(iata),dir=String(direction).toUpperCase();if(!['DEPARTURE','ARRIVAL'].includes(dir))throw new Error('INVALID_DIRECTION');if(status&&!CANONICAL_STATUSES.includes(status))throw new Error('INVALID_STATUS');const airportColumn=dir==='DEPARTURE'?'origin':'destination';const where=[`service_date=?1`,`direction=?2`,`${airportColumn}=?3`];const params=[serviceDate,dir,airport];if(status){where.push(`status=?${params.length+1}`);params.push(status)}params.push(normalizeLimit(limit));return{sql:`SELECT * FROM flight_current WHERE ${where.join(' AND ')} ORDER BY COALESCE(scheduled_departure,scheduled_arrival) LIMIT ?${params.length}`,params}}
export function irregularBoardSpec({serviceDate,status,airportIata=null,direction=null,limit=200}){if(!['DELAYED','CANCELLED'].includes(status))throw new Error('IRREGULAR_STATUS_REQUIRED');const where=['service_date=?1','status=?2'];const params=[serviceDate,status];if(direction){const dir=String(direction).toUpperCase();if(!['DEPARTURE','ARRIVAL'].includes(dir))throw new Error('INVALID_DIRECTION');where.push(`direction=?${params.length+1}`);params.push(dir)}if(airportIata){const iata=normalizeIata(airportIata);where.push(`(origin=?${params.length+1} OR destination=?${params.length+1})`);params.push(iata)}params.push(normalizeLimit(limit,500));return{sql:`SELECT * FROM flight_current WHERE ${where.join(' AND ')} ORDER BY COALESCE(delay_minutes,0) DESC, COALESCE(scheduled_departure,scheduled_arrival) LIMIT ?${params.length}`,params}}
export function flightNumberHistorySpec({flightNumber,limit=30}){return{sql:`SELECT * FROM flight_number_daily_metrics WHERE flight_number=?1 ORDER BY service_date DESC LIMIT ?2`,params:[normalizeFlightNumber(flightNumber),normalizeLimit(limit,90)]}}
async function all(db,spec){const r=await db.prepare(spec.sql).bind(...spec.params).all();return r.results||[]}
export async function searchFlights(db,args){return all(db,flightSearchSpec(args))}
export async function airportBoard(db,args){return all(db,airportBoardSpec(args))}
export async function irregularBoard(db,args){return all(db,irregularBoardSpec(args))}
export async function flightNumberHistory(db,args){return all(db,flightNumberHistorySpec(args))}
