function areaDetailPage(slug){
  const a=areas.find(x=>x.slug===slug)||areas[0], density=a.stores/a.areaKm2, share=a.stores/a.allFood*100; setTitle(`${a.sido} ${a.name} ${a.category} 상권`);
  return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:'상권 분석',href:'/areas'},{label:`${a.sido} ${a.name}`}])}<div class="page-head"><div><span class="eyebrow">AREA DATA</span><h1>${a.sido} ${a.name} ${a.category} 상권 현황</h1><p>업소 수·면적당 밀도·음식점 내 비율을 분리해 보여주는 지역 상세 화면입니다.</p></div></div></div></section><div class="shell content-wrap">${previewNotice()}<div class="summary-grid"><div class="summary-card"><span>${a.category} 업소</span><b>${num(a.stores)}곳</b><small>샘플 집계</small></div><div class="summary-card"><span>면적당 밀도</span><b>${density.toFixed(1)}곳/㎢</b><small>업소 수 ÷ 행정구역 면적</small></div><div class="summary-card"><span>음식점 내 비율</span><b>${pct(share)}</b><small>${num(a.allFood)}곳 중</small></div><div class="summary-card"><span>지역 기준 대비</span><b class="${density>=a.avgDensity?'negative':'positive'}">${density>=a.avgDensity?'+':''}${pct((density-a.avgDensity)/a.avgDensity*100)}</b><small>밀도 비교값 · 좋고 나쁨 아님</small></div></div><div class="two-col"><div class="stack"><section class="panel"><h2>동별 업소 분포</h2><p class="panel-sub">실제 서비스에서는 상가 좌표를 행정동에 매핑해 자동 집계합니다.</p><div class="bar-list">${a.topDongs.map(([d,c])=>`<div class="bar-row"><span class="bar-label">${d}</span><span class="bar-track"><span class="bar-fill" style="width:${c/a.topDongs[0][1]*100}%"></span></span><span class="bar-value">${num(c)}곳</span></div>`).join('')}</div>${sourceLine('소상공인 상가(상권)정보 Adapter 연결 예정')}</section><section class="panel"><h2>지도 UI 미리보기</h2><p class="panel-sub">프리뷰에서는 실제 사업장 좌표를 노출하지 않고 클러스터링 구조만 검수합니다.</p><div class="map-placeholder">${[[18,25],[43,31],[67,22],[32,58],[58,66],[78,51],[49,46],[20,72],[73,78]].map(([l,t])=>`<i class="map-pin" style="left:${l}%;top:${t}%"></i>`).join('')}<span class="map-caption">실서비스: 상가 좌표 → 지도 클러스터 → 반경 필터</span></div></section></div><aside class="stack side-card"><section class="panel"><h3>이 숫자를 이렇게 읽습니다</h3><div class="fact-list"><div class="fact-row"><span>업소 수</span><b>규모</b></div><div class="fact-row"><span>곳/㎢</span><b>밀집도</b></div><div class="fact-row"><span>음식점 내 비율</span><b>업종 집중도</b></div><div class="fact-row"><span>판정</span><b>성공/실패 예측 안 함</b></div></div></section><section class="cta-box"><h3>브랜드까지 같이 보세요.</h3><p>같은 카페 업종이라도 브랜드별 비용과 매장 규모가 다릅니다. 상권 데이터와 브랜드 데이터는 별도 축으로 읽습니다.</p><a class="primary-button" href="#/rankings/cafe">카페 브랜드 보기</a></section></aside></div></div></div>`;
}

function methodologyPage(){
  setTitle('데이터 계산·검수 기준');
  return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:'계산·검수 기준'}])}<div class="page-head"><div><span class="eyebrow">METHODOLOGY</span><h1>숫자가 만들어지는 과정</h1><p>원본 데이터, 자체 계산, 사용자 시뮬레이션을 섞지 않는 것이 이 서비스의 핵심 검수 기준입니다.</p></div></div></div></section><div class="shell content-wrap"><div class="prose"><h2>1. 세 종류의 숫자를 분리합니다</h2><p><b>공식 공개 데이터</b>는 제공기관의 원본 필드를 의미합니다. <b>자체 계산</b>은 원본값으로 중앙값·증감률·비율을 계산한 값입니다. <b>시뮬레이션</b>은 사용자가 직접 넣은 가정으로 계산한 결과입니다.</p><h2>2. 누락값은 0이 아닙니다</h2><p>API의 null, 미제공, 비공개 값을 0원이나 0개로 바꾸지 않습니다. 화면에서 ‘정보 없음’으로 표시하고 랭킹 계산에서도 제외합니다.</p><h2>3. 스냅샷을 보존합니다</h2><p>최신값으로 덮어쓰지 않고 기준연도·기준일별 스냅샷을 저장합니다. 이렇게 해야 매장 수나 공개비용의 변화를 자체 데이터로 계산할 수 있습니다.</p><div class="formula">가맹점 증감률 = (현재 가맹점 수 − 이전 가맹점 수) ÷ 이전 가맹점 수 × 100</div><h2>4. 업종 중앙값을 사용합니다</h2><p>극단값 영향을 줄이기 위해 단순 평균만 보여주지 않고 동일 업종의 중앙값과 함께 비교합니다.</p><div class="formula">비용 차이율 = (브랜드 공개비용 − 업종 중앙값) ÷ 업종 중앙값 × 100</div><h2>5. 상권 밀도는 성공확률이 아닙니다</h2><p>업소 수, 면적당 점포 수, 전체 음식점 중 해당 업종 비율은 ‘얼마나 몰려 있는지’를 설명할 뿐입니다. 경쟁이 많다/적다는 사실을 사업 성공 또는 실패로 자동 번역하지 않습니다.</p><div class="formula">업종 밀도 = 해당 지역 업종 점포 수 ÷ 행정구역 면적(km²)</div><h2>6. 계산기는 사용자 가정을 그대로 계산합니다</h2><p>창업비용 계산기는 공식 공개비용에 사용자 입력 항목을 더합니다. 손익분기 계산기는 사용자가 입력한 월매출·비용률·고정비가 지속된다는 단순 가정으로 계산합니다.</p><div class="formula">단순 회수기간(개월) = 초기 투자금 ÷ 월 예상 영업잉여</div><h2>7. 데이터 상태를 관리합니다</h2><ul><li><b>VALID</b>: 정상값</li><li><b>MISSING</b>: 원본 미제공</li><li><b>STALE</b>: 업데이트 기준 초과</li><li><b>INVALID</b>: 급격한 이상치 등 자동 검수 실패</li></ul><h2>8. 프리뷰 데이터</h2><p>현재 외부 검수 URL은 UI와 계산 흐름을 평가하기 위한 fixture 모드입니다. 실제 브랜드 수치로 인용하거나 의사결정에 사용해서는 안 됩니다. 공식 API의 이용허락과 승인 절차가 확인된 뒤 데이터 adapter만 교체할 수 있도록 설계했습니다.</p></div></div></div>`;
}

function sourcesPage(){
  setTitle('데이터 출처');
  return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:'데이터 출처'}])}<div class="page-head"><div><span class="eyebrow">SOURCES</span><h1>데이터 출처와 역할</h1><p>어떤 기관의 어떤 데이터가 화면의 어느 숫자에 쓰이는지 분리해서 공개합니다.</p></div></div></div></section><div class="shell content-wrap"><div class="prose" style="max-width:900px">${sources.map(s=>`<article class="source-card"><h3>${esc(s.name)}</h3><p>${esc(s.purpose)}</p><div class="source-meta"><span>제공: ${esc(s.provider)}</span><span>${esc(s.license)}</span><span>최근 구조 검수: ${PREVIEW_DATE}</span></div><a href="${s.url}" ${s.url.startsWith('http')?'target="_blank" rel="noopener noreferrer"':''}>출처 확인 →</a></article>`).join('')}<div class="notice"><strong>운영 전 조건</strong><span>각 API의 서비스별 이용허락, 상업적 이용 가능 여부, 호출 제한, 승인 필요 여부를 별도로 확인한 항목만 production adapter에서 활성화합니다.</span></div></div></div></div>`;
}

function staticPage(type){
  const pages={
    about:{title:'서비스 소개',eyebrow:'ABOUT',body:`<p>창업데이터랩은 프랜차이즈 브랜드를 홍보하거나 추천하기보다, 예비창업자가 공개된 숫자를 같은 기준으로 비교하고 자기 조건으로 다시 계산할 수 있게 만드는 데이터 도구입니다.</p><h2>우리가 해결하려는 문제</h2><p>창업 검색 결과에는 ‘얼마가 든다’는 단일 숫자가 많지만, 비용의 기준연도·포함 항목·임대차 비용 여부가 서로 다릅니다. 이 서비스는 출처와 기준을 먼저 보여주고 같은 단위로 비교합니다.</p><h2>제품 원칙</h2><ul><li>공식값과 추정값을 섞지 않습니다.</li><li>비어 있는 값은 0으로 채우지 않습니다.</li><li>‘추천 브랜드’ 점수보다 관찰 가능한 데이터 항목을 제공합니다.</li><li>사용자가 직접 조건을 넣는 계산기를 핵심 가치로 둡니다.</li></ul>`},
    privacy:{title:'개인정보처리방침',eyebrow:'PRIVACY',body:`<p>현재 프리뷰는 회원가입, 로그인, 광고 식별자, 서버 저장형 문의폼을 사용하지 않습니다.</p><h2>현재 수집하는 정보</h2><p>브라우저에서 계산기에 입력한 값은 계산을 위해 화면에서만 사용하며 서버로 전송하거나 저장하지 않습니다. 프리뷰 이벤트는 개발자 콘솔에만 기록합니다.</p><h2>외부 링크</h2><p>공식 데이터 출처를 확인하기 위해 외부 공공기관 사이트로 이동할 수 있으며, 해당 사이트에는 각 기관의 개인정보처리방침이 적용됩니다.</p><h2>정식 서비스 전</h2><p>분석 도구, 광고, 문의 기능 등이 추가되면 실제 적용 서비스에 맞춘 개인정보처리방침으로 개정합니다.</p>`},
    terms:{title:'이용약관·정보 이용 안내',eyebrow:'TERMS',body:`<p>본 서비스는 정부기관 또는 프랜차이즈 본사가 운영하는 공식 서비스가 아닙니다. 공개 데이터를 이해하기 쉽게 가공한 참고용 정보 서비스입니다.</p><h2>정보의 한계</h2><p>데이터 제공기관의 갱신시점, 계약조건, 매장 규모, 지역에 따라 실제 창업비용과 운영조건이 달라질 수 있습니다. 실제 계약 전에는 최신 정보공개서와 본사 안내를 확인해야 합니다.</p><h2>시뮬레이션</h2><p>계산기 결과는 사용자가 입력한 가정을 계산한 값이며, 매출·이익·투자회수를 보장하거나 예측하지 않습니다.</p>`},
    contact:{title:'문의·오류제보',eyebrow:'CONTACT',body:`<p>프리뷰 단계에서는 별도의 개인정보 수집형 문의폼을 열지 않습니다. 외부 검수자는 우측 상단의 ‘검수 포인트’에서 현재 화면 링크를 복사해 피드백과 함께 전달할 수 있습니다.</p><h2>오류제보 시 필요한 정보</h2><ul><li>문제가 보이는 페이지 URL</li><li>브랜드 또는 지역명</li><li>잘못 보이는 데이터 항목</li><li>가능한 경우 공식 출처 링크</li></ul><h2>운영 전 추가 예정</h2><p>정식 도메인 확정 후 운영자 정보와 전용 연락처를 명시하고, 개인정보 수집을 최소화한 오류제보 경로를 제공합니다.</p>`}
  }; const p=pages[type]||pages.about; setTitle(p.title); return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:p.title}])}<div class="page-head"><div><span class="eyebrow">${p.eyebrow}</span><h1>${p.title}</h1></div></div></div></section><div class="shell content-wrap"><div class="prose">${p.body}</div></div></div>`;
}

function notFound(){ setTitle('페이지를 찾을 수 없음'); return `<div class="shell content-wrap"><div class="empty"><h2>페이지를 찾을 수 없습니다.</h2><p>프리뷰에서 아직 연결되지 않은 경로입니다.</p><a class="primary-button" href="#/">홈으로</a></div></div>`; }
