function comparePage(aSlug,bSlug){
  const a=bySlug(aSlug||'mega-mgc-coffee'), b=bySlug(bSlug||'compose-coffee'), da=derived(a), db=derived(b); setTitle(`${a.name} vs ${b.name} 창업 비교`);
  const rows=[['창업 관련 공개비용',won(a.cost),won(b.cost),`${won(Math.abs(a.cost-b.cost))} 차이`],['인테리어 관련 비용',won(a.interior),won(b.interior),`${won(Math.abs(a.interior-b.interior))} 차이`],['가맹점 수',`${num(a.stores)}개`,`${num(b.stores)}개`,`${num(Math.abs(a.stores-b.stores))}개 차이`],['직영점 수',`${num(a.direct)}개`,`${num(b.direct)}개`,`${num(Math.abs(a.direct-b.direct))}개 차이`],['매출 관련 공개지표',won(a.sales),won(b.sales),`${won(Math.abs(a.sales-b.sales))} 차이`],['가맹점 전년 대비',`${da.yoy>=0?'+':''}${pct(da.yoy)}`,`${db.yoy>=0?'+':''}${pct(db.yoy)}`,'스냅샷 자체 계산']];
  return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:'브랜드 비교'}])}<div class="page-head"><div><span class="eyebrow">SIDE BY SIDE</span><h1>${esc(a.name)} vs ${esc(b.name)}</h1><p>서로 다른 브랜드의 공개값을 같은 단위·같은 기준으로 맞춘 뒤 차이를 계산합니다.</p></div></div></div></section><div class="shell content-wrap">${previewNotice()}<section class="panel"><div class="compare-picker"><div class="field"><label>브랜드 A</label><select id="compareA">${brands.map(x=>`<option value="${x.slug}" ${x.slug===a.slug?'selected':''}>${esc(x.name)} · ${x.category}</option>`).join('')}</select></div><div class="vs">VS</div><div class="field"><label>브랜드 B</label><select id="compareB">${brands.map(x=>`<option value="${x.slug}" ${x.slug===b.slug?'selected':''}>${esc(x.name)} · ${x.category}</option>`).join('')}</select></div></div></section><section class="panel" style="margin-top:16px"><div class="compare-head"><div>비교 항목</div><div class="compare-brand">${avatar(a)}<div><b>${esc(a.name)}</b><small style="display:block;color:var(--muted)">${a.category}</small></div></div><div class="compare-brand">${avatar(b)}<div><b>${esc(b.name)}</b><small style="display:block;color:var(--muted)">${b.category}</small></div></div></div>${rows.map(([label,av,bv,delta])=>`<div class="compare-row"><div class="label">${label}</div><div class="compare-value"><b>${av}</b><span class="compare-delta">${delta}</span></div><div class="compare-value"><b>${bv}</b><span class="compare-delta">${delta}</span></div></div>`).join('')}${sourceLine('브랜드별 fixture를 동일 기준으로 비교')}</section><div class="insight-banner"><p><b>비교 해석.</b> 샘플 기준 ${a.name}의 공개비용은 ${b.name}보다 <b>${won(Math.abs(a.cost-b.cost))} ${a.cost<b.cost?'낮고':'높습니다'}.</b> 가맹점 수는 <b>${num(Math.abs(a.stores-b.stores))}개 ${a.stores>b.stores?'많습니다':'적습니다'}.</b> 비용이 낮거나 매장이 많다는 사실만으로 수익성을 판단하지 않습니다.</p><span class="insight-label">중립적 파생 설명</span></div><section class="section" style="padding-bottom:0"><div class="section-head"><div><h2>다음 행동으로 연결</h2><p>비교 후 실제 내 임대조건을 넣어 준비자금을 계산할 수 있습니다.</p></div></div><div class="tool-cards"><article class="tool-card"><span class="tool-icon">₩</span><h3>${a.short} 조건 계산</h3><p>${a.name} 공개비용 예시에 임대·권리금·운전자금을 더합니다.</p><a class="text-link" href="#/tools/startup-cost?brand=${a.slug}">계산하기 →</a></article><article class="tool-card"><span class="tool-icon">₩</span><h3>${b.short} 조건 계산</h3><p>${b.name} 공개비용 예시에 임대·권리금·운전자금을 더합니다.</p><a class="text-link" href="#/tools/startup-cost?brand=${b.slug}">계산하기 →</a></article><article class="tool-card"><span class="tool-icon">↗</span><h3>업종 랭킹 보기</h3><p>같은 업종 브랜드를 매장 수·공개비용 기준으로 나란히 봅니다.</p><a class="text-link" href="#/rankings/${a.categorySlug}">${a.category} 랭킹 →</a></article></div></section></div></div>`;
}

function rankingPage(cat='cafe'){
  const list=catBrands(cat).length?catBrands(cat):brands, label=categories[cat]?.name||'전체'; setTitle(`${label} 프랜차이즈 데이터 랭킹`);
  const rows=[...list].sort((a,b)=>b.stores-a.stores);
  return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:'업종 랭킹'},{label}])}<div class="page-head"><div><span class="eyebrow">CATEGORY RANKING</span><h1>${label} 프랜차이즈 데이터 랭킹</h1><p>‘추천 순위’가 아니라 공개비용·가맹점 수 같은 객관 항목별 정렬을 제공하는 페이지입니다.</p></div></div></div></section><div class="shell content-wrap">${previewNotice()}<div class="panel"><div class="field" style="max-width:260px"><label>업종 선택</label><select id="rankingCategory">${Object.entries(categories).map(([k,v])=>`<option value="${k}" ${k===cat?'selected':''}>${v.name}</option>`).join('')}</select></div></div><section class="panel" style="margin-top:16px"><h2>가맹점 수 기준</h2><p class="panel-sub">현재 샘플 브랜드만 비교하며 실제 공개 전 전체 데이터셋으로 확대합니다.</p><div class="data-table-wrap"><table class="data-table"><thead><tr><th>순위</th><th>브랜드</th><th class="num">가맹점</th><th class="num">공개비용</th><th class="num">매출 관련 지표</th><th class="num">증감</th></tr></thead><tbody>${rows.map((b,i)=>{const d=derived(b);return `<tr><td><span class="rank ${i<3?'top':''}">${i+1}</span></td><td><div class="brand-cell">${avatar(b)}<a class="table-link" href="#/brand/${b.slug}">${esc(b.name)}</a></div></td><td class="num"><b>${num(b.stores)}개</b></td><td class="num">${won(b.cost)}</td><td class="num">${won(b.sales)}</td><td class="num"><span class="trend ${d.yoy>=0?'up':'down'}">${d.yoy>=0?'▲':'▼'} ${pct(Math.abs(d.yoy))}</span></td></tr>`}).join('')}</tbody></table></div>${sourceLine('업종별 fixture + 자체 정렬')}</section><div class="notice" style="margin-top:16px"><strong>랭킹 원칙</strong><span>‘1위 = 좋은 창업’으로 표현하지 않습니다. 화면의 순위는 선택한 단일 데이터 항목의 정렬일 뿐이며, 실제 수익성·계약 적합성에 대한 추천 점수가 아닙니다.</span></div></div></div>`;
}

function startupCostPage(){
  const qs=(location.hash.split('?')[1]||''); const params=new URLSearchParams(qs); const slug=params.get('brand')||'mega-mgc-coffee'; const b=bySlug(slug); setTitle('프랜차이즈 창업비용 계산기');
  return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:'계산기'},{label:'창업비용'}])}<div class="page-head"><div><span class="eyebrow">STARTUP COST CALCULATOR</span><h1>창업비용 계산기</h1><p>브랜드 공개비용과 임대차·권리금·추가공사·운전자금을 분리해 실제 준비자금의 구조를 확인합니다.</p></div><div class="page-actions"><a class="outline-button" href="#/tools/break-even">손익분기 계산 →</a></div></div></div></section><div class="shell content-wrap">${previewNotice()}<div class="form-layout"><section class="form-card"><div class="form-grid"><div class="field span-2"><label>브랜드</label><select id="costBrand">${brands.map(x=>`<option value="${x.slug}" ${x.slug===b.slug?'selected':''}>${esc(x.name)} · 공개비용 예시 ${won(x.cost)}</option>`).join('')}</select><small class="field-help">브랜드 변경 시 공식 공개비용 예시만 바뀌며 사용자 입력값은 유지합니다.</small></div>${costInput('deposit','임대보증금',3000,'만원')}${costInput('keyMoney','권리금',0,'만원')}${costInput('monthlyRent','월 임대료',300,'만원')}${costInput('extraInterior','추가 인테리어·공사',1000,'만원')}${costInput('equipment','추가 설비',500,'만원')}${costInput('initialGoods','초도물품',300,'만원')}${costInput('workingCapital','운전자금',2000,'만원')}${costInput('otherCost','기타 비용',200,'만원')}</div></section><aside class="result-card"><span class="result-kicker">입력 조건 기준 예상 초기 필요자금</span><h2 class="result-total" id="startupTotal">—</h2><div class="result-lines"><div class="result-line"><span>브랜드 공개비용 예시</span><b id="officialCost">${won(b.cost)}</b></div><div class="result-line"><span>임대차·권리금</span><b id="leaseCost">—</b></div><div class="result-line"><span>추가 공사·설비·초도물품</span><b id="fitoutCost">—</b></div><div class="result-line"><span>운전자금·기타</span><b id="workingCost">—</b></div><div class="result-line"><span>월 고정 임대료</span><b id="rentCost">—</b></div></div><div class="result-note">실제 계약금액 예측이 아니라 입력값을 더한 단순 시뮬레이션입니다. 매장 면적·공사범위·임대차 조건·VAT·계약시점에 따라 실제 비용은 달라질 수 있습니다.</div><a class="primary-button mint" id="toBreakEven" style="display:block;text-align:center;margin-top:13px" href="#/tools/break-even">이 투자금으로 손익분기 계산</a></aside></div></div></div>`;
}
function costInput(id,label,value,unit){return `<div class="field"><label for="${id}">${label}</label><div class="input-with-unit"><input id="${id}" class="cost-input" inputmode="numeric" type="number" min="0" step="10" value="${value}"><span class="input-unit">${unit}</span></div></div>`;}

function breakEvenPage(){
  setTitle('손익분기점 시뮬레이터');
  return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:'계산기'},{label:'손익분기'}])}<div class="page-head"><div><span class="eyebrow">BREAK-EVEN SIMULATOR</span><h1>손익분기점 시뮬레이터</h1><p>월매출 가정에서 재료비·인건비·월세·수수료 등을 차감해 단순 영업잉여와 투자금 회수기간을 계산합니다.</p></div></div></div></section><div class="shell content-wrap"><div class="notice"><strong>가정 기반 계산</strong><span>브랜드의 실제 수익을 예측하는 기능이 아닙니다. 사용자가 넣은 가정이 계속 유지된다는 전제의 단순 산술 결과입니다.</span></div><div class="form-layout"><section class="form-card"><div class="form-grid">${costInput('revenue','월 매출 가정',4000,'만원')}<div class="field"><label>재료비율</label><div class="input-with-unit"><input id="materialPct" class="be-input" type="number" min="0" max="100" step="1" value="35"><span class="input-unit">%</span></div></div>${costInput('labor','월 인건비',900,'만원')}${costInput('rent','월세',300,'만원')}<div class="field"><label>결제·플랫폼 수수료율</label><div class="input-with-unit"><input id="feePct" class="be-input" type="number" min="0" max="100" step=".1" value="3"><span class="input-unit">%</span></div></div>${costInput('royalty','월 로열티',80,'만원')}${costInput('utilities','관리비·공과금',180,'만원')}${costInput('beOther','기타 월 비용',150,'만원')}${costInput('investment','초기 투자금',14000,'만원')}</div></section><aside class="result-card"><span class="result-kicker">사용자 가정 기준</span><h2 class="result-total" id="surplusResult">—</h2><p style="margin:-12px 0 15px;color:#a9bdca;font-size:11px">월 예상 단순 영업잉여</p><div class="result-lines"><div class="result-line"><span>월 매출</span><b id="beRevenue">—</b></div><div class="result-line"><span>재료비</span><b id="materialCost">—</b></div><div class="result-line"><span>고정·기타비용</span><b id="fixedCost">—</b></div><div class="result-line"><span>결제·플랫폼 수수료</span><b id="feeCost">—</b></div><div class="result-line"><span>단순 투자금 회수기간</span><b id="paybackResult">—</b></div></div><div class="result-note">세금, 감가상각, 이자, 폐기·로스, 매출 변동, 추가 인력 등은 별도입니다. 결과가 양수여도 사업 성공을 의미하지 않습니다.</div></aside></div></div></div>`;
}

function areasPage(){
  setTitle('지역별 상권 분석');
  return `<div class="page"><section class="page-hero"><div class="shell">${crumb([{label:'상권 분석'}])}<div class="page-head"><div><span class="eyebrow">LOCAL COMMERCIAL DATA</span><h1>지역별 상권 밀도</h1><p>상가 업소 좌표를 지역·업종 단위로 집계해 ‘경쟁이 좋다/나쁘다’가 아니라 얼마나 밀집했는지를 보여줍니다.</p></div></div></div></section><div class="shell content-wrap">${previewNotice()}<div class="area-grid">${areas.map(a=>{const density=a.stores/a.areaKm2;return `<article class="area-card" data-area="${a.slug}"><span class="eyebrow">${a.sido}</span><h3>${a.name} ${a.category}</h3><div class="density-meter"><span style="width:${Math.min(100,density/90*100)}%"></span></div><div class="area-meta"><span>업소 ${num(a.stores)}곳</span><b>${density.toFixed(1)}곳/㎢</b></div></article>`}).join('')}</div><section class="section" style="padding-bottom:0"><div class="section-head"><div><h2>밀도 계산기는 ‘점포 수’를 해석합니다</h2><p>실제 API 연결 시 주소 반경 300m·500m·1km 업종 수를 좌표로 계산합니다.</p></div></div><div class="tool-cards"><article class="tool-card"><span class="tool-icon">300</span><h3>도보권 300m</h3><p>같은 업종이 바로 주변에 얼마나 붙어 있는지 보는 초근거리 지표.</p></article><article class="tool-card"><span class="tool-icon">500</span><h3>생활권 500m</h3><p>상권 중심부 비교에 기본값으로 사용할 수 있는 반경 집계.</p></article><article class="tool-card"><span class="tool-icon">1K</span><h3>상권권 1km</h3><p>지역 전체의 업종 집중도를 넓게 비교하는 보조 지표.</p></article></div></section></div></div>`;
}
