export const CANONICAL_STATUSES = Object.freeze(['SCHEDULED','BOARDING','DEPARTED','AIRBORNE','LANDED','ARRIVED','DELAYED','CANCELLED','DIVERTED','UNKNOWN']);
const IATA=/^[A-Z0-9]{3}$/; const FLIGHT_NO=/^[A-Z0-9]{2,3}\s?\d{1,4}[A-Z]?$/;
export function canonicalFlightInstanceId({serviceDate,operatingFlightNumber,origin,destination,direction}){for(const[k,v]of Object.entries({serviceDate,operatingFlightNumber,origin,destination,direction}))if(!v)throw new Error(`flight instance id requires ${k}`);return `${serviceDate}:${operatingFlightNumber.replace(/\s+/g,'').toUpperCase()}:${origin}:${destination}:${direction}`}
export function validateFlightInstance(v){const required=['flightInstanceId','serviceDate','flightNumber','operatingFlightNumber','origin','destination','direction','status','sourceId','observedAt'];for(const k of required)if(!v[k])throw new Error(`FlightInstance.${k} is required`);if(!IATA.test(v.origin)||!IATA.test(v.destination))throw new Error('origin/destination must be IATA codes');if(v.origin===v.destination)throw new Error('origin and destination must differ');if(!['DEPARTURE','ARRIVAL'].includes(v.direction))throw new Error('direction must be DEPARTURE or ARRIVAL');if(!CANONICAL_STATUSES.includes(v.status))throw new Error(`unknown canonical status: ${v.status}`);if(v.delayMinutes!=null&&(!Number.isFinite(v.delayMinutes)||v.delayMinutes<0))throw new Error('delayMinutes must be null or >=0');if(!FLIGHT_NO.test(v.flightNumber.replace(/\s+/g,'')))throw new Error(`invalid flight number: ${v.flightNumber}`);return v}
export function createFlightInstance(input){const operatingFlightNumber=(input.operatingFlightNumber||input.flightNumber||'').replace(/\s+/g,'').toUpperCase();const flightNumber=(input.flightNumber||operatingFlightNumber).replace(/\s+/g,'').toUpperCase();const flightInstanceId=input.flightInstanceId||canonicalFlightInstanceId({serviceDate:input.serviceDate,operatingFlightNumber,origin:input.origin,destination:input.destination,direction:input.direction});return validateFlightInstance({...input,flightNumber,operatingFlightNumber,marketingAirline:input.marketingAirline??null,operatingAirline:input.operatingAirline??null,isCodeshare:Boolean(input.isCodeshare),masterFlightNumber:input.masterFlightNumber??null,scheduledDeparture:input.scheduledDeparture??null,estimatedDeparture:input.estimatedDeparture??null,actualDeparture:input.actualDeparture??null,scheduledArrival:input.scheduledArrival??null,estimatedArrival:input.estimatedArrival??null,actualArrival:input.actualArrival??null,terminal:input.terminal??null,gate:input.gate??null,checkinCounter:input.checkinCounter??null,baggageCarousel:input.baggageCarousel??null,statusRaw:input.statusRaw??null,delayMinutes:input.delayMinutes??null,statusUpdatedAt:input.statusUpdatedAt??null,sourceUpdatedAt:input.sourceUpdatedAt??null,sourceRecordKey:input.sourceRecordKey??null,flightInstanceId})}
export function createAirportSnapshot(input){const required=['iata','icao','name','region','dataAsOf','lastSuccessfulIngestAt','sourceIds'];for(const k of required)if(input[k]==null)throw new Error(`AirportSnapshot.${k} is required`);if(!IATA.test(input.iata))throw new Error('invalid IATA');for(const k of ['departuresCount','arrivalsCount','delayedCount','cancelledCount','delayRate'])if(input[k]!=null&&!Number.isFinite(input[k]))throw new Error(`AirportSnapshot.${k} must be numeric`);return{...input,departuresCount:input.departuresCount??null,arrivalsCount:input.arrivalsCount??null,delayedCount:input.delayedCount??null,cancelledCount:input.cancelledCount??null,delayRate:input.delayRate??null,baselineDelayRate:input.baselineDelayRate??null,baselineSampleSize:input.baselineSampleSize??null}}
const IIAC_REMARK=Object.freeze({'도착':'ARRIVED','결항':'CANCELLED','지연':'DELAYED','회항':'DIVERTED','착륙':'LANDED'});
export function mapIiacRemark(raw){if(!raw)return'UNKNOWN';return IIAC_REMARK[String(raw).trim()]||'UNKNOWN'}
export function computeDelayMinutes(scheduledIso,comparisonIso){if(!scheduledIso||!comparisonIso)return null;const a=Date.parse(scheduledIso),b=Date.parse(comparisonIso);if(!Number.isFinite(a)||!Number.isFinite(b))return null;return Math.max(0,Math.round((b-a)/60000))}
export function fallbackDelayStatus({canonicalStatus,scheduledIso,comparisonIso,thresholdMinutes=15}){if(canonicalStatus&&canonicalStatus!=='UNKNOWN')return canonicalStatus;const minutes=computeDelayMinutes(scheduledIso,comparisonIso);if(minutes==null)return'UNKNOWN';return minutes>=thresholdMinutes?'DELAYED':'SCHEDULED'}
export const SOURCE_STATES=Object.freeze({DOC_VERIFIED:'DOC_VERIFIED',LIVE_VERIFIED:'LIVE_VERIFIED',PARTIAL:'PARTIAL',UNAVAILABLE:'UNAVAILABLE',DOC_MISMATCH:'DOC_MISMATCH'});export const READINESS=Object.freeze({LIVE_PROBE_REQUIRED:'LIVE_PROBE_REQUIRED',FIXTURE_READY:'FIXTURE_READY',BLOCKED:'BLOCKED',DOC_MISMATCH:'DOC_MISMATCH'});
export const SOURCES=Object.freeze({KAC_FLIGHT_SEARCH_GW:{id:'KAC_FLIGHT_SEARCH_GW',provider:'한국공항공사',datasetId:'15160195',baseUrl:'https://apis.data.go.kr/B551178/flight-search',state:SOURCE_STATES.DOC_VERIFIED,readiness:READINESS.LIVE_PROBE_REQUIRED,productionEnabled:false,documentedDailyDevQuota:5000,scope:'인천 제외 14개 공항, 편명 검색',notes:'schFln 검색과 편명별 출도착/지연/결항 제공은 문서 확인. operation path/response field map은 승인 키 fixture 후 고정.'},IIAC_PASSENGER_ARRIVAL:{id:'IIAC_PASSENGER_ARRIVAL',provider:'인천국제공항공사',datasetId:'15095093',endpoint:'https://apis.data.go.kr/B551177/StatusOfPassengerFlightsOdp/getPassengerArrivalsOdp',state:SOURCE_STATES.DOC_VERIFIED,readiness:READINESS.FIXTURE_READY,productionEnabled:false,documentedDailyDevQuota:1000,scope:'ICN 당일 여객 도착',notes:'공식 페이지의 도착 operation과 fields만 사용.'},IIAC_PASSENGER_DEPARTURE:{id:'IIAC_PASSENGER_DEPARTURE',provider:'인천국제공항공사',datasetId:'15095093',state:SOURCE_STATES.UNAVAILABLE,readiness:READINESS.BLOCKED,productionEnabled:false,scope:'ICN 여객 출발',notes:'공식 operation 검증 전 이름을 추측해 호출하지 않는다.'},KMA_METAR_SPECI:{id:'KMA_METAR_SPECI',provider:'기상청 API허브/항공기상',endpoint:'https://apihub.kma.go.kr/api/typ02/openApi/AmmIwxxmService/getMetar',state:SOURCE_STATES.DOC_MISMATCH,readiness:READINESS.DOC_MISMATCH,productionEnabled:false,scope:'국내 공항 METAR/SPECI',notes:'IWXXM 구조화 fields 사용. 2025-08-01 이후 msgText 미제공 공지 때문에 msgText에 의존하지 않는다.'},KMA_TAF:{id:'KMA_TAF',provider:'기상청 API허브/항공기상',endpoint:'https://apihub.kma.go.kr/api/typ02/openApi/AmmIwxxmService/getTaf',state:SOURCE_STATES.DOC_VERIFIED,readiness:READINESS.LIVE_PROBE_REQUIRED,productionEnabled:false,scope:'국내 공항 TAF',notes:'live fixture 검증 전 실데이터 표기 금지.'}});
export function productionReadySources(){return Object.values(SOURCES).filter(s=>s.state===SOURCE_STATES.LIVE_VERIFIED&&s.productionEnabled)}
const SEOUL='+09:00';export function kstIso(serviceDate,hhmm){if(!serviceDate||!hhmm||!/^\d{4}$/.test(String(hhmm)))return null;const h=Number(String(hhmm).slice(0,2)),m=Number(String(hhmm).slice(2));if(h>24||m>59)return null;const d=new Date(`${serviceDate}T00:00:00${SEOUL}`);d.setTime(d.getTime()+((h===24?24:h)*60+m)*60000);const yyyy=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);return`${yyyy}T${parts}:00+09:00`}
function terminalName(id){return({P01:'T1',P02:'CONCOURSE',P03:'T2',C01:'CARGO_SOUTH',C02:'CARGO_NORTH',C03:'CARGO_T2'})[id]||id||null}
export function normalizeIiacArrival(row,{serviceDate,observedAt}){if(!row?.flightId)throw new Error('IIAC arrival row requires flightId');const operatingFlightNumber=(row.masterflightid||row.flightId).replace(/\s+/g,'').toUpperCase();const scheduledArrival=kstIso(serviceDate,row.scheduleDateTime);let estimatedArrival=kstIso(serviceDate,row.estimatedDateTime);if(scheduledArrival&&estimatedArrival&&Date.parse(estimatedArrival)<Date.parse(scheduledArrival)-12*3600_000)estimatedArrival=new Date(Date.parse(estimatedArrival)+86400_000).toISOString().replace('.000Z','+00:00');const status=mapIiacRemark(row.remark);return createFlightInstance({serviceDate,flightNumber:row.flightId,operatingFlightNumber,marketingAirline:row.flightId.slice(0,2),operatingAirline:null,isCodeshare:Boolean(row.codeshare||row.masterflightid),masterFlightNumber:row.masterflightid||null,origin:row.airportCode,destination:'ICN',direction:'ARRIVAL',scheduledArrival,estimatedArrival,terminal:terminalName(row.terminalId),gate:row.gatenumber||null,baggageCarousel:row.carousel||null,statusRaw:row.remark||null,status,delayMinutes:computeDelayMinutes(scheduledArrival,estimatedArrival),statusUpdatedAt:null,sourceId:'IIAC_PASSENGER_ARRIVAL',sourceUpdatedAt:null,observedAt,sourceRecordKey:`${serviceDate}:${row.flightId}:${row.scheduleDateTime}:${row.airportCode}`})}
export function buildKacSearchRequest(){throw new Error('KAC_LIVE_FIXTURE_REQUIRED: official dataset is doc-verified, but operation path/response field map must be captured with an approved service key before coding normalization.')}
export function normalizeKacSearchRow(){throw new Error('KAC_LIVE_FIXTURE_REQUIRED: do not guess KAC response field names.')}
function pick(obj,keys){for(const k of keys)if(obj?.[k]!=null)return obj[k];return null}function num(v){if(v==null||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
export function normalizeKmaMetarDocumentedShape(row,{icao,observedAt}){if(!icao)throw new Error('icao required');return{icao,kind:'METAR_OR_SPECI',phenomenonTime:pick(row,['om:phenomenonTime','phenomenonTime']),airTemperature:num(pick(row,['iwxxm:airTemperature','airTemperature'])),dewpointTemperature:num(pick(row,['iwxxm:dewpointTemperature','dewpointTemperature'])),qnh:num(pick(row,['iwxxm:qnh','qnh'])),meanWindDirection:num(pick(row,['iwxxm:meanWindDirection','meanWindDirection'])),meanWindSpeed:num(pick(row,['iwxxm:meanWindSpeed','meanWindSpeed'])),windGustSpeed:num(pick(row,['iwxxm:windGustSpeed','windGustSpeed'])),visibility:num(pick(row,['iwxxm:AerodromeHorizontal Visibility','visibility','prevailingVisibility'])),presentWeather:pick(row,['iwxxm:presentWeather','presentWeather']),observedAt,sourceId:'KMA_METAR_SPECI',rawText:null}}
export function buildKmaMetarUrl({icao,authKey,dataType='JSON',pageNo=1,numOfRows=10}){if(!icao||!authKey)throw new Error('icao and authKey required');const u=new URL('https://apihub.kma.go.kr/api/typ02/openApi/AmmIwxxmService/getMetar');for(const[k,v]of Object.entries({pageNo,numOfRows,dataType,icao,authKey}))u.searchParams.set(k,String(v));return u.toString()}
export function buildKmaTafUrl({icao,authKey,dataType='JSON',pageNo=1,numOfRows=10}){if(!icao||!authKey)throw new Error('icao and authKey required');const u=new URL('https://apihub.kma.go.kr/api/typ02/openApi/AmmIwxxmService/getTaf');for(const[k,v]of Object.entries({pageNo,numOfRows,dataType,icao,authKey}))u.searchParams.set(k,String(v));return u.toString()}
export const MEANINGFUL_FIELDS=Object.freeze(['status','scheduledDeparture','estimatedDeparture','actualDeparture','scheduledArrival','estimatedArrival','actualArrival','terminal','gate','checkinCounter','baggageCarousel','delayMinutes']);export function meaningfulDiff(previous,next){if(!previous)return{changed:true,fields:['__NEW__']};const fields=MEANINGFUL_FIELDS.filter(k=>(previous[k]??null)!==(next[k]??null));return{changed:fields.length>0,fields}}
export function delayRate(instances,{direction='DEPARTURE'}={}){const eligible=instances.filter(x=>x.direction===direction&&x.status!=='UNKNOWN');if(!eligible.length)return{rate:null,delayed:0,cancelled:0,denominator:0};const delayed=eligible.filter(x=>x.status==='DELAYED').length,cancelled=eligible.filter(x=>x.status==='CANCELLED').length;return{rate:+(delayed/eligible.length*100).toFixed(1),delayed,cancelled,denominator:eligible.length}}
export function compareBaseline(currentRate,baselineRate,baselineSampleSize,minBaselineSample=20){if(currentRate==null||baselineRate==null||baselineSampleSize<minBaselineSample)return{comparable:false,deltaPp:null,label:null};const d=+(currentRate-baselineRate).toFixed(1);return{comparable:true,deltaPp:d,label:Math.abs(d)<1?null:d>0?'평소보다 높음':'평소보다 낮음'}}
export function syncPlan(){return[{sourceId:'IIAC_PASSENGER_ARRIVAL',everyMinutes:5,enabled:false},{sourceId:'KAC_FLIGHT_SEARCH_GW',everyMinutes:5,enabled:false},{sourceId:'KMA_METAR_SPECI',everyMinutes:10,enabled:false},{sourceId:'KMA_TAF',everyMinutes:30,enabled:false}].map(x=>({...x,reason:SOURCES[x.sourceId]?.productionEnabled?null:'PRODUCTION_DISABLED_UNTIL_USER_APPROVAL_AND_LIVE_VERIFICATION'}))}
