import { communityConfig,publicSelect,userRpc,userSelect } from "./rest";
import { isPublishableCommunityPost, publicCommunityAuthorName } from "./content-quality";
export type QuestionFeedRow={id:string;game_universe_id:number|string;game_slug:string;game_name_ko:string;author_id:string|null;author_handle:string|null;author_name:string;title:string;body:string;status:string;accepted_answer_id:string|null;created_at:string;updated_at:string;answer_count:number;comment_count:number};
export type AnswerFeedRow={id:string;question_id:string;author_id:string|null;author_handle:string|null;author_name:string;body:string;created_at:string;updated_at:string;is_accepted:boolean;comment_count:number};
export type CommentFeedRow={id:string;question_id:string|null;answer_id:string|null;author_id:string|null;author_handle:string|null;author_name:string;body:string;created_at:string;updated_at:string};
export type PublicProfile={id:string;handle:string;display_name:string|null;bio:string;created_at:string;updated_at:string};
export async function getQuestionFeed({gameUniverseId,limit=30}:{gameUniverseId?:number;limit?:number}={}){if(!communityConfig())return [];const rows=await publicSelect<QuestionFeedRow>("r1_question_feed",{select:"*",...(gameUniverseId?{game_universe_id:`eq.${gameUniverseId}`} : {}),order:"created_at.desc",limit});return rows.map(row=>({...row,author_name:publicCommunityAuthorName(row.author_name)}));}
export async function getQuestion(id:string){if(!communityConfig())return null;const rows=await publicSelect<QuestionFeedRow>("r1_question_feed",{select:"*",id:`eq.${id}`,limit:1});const row=rows[0]??null;return row?{...row,author_name:publicCommunityAuthorName(row.author_name)}:null;}
export async function getAnswers(questionId:string){if(!communityConfig())return [] as AnswerFeedRow[];const rows=await publicSelect<AnswerFeedRow>("r1_answer_feed",{select:"*",question_id:`eq.${questionId}`,order:"is_accepted.desc,created_at.asc",limit:100});return rows.map(row=>({...row,author_name:publicCommunityAuthorName(row.author_name)}));}
export async function getQuestionComments(questionId:string){if(!communityConfig())return [] as CommentFeedRow[];const rows=await publicSelect<CommentFeedRow>("r1_comment_feed",{select:"*",question_id:`eq.${questionId}`,order:"created_at.asc",limit:100});return rows.map(row=>({...row,author_name:publicCommunityAuthorName(row.author_name)}));}
export async function getProfile(id:string){if(!communityConfig())return null;const rows=await publicSelect<PublicProfile>("profiles",{select:"id,handle,display_name,bio,created_at,updated_at",id:`eq.${id}`,limit:1});return rows[0]??null;}
export async function getOwnFollow(token:string,userId:string,universeId:number){const rows=await userSelect<{user_id:string;universe_id:number|string}>("game_follows",token,{select:"user_id,universe_id",user_id:`eq.${userId}`,universe_id:`eq.${universeId}`,limit:1});return rows.length>0;}
export type CommunityPermissions={authenticated:boolean;active:boolean;role:"user"|"moderator"|"admin"|null};
export async function getCommunityPermissions(token:string){return userRpc<CommunityPermissions>("r1_my_community_permissions",token);}
export type NotificationRow={id:string;kind:string;actor_id:string|null;game_universe_id:number|string|null;question_id:string|null;answer_id:string|null;comment_id:string|null;update_event_id:string|null;payload:Record<string,unknown>;read_at:string|null;created_at:string};
export function getNotifications(token:string,userId:string){return userSelect<NotificationRow>("notifications",token,{select:"*",user_id:`eq.${userId}`,order:"created_at.desc",limit:100});}
export function getUnreadNotificationCount(token:string){return userRpc<number>("r1_my_unread_notification_count",token);}
export type ReportRow={id:string;reporter_id:string;target_type:string;target_id:string;reason:string;details:string;status:string;created_at:string;reviewed_at:string|null;reviewed_by:string|null};
export function getModerationReports(token:string){return userSelect<ReportRow>("reports",token,{select:"*",order:"status.asc,created_at.asc",limit:100});}
export async function getAnswerComments(answerIds:string[]){if(!answerIds.length||!communityConfig())return [] as CommentFeedRow[];const rows=await publicSelect<CommentFeedRow>("r1_comment_feed",{select:"*",answer_id:`in.(${answerIds.join(",")})`,order:"created_at.asc",limit:300});return rows.map(row=>({...row,author_name:publicCommunityAuthorName(row.author_name)}));}

export type CommunityGuideRow={id:string;game_universe_id:number|string;game_slug:string;game_name_ko:string;author_id:string|null;author_handle:string|null;author_name:string;guide_type:string;title:string;body:string;created_at:string;updated_at:string};
export async function getCommunityGuideFeed({gameUniverseId,limit=30}:{gameUniverseId?:number;limit?:number}={}){if(!communityConfig())return [] as CommunityGuideRow[];const rows=await publicSelect<CommunityGuideRow>("r1_community_guide_feed",{select:"*",...(gameUniverseId?{game_universe_id:`eq.${gameUniverseId}`}:{}),order:"created_at.desc,id.desc",limit});return rows.map(row=>({...row,author_name:publicCommunityAuthorName(row.author_name)}));}
export async function getCommunityGuide(id:string){if(!communityConfig())return null;const rows=await publicSelect<CommunityGuideRow>("r1_community_guide_feed",{select:"*",id:`eq.${id}`,limit:1});const row=rows[0]??null;return row?{...row,author_name:publicCommunityAuthorName(row.author_name)}:null;}

export type CommunityPostRow={id:string;game_universe_id:number|string|null;game_slug:string|null;game_name_ko:string|null;author_id:string|null;author_handle:string|null;author_name:string;title:string;body:string;created_at:string;updated_at:string;comment_count:number};
export type CommunityPostCommentRow={id:string;post_id:string;author_id:string|null;author_handle:string|null;author_name:string;body:string;created_at:string;updated_at:string};
export async function getCommunityPostFeed({gameUniverseId,limit=30}:{gameUniverseId?:number;limit?:number}={}){if(!communityConfig())return [] as CommunityPostRow[];const rows=await publicSelect<CommunityPostRow>("r1_community_post_feed",{select:"*",...(gameUniverseId?{game_universe_id:`eq.${gameUniverseId}`}:{}),order:"created_at.desc,id.desc",limit:Math.min(Math.max(limit*2,limit),100)});return rows.filter(row=>isPublishableCommunityPost(row.title,row.body)).slice(0,limit).map(row=>({...row,author_name:publicCommunityAuthorName(row.author_name)}));}
export async function getCommunityPost(id:string){if(!communityConfig())return null;const rows=await publicSelect<CommunityPostRow>("r1_community_post_feed",{select:"*",id:`eq.${id}`,limit:1});const row=rows[0]??null;if(!row||!isPublishableCommunityPost(row.title,row.body))return null;return {...row,author_name:publicCommunityAuthorName(row.author_name)};}
export async function getCommunityPostComments(postId:string){if(!communityConfig())return [] as CommunityPostCommentRow[];const rows=await publicSelect<CommunityPostCommentRow>("r1_community_post_comment_feed",{select:"*",post_id:`eq.${postId}`,order:"created_at.asc,id.asc",limit:200});return rows.map(row=>({...row,author_name:publicCommunityAuthorName(row.author_name)}));}
