import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const code=fs.readFileSync(new URL('../../docs/airport-now-preview/site.js',import.meta.url),'utf8');
function ctx(){const c=vm.createContext({window:{},document:{querySelector(){return null},addEventListener(){}},Intl,Date,console,setTimeout,clearTimeout});vm.runInContext(code,c);return c;}
const row=()=>({flight_number:'KE123',origin:'NRT',destination:'ICN',direction:'ARRIVAL',terminal:'T2',status:'DELAYED',service_date:new Date(Date.now()+9*3600000).toISOString().slice(0,10),flight_instance_id:'exact/id',last_collected_at:new Date().toISOString(),collection_readiness:'LIVE_CAPTURED'});
test('live search preserves exact flight/date pickup link and never loops back to search',()=>{const c=ctx();const r=c.liveFlightToIndex(row());assert.ok(r.pickupUrl.endsWith('id=exact%2Fid&date='+row().service_date));assert.doesNotMatch(r.url,/flights/);assert.match(r.meta,/제2터미널/);const d=row();d.direction='DEPARTURE';assert.equal(c.liveFlightToIndex(d).pickupUrl,null);});
test('search excludes stale and not-yet-published rows',()=>{const c=ctx(),r=row();r.last_collected_at=new Date(Date.now()-1800000).toISOString();assert.equal(c.liveFlightToIndex(r),null);r.last_collected_at=new Date().toISOString();r.observed_at=new Date(Date.now()+10000).toISOString();assert.equal(c.liveFlightToIndex(r),null);});

test('fresh source health cannot make a previous service date live',()=>{const c=ctx(),r=row();r.service_date='2020-01-01';assert.equal(c.liveFlightToIndex(r),null);});
test('dated search passes the selected date and excludes responses from another date',async()=>{const c=ctx();vm.runInContext("API_BASE='https://test'",c);let requested='';c.fetchLiveJson=async path=>{requested=path;return{results:[row()]}};const selected='2020-01-01';assert.equal((await c.searchLiveFlights('KE123',selected)).items.length,0);assert.match(requested,/date=2020-01-01/);});

test('search distinguishes outage, empty response, stale results and unsupported dates',()=>{const c=ctx();assert.equal(c.classifySearchResponse(null).state,'CONNECTION_FAILED');assert.equal(c.classifySearchResponse({results:[]}).state,'NOT_FOUND');const r=row();r.last_collected_at=new Date(Date.now()-31*60000).toISOString();assert.equal(c.classifySearchResponse({results:[r]}).state,'STALE');assert.equal(c.classifySearchResponse({results:[]},'2020-01-01').state,'DATE_UNAVAILABLE');assert.equal(c.classifySearchResponse({results:[r,row()]}).state,'PARTIAL');});
