-- Resonance Radar schema
-- Public preview surfaces are read-only. Raw wallets, trades and internal state stay private.

create extension if not exists pgcrypto;

create table if not exists public.traders (
  id uuid primary key default gen_random_uuid(),
  external_key text unique not null,
  label text,
  score numeric not null default 50 check (score >= 0 and score <= 100),
  pnl_30d numeric,
  win_rate_30d numeric,
  trade_count_30d integer,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wallets (
  id uuid primary key default gen_random_uuid(),
  trader_id uuid references public.traders(id) on delete set null,
  address text not null,
  chain text not null,
  cluster_id text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(chain, address)
);

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  provider_trade_id text unique not null,
  chain text not null,
  wallet_address text not null,
  trader_key text not null,
  trader_label text,
  cluster_key text not null,
  trader_score numeric not null default 50,
  token_address text not null,
  symbol text not null,
  side text not null check (side in ('BUY','SELL')),
  amount_usd numeric not null default 0,
  amount_token numeric,
  price numeric,
  liquidity_usd numeric,
  market_cap_usd numeric,
  tx_hash text,
  executed_at timestamptz not null,
  received_at timestamptz not null default now()
);

create index if not exists trades_token_window_idx on public.trades(chain, token_address, executed_at desc);
create index if not exists trades_recent_idx on public.trades(executed_at desc);
create index if not exists trades_cluster_idx on public.trades(cluster_key, executed_at desc);

create table if not exists public.radar_current (
  chain text not null,
  token_address text not null,
  symbol text not null,
  name text,
  score integer not null default 0,
  signal_type text not null default 'WATCH',
  buyers_5m integer not null default 0,
  buyers_15m integer not null default 0,
  buyers_60m integer not null default 0,
  sellers_15m integer not null default 0,
  buy_volume_15m numeric not null default 0,
  sell_volume_15m numeric not null default 0,
  net_flow_15m numeric not null default 0,
  liquidity_usd numeric,
  market_cap_usd numeric,
  top_traders integer not null default 0,
  flags text[] not null default '{}',
  first_seen_at timestamptz not null default now(),
  last_trade_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(chain, token_address)
);

create index if not exists radar_current_score_idx on public.radar_current(score desc, updated_at desc);

create table if not exists public.signals (
  id uuid primary key default gen_random_uuid(),
  chain text not null,
  token_address text not null,
  symbol text not null,
  score integer not null,
  signal_type text not null,
  reason text not null,
  buyers_5m integer not null default 0,
  buyers_15m integer not null default 0,
  buyers_60m integer not null default 0,
  sellers_15m integer not null default 0,
  net_flow_15m numeric not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists signals_recent_idx on public.signals(created_at desc);
create index if not exists signals_token_idx on public.signals(chain, token_address, created_at desc);

create table if not exists public.collector_state (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.collector_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  status text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  events_received integer not null default 0,
  events_inserted integer not null default 0,
  affected_tokens integer not null default 0,
  alerts_sent integer not null default 0,
  api_latency_ms integer,
  duration_ms integer,
  error text
);

create index if not exists collector_runs_started_idx on public.collector_runs(started_at desc);

-- A separate safe projection table avoids exposing raw wallet/trader keys.
drop view if exists public.radar_recent_trades;
create table if not exists public.radar_recent_trades_public (
  id text primary key,
  trader_label text not null default 'Tracked trader',
  side text not null check (side in ('BUY','SELL')),
  symbol text not null,
  amount_usd numeric not null default 0,
  executed_at timestamptz not null
);

create index if not exists radar_recent_trades_public_executed_idx
  on public.radar_recent_trades_public(executed_at desc);

alter table public.traders enable row level security;
alter table public.wallets enable row level security;
alter table public.trades enable row level security;
alter table public.radar_current enable row level security;
alter table public.signals enable row level security;
alter table public.collector_state enable row level security;
alter table public.collector_runs enable row level security;
alter table public.radar_recent_trades_public enable row level security;

-- Remove default Data API privileges first. Worker writes use a server-side secret/service role key.
revoke all on table public.traders from anon, authenticated;
revoke all on table public.wallets from anon, authenticated;
revoke all on table public.trades from anon, authenticated;
revoke all on table public.radar_current from anon, authenticated;
revoke all on table public.signals from anon, authenticated;
revoke all on table public.collector_state from anon, authenticated;
revoke all on table public.collector_runs from anon, authenticated;
revoke all on table public.radar_recent_trades_public from anon, authenticated;

-- Preview needs only these four read surfaces.
grant select on table public.radar_current to anon;
grant select on table public.collector_runs to anon;
grant select on table public.traders to anon;
grant select on table public.radar_recent_trades_public to anon;

-- Idempotent read policies.
drop policy if exists "anon read radar" on public.radar_current;
create policy "anon read radar" on public.radar_current for select to anon using (true);

drop policy if exists "anon read collector health" on public.collector_runs;
create policy "anon read collector health" on public.collector_runs for select to anon using (true);

drop policy if exists "anon read traders" on public.traders;
create policy "anon read traders" on public.traders for select to anon using (status = 'active');

drop policy if exists "anon read recent trades" on public.radar_recent_trades_public;
create policy "anon read recent trades" on public.radar_recent_trades_public for select to anon using (true);

notify pgrst, 'reload schema';
