import {createClient} from '@supabase/supabase-js';
const $=selector=>document.querySelector(selector);
const state={db:null,user:null,profile:null,vehicles:[],kind:'',vehicle:'',page:0,post:null,edit:null,report:null,sequence:0};
const label={question:'질문',review:'실사용 후기'};
const message=(selector,text)=>{$(selector).textContent=text;};
function el(tag,text,cls){const node=document.createElement(tag);if(text!=null)node.textContent=text;if(cls)node.className=cls;return node;}
function button(text,action){const node=el('button',text);node.type='button';node.addEventListener('click',()=>Promise.resolve(action()).catch(error=>message('#actionStatus',friendly(error))));return node;}
function friendly(error){const code=error?.code;const msg=String(error?.message||'');if(code==='23505')return '이미 사용 중인 닉네임이거나 접수한 신고입니다.';if(/rate_limit/.test(msg))return '잠시 후 다시 작성해 주세요.';if(/profile_required/.test(msg))return '먼저 닉네임을 설정해 주세요.';if(/not_allowed|not_found/.test(msg))return '삭제되었거나 접근할 수 없는 글입니다.';if(/auth_required/.test(msg))return '로그인 후 다시 시도해 주세요.';return '처리하지 못했습니다. 입력한 내용은 유지됩니다. 잠시 후 다시 시도해 주세요.';}
function date(value){return new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
function vehicleName(id){const v=state.vehicles.find(v=>v.id===id);return v?`${v.maker} ${v.name}`:'이전 등록 차종';}
function metadata(row,withVehicle=false){const node=el('div',null,'post-meta');if(withVehicle)node.append(el('span',vehicleName(row.vehicle_id)),el('span',label[row.kind],'post-type'));node.append(el('span',row.author_nickname),el('time',date(row.created_at)));return node;}
function setUrl(post=null){const url=new URL(location.href);url.searchParams.delete('code');url.searchParams.delete('error');url.searchParams.delete('error_description');if(post)url.searchParams.set('post',post);else url.searchParams.delete('post');if(state.vehicle)url.searchParams.set('vehicle',state.vehicle);else url.searchParams.delete('vehicle');if(state.kind)url.searchParams.set('kind',state.kind);else url.searchParams.delete('kind');history.pushState({},'',url);}
async function mutate(action,payload){if(!state.db||!state.user)throw Error('auth_required');const{data,error}=await state.db.rpc('pmc_write',{action,payload});if(error)throw error;return data;}
async function busy(form,status,task){const submit=form.querySelector('[type=submit]');if(submit.disabled)return;submit.disabled=true;message(status,'');try{await task();}catch(error){message(status,friendly(error));}finally{submit.disabled=false;}}
async function authenticate(){if(!state.db)return false;if(!state.user){await login();return false;}if(!state.profile){$('#profile').showModal();return false;}return true;}
async function login(){if(!state.db)return;const returnUrl=new URL('./',location.href);returnUrl.search=new URL(location.href).search;returnUrl.searchParams.delete('code');const{error}=await state.db.auth.signInWithOAuth({provider:'google',options:{redirectTo:returnUrl.href}});if(error)message('#actionStatus','구글 로그인을 시작하지 못했습니다. 잠시 후 다시 시도해 주세요.');}
async function refreshAccount(session){state.user=session?.user||null;state.profile=null;$('#login').hidden=!!state.user;$('#logout').hidden=!state.user;message('#accountName','');if(state.user){const{data,error}=await state.db.from('pmc_profiles').select('nickname').eq('id',state.user.id).maybeSingle();if(error){message('#actionStatus','회원 정보를 불러오지 못했습니다. 새로고침 후 다시 시도해 주세요.');return;}state.profile=data;message('#accountName',data?.nickname||'닉네임 미설정');}if(state.post)renderPostActions();}
function fillVehicles(){const query=$('#vehicleQuery').value.trim().toLocaleLowerCase();const visible=state.vehicles.filter(v=>`${v.maker} ${v.name}`.toLocaleLowerCase().includes(query)||v.id===state.vehicle);const select=$('#vehicleFilter');select.replaceChildren(new Option('모든 차종',''),...visible.map(v=>new Option(`${v.maker} ${v.name}`,v.id)));select.value=state.vehicle;}
async function list(reset=true){message('#boardName',state.vehicle?vehicleName(state.vehicle):'모든 차종');if(!state.db)return;if(reset){state.page=0;$('#posts').replaceChildren();}const ticket=++state.sequence;$('#loadMore').hidden=true;message('#listStatus','글을 불러오는 중입니다.');let query=state.db.from('pmc_posts').select('id,vehicle_id,kind,title,author_nickname,created_at').eq('status','published').order('created_at',{ascending:false}).order('id',{ascending:false}).range(state.page*20,state.page*20+20);if(state.vehicle)query=query.eq('vehicle_id',state.vehicle);if(state.kind)query=query.eq('kind',state.kind);const{data,error}=await query;if(ticket!==state.sequence)return;if(error){message('#listStatus','글을 불러오지 못했습니다.');$('#listStatus').append(button('다시 시도',()=>list(reset)));return;}message('#listStatus',!data.length&&reset?'아직 등록된 글이 없습니다. 첫 질문이나 후기를 남겨주세요.':'');for(const row of data.slice(0,20)){const li=el('li');const a=el('a',null,'post-link');const url=new URL(location.href);url.searchParams.set('post',row.id);a.href=url;const h=el('h2',row.title);a.append(metadata(row,true),h);a.addEventListener('click',event=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();setUrl(row.id);void openPost(row.id);});li.append(a);$('#posts').append(li);}$('#loadMore').hidden=data.length<=20;message('#boardName',state.vehicle?vehicleName(state.vehicle):'모든 차종');}
function renderPostActions(){const row=state.post;if(!row)return;const target=$('#postActions');target.replaceChildren(button('신고',()=>openReport('post',row.id)));if(state.user?.id===row.author_id){target.append(button('수정',()=>openEditor(row)),button('삭제',async()=>{if(!confirm('글을 삭제할까요? 이 작업은 되돌릴 수 없습니다.'))return;await mutate('delete_post',{id:row.id});await showList();}));}}
async function openPost(id){if(!state.db)return;const ticket=++state.sequence;$('#boardView').hidden=true;$('#postView').hidden=false;state.post=null;$('#postActions').replaceChildren();$('#postContent').replaceChildren(el('p','글을 불러오는 중입니다.'));$('#comments').replaceChildren();$('#commentForm').hidden=true;message('#commentStatus','');const{data,error}=await state.db.from('pmc_posts').select('id,vehicle_id,kind,title,body,author_id,author_nickname,created_at').eq('id',id).eq('status','published').maybeSingle();if(ticket!==state.sequence)return;if(error||!data){$('#postContent').replaceChildren(el('h2',error?'글을 불러오지 못했습니다.':'삭제되었거나 공개되지 않은 글입니다.'));if(error)$('#postContent').append(button('다시 시도',()=>openPost(id)));return;}state.post=data;$('#postContent').replaceChildren(metadata(data,true),el('h2',data.title),el('p',data.body,'post-body'));renderPostActions();$('#commentForm').hidden=false;await comments(id);}
async function comments(postId){message('#commentStatus','댓글을 불러오는 중입니다.');const{data,error}=await state.db.from('pmc_comments').select('id,post_id,body,author_id,author_nickname,created_at').eq('post_id',postId).eq('status','published').order('created_at').order('id').limit(100);if(state.post?.id!==postId)return;$('#comments').replaceChildren();if(error){message('#commentStatus','댓글을 불러오지 못했습니다.');$('#commentStatus').append(button('다시 시도',()=>comments(postId)));return;}message('#commentStatus',data.length?'':'첫 댓글을 남겨주세요.');for(const row of data){const li=el('li');li.append(metadata(row),el('p',row.body,'comment-body'));const actions=el('div',null,'comment-actions');actions.append(button('신고',()=>openReport('comment',row.id)));if(state.user?.id===row.author_id){actions.append(button('수정',()=>{const form=el('form');const input=document.createElement('textarea');input.value=row.body;input.maxLength=2000;input.required=true;input.setAttribute('aria-label','댓글 수정');const submit=el('button','저장');submit.type='submit';const status=el('p');status.setAttribute('role','status');form.append(input,submit,button('취소',()=>comments(postId)),status);form.addEventListener('submit',async event=>{event.preventDefault();if(submit.disabled)return;submit.disabled=true;try{await mutate('edit_comment',{id:row.id,body:input.value.trim()});await comments(postId);}catch(error){status.textContent=friendly(error);submit.disabled=false;}});li.replaceChildren(form);input.focus();}),button('삭제',async()=>{if(!confirm('댓글을 삭제할까요?'))return;await mutate('delete_comment',{id:row.id});await comments(postId);}));}li.append(actions);$('#comments').append(li);}if(data.length===100)$('#comments').append(el('li','댓글은 오래된 순서로 최대 100개까지 표시합니다.'));}
async function showList(){state.post=null;setUrl();$('#postView').hidden=true;$('#boardView').hidden=false;await list();}
async function openEditor(row=null){if(!await authenticate())return;state.edit=row?.id||null;const form=$('#postForm');form.reset();form.elements.vehicle_id.value=row?.vehicle_id||state.vehicle;form.elements.kind.value=row?.kind||'question';form.elements.title.value=row?.title||'';form.elements.body.value=row?.body||'';message('#editorTitle',row?'글 수정':'글쓰기');message('#editorStatus','');$('#editor').showModal();}
async function openReport(type,id){if(!await authenticate())return;state.report={type,id};$('#reportForm').reset();message('#reportStatus','');$('#report').showModal();}
$('#filterForm').addEventListener('submit',event=>event.preventDefault());$('#vehicleQuery').addEventListener('input',fillVehicles);$('#vehicleFilter').addEventListener('change',()=>{state.vehicle=$('#vehicleFilter').value;setUrl();void list();});document.querySelectorAll('[data-kind]').forEach(node=>node.addEventListener('click',()=>{state.kind=node.dataset.kind;document.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b===node)));setUrl();void list();}));$('#loadMore').addEventListener('click',()=>{state.page++;void list(false);});$('#login').addEventListener('click',login);$('#logout').addEventListener('click',async()=>{const{error}=await state.db.auth.signOut();if(error)message('#actionStatus','로그아웃하지 못했습니다. 다시 시도해 주세요.');else await refreshAccount(null);});$('#writePost').addEventListener('click',()=>void openEditor());$('#backToList').addEventListener('click',()=>void showList());document.querySelectorAll('[data-close]').forEach(node=>node.addEventListener('click',()=>$('#'+node.dataset.close).close()));
$('#postForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void busy(form,'#editorStatus',async()=>{const payload=Object.fromEntries(new FormData(form));payload.title=payload.title.trim();payload.body=payload.body.trim();if(state.edit)payload.id=state.edit;const id=await mutate(state.edit?'edit_post':'create_post',payload);$('#editor').close();setUrl(id);await openPost(id);});});
$('#profileForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void busy(form,'#profileStatus',async()=>{await mutate('profile',{nickname:form.elements.nickname.value.trim()});const{data}=await state.db.auth.getSession();await refreshAccount(data.session);$('#profile').close();message('#actionStatus','닉네임을 저장했습니다. 글이나 댓글을 작성할 수 있습니다.');});});
$('#commentForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!await authenticate())return;const postId=state.post?.id;if(!postId)return;await busy(form,'#commentStatus',async()=>{await mutate('create_comment',{post_id:postId,body:form.elements.body.value.trim()});form.reset();await comments(postId);});});
$('#reportForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void busy(form,'#reportStatus',async()=>{await mutate('report',{...state.report,...Object.fromEntries(new FormData(form))});$('#report').close();message('#actionStatus','신고를 접수했습니다.');});});
async function route(){const url=new URL(location.href);state.vehicle=state.vehicles.some(v=>v.id===url.searchParams.get('vehicle'))?url.searchParams.get('vehicle'):'';state.kind=Object.hasOwn(label,url.searchParams.get('kind'))?url.searchParams.get('kind'):'';fillVehicles();document.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===state.kind)));if(url.searchParams.has('post'))await openPost(url.searchParams.get('post'));else{$('#postView').hidden=true;$('#boardView').hidden=false;await list();}}
addEventListener('popstate',()=>void route());
async function start(){try{const[configRes,vehicleRes]=await Promise.all([fetch('./config.json'),fetch('./vehicles.json')]);if(!configRes.ok||!vehicleRes.ok)throw Error('load');const config=await configRes.json();state.vehicles=(await vehicleRes.json()).sort((a,b)=>`${a.maker} ${a.name}`.localeCompare(`${b.maker} ${b.name}`,'ko'));$('#editorVehicle').append(...state.vehicles.map(v=>new Option(`${v.maker} ${v.name}`,v.id)));fillVehicles();if(!config.url||!config.key){$('#serviceNotice').hidden=false;message('#serviceNotice','커뮤니티 연결 전 미리보기입니다. 글과 댓글은 아직 게시되지 않습니다.');message('#listStatus','차종을 검색해 게시판 구성을 확인할 수 있습니다.');$('#login').disabled=true;$('#writePost').disabled=true;return;}state.db=createClient(config.url,config.key,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});const{data,error}=await state.db.auth.getSession();if(error)message('#actionStatus','로그인을 완료하지 못했습니다. 다시 로그인해 주세요.');await refreshAccount(data.session);state.db.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>void refreshAccount(session),0);});await route();}catch{message('#listStatus','화면을 불러오지 못했습니다. 새로고침해 주세요.');$('#login').disabled=true;$('#writePost').disabled=true;}}
void start();
