import {preparePhoto} from './photos.js';
import {createClient} from '@supabase/supabase-js';
const $=selector=>document.querySelector(selector);
const state={db:null,user:null,profile:null,vehicles:[],kind:'free',vehicle:'',query:'',photos:[],photoBusy:false,page:0,post:null,edit:null,report:null,sequence:0};
const label={free:'자유게시판',question:'질문',review:'실사용 후기'};
const message=(selector,text)=>{$(selector).textContent=text;};
function el(tag,text,cls){const node=document.createElement(tag);if(text!=null)node.textContent=text;if(cls)node.className=cls;return node;}
function button(text,action){const node=el('button',text);node.type='button';node.addEventListener('click',()=>Promise.resolve(action()).catch(error=>message('#actionStatus',friendly(error))));return node;}
function friendly(error){const code=error?.code;const msg=String(error?.message||'');if(code==='23505')return '이미 사용 중인 닉네임이거나 접수한 신고입니다.';if(/rate_limit/.test(msg))return '잠시 후 다시 작성해 주세요.';if(/profile_required/.test(msg))return '먼저 닉네임을 설정해 주세요.';if(/not_allowed|not_found/.test(msg))return '삭제되었거나 접근할 수 없는 글입니다.';if(/auth_required/.test(msg))return '로그인 후 다시 시도해 주세요.';return '처리하지 못했습니다. 입력한 내용은 유지됩니다. 잠시 후 다시 시도해 주세요.';}
function date(value){return new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
function vehicleName(id){const v=state.vehicles.find(v=>v.id===id);return v?`${v.maker} ${v.name}`:'이전 등록 차종';}
function metadata(row,withVehicle=false){const node=el('div',null,'post-meta');if(withVehicle){if(row.vehicle_id)node.append(el('span',vehicleName(row.vehicle_id)));node.append(el('span',label[row.kind],'post-type'));}node.append(el('span',row.author_nickname),el('time',date(row.created_at)));return node;}
function setUrl(post=null){const url=new URL(location.href);url.searchParams.delete('code');url.searchParams.delete('error');url.searchParams.delete('error_description');if(post)url.searchParams.set('post',post);else url.searchParams.delete('post');if(state.vehicle)url.searchParams.set('vehicle',state.vehicle);else url.searchParams.delete('vehicle');if(state.kind)url.searchParams.set('kind',state.kind);else url.searchParams.delete('kind');if(state.query)url.searchParams.set('q',state.query);else url.searchParams.delete('q');history.pushState({},'',url);}
async function mutate(action,payload){if(!state.db||!state.user)throw Error('auth_required');const{data,error}=await state.db.rpc('pmc_write',{action,payload});if(error)throw error;return data;}
async function busy(form,status,task){const submit=form.querySelector('[type=submit]');if(submit.disabled)return;submit.disabled=true;message(status,'');try{await task();}catch(error){message(status,friendly(error));}finally{submit.disabled=false;}}
async function authenticate(){if(!state.db)return false;if(!state.user){await login();return false;}if(!state.profile){$('#profile').showModal();return false;}return true;}
async function login(){if(!state.db)return;const returnUrl=new URL('./',location.href);returnUrl.search=new URL(location.href).search;returnUrl.searchParams.delete('code');const{error}=await state.db.auth.signInWithOAuth({provider:'google',options:{redirectTo:returnUrl.href}});if(error)message('#actionStatus','구글 로그인을 시작하지 못했습니다. 잠시 후 다시 시도해 주세요.');}
async function refreshAccount(session){state.user=session?.user||null;state.profile=null;$('#login').hidden=!!state.user;$('#logout').hidden=!state.user;message('#accountName','');if(state.user){const{data,error}=await state.db.from('pmc_profiles').select('nickname').eq('id',state.user.id).maybeSingle();if(error){message('#actionStatus','회원 정보를 불러오지 못했습니다. 새로고침 후 다시 시도해 주세요.');return;}state.profile=data;message('#accountName',data?.nickname||'닉네임 미설정');}if(state.post)renderPostActions();}
function fillVehicles(){
 const query=$('#vehicleQuery').value.trim().replace(/\s/g,'').toLocaleLowerCase();
 const box=$('#vehicleResults');box.replaceChildren();box.hidden=!query;$('#vehicleQuery').setAttribute('aria-expanded',String(!!query));
 if(!query)return;
 const matches=state.vehicles.filter(v=>(v.maker+v.name).replace(/\s/g,'').toLocaleLowerCase().includes(query));
 for(const v of matches.slice(0,8))box.append(button(v.maker+' '+v.name,()=>chooseVehicle(v)));
 if(!matches.length)box.append(el('p','일치하는 차종이 없습니다.'));
 if(matches.length>8)box.append(el('p','이름을 더 입력하면 결과를 좁힐 수 있습니다.'));
}
function selectVehicleLabel(){const node=$('#selectedVehicle');node.replaceChildren();node.hidden=!state.vehicle;if(state.vehicle)node.append(el('span',vehicleName(state.vehicle)),button('선택 해제',()=>chooseVehicle(null)));}
async function chooseVehicle(v){state.vehicle=v?.id||'';$('#vehicleQuery').value='';fillVehicles();selectVehicleLabel();setUrl();await list();}
async function list(reset=true){message('#boardName',label[state.kind]+(state.vehicle?' · '+vehicleName(state.vehicle):''));if(!state.db)return;if(reset){state.page=0;$('#posts').replaceChildren();}const ticket=++state.sequence;$('#loadMore').hidden=true;message('#listStatus','글을 불러오는 중입니다.');let query=state.db.from('pmc_posts').select('id,vehicle_id,kind,title,author_nickname,created_at').eq('status','published').order('created_at',{ascending:false}).order('id',{ascending:false}).range(state.page*20,state.page*20+20);if(state.vehicle){const car=state.vehicles.find(v=>v.id===state.vehicle);const name=(car?.name||'').replace(/[^\p{L}\p{N}\s-]/gu,' ').trim();query=query.or('vehicle_id.eq.'+state.vehicle+(name?',title.ilike.%'+name+'%,body.ilike.%'+name+'%':''));}if(state.kind)query=query.eq('kind',state.kind);if(state.query){const term=state.query.replace(/[%,()._*\\]/g,' ').trim();if(term)query=query.or('title.ilike.%'+term+'%,body.ilike.%'+term+'%');}const{data,error}=await query;if(ticket!==state.sequence)return;if(error){message('#listStatus','글을 불러오지 못했습니다.');$('#listStatus').append(button('다시 시도',()=>list(reset)));return;}message('#listStatus',!data.length&&reset?state.query||state.vehicle?'조건에 맞는 글이 없습니다. 검색 조건을 바꿔보세요.':'아직 등록된 글이 없습니다. 첫 이야기를 남겨주세요.':'');for(const row of data.slice(0,20)){const li=el('li');const a=el('a',null,'post-link');const url=new URL(location.href);url.searchParams.set('post',row.id);a.href=url;const h=el('h2',row.title);a.append(metadata(row,true),h);a.addEventListener('click',event=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();setUrl(row.id);void openPost(row.id);});li.append(a);$('#posts').append(li);}$('#loadMore').hidden=data.length<=20;message('#boardName',label[state.kind]+(state.vehicle?' · '+vehicleName(state.vehicle):''));}
function renderPostActions(){const row=state.post;if(!row)return;const target=$('#postActions');target.replaceChildren(button('신고',()=>openReport('post',row.id)));if(state.user?.id===row.author_id){target.append(button('수정',()=>openEditor(row)),button('삭제',async()=>{if(!confirm('글을 삭제할까요? 이 작업은 되돌릴 수 없습니다.'))return;await mutate('delete_post',{id:row.id});await removeFiles(row.photo_paths||[]);await showList();}));}}
async function openPost(id){if(!state.db)return;const ticket=++state.sequence;$('#boardView').hidden=true;$('#postView').hidden=false;state.post=null;$('#postActions').replaceChildren();$('#postContent').replaceChildren(el('p','글을 불러오는 중입니다.'));$('#comments').replaceChildren();$('#commentForm').hidden=true;message('#commentStatus','');const{data,error}=await state.db.from('pmc_posts').select('id,vehicle_id,kind,title,body,author_id,author_nickname,created_at,photo_paths').eq('id',id).eq('status','published').maybeSingle();if(ticket!==state.sequence)return;if(error||!data){$('#postContent').replaceChildren(el('h2',error?'글을 불러오지 못했습니다.':'삭제되었거나 공개되지 않은 글입니다.'));if(error)$('#postContent').append(button('다시 시도',()=>openPost(id)));return;}state.post=data;$('#postContent').replaceChildren(metadata(data,true),el('h2',data.title),el('p',data.body,'post-body'));renderPostActions();$('#commentForm').hidden=false;await Promise.all([showPhotos(data),comments(id)]);}
async function comments(postId){message('#commentStatus','댓글을 불러오는 중입니다.');const{data,error}=await state.db.from('pmc_comments').select('id,post_id,body,author_id,author_nickname,created_at').eq('post_id',postId).eq('status','published').order('created_at').order('id').limit(100);if(state.post?.id!==postId)return;$('#comments').replaceChildren();if(error){message('#commentStatus','댓글을 불러오지 못했습니다.');$('#commentStatus').append(button('다시 시도',()=>comments(postId)));return;}message('#commentStatus',data.length?'':'첫 댓글을 남겨주세요.');for(const row of data){const li=el('li');li.append(metadata(row),el('p',row.body,'comment-body'));const actions=el('div',null,'comment-actions');actions.append(button('신고',()=>openReport('comment',row.id)));if(state.user?.id===row.author_id){actions.append(button('수정',()=>{const form=el('form');const input=document.createElement('textarea');input.value=row.body;input.maxLength=2000;input.required=true;input.setAttribute('aria-label','댓글 수정');const submit=el('button','저장');submit.type='submit';const status=el('p');status.setAttribute('role','status');form.append(input,submit,button('취소',()=>comments(postId)),status);form.addEventListener('submit',async event=>{event.preventDefault();if(submit.disabled)return;submit.disabled=true;try{await mutate('edit_comment',{id:row.id,body:input.value.trim()});await comments(postId);}catch(error){status.textContent=friendly(error);submit.disabled=false;}});li.replaceChildren(form);input.focus();}),button('삭제',async()=>{if(!confirm('댓글을 삭제할까요?'))return;await mutate('delete_comment',{id:row.id});await comments(postId);}));}li.append(actions);$('#comments').append(li);}if(data.length===100)$('#comments').append(el('li','댓글은 오래된 순서로 최대 100개까지 표시합니다.'));}
async function showList(){state.post=null;setUrl();$('#postView').hidden=true;$('#boardView').hidden=false;await list();}
async function openEditor(row=null){if(!await authenticate())return;state.edit=row?.id||null;const form=$('#postForm');form.reset();resetPhotos();state.photos=(row?.photo_paths||[]).map(path=>({path}));form.elements.kind.value=row?.kind||state.kind;void renderPhotoPreviews();form.elements.title.value=row?.title||'';form.elements.body.value=row?.body||'';message('#editorTitle',row?'글 수정':'글쓰기');message('#editorStatus','');$('#editor').showModal();}
async function openReport(type,id){if(!await authenticate())return;state.report={type,id};$('#reportForm').reset();message('#reportStatus','');$('#report').showModal();}
$('#filterForm').addEventListener('submit',event=>event.preventDefault());$('#vehicleQuery').addEventListener('input',fillVehicles);let searchTimer;$('#postQuery').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=$('#postQuery').value.trim();setUrl();void list();},250);});$('#vehicleQuery').addEventListener('keydown',event=>{if(event.key==='ArrowDown'){$('#vehicleResults button')?.focus();event.preventDefault();}if(event.key==='Escape'){$('#vehicleResults').hidden=true;$('#vehicleQuery').setAttribute('aria-expanded','false');}});document.querySelectorAll('[data-kind]').forEach(node=>node.addEventListener('click',()=>{state.kind=node.dataset.kind;document.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b===node)));setUrl();void list();}));$('#loadMore').addEventListener('click',()=>{state.page++;void list(false);});$('#login').addEventListener('click',login);$('#logout').addEventListener('click',async()=>{const{error}=await state.db.auth.signOut();if(error)message('#actionStatus','로그아웃하지 못했습니다. 다시 시도해 주세요.');else await refreshAccount(null);});$('#writePost').addEventListener('click',()=>void openEditor());$('#backToList').addEventListener('click',()=>void showList());document.querySelectorAll('[data-close]').forEach(node=>node.addEventListener('click',()=>$('#'+node.dataset.close).close()));
$('#postForm').addEventListener('submit',event=>{event.preventDefault();if(state.photoBusy)return;const form=event.currentTarget;void busy(form,'#editorStatus',async()=>{
 const payload=Object.fromEntries(new FormData(form));payload.title=payload.title.trim();payload.body=payload.body.trim();if(state.edit)payload.id=state.edit;
 const actor=state.user.id;const added=[];const old=state.post?.photo_paths||[];
 state.photoBusy=true;lockPhotoEditor(true);
 let id;
 try{for(const photo of state.photos){if(!photo.path){const path=actor+'/'+crypto.randomUUID()+'.webp';const{error}=await state.db.storage.from('pmc-post-images').upload(path,photo.blob,{contentType:'image/webp',upsert:false});if(error)throw error;photo.path=path;added.push(path);}}
 payload.photos=state.photos.map(p=>p.path);id=await mutate(state.edit?'edit_post':'create_post',payload);
 }catch(error){await removeFiles(added);for(const p of state.photos)if(added.includes(p.path))delete p.path;throw error;}
 finally{state.photoBusy=false;lockPhotoEditor(false);}
 await removeFiles(old.filter(path=>!payload.photos.includes(path)));$('#editor').close();resetPhotos();setUrl(id);await openPost(id);
 });});
$('#profileForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void busy(form,'#profileStatus',async()=>{await mutate('profile',{nickname:form.elements.nickname.value.trim()});const{data}=await state.db.auth.getSession();await refreshAccount(data.session);$('#profile').close();message('#actionStatus','닉네임을 저장했습니다. 글이나 댓글을 작성할 수 있습니다.');});});
$('#commentForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!await authenticate())return;const postId=state.post?.id;if(!postId)return;await busy(form,'#commentStatus',async()=>{await mutate('create_comment',{post_id:postId,body:form.elements.body.value.trim()});form.reset();await comments(postId);});});
$('#reportForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;void busy(form,'#reportStatus',async()=>{await mutate('report',{...state.report,...Object.fromEntries(new FormData(form))});$('#report').close();message('#actionStatus','신고를 접수했습니다.');});});
async function route(){const url=new URL(location.href);state.vehicle=state.vehicles.some(v=>v.id===url.searchParams.get('vehicle'))?url.searchParams.get('vehicle'):'';state.kind=Object.hasOwn(label,url.searchParams.get('kind'))?url.searchParams.get('kind'):'free';state.query=url.searchParams.get('q')||'';$('#postQuery').value=state.query;fillVehicles();selectVehicleLabel();document.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===state.kind)));if(url.searchParams.has('post'))await openPost(url.searchParams.get('post'));else{$('#postView').hidden=true;$('#boardView').hidden=false;await list();}}
addEventListener('popstate',()=>void route());
async function start(){try{const[configRes,vehicleRes]=await Promise.all([fetch('./config.json'),fetch('./vehicles.json')]);if(!configRes.ok||!vehicleRes.ok)throw Error('load');const config=await configRes.json();state.vehicles=(await vehicleRes.json()).sort((a,b)=>`${a.maker} ${a.name}`.localeCompare(`${b.maker} ${b.name}`,'ko'));fillVehicles();if(!config.url||!config.key){$('#serviceNotice').hidden=false;message('#serviceNotice','커뮤니티 연결 전 미리보기입니다. 글과 댓글은 아직 게시되지 않습니다.');message('#listStatus','차종을 검색해 게시판 구성을 확인할 수 있습니다.');$('#login').disabled=true;$('#writePost').disabled=true;return;}state.db=createClient(config.url,config.key,{auth:{flowType:'pkce',detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});const{data,error}=await state.db.auth.getSession();if(error)message('#actionStatus','로그인을 완료하지 못했습니다. 다시 로그인해 주세요.');await refreshAccount(data.session);state.db.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>void refreshAccount(session),0);});await route();}catch{message('#listStatus','화면을 불러오지 못했습니다. 새로고침해 주세요.');$('#login').disabled=true;$('#writePost').disabled=true;}}
function lockPhotoEditor(locked){$('#postForm').querySelectorAll('input,textarea,button').forEach(node=>node.disabled=locked);}
function resetPhotos(){for(const p of state.photos)if(p.blob&&p.url)URL.revokeObjectURL(p.url);state.photos=[];$('#photoPreviews').replaceChildren();message('#photoStatus','');}
async function signedPhoto(path){const{data,error}=await state.db.storage.from('pmc-post-images').createSignedUrl(path,300);if(error)throw error;return data.signedUrl;}
async function removeFiles(paths){if(!paths.length)return;const{error}=await state.db.storage.from('pmc-post-images').remove(paths);if(error)message('#actionStatus','글은 저장되었습니다. 첨부 파일 정리는 완료되지 않아 문의가 필요합니다.');}
async function renderPhotoPreviews(){const target=$('#photoPreviews');target.replaceChildren();for(const photo of state.photos){const li=el('li');const img=el('img');img.alt='첨부 사진 미리보기';li.append(img,button('사진 삭제',()=>{if(state.photoBusy)return;if(photo.blob&&photo.url)URL.revokeObjectURL(photo.url);state.photos=state.photos.filter(p=>p!==photo);void renderPhotoPreviews();}));target.append(li);try{img.src=photo.url||await signedPhoto(photo.path);}catch{img.replaceWith(el('span','사진을 불러오지 못했습니다.'));}}}
async function showPhotos(post){const gallery=el('div',null,'post-photos');$('#postContent').append(gallery);for(const path of post.photo_paths||[]){const img=el('img');img.alt='작성자가 첨부한 사진';img.loading='lazy';img.addEventListener('error',()=>img.replaceWith(el('p','사진을 불러오지 못했습니다. 새로고침해 주세요.')),{once:true});gallery.append(img);try{img.src=await signedPhoto(path);}catch{img.replaceWith(el('p','사진을 불러오지 못했습니다.'));}}}
$('#postPhotos').addEventListener('change',async event=>{if(state.photoBusy)return;const files=[...event.target.files];event.target.value='';message('#photoStatus','');if(state.photos.length+files.length>5){message('#photoStatus','사진은 최대 5장까지 첨부할 수 있습니다.');return;}state.photoBusy=true;lockPhotoEditor(true);try{for(const file of files)state.photos.push(await preparePhoto(file));}catch(error){message('#photoStatus',error.message);}finally{await renderPhotoPreviews();state.photoBusy=false;lockPhotoEditor(false);}});
$('#editor').addEventListener('cancel',event=>{if(state.photoBusy)event.preventDefault();});
$('#editor').addEventListener('close',()=>{if(!state.photoBusy)resetPhotos();});
void start();
