import 'jsr:@supabase/functions-js/edge-runtime.d.ts'

type Wallet={address:string;traderKey:string;traderLabel:string;clusterKey:string;traderScore:number}
type Candidate={signature:string;wallet:string;mint:string;side:'BUY'|'SELL';amountToken:number;executedAt:string}
type Market={symbol:string;priceUsd:number|null;liquidityUsd:number|null;marketCapUsd:number|null}
const SB_URL=Deno.env.get('SUPABASE_URL')||''
const RPC_URL=Deno.env.get('SOLANA_RPC_URL')||'https://api.mainnet.solana.com'
const BASE_MINTS=new Set(['So11111111111111111111111111111111111111112','EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v','Es9vMFrzaCERmJfrF4H2FYD7Vt2B6x6qS31Yf3ZZ3'])
function secretKey(){try{const v=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');if(v.default)return String(v.default)}catch{}return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''}
const SB_KEY=secretKey(),sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms)),num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0},nullable=(v:unknown)=>{const n=Number(v);return v==null||!Number.isFinite(n)?null:n}
async function db(path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('apikey',SB_KEY);if(!h.has('content-type'))h.set('content-type','application/json');const r=await fetch(`${SB_URL}/rest/v1/${path}`,{...init,headers:h}),t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t.slice(0,300)}`);return t?JSON.parse(t):null}
async function state(key:string){const r=await db(`collector_state?key=eq.${encodeURIComponent(key)}&select=value&limit=1`) as Array<{value:Record<string,unknown>}>;return r?.[0]?.value||{}}
async function setState(key:string,value:Record<string,unknown>){await db('collector_state?on_conflict=key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{key,value,updated_at:new Date().toISOString()}])})}
async function expectedSecret(){const v=await state('rpc_poll_secret');return typeof v.secret==='string'?v.secret:''}
async function wallets():Promise<Wallet[]>{const ws=await db('wallets?is_active=eq.true&chain=eq.solana&select=address,cluster_id,trader_id&limit=5') as Array<{address:string;cluster_id:string|null;trader_id:string|null}>,ids=[...new Set(ws.map(w=>w.trader_id).filter(Boolean))] as string[],tm=new Map<string,any>();if(ids.length){const ts=await db(`traders?id=in.(${ids.map(encodeURIComponent).join(',')})&status=eq.active&select=id,external_key,label,score`) as any[];ts.forEach(t=>tm.set(t.id,t))}return ws.map(w=>{const t=w.trader_id?tm.get(w.trader_id):null,k=t?.external_key||w.address;return{address:w.address,traderKey:k,traderLabel:t?.label||k,clusterKey:w.cluster_id||k,traderScore:num(t?.score||50)}})}
let rpcId=0
async function rpc(method:string,params:unknown[]){await sleep(275);const r=await fetch(RPC_URL,{method:'POST',headers:{'content-type':'application/json','user-agent':'resonance-radar-feedback/0.1'},body:JSON.stringify({jsonrpc:'2.0',id:++rpcId,method,params})});if(r.status===429)throw new Error(`RPC_RATE_LIMIT:${r.headers.get('retry-after')||''}`);if(!r.ok)throw new Error(`RPC_HTTP_${r.status}`);const j=await r.json() as any;if(j.error)throw new Error(`RPC_${j.error.code}:${j.error.message}`);return j.result}
async function signatures(address:string,cursor:string|null){if(!cursor)return await rpc('getSignaturesForAddress',[address,{limit:1,commitment:'confirmed'}]) as any[];let all:any[]=[],before:string|undefined;for(let page=0;page<4;page++){const cfg:any={limit:10,commitment:'confirmed',until:cursor};if(before)cfg.before=before;const rows=await rpc('getSignaturesForAddress',[address,cfg]) as any[];all.push(...rows);if(rows.length<10)break;before=rows.at(-1)?.signature;if(!before)break}return all}
function uiAmount(x:any){const raw=num(x?.uiTokenAmount?.amount),dec=Math.max(0,num(x?.uiTokenAmount?.decimals));return raw/(10**dec)}
function tokenMap(rows:any[],owner:string){const out=new Map<string,number>();for(const x of rows||[]){if(x?.owner!==owner||!x?.mint)continue;out.set(x.mint,(out.get(x.mint)||0)+uiAmount(x))}return out}
function txCandidates(tx:any,wallet:string,signature:string):Candidate[]{if(!tx?.meta||tx.meta.err)return[];const pre=tokenMap(tx.meta.preTokenBalances,wallet),post=tokenMap(tx.meta.postTokenBalances,wallet),mints=new Set([...pre.keys(),...post.keys()]);let baseDelta=0;for(const mint of BASE_MINTS)baseDelta+=(post.get(mint)||0)-(pre.get(mint)||0);const keys=tx.transaction?.message?.accountKeys||[];const idx=keys.findIndex((x:any)=>(typeof x==='string'?x:x?.pubkey)===wallet);if(idx>=0&&tx.meta.preBalances?.[idx]!=null&&tx.meta.postBalances?.[idx]!=null)baseDelta+=(num(tx.meta.postBalances[idx])-num(tx.meta.preBalances[idx]))/1e9;const eps=1e-7,at=new Date(num(tx.blockTime)*1000).toISOString();const out:Candidate[]=[];for(const mint of mints){if(BASE_MINTS.has(mint))continue;const delta=(post.get(mint)||0)-(pre.get(mint)||0);if(Math.abs(delta)<=eps)continue;if(delta>0&&baseDelta<-eps)out.push({signature,wallet,mint,side:'BUY',amountToken:delta,executedAt:at});else if(delta<0&&baseDelta>eps)out.push({signature,wallet,mint,side:'SELL',amountToken:Math.abs(delta),executedAt:at})}return out}
async function market(mints:string[]){const out=new Map<string,Market>(),unique=[...new Set(mints)];for(let i=0;i<unique.length;i+=30){const batch=unique.slice(i,i+30);try{const r=await fetch(`https://api.dexscreener.com/tokens/v1/solana/${batch.join(',')}`,{headers:{accept:'application/json','user-agent':'resonance-radar-feedback/0.1'}});if(!r.ok)continue;const pairs=await r.json() as any[];for(const mint of batch){const ps=(Array.isArray(pairs)?pairs:[]).filter(p=>p?.baseToken?.address===mint).sort((a,b)=>num(b?.liquidity?.usd)-num(a?.liquidity?.usd)),p=ps[0];if(p)out.set(mint,{symbol:p.baseToken?.symbol||mint.slice(0,6).toUpperCase(),priceUsd:nullable(p.priceUsd),liquidityUsd:nullable(p.liquidity?.usd),marketCapUsd:nullable(p.marketCap)??nullable(p.fdv)})}}catch(e){console.error('dex',e)}}return out}
async function insert(candidates:Candidate[],wm:Map<string,Wallet>){if(!candidates.length)return 0;const mk=await market(candidates.map(c=>c.mint)),received=new Date().toISOString(),rows=candidates.flatMap(c=>{const w=wm.get(c.wallet);if(!w)return[];const m=mk.get(c.mint),price=m?.priceUsd??null;return[{provider_trade_id:`solana:${c.signature}:${c.wallet}:${c.mint}`,chain:'solana',wallet_address:c.wallet,trader_key:w.traderKey,trader_label:w.traderLabel,cluster_key:w.clusterKey,trader_score:w.traderScore,token_address:c.mint,symbol:m?.symbol||c.mint.slice(0,6).toUpperCase(),side:c.side,amount_usd:price==null?0:Math.round(c.amountToken*price*100)/100,amount_token:c.amountToken,price,liquidity_usd:m?.liquidityUsd??null,market_cap_usd:m?.marketCapUsd??null,tx_hash:c.signature,executed_at:c.executedAt,received_at:received}]});const inserted=await db('trades?on_conflict=provider_trade_id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=representation'},body:JSON.stringify(rows)}) as any[];await db('radar_recent_trades_public?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(rows.map(t=>({id:t.provider_trade_id,trader_label:t.trader_label||'Tracked trader',side:t.side,symbol:t.symbol,amount_usd:t.amount_usd,executed_at:t.executed_at}))) });return Array.isArray(inserted)?inserted.length:0}
async function triggerRecompute(){const s=await state('edge_cron_secret'),secret=typeof s.secret==='string'?s.secret:'';if(!secret)return;await fetch(`${SB_URL}/functions/v1/resonance-radar-collector`,{method:'POST',headers:{'content-type':'application/json','x-radar-cron-secret':secret},body:'{"action":"tick"}'})}
async function poll(){const started=Date.now(),ws=await wallets(),wm=new Map(ws.map(w=>[w.address,w])),all:Candidate[]=[],errors:string[]=[];for(const w of ws){const key=`rpc_cursor:${w.address}`,s=await state(key),cursor=typeof s.signature==='string'?s.signature:null;try{const sigs=await signatures(w.address,cursor);if(!cursor){const latest=sigs[0]?.signature;if(latest)await setState(key,{signature:latest,bootstrapped_at:new Date().toISOString()});continue}if(!sigs.length)continue;let ok=true,cs:Candidate[]=[];for(const item of [...sigs].reverse()){if(item.err)continue;try{const tx=await rpc('getTransaction',[item.signature,{encoding:'jsonParsed',commitment:'confirmed',maxSupportedTransactionVersion:0}]);if(!tx){ok=false;break}cs.push(...txCandidates(tx,w.address,item.signature))}catch(e){ok=false;errors.push(`${w.traderLabel}:${e instanceof Error?e.message:String(e)}`);break}}if(ok){all.push(...cs);await setState(key,{signature:sigs[0].signature,updated_at:new Date().toISOString()})}}catch(e){errors.push(`${w.traderLabel}:${e instanceof Error?e.message:String(e)}`)}}const inserted=await insert(all,wm);if(inserted>0)await triggerRecompute();if(inserted>0||errors.length){await db('collector_runs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{source:'solana-public-rpc',status:errors.length?'partial':'ok',started_at:new Date(started).toISOString(),finished_at:new Date().toISOString(),events_received:all.length,events_inserted:inserted,affected_tokens:new Set(all.map(c=>c.mint)).size,alerts_sent:0,api_latency_ms:null,duration_ms:Date.now()-started,error:errors.length?errors.join('; ').slice(0,1800):null}])})}return{ok:true,mode:'feedback-rpc',wallets:ws.length,candidates:all.length,inserted,errors:errors.length}}
Deno.serve(async req=>{try{if(req.method==='GET'){const ws=await wallets();return Response.json({ok:true,service:'resonance-rpc-poller',rpc:RPC_URL.includes('api.mainnet.solana.com')?'public-mainnet':'custom',feedbackOnly:true,trackedWallets:ws.length})}if(req.method!=='POST')return Response.json({ok:false,error:'method_not_allowed'},{status:405});const expected=await expectedSecret();if(!expected||req.headers.get('x-radar-rpc-secret')!==expected)return Response.json({ok:false,error:'unauthorized'},{status:401});return Response.json(await poll())}catch(e){console.error(e);return Response.json({ok:false,error:e instanceof Error?e.message:'internal_error'},{status:500})}})
