import assert from "node:assert/strict";
import test from "node:test";
import { handleDeleteAccount } from "../supabase/functions/r1-delete-account/handler";
const id="b4a744ad-0716-47f4-a7b0-111111111111",now=Date.parse("2026-09-23T10:00:00Z");
const sid="b4a744ad-0716-47f4-a7b0-222222222222";
const bearer="header."+Buffer.from(JSON.stringify({session_id:sid})).toString("base64url")+".signature";
const env={url:"https://example.supabase.co",anonKey:"public",serviceKey:"service-secret"};
function scenario(overrides:{age?:number;role?:string;google?:boolean;active?:boolean;ready?:boolean;failDelete?:boolean;authFail?:boolean;recent?:boolean}={}){const calls:{url:string;init?:RequestInit}[]=[];const f=(async(input:unknown,init?:RequestInit)=>{const url=String(input);calls.push({url,init});if(url.endsWith("/auth/v1/user"))return Response.json({id,last_sign_in_at:new Date(now-(overrides.age??1000)).toISOString(),app_metadata:{provider:overrides.google===false?"email":"google"}},{status:overrides.authFail?401:200});if(url.endsWith("r1_my_community_permissions"))return Response.json({authenticated:true,role:overrides.role??"user",active:overrides.active??true});if(url.endsWith("r1_account_recent_session"))return Response.json(overrides.recent??true);if(url.endsWith("r1_account_erasure_ready"))return Response.json(overrides.ready??true);return Response.json({},{status:overrides.failDelete?500:200});}) as typeof fetch;return {calls,f};}
const req=(body:unknown={confirmation:"탈퇴",acknowledged:true,user_id:"forged-other-id"},token=true)=>new Request("https://example.test/delete",{method:"POST",headers:{"content-type":"application/json",...(token?{authorization:"Bearer "+bearer}:{})},body:JSON.stringify(body)});
test("delete uses getUser identity not caller supplied id and only verified server key",async()=>{const s=scenario();const res=await handleDeleteAccount(req(),env,s.f,now);assert.equal(res.status,200);assert.deepEqual(await res.json(),{code:"deleted"});const del=s.calls.find(c=>c.init?.method==="DELETE");assert.equal(del?.url,env.url+"/auth/v1/admin/users/"+id);assert.equal(del?.init?.body,JSON.stringify({should_soft_delete:false}));assert.equal(new Headers(s.calls[0].init?.headers).get("authorization"),"Bearer "+bearer);assert.equal(new Headers(del?.init?.headers).get("apikey"),"service-secret");});
for(const [name,options,expected] of [["old login",{age:11*60*1000},401],["old or revoked session",{recent:false},401],["operator",{role:"admin"},403],["moderator",{role:"moderator"},403],["email provider",{google:false},403],["missing migration",{ready:false},503],["invalid auth",{authFail:true},401]] as const){test("deletion rejects "+name,async()=>{const s=scenario(options);const res=await handleDeleteAccount(req(),env,s.f,now);assert.equal(res.status,expected);assert.equal(s.calls.some(c=>c.init?.method==="DELETE"),false);});}
test("restricted ordinary users may still delete and failed deletion never reports success",async()=>{for(const failDelete of [false,true]){const s=scenario({active:false,failDelete});const res=await handleDeleteAccount(req(),env,s.f,now);assert.equal(res.status,failDelete?503:200);}});
test("confirmation and login are required before any privileged request",async()=>{for(const r of [req({},true),req(undefined,false),new Request("https://example.test/delete")]){const s=scenario();assert.notEqual((await handleDeleteAccount(r,env,s.f,now)).status,200);assert.equal(s.calls.length,0);}});
test("oversized requests cannot cause an unbounded body read",async()=>{const s=scenario();const res=await handleDeleteAccount(req({confirmation:"탈퇴",acknowledged:true,padding:"a".repeat(2200)}),env,s.f,now);assert.equal(res.status,413);assert.equal(s.calls.length,0);});
