(()=>{
  const $$=(s,r=document)=>[...r.querySelectorAll(s)],$=(s,r=document)=>r.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const splitCsv=text=>{const rows=[];let row=[],cell='',q=false;const src=String(text||'').replace(/^\ufeff/,'');for(let i=0;i<src.length;i++){const ch=src[i];if(q){if(ch==='"'&&src[i+1]==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else if(ch==='"')q=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(ch!=='\r')cell+=ch}if(cell.length||row.length){row.push(cell);rows.push(row)}return rows.filter(r=>r.some(x=>String(x).trim()!==''))};
  const csvCell=v=>{const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s};
  const parseBatch=(text,schema)=>{const m=splitCsv(text);if(!m.length)return {errors:['CSV가 비어 있습니다.'],rows:[],header:[]};const header=m[0].map(x=>x.trim()),props=schema.properties||{},allowed=new Set(Object.keys(props)),unknown=header.filter(x=>!allowed.has(x)),missing=(schema.required||[]).filter(x=>!header.includes(x)),errors=[];if(unknown.length)errors.push(`허용하지 않는 열: ${unknown.join(', ')}`);if(missing.length)errors.push(`필수 열 누락: ${missing.join(', ')}`);if(errors.length)return {errors,rows:[],header};const ids=new Set(),rows=[];m.slice(1).forEach((cells,idx)=>{const r={};header.forEach((h,i)=>r[h]=String(cells[i]??'').trim());const errs=[];for(const k of schema.required||[])if(r[k]==='')errs.push(`${k} 필수`);if(r.sample_id){if(ids.has(r.sample_id))errs.push('sample_id 중복');ids.add(r.sample_id)}for(const [k,rule] of Object.entries(props)){if(r[k]===''||r[k]==null)continue;if(rule.enum&&!rule.enum.includes(r[k]))errs.push(`${k} 허용값 아님`);const types=Array.isArray(rule.type)?rule.type:[rule.type];if(types.includes('number')||types.includes('integer')){const n=Number(r[k]);if(!Number.isFinite(n))errs.push(`${k} 숫자 아님`);else{r[k]=n;if(types.includes('integer')&&!Number.isInteger(n))errs.push(`${k} 정수 아님`);if(rule.minimum!=null&&n<rule.minimum)errs.push(`${k} 최소값 미만`);if(rule.maximum!=null&&n>rule.maximum)errs.push(`${k} 최대값 초과`);if(rule.exclusiveMinimum!=null&&n<=rule.exclusiveMinimum)errs.push(`${k} 0보다 커야 함`)}}if(rule.pattern&&!new RegExp(rule.pattern).test(String(r[k])))errs.push(`${k} 형식 불일치`)}rows.push({row:r,line:idx+2,errors:errs})});return {errors:[],rows,header}};
  const signature=r=>[r.quote_month,r.region_level1,Number(r.supply_pyeong).toFixed(1),r.building_type,r.scope,r.bathroom_count,r.window_scope,r.vat_state,r.waste_state,Number(r.total_amount_manwon).toFixed(1)].join('|');
  const reviewRows=valid=>{const sig=new Map();valid.forEach(x=>{const k=signature(x.row);if(!sig.has(k))sig.set(k,[]);sig.get(k).push(x)});const dup=new Set([...sig.values()].filter(x=>x.length>1).flat());return valid.map(x=>{const r=x.row,reasons=[];if(dup.has(x))reasons.push('중복 의심');if(r.exclusive_pyeong!==''&&Number(r.exclusive_pyeong)>Number(r.supply_pyeong))reasons.push('전용>공급');const total=Number(r.total_amount_manwon),trades=Object.entries(r).filter(([k,v])=>k.endsWith('_manwon')&&k!=='total_amount_manwon'&&v!==''&&Number.isFinite(Number(v))).map(([,v])=>Number(v)),sum=trades.reduce((a,b)=>a+b,0);if(sum>total*1.05)reasons.push('공종합>총액');if(trades.some(v=>v>total))reasons.push('공종>총액');return {...x,reasons,status:x.errors.length?'blocked':reasons.length?'review':'clean'}})};
  function initBatch(){$$('[data-v12-batch]').forEach(async root=>{let schema={};try{schema=await fetch('/pm-lab/interior-cost-preview/data/quote-sample-schema.json').then(r=>r.json())}catch{}const ta=$('[data-v12-batch-text]',root),file=$('[data-v12-batch-file]',root),run=$('[data-v12-batch-run]',root),body=$('[data-v12-batch-body]',root),msg=$('[data-v12-batch-msg]',root),exp=$('[data-v12-batch-export]',root);let last=null;file?.addEventListener('change',async()=>{const f=file.files?.[0];if(f&&ta)ta.value=await f.text()});run?.addEventListener('click',()=>{const p=parseBatch(ta?.value||'',schema);if(p.errors.length){msg.textContent=p.errors.join(' · ');body.innerHTML='<tr><td colspan="5">검증 차단</td></tr>';exp.disabled=true;return}const rows=reviewRows(p.rows),clean=rows.filter(x=>x.status==='clean'),review=rows.filter(x=>x.status==='review'),blocked=rows.filter(x=>x.status==='blocked');last={header:p.header,rows};msg.textContent=`전체 ${rows.length} · 정상 ${clean.length} · 검토 ${review.length} · 차단 ${blocked.length}`;body.innerHTML=rows.slice(0,100).map(x=>`<tr><td>${x.line}</td><td>${esc(x.row.sample_id||'')}</td><td>${x.status==='clean'?'정상':x.status==='review'?'검토':'차단'}</td><td>${esc((x.errors||[]).join(' / ')||(x.reasons||[]).join(' / ')||'—')}</td><td>${esc(x.row.region_level1||'')} · ${esc(x.row.supply_pyeong||'')}평</td></tr>`).join('')||'<tr><td colspan="5">행 없음</td></tr>';exp.disabled=!clean.length});exp?.addEventListener('click',()=>{if(!last)return;const usable=last.rows.filter(x=>x.status==='clean').map(x=>x.row),text=[last.header.join(','),...usable.map(r=>last.header.map(h=>csvCell(r[h])).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download='quote-batch-clean.csv';a.click();URL.revokeObjectURL(a.href)})})}
  function initTarget(){$$('[data-v12-targets]').forEach(root=>{const q=$('[data-v12-target-q]',root),state=$('[data-v12-target-state]',root);const apply=()=>{const n=(q?.value||'').trim().toLowerCase(),s=state?.value||'';$$('[data-v12-target-row]',root).forEach(x=>{const ok=(!n||(x.dataset.search||'').toLowerCase().includes(n))&&(!s||x.dataset.state===s);x.hidden=!ok})};q?.addEventListener('input',apply);state?.addEventListener('change',apply)})}
  function initProduction(){$$('[data-v12-prod-sim]').forEach(root=>{$$('[data-v12-prod-filter]',root).forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.v12ProdFilter;$$('[data-v12-prod-row]',root).forEach(r=>r.hidden=v!=='all'&&r.dataset.state!==v)}))})}
  document.addEventListener('DOMContentLoaded',()=>{initBatch();initTarget();initProduction()});
})();
