(() => {
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const fmt=n=>Number(n||0).toLocaleString('ko-KR',{maximumFractionDigits:2});
  const INDEX={'2025-08':130.9,'2025-09':131.7,'2025-10':132.0,'2025-11':132.45,'2025-12':132.7,'2026-01':133.28,'2026-02':133.69,'2026-03':134.4,'2026-04':136.88,'2026-05':137.67,'2026-06':138.22,'2026-07':138.59};
  const GROUPS={base:{label:'철거·기초',ids:['demolition','waste','waterproof']},room:{label:'욕실·주방',ids:['bathroom','kitchen']},finish:{label:'마감·전기',ids:['wallpaper','flooring','carpentry','electrical']},other:{label:'샷시·관리',ids:['window','management','vat']}};

  function compareKey(el){const row=el.closest('[data-compare-row]'),kind=el.hasAttribute('data-state')?'state':'amount';return `${row?.dataset.compareRow||'unknown'}:${el.dataset.vendor||'x'}:${kind}`}
  function readCompare(){const out={};$$('[data-compare-table] [data-vendor]').forEach(el=>out[compareKey(el)]=el.value);return out}
  function applyCompare(){let saved={};try{saved=JSON.parse(localStorage.getItem('interior-compare-v6')||'{}')}catch{};$$('[data-compare-table] [data-vendor]').forEach(el=>{const v=saved[compareKey(el)];if(v!=null)el.value=v})}
  function vendorAmounts(vendor){const grouped={base:0,room:0,finish:0,other:0};for(const [group,meta] of Object.entries(GROUPS))meta.ids.forEach(id=>{const row=$(`[data-compare-row="${id}"]`),el=row?.querySelector(`[data-vendor="${vendor}"][data-amount]`);grouped[group]+=Number(el?.value||0)});return grouped}
  function renderCompareChart(){const root=$('[data-v6-compare-chart]');if(!root)return;['a','b','c'].forEach(vendor=>{const groups=vendorAmounts(vendor),total=Object.values(groups).reduce((a,b)=>a+b,0),bar=$(`[data-v6-stack="${vendor}"]`,root),totalEl=$(`[data-v6-stack-total="${vendor}"]`,root),legacyTotal=$(`[data-total="${vendor}"]`);if(totalEl)totalEl.textContent=total?`${fmt(total)}만원`:'입력 전';if(legacyTotal)legacyTotal.textContent=`${fmt(total)}만원`;if(!bar)return;bar.innerHTML=Object.entries(groups).map(([key,value])=>`<span class="v6-stack-seg" data-group="${key}" style="width:${total?value/total*100:0}%" title="${GROUPS[key].label} ${fmt(value)}만원"></span>`).join('');bar.setAttribute('aria-label',total?`${vendor.toUpperCase()} 업체 입력금액 ${fmt(total)}만원`:`${vendor.toUpperCase()} 업체 금액 입력 전`)})}
  function initCompareV6(){const host=$('[data-compare-table]');if(!host)return;applyCompare();const rerender=()=>requestAnimationFrame(renderCompareChart);$$('[data-vendor]',host).forEach(el=>{el.addEventListener('input',rerender);el.addEventListener('change',rerender)});$('[data-save-compare]',host)?.addEventListener('click',()=>{try{localStorage.setItem('interior-compare-v6',JSON.stringify(readCompare()))}catch{}});$('[data-reset-compare]',host)?.addEventListener('click',()=>{try{localStorage.removeItem('interior-compare-v6')}catch{}},{capture:true});renderCompareChart()}

  function initIndexConverter(){const root=$('[data-v6-index-tool]');if(!root)return;const amount=$('[data-v6-index-amount]',root),from=$('[data-v6-index-from]',root),to=$('[data-v6-index-to]',root),result=$('[data-v6-index-result]',root),ratio=$('[data-v6-index-ratio]',root);const calc=()=>{const base=Number(amount?.value||0),a=INDEX[from?.value],b=INDEX[to?.value];if(!a||!b){if(result)result.textContent='—';return}const r=b/a;if(ratio)ratio.textContent=`지수비 ${r.toFixed(4)} · ${((r-1)*100).toFixed(2)}%`;if(result)result.textContent=base?`${fmt(Math.round(base*r))}만원`:'금액 입력'};[amount,from,to].filter(Boolean).forEach(el=>{el.addEventListener('input',calc);el.addEventListener('change',calc)});calc()}
  function initHomeSearch(){const form=$('[data-v6-search]');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const q=$('input',form)?.value.trim();if(q)location.href=`/pm-lab/interior-cost-preview/search/?q=${encodeURIComponent(q)}`})}
  initCompareV6();initIndexConverter();initHomeSearch();
})();
