(() => {
  const BASE='/pm-lab/interior-cost-preview';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const NUMERIC=new Set(['supply_pyeong','exclusive_pyeong','bathroom_count','total_amount_manwon','demolition_manwon','waste_manwon','waterproof_manwon','bathroom_manwon','kitchen_manwon','wallpaper_manwon','flooring_manwon','carpentry_manwon','electrical_manwon','window_manwon','management_manwon']);
  const TRADE=[...NUMERIC].filter(x=>x.endsWith('_manwon')&&x!=='total_amount_manwon');
  const PUBLIC_N=30,SEGMENT_N=20;
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;const src=String(text||'').replace(/^\ufeff/,'');for(let i=0;i<src.length;i++){const ch=src[i];if(quoted){if(ch==='"'&&src[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch;}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell.trim());cell='';}else if(ch==='\n'){row.push(cell.trim());rows.push(row);row=[];cell='';}else if(ch!=='\r')cell+=ch;}if(cell.length||row.length){row.push(cell.trim());rows.push(row)}return rows.filter(r=>r.some(v=>String(v).trim()!==''));}
  function quantile(values,p){const a=values.filter(Number.isFinite).slice().sort((a,b)=>a-b);if(!a.length)return null;const i=(a.length-1)*p,lo=Math.floor(i),hi=Math.ceil(i);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(i-lo)}
  const fmt=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:1});
  function download(name,type,text){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function pyeongBand(v){const n=Number(v);if(n<20)return '20평 미만';if(n<30)return '20평대';if(n<40)return '30평대';if(n<50)return '40평대';return '50평 이상'}
  async function init(root){
    let schema;try{schema=await fetch(`${BASE}/data/quote-sample-schema.json`,{cache:'no-store'}).then(r=>r.json())}catch{return}
    const allowed=new Set(Object.keys(schema.properties||{})),required=schema.required||[];
    let rows=[],messages=[],header=[];
    const drop=$('[data-v7-drop]',root),file=$('[data-v7-file]',root),paste=$('[data-v7-paste]',root),run=$('[data-v7-run]',root),example=$('[data-v7-example]',root),exportJson=$('[data-v7-export-json]',root),exportCsv=$('[data-v7-export-csv]',root);
    const region=$('[data-v7-region]',root),band=$('[data-v7-band]',root),scope=$('[data-v7-scope]',root),building=$('[data-v7-building]',root);
    function validate(text){
      const matrix=parseCsv(text);messages=[];rows=[];header=[];if(!matrix.length){messages.push({row:'-',field:'CSV',message:'데이터가 비어 있음'});render();return}
      header=matrix[0].map(x=>x.trim());const unknown=header.filter(h=>!allowed.has(h)),missing=required.filter(h=>!header.includes(h));unknown.forEach(x=>messages.push({row:'-',field:x,message:'허용하지 않는 열'}));missing.forEach(x=>messages.push({row:'-',field:x,message:'필수 열 누락'}));if(messages.length){render();return}
      const seen=new Set();
      matrix.slice(1).forEach((cells,idx)=>{const raw={};header.forEach((h,i)=>raw[h]=(cells[i]??'').trim());const out={},errs=[];for(const [key,rule] of Object.entries(schema.properties||{})){const value=raw[key];if(value===''||value==null){out[key]=Array.isArray(rule.type)&&rule.type.includes('null')?null:'';if(required.includes(key))errs.push([key,'필수값 누락']);continue}let v=NUMERIC.has(key)?Number(value):String(value).trim();out[key]=v;if(rule.enum&&!rule.enum.includes(v))errs.push([key,'허용값 아님']);if(rule.pattern&&!(new RegExp(rule.pattern).test(String(v))))errs.push([key,'형식 불일치']);if(NUMERIC.has(key)){if(!Number.isFinite(v))errs.push([key,'숫자 아님']);if(rule.minimum!=null&&v<rule.minimum)errs.push([key,'최소값 미만']);if(rule.maximum!=null&&v>rule.maximum)errs.push([key,'최대값 초과']);if(rule.exclusiveMinimum!=null&&v<=rule.exclusiveMinimum)errs.push([key,'0보다 커야 함']);}}
        if(out.sample_id){if(seen.has(out.sample_id))errs.push(['sample_id','중복 ID']);else seen.add(out.sample_id)}
        const total=Number(out.total_amount_manwon),components=TRADE.map(f=>Number(out[f])).filter(Number.isFinite),sum=components.reduce((a,b)=>a+b,0);out._component_sum_manwon=sum;out._component_fields=components.length;out._vat_included_total_manwon=out.vat_state==='포함'?total:out.vat_state==='별도'?Number((total*1.1).toFixed(1)):null;out._per_supply_pyeong_manwon=Number(out.supply_pyeong)>0?Number((total/Number(out.supply_pyeong)).toFixed(2)):null;out._pyeong_band=pyeongBand(out.supply_pyeong);out._component_over_total=total>0&&sum>total*1.25;
        if(out._component_over_total)errs.push(['공종합계','공종별 합계가 총액의 125%를 초과']);
        if(errs.length)errs.forEach(e=>messages.push({row:idx+2,field:e[0],message:e[1]}));else rows.push(out);
      });render();populateFilters();applyFilters();
    }
    function render(){const valid=$('[data-v7-valid]',root),invalid=$('[data-v7-invalid]',root),table=$('[data-v7-error-body]',root);if(valid)valid.textContent=`${rows.length}건`;if(invalid)invalid.textContent=`${messages.length}건`;if(table)table.innerHTML=messages.slice(0,100).map(m=>`<tr><td>${esc(m.row)}</td><td>${esc(m.field)}</td><td>${esc(m.message)}</td></tr>`).join('')||'<tr><td colspan="3">오류 없음</td></tr>';if(exportJson)exportJson.disabled=!rows.length;if(exportCsv)exportCsv.disabled=!rows.length;const ratio=$('[data-v7-valid-ratio]',root);if(ratio){const total=rows.length+new Set(messages.filter(m=>Number.isFinite(Number(m.row))).map(m=>m.row)).size;ratio.textContent=total?`${Math.round(rows.length/total*100)}%`:'—'}const vat=$('[data-v7-vat-known]',root);if(vat)vat.textContent=rows.length?`${Math.round(rows.filter(r=>r.vat_state!=='미기재').length/rows.length*100)}%`:'—';const trade=$('[data-v7-trade-cover]',root);if(trade){const denom=rows.length*TRADE.length,filled=rows.reduce((n,r)=>n+TRADE.filter(f=>r[f]!=null&&r[f]!=='').length,0);trade.textContent=denom?`${Math.round(filled/denom*100)}%`:'—'}}
    function populateFilters(){const set=(el,vals,label)=>{if(!el)return;const current=el.value;el.innerHTML=`<option value="">${label}</option>`+[...new Set(vals.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'ko')).map(v=>`<option>${esc(v)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current};set(region,rows.map(r=>r.region_level1),'전체 지역');set(band,rows.map(r=>r._pyeong_band),'전체 평수');set(scope,rows.map(r=>r.scope),'전체 범위');set(building,rows.map(r=>r.building_type),'전체 건물')}
    function filtered(){return rows.filter(r=>(!region?.value||r.region_level1===region.value)&&(!band?.value||r._pyeong_band===band.value)&&(!scope?.value||r.scope===scope.value)&&(!building?.value||r.building_type===building.value))}
    function applyFilters(){const list=filtered(),filteredMode=!!(region?.value||band?.value||scope?.value||building?.value),threshold=filteredMode?SEGMENT_N:PUBLIC_N,totals=list.map(r=>Number(r.total_amount_manwon)).filter(Number.isFinite),per=list.map(r=>Number(r._per_supply_pyeong_manwon)).filter(Number.isFinite),eligible=list.length>=threshold;const set=(sel,val)=>{const el=$(sel,root);if(el)el.textContent=val};set('[data-v7-n]',`${list.length}건`);set('[data-v7-p25]',eligible?`${fmt(quantile(totals,.25))}만원`:'보류');set('[data-v7-median]',eligible?`${fmt(quantile(totals,.5))}만원`:'보류');set('[data-v7-p75]',eligible?`${fmt(quantile(totals,.75))}만원`:'보류');set('[data-v7-per]',eligible?`${fmt(quantile(per,.5))}만원/평`:'보류');const note=$('[data-v7-gate-note]',root);if(note)note.textContent=eligible?`N=${list.length} · 공개 게이트 충족`:`N=${list.length} · ${filteredMode?'세그먼트':'전체'} 기준 N≥${threshold} 미달`;root.dataset.filtered=String(list.length)}
    async function readFile(f){if(!f)return;const text=await f.text();if(paste)paste.value=text;validate(text)}
    file?.addEventListener('change',e=>readFile(e.target.files?.[0]));['dragenter','dragover'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('is-over')}));['dragleave','drop'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('is-over')}));drop?.addEventListener('drop',e=>readFile(e.dataTransfer?.files?.[0]));run?.addEventListener('click',()=>validate(paste?.value||''));example?.addEventListener('click',async()=>{const t=await fetch(`${BASE}/data/quote-sample-template.csv`).then(r=>r.text());if(paste)paste.value=t;validate(t)});[region,band,scope,building].forEach(el=>el?.addEventListener('change',applyFilters));
    exportJson?.addEventListener('click',()=>download('interior-quotes-clean.json','application/json',JSON.stringify({version:'7.0.0',rows},null,2)));
    exportCsv?.addEventListener('click',()=>{if(!rows.length)return;const cols=[...header,'normalized_vat_included_manwon','per_supply_pyeong_manwon','pyeong_band'];const lines=[cols.join(','),...rows.map(r=>cols.map(c=>{const key=c==='normalized_vat_included_manwon'?'_vat_included_total_manwon':c==='per_supply_pyeong_manwon'?'_per_supply_pyeong_manwon':c==='pyeong_band'?'_pyeong_band':c;const v=r[key]??'';return /[",\n]/.test(String(v))?`"${String(v).replace(/"/g,'""')}"`:v}).join(','))];download('interior-quotes-clean.csv','text/csv;charset=utf-8','\ufeff'+lines.join('\n'))});
  }
  document.addEventListener('DOMContentLoaded',()=>$$('[data-v7-market]').forEach(init));
})();
