const {test,expect}=require('@playwright/test');
const fs=require('fs');const path=require('path');
const BASE=process.env.V28_BASE_URL||'http://127.0.0.1:4173/pm-lab/interior-cost-preview';
const out=path.resolve('artifacts/v28-browser');fs.mkdirSync(out,{recursive:true});
async function audit(page,url){const errs=[];page.on('pageerror',e=>errs.push(e.message));page.on('console',m=>{if(m.type()==='error')errs.push(m.text())});const res=await page.goto(url,{waitUntil:'domcontentloaded'});const s=await page.evaluate(()=>({w:document.documentElement.clientWidth,sw:document.documentElement.scrollWidth,h:document.documentElement.scrollHeight,robots:document.querySelector('meta[name="robots"]')?.content||'',bg:getComputedStyle(document.body).backgroundColor,text:document.body.innerText}));expect(res&&res.ok()).toBeTruthy();expect(s.sw).toBeLessThanOrEqual(s.w+2);expect(s.robots).toContain('noindex');expect(errs).toEqual([]);return s;}

test('home is service-grid first with no AI hero copy',async({browser})=>{for(const vp of [{width:390,height:844},{width:1440,height:900}]){const ctx=await browser.newContext({viewport:vp});const page=await ctx.newPage();await audit(page,`${BASE}/?v=28`);await expect(page.locator('.v28-home')).toBeVisible();await expect(page.locator('.v28-service-card')).toHaveCount(4);await expect(page.locator('body')).not.toContainText('받은 인테리어 견적서, 빠진 비용부터 확인하세요');await expect(page.locator('.v28-home')).toContainText('견적 도구');await expect(page.locator('.v28-home')).toContainText('평수별 비용');await expect(page.locator('.v28-home')).toContainText('공사별 비용');const hero=page.locator('.v27-home-hero');await expect(hero).toHaveCount(0);const bg=await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor);expect(bg).toBe('rgb(255, 255, 255)');await ctx.close();}});

test('quote check starts at tool, not marketing copy',async({page})=>{await page.setViewportSize({width:390,height:844});await audit(page,`${BASE}/quote-check/`);await expect(page.locator('h1')).toHaveText('견적서 확인');await expect(page.locator('.tool-hero .lead')).toHaveCount(0);await expect(page.locator('.quote-check-table')).toBeVisible();await expect(page.locator('.qrow')).toHaveCount(12);const first=page.locator('.qrow').first();await expect(first.locator('.v27-q-details')).not.toHaveAttribute('open','');const rect=await page.locator('.quote-check-table').boundingBox();expect(rect.y).toBeLessThan(420);});

test('quote compare remains progressive and visually flat',async({page})=>{await page.setViewportSize({width:390,height:844});await audit(page,`${BASE}/quote-compare/`);await expect(page.locator('h1')).toHaveText('견적 비교');await expect(page.locator('.tool-hero .lead')).toHaveCount(0);await expect(page.locator('[data-v27-count="2"]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('.v6-compare-chart')).toBeHidden();const border=await page.locator('.v27-compare-start').evaluate(el=>getComputedStyle(el).borderRadius);expect(parseFloat(border)).toBeLessThanOrEqual(10);});

test('calculator stays mode-first',async({page})=>{await page.setViewportSize({width:390,height:844});await audit(page,`${BASE}/calculator/`);await expect(page.locator('h1')).toHaveText('비용 계산기');await expect(page.locator('.tool-hero .lead')).toHaveCount(0);await expect(page.locator('.v27-calc-start')).toBeVisible();const before=await page.locator('.budget-row:visible').count();expect(before).toBe(0);await page.locator('[data-v27-calc-mode="bathroom"]').click();const after=await page.locator('.budget-row:visible').count();expect(after).toBeGreaterThan(0);expect(after).toBeLessThan(12);});

test('pyeong detail is compact and duplicate intro is gone',async({page})=>{await page.setViewportSize({width:390,height:844});await audit(page,`${BASE}/interior-cost/32-pyeong/`);await expect(page.locator('h1')).toContainText('32평');await expect(page.locator('.article-hero .lead')).toHaveCount(0);await expect(page.locator('.v26-data-boundary')).toHaveCount(0);await expect(page.locator('.direct-answer')).toHaveCount(0);await expect(page.locator('.data-table').first()).toBeVisible();});

test('trade detail removes empty stats and keeps useful public data',async({page})=>{await page.setViewportSize({width:390,height:844});await audit(page,`${BASE}/cost/bathroom/`);await expect(page.locator('h1')).toHaveText('욕실 견적');await expect(page.locator('.article-hero .lead')).toHaveCount(0);await expect(page.locator('.v7-trade-stat')).toHaveCount(0);await expect(page.locator('.v9-trade-board')).toHaveCount(0);await expect(page.locator('.v63-unit-card')).toHaveCount(4);await expect(page.locator('.data-table').first()).toBeVisible();});

test('data and guides share the same premium shell',async({browser})=>{for(const route of ['/data/','/guides/']){const ctx=await browser.newContext({viewport:{width:390,height:844}});const page=await ctx.newPage();await audit(page,`${BASE}${route}`);const bodyClass=await page.locator('body').getAttribute('class');expect(bodyClass).toContain('v28-ohou');await expect(page.locator('.article-hero .lead,.tool-hero .lead')).toHaveCount(0);await ctx.close();}});

test('capture v28 representative screenshots',async({browser})=>{const targets=[['home-mobile-v28.png',390,844,'/'],['home-desktop-v28.png',1440,900,'/'],['quote-check-mobile-v28.png',390,844,'/quote-check/'],['quote-compare-mobile-v28.png',390,844,'/quote-compare/'],['calculator-mobile-v28.png',390,844,'/calculator/'],['pyeong32-mobile-v28.png',390,844,'/interior-cost/32-pyeong/'],['bathroom-mobile-v28.png',390,844,'/cost/bathroom/'],['data-mobile-v28.png',390,844,'/data/']];for(const [name,w,h,route] of targets){const ctx=await browser.newContext({viewport:{width:w,height:h}});const page=await ctx.newPage();await page.goto(`${BASE}${route}`,{waitUntil:'domcontentloaded'});await page.screenshot({path:path.join(out,name),fullPage:true});await ctx.close();}for(const [name] of targets)expect(fs.existsSync(path.join(out,name))).toBeTruthy();});
