import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='11.0.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8');
const write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)};
const json=(r,fallback={})=>{try{return JSON.parse(read(r))}catch{return fallback}};
const coreJson=(r,fallback={})=>{try{return JSON.parse(fs.readFileSync(path.join(CORE,r),'utf8'))}catch{return fallback}};
const reviewed=json('data/v5-report.json',{}).reviewed_on||new Date().toISOString().slice(0,10);
const quote=json('data/quote-statistics.json',{sample_count:0,publication_threshold:30,segment_threshold:20,segments:{}}),health=json('data/quote-data-health.json',{valid_rows:0,trade_field_counts:{},trade_field_completion_percent:{}}),schema=json('data/quote-sample-schema.json',{properties:{},required:[]}),regionMap=json('data/region-pyeong-map.json',{routes:[]}),baseAnswers=json('data/answer-index-v10.json',{answers:[]}),index=json('data/construction-cost-index.json',{}),wage=json('data/construction-wage-2026-h2.json',{}),unit=json('data/public-unit-cost-v8.json',{items:[]}),sourceWatch=coreJson('source-watch-v11.json',{sources:[],update_required:false});
const css=fs.readFileSync(path.join(CORE,'site-v11.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v11.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v11.css',css);write('assets/app-v11.js',js);
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const strip=s=>String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim();
const fmt=n=>Number(n||0).toLocaleString('ko-KR',{maximumFractionDigits:1});
const days=(a,b)=>Math.max(0,Math.floor((new Date(`${b}T00:00:00Z`)-new Date(`${a}T00:00:00Z`))/86400000));
const regions=[['seoul','서울'],['busan','부산'],['daegu','대구'],['incheon','인천'],['gwangju','광주'],['daejeon','대전'],['ulsan','울산'],['sejong','세종'],['gyeonggi','경기'],['gangwon','강원'],['chungbuk','충북'],['chungnam','충남'],['jeonbuk','전북'],['jeonnam','전남'],['gyeongbuk','경북'],['gyeongnam','경남'],['jeju','제주']].map(([slug,name])=>({slug,name}));
const pyeongs=[24,30,32,34,40],overallN=quote.publication_threshold||30,segmentN=quote.segment_threshold||20;
const tradeFields={demolition_manwon:'철거',waste_manwon:'폐기물',waterproof_manwon:'방수',bathroom_manwon:'욕실',kitchen_manwon:'주방',wallpaper_manwon:'도배',flooring_manwon:'바닥',carpentry_manwon:'목공',electrical_manwon:'전기',window_manwon:'창호',management_manwon:'현장관리'};
const cell=(dim,key)=>(quote.segments?.[dim]||[]).find(x=>x.key===key)||null;
const regionRows=regions.map(r=>{const c=cell('region_level1',r.name),n=c?.n||0;return {...r,n,status:c?.status||'withheld',needed:Math.max(0,segmentN-n),published:c?.status==='published'}});
const pyeongRows=pyeongs.map(p=>{const c=cell('supply_pyeong_rounded',`${p}평`),n=c?.n||0;return {pyeong:p,n,status:c?.status||'withheld',needed:Math.max(0,segmentN-n),published:c?.status==='published'}});
const routeRows=regions.flatMap(r=>pyeongs.map(p=>{const key=`${r.name} · ${p}평`,c=cell('region_pyeong_rounded',key),existing=(regionMap.routes||[]).find(x=>x.key===key),n=c?.n??existing?.sample_count??0;return {region:r.name,region_slug:r.slug,pyeong:p,key,n,status:c?.status||existing?.status||'withheld',needed:Math.max(0,segmentN-n),published:(c?.status||existing?.status)==='published'}}));
const tradeRows=Object.entries(tradeFields).map(([field,label])=>{const n=Number(health.trade_field_counts?.[field]||0);return {field,label,n,completion_percent:Number(health.trade_field_completion_percent?.[field]||0),needed:Math.max(0,segmentN-n),published:n>=segmentN}});
const coverage={version:VERSION,reviewed_on:reviewed,thresholds:{overall_n:overallN,segment_n:segmentN},overall:{n:quote.sample_count||0,status:quote.status||'withheld',needed:Math.max(0,overallN-(quote.sample_count||0))},regions:{total:regions.length,published:regionRows.filter(x=>x.published).length,cells:regionRows},pyeongs:{total:pyeongs.length,published:pyeongRows.filter(x=>x.published).length,cells:pyeongRows},region_pyeong:{total:routeRows.length,published:routeRows.filter(x=>x.published).length,coverage_percent:Number((routeRows.filter(x=>x.published).length/routeRows.length*100).toFixed(1)),cells:routeRows},trade_fields:{total:tradeRows.length,published:tradeRows.filter(x=>x.published).length,cells:tradeRows},raw_rows_public:false,mean_published:false};
write('data/quote-coverage-v11.json',JSON.stringify(coverage,null,2));
const priorities=[{type:'overall',key:'전체 실제견적',n:coverage.overall.n,threshold:overallN,needed:coverage.overall.needed,status:coverage.overall.status,url:`${BASE}/data/quote-statistics/`},...routeRows.map(x=>({type:'region_pyeong',key:x.key,n:x.n,threshold:segmentN,needed:x.needed,status:x.status,url:`${BASE}/region/${x.region_slug}/`})),...tradeRows.map(x=>({type:'trade',key:`${x.label} 공종금액`,n:x.n,threshold:segmentN,needed:x.needed,status:x.published?'published':'withheld',url:`${BASE}/data/coverage/`}))].sort((a,b)=>a.status==='published'&&b.status!=='published'?1:b.status==='published'&&a.status!=='published'?-1:a.needed-b.needed||b.n-a.n||a.key.localeCompare(b.key,'ko'));
write('data/data-gap-priorities-v11.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,rule:'공개 기준까지 남은 표본 수가 적은 순. 동률은 현재 N이 큰 순, 그 다음 이름순. 검색량·상업가치를 임의 추정하지 않음.',items:priorities},null,2));

const sourceRows=[
 {id:'kict-cost-index',name:'건설공사비지수',current:index.latest_month||'2026-07',published:index.published||'2026-08-28',cadence:'월간 공표',stale_days:55,url:index.source?.url||'https://cost.kict.re.kr/index.html'},
 {id:'cak-wage',name:'건설업 임금실태조사',current:wage.period||'2026-H2',published:wage.published||'2026-09-01',cadence:'반기 공표',stale_days:220,url:wage.source?.url||'https://www.cak.or.kr'},
 {id:'codil-standard-market',name:'표준시장단가',current:unit.period||'2026-H2',published:'2026-05-08',cadence:'반기 공표',stale_days:230,url:unit.official_source||'https://www.codil.or.kr'}
].map(s=>{const watch=(sourceWatch.sources||[]).find(x=>x.id===s.id)||{},age=days(s.published,reviewed),stale=age>s.stale_days;return {...s,age_days:age,stale,watch_detected:watch.detected||null,watch_reachable:watch.reachable??null,update_required:Boolean(watch.update_required||stale),status:watch.update_required?'new_period_detected':stale?'stale_local_data':'current'}});
const freshness={version:VERSION,reviewed_on:reviewed,watch_mode:sourceWatch.mode||'not_run',watch_checked_on:sourceWatch.checked_on||null,update_required:sourceRows.some(x=>x.update_required),sources:sourceRows,policy:'감시기는 새 공표 기간을 탐지하지만 숫자 값은 자동 덮어쓰지 않는다. 원문 확인 후 검증 데이터만 반영.'};
write('data/source-freshness-v11.json',JSON.stringify(freshness,null,2));
const opsContract={version:VERSION,reviewed_on:reviewed,collection:{client_only:true,server_upload:false,local_storage:true,export:'CSV',schema:`${BASE}/data/quote-sample-schema.json`,template:`${BASE}/data/quote-sample-template.csv`},private_validation:{command:'node interior-cost-core/audit-quote-dataset-v11.mjs --input PRIVATE.csv --output /tmp/quote-audit.json',raw_rows_written_to_docs:false,pii_columns_rejected:true},aggregation:{private_env:'INTERIOR_QUOTE_DATASET',compiler:'interior-cost-core/compile-quote-stats-v6-7.mjs',public_outputs:['quote-statistics.json','quote-data-health.json','quote-coverage-v11.json','region-pyeong-map.json'],raw_rows_public:false},publication:{overall_n:overallN,segment_n:segmentN,metrics:['P25','median','P75'],mean:false,region_pyeong_page_rule:`exact cell N>=${segmentN}`},source_watch:{workflow:'.github/workflows/interior-v11-source-watch.yml',detector:'interior-cost-core/source-watch-v11.mjs',values_auto_overwritten:false}};
write('data/quote-ops-contract-v11.json',JSON.stringify(opsContract,null,2));

const template=read('data/index.html'),header=template.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=template.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',styles=[...template.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scripts=[...template.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const head=(title,desc,canonical,schemaObj=null)=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${canonical}">${styles}${schemaObj?`<script type="application/ld+json">${JSON.stringify(schemaObj)}</script>`:''}</head><body>`;

const input=(name,label,type='number',extra='')=>`<label>${label}<input data-v11-field="${name}" type="${type}" ${extra}></label>`;
const select=(name,label,vals)=>`<label>${label}<select data-v11-field="${name}">${vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select></label>`;
const tradeInputs=Object.entries(tradeFields).map(([f,l])=>input(f,`${l} 금액(만원)`,'number','min="0" step="0.1" placeholder="선택"')).join('');
const intakeSchema={'@context':'https://schema.org','@type':'WebApplication',name:'익명 인테리어 견적 행 만들기',applicationCategory:'BusinessApplication',operatingSystem:'Web',description:'개인정보 없이 견적 조건과 금액을 브라우저에서 정리해 익명 CSV로 내보내는 로컬 도구',url:`${SITE}/quote-intake/`};
write('quote-intake/index.html',`${head('익명 인테리어 견적 데이터 만들기 | CSV 수집 도구','이름·전화번호·상세주소·업체명을 받지 않고 인테리어 견적 조건과 금액을 브라우저에서 익명 CSV 행으로 정리합니다.',`${SITE}/quote-intake/`,intakeSchema)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">LOCAL QUOTE INTAKE</p><h1>익명 견적 행 만들기</h1><p>서버 전송 없음 · 브라우저 로컬 저장 · 개인정보 필드 없음 · CSV 내보내기</p></div></section><section class="v11-section"><div class="site-shell"><div class="v11-section-head"><div><h2>견적 조건 입력</h2><p>실제 시장 통계를 만들기 위한 익명 행 형식입니다. 업체명·성명·전화번호·이메일·상세주소는 입력하지 않습니다.</p></div></div><div class="v11-intake" data-v11-intake><div class="v11-intake-form"><div class="v11-field-grid">${input('sample_id','익명 sample_id','text','pattern="[A-Za-z0-9_-]{3,40}"')}<label>새 ID<button type="button" class="secondary" data-v11-new-id>무작위 ID 만들기</button></label>${input('quote_month','견적 월','month')}${select('region_level1','시도',schema.properties.region_level1.enum||regions.map(x=>x.name))}${input('supply_pyeong','공급 평수','number','min="5" max="100" step="0.1"')}${input('exclusive_pyeong','전용 평수(선택)','number','min="0" max="100" step="0.1"')}${select('building_type','주택 유형',schema.properties.building_type.enum||['아파트','빌라','주택'])}${select('scope','공사 범위',schema.properties.scope.enum||['올수리','부분'])}${input('bathroom_count','욕실 수','number','min="0" max="5" step="1"')}${select('window_scope','창호 범위',schema.properties.window_scope.enum||['전체','부분','제외','미기재'])}${select('vat_state','VAT',schema.properties.vat_state.enum||['포함','별도','미기재'])}${select('waste_state','폐기물',schema.properties.waste_state.enum||['포함','별도','미기재'])}${input('total_amount_manwon','총액(만원)','number','min="0.1" step="0.1"')}<div class="wide"><strong>공종별 금액 · 선택 입력</strong></div>${tradeInputs}</div><div class="v11-intake-actions"><button type="button" data-v11-add-row>익명 행 추가</button><button type="button" class="secondary" data-v11-load-example>예시 채우기</button></div><p class="v11-message" data-v11-message></p><p class="v11-intake-note">이 도구는 데이터를 서버로 보내지 않습니다. 브라우저에 임시로 행을 모은 뒤 CSV를 직접 내려받습니다. CSV를 공개 저장소에 올리는 용도가 아니며, 운영자는 비공개 원본에서 검증·집계한 통계만 공개합니다.</p></div><aside class="v11-batch"><div class="v11-section-head"><div><h2>로컬 배치</h2><p data-v11-batch-count>0건</p></div></div><div class="v11-batch-list" data-v11-batch-list></div><div class="v11-intake-actions"><button type="button" data-v11-export-csv>CSV 내보내기</button><button type="button" class="secondary" data-v11-clear-batch>전체 삭제</button></div><p class="v11-intake-note"><a href="${BASE}/data/quote-sample-schema.json">스키마 JSON</a> · <a href="${BASE}/data/quote-sample-template.csv">빈 CSV 템플릿</a> · <a href="${BASE}/data/quote-operations/">운영 검수 절차</a></p></aside></div></div></section></main>${footer}${scripts}</body></html>`);

const heatHead=pyeongs.map(p=>`<th>${p}평</th>`).join('');
const heatRows=regions.map(r=>`<tr data-v11-coverage-row data-region="${r.name}"><th>${r.name}</th>${pyeongs.map(p=>{const x=routeRows.find(y=>y.region===r.name&&y.pyeong===p),state=x.published?'published':x.needed<=5?'near':'withheld';return `<td class="v11-cell" data-state="${state}">N=${x.n}<small>${x.published?'공개':`${x.needed}건 남음`}</small></td>`}).join('')}</tr>`).join('');
const regionTable=regionRows.map(x=>`<tr><th>${x.name}</th><td>${x.n}</td><td>${x.published?'공개':'보류'}</td><td>${x.needed}</td><td><a href="${BASE}/region/${x.slug}/">지역 허브</a></td></tr>`).join('');
const tradeTable=tradeRows.map(x=>`<tr><th>${x.label}</th><td>${x.n}</td><td>${x.completion_percent}%</td><td>${x.published?'통계 가능':'보류'}</td><td>${x.needed}</td></tr>`).join('');
const coverageSchema={'@context':'https://schema.org','@type':'Dataset',name:'인테리어 견적 데이터 커버리지',dateModified:reviewed,description:'지역·평수·공종별 익명 견적 표본 수와 공개 기준까지 남은 건수를 보여주는 집계 데이터',url:`${SITE}/data/coverage/`,distribution:[{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE}/data/quote-coverage-v11.json`} ]};
write('data/coverage/index.html',`${head('인테리어 견적 데이터 커버리지 | 지역×평수 히트맵','17개 시도와 24·30·32·34·40평 조합의 표본 N, 공개 여부, 공개 기준까지 남은 건수를 확인합니다.',`${SITE}/data/coverage/`,coverageSchema)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">QUOTE COVERAGE</p><h1>견적 데이터 커버리지</h1><p>표본 수를 숨기지 않고 지역×평수·공종별 공개 가능 상태를 그대로 보여줍니다.</p></div></section><section class="v11-section"><div class="site-shell"><div class="v11-kpi"><div><span>전체 표본</span><strong>N=${coverage.overall.n}</strong><em>${coverage.overall.needed}건 후 전체 분포 기준</em></div><div><span>지역 공개</span><strong>${coverage.regions.published}/${coverage.regions.total}</strong><em>각 지역 N≥${segmentN}</em></div><div><span>지역×평수 공개</span><strong>${coverage.region_pyeong.published}/${coverage.region_pyeong.total}</strong><em>${coverage.region_pyeong.coverage_percent}%</em></div><div><span>공종 금액 필드</span><strong>${coverage.trade_fields.published}/${coverage.trade_fields.total}</strong><em>각 필드 N≥${segmentN}</em></div><div><span>원본 공개</span><strong>안 함</strong><em>집계만 공개</em></div><div><span>평균값</span><strong>안 씀</strong><em>P25·중앙값·P75</em></div></div></div></section><section class="v11-section"><div class="site-shell" data-v11-coverage><div class="v11-section-head"><div><h2>지역 × 평수 히트맵</h2><p>회색은 N 기준 미달, 기준 통과 시 공개 셀로 전환됩니다. 전국값을 지역 셀에 복사하지 않습니다.</p></div></div><label class="v11-coverage-filter">지역 보기 <select data-v11-region-filter><option value="">전체</option>${regions.map(r=>`<option>${r.name}</option>`).join('')}</select></label><div class="v11-heatmap-wrap"><table class="v11-heatmap"><thead><tr><th>지역</th>${heatHead}</tr></thead><tbody>${heatRows}</tbody></table></div></div></section><section class="v11-section"><div class="site-shell"><div class="v11-section-head"><div><h2>지역 표본 상태</h2><p>시도 단위만 수집하며 상세주소는 수집하지 않습니다.</p></div></div><div class="table-wrap"><table class="v11-coverage-table"><thead><tr><th>지역</th><th>N</th><th>가격통계</th><th>기준까지</th><th>상세</th></tr></thead><tbody>${regionTable}</tbody></table></div></div></section><section class="v11-section"><div class="site-shell"><div class="v11-section-head"><div><h2>공종 금액 입력 커버리지</h2><p>공종별 금액이 들어온 행 수를 별도로 관리합니다. 전체 견적 N과 같은 숫자로 가정하지 않습니다.</p></div></div><div class="table-wrap"><table class="v11-coverage-table"><thead><tr><th>공종</th><th>금액 입력 N</th><th>전체행 대비</th><th>공개 상태</th><th>기준까지</th></tr></thead><tbody>${tradeTable}</tbody></table></div><p class="v11-intake-note"><a href="${BASE}/data/quote-coverage-v11.json">coverage JSON</a> · <a href="${BASE}/data/data-gaps/">데이터 부족 우선순위</a> · <a href="${BASE}/quote-intake/">익명 견적 행 만들기</a></p></div></section></main>${footer}${scripts}</body></html>`);

const gapRows=priorities.filter(x=>x.status!=='published').slice(0,30).map(x=>`<div class="v11-gap-item"><div><strong>${esc(x.key)}</strong><span>${x.type} · 현재 N=${x.n} / 기준 ${x.threshold}</span></div><b>${x.needed}건</b></div>`).join('');
write('data/data-gaps/index.html',`${head('인테리어 견적 데이터 부족 현황 | 공개 기준까지 남은 표본','전체·지역×평수·공종 금액별로 통계 공개 기준까지 몇 건이 남았는지 정해진 규칙으로 정렬합니다.',`${SITE}/data/data-gaps/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">DATA GAPS</p><h1>데이터 부족 현황</h1><p>검색량을 추정해 우선순위를 꾸미지 않고, 공개 기준까지 남은 표본 수만 계산합니다.</p></div></section><section class="v11-section"><div class="site-shell"><div class="v11-section-head"><div><h2>기준에 가까운 셀</h2><p>남은 건수 오름차순 → 현재 N 내림차순 → 이름순. 실제 수집이 시작되면 자동으로 순서가 바뀝니다.</p></div></div><div class="v11-gap-list">${gapRows||'<p>모든 셀이 공개 기준을 충족했습니다.</p>'}</div><p class="v11-intake-note">현재 표본이 0이면 대부분의 세부 셀은 동일하게 N 20이 남습니다. 이 목록은 시장 수요 순위가 아니라 데이터 완성도 관리 도구입니다.</p></div></section><section class="v11-section"><div class="site-shell"><div class="v11-data-links"><a href="${BASE}/quote-intake/"><span>COLLECT</span><strong>익명 견적 행 만들기</strong></a><a href="${BASE}/data/coverage/"><span>COVERAGE</span><strong>17×5 히트맵</strong></a><a href="${BASE}/data/quote-operations/"><span>OPERATIONS</span><strong>비공개 검수 절차</strong></a></div></div></section></main>${footer}${scripts}</body></html>`);

const sourceTable=sourceRows.map(s=>`<tr><th>${s.name}</th><td>${s.current}</td><td>${s.published}</td><td>${s.age_days}일</td><td>${s.watch_detected||'—'}</td><td><span class="v11-status ${s.status==='current'?'ok':s.status==='new_period_detected'?'block':'warn'}">${s.status==='current'?'현재 자료':s.status==='new_period_detected'?'새 공표 감지':'갱신 검토'}</span></td><td><a href="${s.url}" rel="noopener">원출처</a></td></tr>`).join('');
write('data/source-freshness/index.html',`${head('공식 인테리어 비용 데이터 신선도 | 공표 기간 감시','건설공사비지수·건설업 임금·표준시장단가의 현재 반영 기간과 새 공표 탐지 상태를 확인합니다.',`${SITE}/data/source-freshness/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">SOURCE FRESHNESS</p><h1>공식 출처 신선도</h1><p>새 공표 기간은 자동 탐지하되 숫자 값은 원문 확인 없이 자동 교체하지 않습니다.</p></div></section><section class="v11-section"><div class="site-shell"><div class="v11-kpi"><div><span>감시 출처</span><strong>${sourceRows.length}개</strong></div><div><span>새 공표 감지</span><strong>${sourceRows.filter(x=>x.status==='new_period_detected').length}개</strong></div><div><span>갱신 검토</span><strong>${sourceRows.filter(x=>x.update_required).length}개</strong></div><div><span>감시 모드</span><strong>${esc(sourceWatch.mode||'not_run')}</strong></div><div><span>최근 감시 기록</span><strong>${esc(sourceWatch.checked_on||'—')}</strong></div><div><span>자동 숫자 교체</span><strong>안 함</strong></div></div><div class="table-wrap"><table class="v11-source-table"><thead><tr><th>출처</th><th>사이트 반영</th><th>공표일</th><th>경과</th><th>감시 탐지</th><th>상태</th><th>원문</th></tr></thead><tbody>${sourceTable}</tbody></table></div><p class="v11-intake-note">주간 GitHub Actions 감시는 페이지에서 최신 공표 기간 문자열을 탐지합니다. 새 기간이 감지되면 상태 파일을 갱신하고 프리뷰 재생성을 유도하지만, 지수·임금·단가 숫자를 자동으로 덮어쓰지는 않습니다. 숫자는 원문·기간·단위를 검증한 뒤 반영합니다.</p></div></section></main>${footer}${scripts}</body></html>`);

write('data/quote-operations/index.html',`${head('익명 인테리어 견적 데이터 운영 절차 | 비공개 검수·집계','익명 견적 CSV를 공개 저장하지 않고 검증·집계한 뒤 N 기준을 통과한 통계만 프리뷰에 반영하는 운영 절차입니다.',`${SITE}/data/quote-operations/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">QUOTE DATA OPERATIONS</p><h1>견적 데이터 운영 절차</h1><p>수집 원본과 공개 통계를 분리하고, 개인정보 열은 입력 단계에서 차단합니다.</p></div></section><section class="v11-section"><div class="site-shell"><div class="v11-pipeline"><div><strong>로컬 수집</strong><p>사용자가 브라우저에서 익명 행을 만들고 CSV를 직접 내보냅니다. 서버 업로드는 없습니다.</p></div><div><strong>비공개 검증</strong><p>운영자는 PRIVATE.csv를 로컬/비공개 환경에서 스키마 검증합니다. 허용되지 않는 열이 있으면 집계를 막습니다.</p></div><div><strong>집계 생성</strong><p>원본 행을 docs에 쓰지 않고 N·P25·중앙값·P75와 커버리지 정보만 생성합니다.</p></div><div><strong>N 게이트</strong><p>전체 N≥${overallN}, 세부 셀 N≥${segmentN}일 때만 가격 통계를 공개합니다.</p></div><div><strong>검색 반영</strong><p>지역×평수 셀이 기준을 통과해야 조합 가격 페이지가 생성·색인 후보가 됩니다.</p></div></div></div></section><section class="v11-section"><div class="site-shell"><div class="v11-section-head"><div><h2>운영 명령</h2><p>원본 CSV 경로를 공개 저장소 밖에 둔 상태에서 실행합니다.</p></div></div><p>1) 공개 전 데이터 구조만 검사</p><code class="v11-code">node interior-cost-core/audit-quote-dataset-v11.mjs --input PRIVATE.csv --output /tmp/quote-audit.json</code><button type="button" class="secondary" data-v11-copy="node interior-cost-core/audit-quote-dataset-v11.mjs --input PRIVATE.csv --output /tmp/quote-audit.json">명령 복사</button><p>2) 집계 생성 시 비공개 입력 경로를 환경변수로 전달</p><code class="v11-code">INTERIOR_QUOTE_DATASET=/private/PRIVATE.csv node interior-cost-core/postprocess-review-date.mjs</code><button type="button" class="secondary" data-v11-copy="INTERIOR_QUOTE_DATASET=/private/PRIVATE.csv node interior-cost-core/postprocess-review-date.mjs">명령 복사</button><p class="v11-intake-note">원본 행·이름·전화번호·이메일·상세주소·업체명·계좌·서명은 공개 산출물에 포함하지 않습니다. 운영자가 수집한 원본 파일을 Git에 커밋하지 않는 것이 전제입니다.</p></div></section><section class="v11-section"><div class="site-shell"><div class="table-wrap"><table class="v11-ops-table"><tbody><tr><th>입력 스키마</th><td><a href="${BASE}/data/quote-sample-schema.json">quote-sample-schema.json</a></td></tr><tr><th>집계 계약</th><td><a href="${BASE}/data/quote-aggregate-contract.json">quote-aggregate-contract.json</a></td></tr><tr><th>운영 계약</th><td><a href="${BASE}/data/quote-ops-contract-v11.json">quote-ops-contract-v11.json</a></td></tr><tr><th>현재 커버리지</th><td><a href="${BASE}/data/coverage/">coverage dashboard</a></td></tr><tr><th>원본 공개</th><td>하지 않음</td></tr></tbody></table></div></div></section></main>${footer}${scripts}</body></html>`);

const addedAnswers=[
 ['v11-intake','데이터 수집','익명 인테리어 견적 데이터는 어떻게 만들 수 있나요?','견적 행 만들기 페이지에서 이름·연락처·상세주소 없이 조건과 금액만 입력해 브라우저 로컬 배치에 저장한 뒤 CSV로 내보낼 수 있습니다.',`${BASE}/quote-intake/`],
 ['v11-upload','데이터 수집','견적 CSV가 사이트 서버로 자동 업로드되나요?','아니요. 현재 수집 도구는 서버 전송이 없고 브라우저에서 CSV를 직접 내보내는 방식입니다.',`${BASE}/quote-intake/`],
 ['v11-pii','데이터 수집','견적 데이터에 업체명이나 전화번호를 넣어도 되나요?','안 됩니다. 공개 통계 스키마는 이름·전화번호·이메일·상세주소·업체 식별정보 같은 열을 허용하지 않습니다.',`${BASE}/data/quote-operations/`],
 ['v11-raw','데이터 수집','실제 견적 원본 행을 사이트에서 공개하나요?','공개하지 않습니다. 비공개 원본에서 집계한 N·P25·중앙값·P75와 데이터 품질 정보만 공개합니다.',`${BASE}/data/quote-operations/`],
 ['v11-coverage','데이터 품질','지역×평수 커버리지 히트맵은 무엇을 뜻하나요?',`17개 시도와 24·30·32·34·40평 조합별 실제 표본 N과 세그먼트 공개 기준 N≥${segmentN}까지 남은 건수를 보여줍니다.`,`${BASE}/data/coverage/`],
 ['v11-trade','데이터 품질','욕실이나 주방 공종 통계는 전체 견적 N과 같나요?','아닙니다. 욕실·주방 등 각 공종 금액 필드가 실제로 입력된 행 수를 별도로 계산하며, 공종별 N 기준을 충족해야 해당 가격분포를 공개할 수 있습니다.',`${BASE}/data/coverage/`],
 ['v11-gap','데이터 품질','어떤 견적 데이터를 먼저 모아야 하나요?','데이터 부족 페이지는 공개 기준까지 남은 표본 수가 적은 셀부터 정렬합니다. 검색량이나 시장 수요를 추정해 우선순위를 만들지는 않습니다.',`${BASE}/data/data-gaps/`],
 ['v11-source','출처','공식 데이터가 새로 발표되면 자동으로 숫자가 바뀌나요?','새 공표 기간은 감시기가 탐지하지만 숫자 값은 자동으로 덮어쓰지 않습니다. 원문·기간·단위를 검증한 뒤 반영합니다.',`${BASE}/data/source-freshness/`],
 ['v11-watch','출처','어떤 공식 출처를 자동 감시하나요?','건설공사비지수, 건설업 임금실태조사, 표준시장단가의 공표 기간을 감시합니다.',`${BASE}/data/source-freshness/`],
 ['v11-publish','지역×평수','지역×평수 가격 페이지는 언제 생성되나요?',`해당 지역×반올림 공급평수 셀 자체가 N≥${segmentN}을 충족한 경우에만 가격 페이지 생성·색인 후보가 됩니다.`,`${BASE}/data/coverage/`],
 ['v11-overall','실제견적','전체 실제 견적 가격분포는 몇 건부터 공개하나요?',`사이트 편집 정책상 전체 검수 표본 N≥${overallN}에서 P25·중앙값·P75를 공개합니다.`,`${BASE}/data/quote-statistics/`],
 ['v11-audit','운영','운영자가 CSV를 공개 전에 검증할 수 있나요?','audit-quote-dataset-v11.mjs CLI가 스키마·개인정보 열·N 게이트를 검증하고 원본 행을 결과에 포함하지 않는 요약만 출력합니다.',`${BASE}/data/quote-operations/`]
].map(([id,category,question,answer,url])=>({id,category,question,answer,url,status:'published',source_type:'METHODOLOGY'}));
const answerById=new Map();for(const a of [...(baseAnswers.answers||[]),...addedAnswers])answerById.set(a.id,a);const answers=[...answerById.values()];
write('data/answer-index-v11.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,count:answers.length,answers},null,2));
const cats=[...new Set(answers.map(x=>x.category))];const answerCards=answers.map(a=>`<article data-v11-answer data-category="${esc(a.category)}"><span>${esc(a.category)} · ${esc(a.source_type||'DATA')}</span><h3>${esc(a.question)}</h3><p>${esc(a.answer)}</p><a href="${a.url}">근거 페이지</a></article>`).join('');
write('data/answers-v11/index.html',`${head(`인테리어 비용 질문 ${answers.length}개 | 데이터 근거 답변 허브`,`인테리어 견적·공공단가·지역×평수·데이터 수집·공식 출처에 관한 ${answers.length}개 질문을 근거 페이지와 함께 제공합니다.`,`${SITE}/data/answers-v11/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">ANSWER INDEX V11</p><h1>근거 연결 질문 ${answers.length}개</h1><p>가격을 추정하지 않고 현재 공개 가능한 데이터와 운영 기준을 답변에 연결합니다.</p></div></section><section class="v11-section"><div class="site-shell"><div class="v11-kpi"><div><span>질문</span><strong>${answers.length}개</strong></div><div><span>카테고리</span><strong>${cats.length}개</strong></div><div><span>실제견적 N</span><strong>${quote.sample_count||0}</strong></div><div><span>지역×평수 셀</span><strong>${routeRows.length}</strong></div><div><span>공공단가</span><strong>${unit.items?.length||0}</strong></div><div><span>원본견적 공개</span><strong>안 함</strong></div></div><div class="v10-answer-grid">${answerCards}</div><p class="v11-intake-note"><a href="${BASE}/data/answer-index-v11.json">machine-readable answer index</a></p></div></section></main>${footer}${scripts}</body></html>`);

// Home/data hub entry points.
let home=read('index.html');const homeRail=`<section class="v11-home-rail"><div class="site-shell"><div class="v11-data-links"><a href="${BASE}/quote-intake/"><span>COLLECT</span><strong>익명 견적 행 만들기</strong></a><a href="${BASE}/data/coverage/"><span>COVERAGE</span><strong>17×5 표본 히트맵</strong></a><a href="${BASE}/data/source-freshness/"><span>SOURCES</span><strong>공식 공표 감시</strong></a></div></div></section>`;if(!home.includes('v11-home-rail'))home=home.replace('<main>',`<main>${homeRail}`);home=home.replace(/데이터 v(?:8|9|10)\.0\.0/g,'데이터 v11.0.0');write('index.html',home);
let data=read('data/index.html');if(!data.includes('/data/coverage/'))data=data.replace('</main>',`<section class="v11-section"><div class="site-shell"><div class="v11-section-head"><div><h2>데이터 운영</h2><p>수집·커버리지·공식 출처 감시·운영 검수</p></div></div><div class="v11-data-links"><a href="${BASE}/quote-intake/"><span>COLLECT</span><strong>익명 견적 행 만들기</strong></a><a href="${BASE}/data/coverage/"><span>COVERAGE</span><strong>표본 커버리지</strong></a><a href="${BASE}/data/data-gaps/"><span>GAPS</span><strong>부족 표본</strong></a><a href="${BASE}/data/source-freshness/"><span>SOURCES</span><strong>공식 출처 신선도</strong></a><a href="${BASE}/data/quote-operations/"><span>OPS</span><strong>비공개 검수 절차</strong></a><a href="${BASE}/data/answers-v11/"><span>AEO</span><strong>답변 ${answers.length}개</strong></a></div></div></section></main>`);write('data/index.html',data);

try{const search=json('data/search-index.json',[]);const entries=[['익명 인테리어 견적 행 만들기',`${BASE}/quote-intake/`,'도구','개인정보 없이 견적 조건과 금액을 브라우저에서 익명 CSV로 정리'],['인테리어 견적 데이터 커버리지',`${BASE}/data/coverage/`,'데이터','17개 지역×5개 평수의 표본 N과 공개 기준'],['인테리어 견적 데이터 부족 현황',`${BASE}/data/data-gaps/`,'데이터','공개 기준까지 남은 표본 수'],['공식 출처 신선도',`${BASE}/data/source-freshness/`,'데이터','공사비지수·건설임금·표준시장단가 공표 기간 감시'],['견적 데이터 운영 절차',`${BASE}/data/quote-operations/`,'데이터','비공개 원본 검증과 집계 공개 절차'],[`인테리어 비용 질문 ${answers.length}개`,`${BASE}/data/answers-v11/`,'답변','견적·지역·공공단가·데이터 수집 질문 허브']];for(const [title,url,type,description] of entries)if(!search.some(x=>x.url===url))search.push({title,url,type,description,keywords:title.split(' ')});write('data/search-index.json',JSON.stringify(search,null,2))}catch{}
try{let sm=read('sitemap.xml');for(const p of ['quote-intake/','data/coverage/','data/data-gaps/','data/source-freshness/','data/quote-operations/','data/answers-v11/'])if(!sm.includes(`/${p}</loc>`))sm=sm.replace('</urlset>',`<url><loc>${SITE}/${p}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap.xml',sm)}catch{}
try{let llms=read('llms.txt');if(!llms.includes('v11 data operations'))llms+=`\n\n# v11 data operations\n- Anonymous quote intake: ${SITE}/quote-intake/ (client-only CSV export; no server upload)\n- Coverage: ${SITE}/data/coverage/ and ${SITE}/data/quote-coverage-v11.json\n- Data gaps: ${SITE}/data/data-gaps/\n- Source freshness: ${SITE}/data/source-freshness/\n- Quote operations contract: ${SITE}/data/quote-ops-contract-v11.json\n- Answer index v11: ${SITE}/data/answer-index-v11.json\n- Raw quote rows are never public. Region×pyeong price pages require exact cell N>=${segmentN}. Source watcher detects new periods but never auto-overwrites numeric values.\n`;write('llms.txt',llms)}catch{}

// Inject v11 assets into all HTML and preserve preview noindex.
const walk=(dir=ROOT,out=[])=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())walk(f,out);else if(e.name.endsWith('.html'))out.push(path.relative(ROOT,f).replaceAll('\\','/'))}return out};
for(const rel of walk()){
 let h=read(rel);if(!h.includes('site-v11.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v11.css?v=${build}"></head>`);if(!h.includes('app-v11.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v11.js?v=${build}" defer></script></body>`);if(/<body/.test(h)&&!/<body[^>]*\bv11-ui\b/.test(h))h=h.replace(/<body([^>]*)>/,(_,a)=>{if(/class="/.test(a))return `<body${a.replace(/class="([^"]*)"/,`class="$1 v11-ui"`)}>`;return `<body${a} class="v11-ui">`});write(rel,h)
}

function audit(){const files=walk(),rows=files.map(rel=>{const h=read(rel),main=h.match(/<main[\s\S]*?<\/main>/i)?.[0]||h,title=strip(h.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||''),h1=strip(h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||''),chars=strip(main).length;return {rel,title,h1,chars,noindex:/noindex/.test(h),canonical:/rel="canonical"/.test(h),structured:/application\/ld\+json/.test(h),links:(h.match(/<a\s/gi)||[]).length}});const dup=k=>{const m=new Map();for(const r of rows){if(!r[k])continue;(m.get(r[k])||m.set(r[k],[]).get(r[k])).push(r.rel)}return [...m.entries()].filter(([,v])=>v.length>1)};return {rows,thin:rows.filter(x=>x.chars<500),dupT:dup('title'),dupH:dup('h1')}}
const a=audit(),policy=['about/index.html','contact/index.html','privacy/index.html','terms/index.html','disclaimer/index.html','editorial-policy/index.html','corrections/index.html'];const launch={version:VERSION,reviewed_on:reviewed,status:'preview_review',inventory:{html_pages:a.rows.length,quote_samples:quote.sample_count||0,region_hubs:regions.length,region_pyeong_cells:routeRows.length,public_region_pyeong_cells:routeRows.filter(x=>x.published).length,trade_fields:tradeRows.length,answer_records:answers.length,public_unit_items:unit.items?.length||0},quality:{thin_under_500:a.thin.length,duplicate_titles:a.dupT.length,duplicate_h1:a.dupH.length,noindex_pages:a.rows.filter(x=>x.noindex).length,canonical_pages:a.rows.filter(x=>x.canonical).length,structured_pages:a.rows.filter(x=>x.structured).length,average_text_chars:Number((a.rows.reduce((s,x)=>s+x.chars,0)/a.rows.length).toFixed(1)),average_internal_links:Number((a.rows.reduce((s,x)=>s+x.links,0)/a.rows.length).toFixed(1)),policy_pages_present:policy.filter(p=>fs.existsSync(path.join(ROOT,p))).length,policy_pages_expected:policy.length},data_engine:{overall_threshold:overallN,segment_threshold:segmentN,coverage_json:true,gap_priorities:true,private_audit_cli:true,raw_rows_public:false,pii_columns_allowed:false,source_watch_ready:true,source_update_required:freshness.update_required},production_switch:{preview_noindex_all:a.rows.every(x=>x.noindex),robots_change_requires_owner_approval:true,operating_domain_deployed:false}};
write('data/launch-gate-v11.json',JSON.stringify(launch,null,2));
write('data/launch-gate-v11/index.html',`${head('인테리어 데이터 사이트 v11 운영 전환 게이트','표본 커버리지·정책·Thin·중복·공식 출처·원본 비공개 규칙을 운영 전환 전에 한 번에 점검합니다.',`${SITE}/data/launch-gate-v11/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">LAUNCH GATE V11</p><h1>운영 전환 게이트</h1><p>AdSense 승인이나 검색순위를 보장하는 점수가 아니라, 운영 전환 전에 누락을 막는 내부 감사입니다.</p></div></section><section class="v11-section"><div class="site-shell"><div class="v11-kpi"><div><span>HTML</span><strong>${launch.inventory.html_pages}</strong></div><div><span>500자 미만</span><strong>${launch.quality.thin_under_500}</strong></div><div><span>제목 중복</span><strong>${launch.quality.duplicate_titles}</strong></div><div><span>H1 중복</span><strong>${launch.quality.duplicate_h1}</strong></div><div><span>noindex</span><strong>${launch.quality.noindex_pages}/${launch.inventory.html_pages}</strong></div><div><span>정책</span><strong>${launch.quality.policy_pages_present}/${launch.quality.policy_pages_expected}</strong></div></div><div class="v11-readiness"><div class="v11-checks"><div class="v11-check"><span>원본 견적 공개 금지</span><strong>PASS</strong></div><div class="v11-check"><span>개인정보 열 차단</span><strong>PASS</strong></div><div class="v11-check"><span>지역×평수 N 게이트</span><strong>PASS</strong></div><div class="v11-check"><span>공식 출처 감시 준비</span><strong>PASS</strong></div><div class="v11-check"><span>운영 robots 전환</span><strong>사용자 승인 전 금지</strong></div></div><div><p>실제 견적 표본 N=${quote.sample_count||0}이므로 민간 가격분포를 억지로 채우지 않습니다. 데이터 수집이 진행되면 커버리지 JSON과 지역×평수 공개 후보가 같은 빌드에서 자동 갱신됩니다.</p><p><a href="${BASE}/data/launch-gate-v11.json">launch-gate-v11.json</a></p></div></div></div></section></main>${footer}${scripts}</body></html>`);

// The audit page itself changes the page count; inject assets and perform a final primary audit.
for(const rel of ['data/launch-gate-v11/index.html']){let h=read(rel);if(!h.includes('site-v11.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v11.css?v=${build}"></head>`);if(!h.includes('app-v11.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v11.js?v=${build}" defer></script></body>`);if(!/<body[^>]*\bv11-ui\b/.test(h))h=h.replace('<body>','<body class="v11-ui">');write(rel,h)}
const finalAudit=audit();
const report=json('data/v6-report.json',{});Object.assign(report,{version:VERSION,v11_bulk_batch:true,v11_quote_intake:true,v11_private_audit_cli:true,v11_coverage_dashboard:true,v11_region_pyeong_heatmap:true,v11_trade_coverage:true,v11_data_gap_priorities:true,v11_source_freshness:true,v11_source_watch_ready:true,v11_quote_operations:true,v11_answer_hub:true,v11_answer_count:answers.length,v11_launch_gate:true,v11_assets_injected:true,v11_page_count:finalAudit.rows.length,v11_thin_zero:finalAudit.thin.length===0,v11_unique_titles:finalAudit.dupT.length===0,v11_unique_h1:finalAudit.dupH.length===0,v11_preview_noindex_all:finalAudit.rows.every(x=>x.noindex),quote_segment_dimensions:Object.keys(quote.segments||{}).length,home_version_consistent:read('index.html').includes('데이터 v11.0.0')});write('data/v6-report.json',JSON.stringify(report,null,2));
if(answers.length<85||regions.length!==17||routeRows.length!==85||Object.keys(quote.segments||{}).length<9||!report.v11_quote_intake||!report.v11_coverage_dashboard||!report.v11_source_watch_ready||!report.home_version_consistent||finalAudit.thin.length||finalAudit.dupT.length||finalAudit.dupH.length||!finalAudit.rows.every(x=>x.noindex))throw new Error(`v11 quality gate failed ${JSON.stringify({answers:answers.length,regions:regions.length,routes:routeRows.length,dimensions:Object.keys(quote.segments||{}).length,thin:finalAudit.thin.map(x=>x.rel),dupT:finalAudit.dupT,dupH:finalAudit.dupH,noindex:[finalAudit.rows.filter(x=>x.noindex).length,finalAudit.rows.length],home:report.home_version_consistent})}`);
console.log(JSON.stringify({version:VERSION,pages:finalAudit.rows.length,answers:answers.length,coverage:{regions:coverage.regions.published,region_pyeong:coverage.region_pyeong.published,trades:coverage.trade_fields.published},build},null,2));
