import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='13.0.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8');
const write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)};
const json=(r,fallback={})=>{try{return JSON.parse(read(r))}catch{return fallback}};
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const strip=s=>String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim();
const reviewed=json('data/v5-report.json',{}).reviewed_on||new Date().toISOString().slice(0,10);
const report=json('data/v6-report.json',{}),quality12=json('data/site-quality-v12.json',{}),prod12=json('data/production-index-plan-v12.json',{pages:[]}),quote=json('data/quote-statistics.json',{sample_count:0}),fresh=json('data/source-freshness-v11.json',{sources:[],update_required:false}),answers12=json('data/answer-index-v12.json',{answers:[]}),unit=json('data/public-unit-cost-v8.json',{items:[]});
const css13=fs.readFileSync(path.join(CORE,'site-v13.css'),'utf8'),js13=fs.readFileSync(path.join(CORE,'app-v13.js'),'utf8');
write('assets/site-v13.css',css13);write('assets/app-v13.js',js13);

function htmlFiles(){const out=[];const walk=(dir,base='')=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const rel=path.posix.join(base,e.name),full=path.join(dir,e.name);if(e.isDirectory())walk(full,rel);else if(e.name.endsWith('.html'))out.push(rel)}};walk(ROOT);return out.sort()}
const route=rel=>rel==='index.html'?'/' : rel==='404.html'?'/404.html' : '/'+rel.replace(/index\.html$/,'');
const url=rel=>SITE+route(rel);
const prodByPath=new Map((prod12.pages||[]).map(x=>[x.path,x]));
const policySet=new Set(['about/index.html','contact/index.html','privacy/index.html','terms/index.html','disclaimer/index.html','editorial-policy/index.html','corrections/index.html']);
const toolRoots=new Set(['quote-check','quote-compare','calculator','checklist','one-set','quote-paste','quote-intake','quote-batch','quote-market','cost-combination']);
const opsPrefixes=['data/launch','data/publisher','data/site-quality','data/source-freshness','data/quote-operations','data/data-gaps','data/coverage-targets','data/contribute','data/production-simulator','data/ad-layout','data/prelaunch-v13','data/link-audit-v13','data/search-purpose-v13','data/schema-audit-v13','data/performance-v13','data/accessibility-v13','data/sitemaps-v13'];
function kindFor(rel){
  if(rel==='index.html')return 'home';if(rel==='404.html'||rel.startsWith('search/'))return 'error_search';if(policySet.has(rel))return 'policy';
  const first=rel.split('/')[0];if(toolRoots.has(first))return 'tool';if(rel.startsWith('region/')&&/^region\/[^/]+\/\d+-pyeong\//.test(rel))return 'region_pyeong';if(rel.startsWith('region/'))return 'region';
  if(rel.startsWith('interior-cost/'))return 'pyeong';if(rel.startsWith('cost/'))return 'trade';if(rel.startsWith('guides/')||rel.startsWith('guide/'))return 'guide';
  if(rel.startsWith('data/public-unit-cost/'))return 'public_reference';if(opsPrefixes.some(p=>rel.startsWith(p)))return 'operations';if(rel.startsWith('data/'))return 'data';return 'content';
}
function intentFor(rel,title){const k=kindFor(rel),slug=route(rel).replace(/^\//,'').replace(/\/$/,'');if(k==='home')return '인테리어 비용 데이터·견적 비교 허브';if(k==='pyeong')return `평수별 인테리어 비용 조건 · ${slug.split('/').at(-1)}`;if(k==='trade')return `공종별 인테리어 비용 · ${slug.split('/').at(-1)}`;if(k==='region')return `지역별 실제 견적 상태 · ${slug.split('/').at(-1)}`;if(k==='region_pyeong')return `지역×평수 실제 견적 분포 · ${slug.split('/').slice(-2).join(' ')}`;if(k==='tool')return `인테리어 견적 도구 · ${slug}`;if(k==='public_reference')return `공공 표준시장단가 참고 · ${slug.split('/').at(-1)}`;return title||slug}
function internalTarget(href){
  let h=String(href||'').trim();if(!h||h.startsWith('#')||h.startsWith('mailto:')||h.startsWith('tel:')||h.startsWith('javascript:'))return null;
  h=h.split('#')[0].split('?')[0];if(h.startsWith(SITE))h=h.slice(SITE.length)||'/';else if(h.startsWith(BASE))h=h.slice(BASE.length)||'/';else return null;
  if(/\.(json|xml|txt|csv|js|css|png|jpg|jpeg|webp|svg)$/i.test(h))return {asset:true,path:h.replace(/^\//,'')};
  if(h==='/')return {asset:false,path:'index.html'};if(h==='/404.html')return {asset:false,path:'404.html'};h=h.replace(/^\//,'');if(h.endsWith('/'))return {asset:false,path:h+'index.html'};if(h.endsWith('.html'))return {asset:false,path:h};return {asset:false,path:h+'/index.html'};
}
function removeLegacyHome(html){
  const patterns=[
    /<div class="site-shell"><nav class="v12-home-rail"[\s\S]*?<\/nav><\/div>/g,
    /<section class="v11-home-rail"[\s\S]*?<\/section>/g,
    /<div class="site-shell"><nav class="v10-mobile-launch"[\s\S]*?<\/nav><\/div>/g,
    /<section class="v6-section v9-command-wrap"[\s\S]*?<\/section>/g,
    /<div class="site-shell"><section class="v8-board"[\s\S]*?<\/section><\/div>/g,
    /<section class="v7-rail"[\s\S]*?<\/section>/g
  ];for(const p of patterns)html=html.replace(p,'');return html;
}
const official=report.official_index_latest||{},wage=report.official_wage||{},sourceCurrent=!fresh.update_required,quoteN=quote.sample_count||0;
const launch=`<section class="v13-launch"><div class="site-shell"><div class="v13-launch-head"><h2>견적을 같은 기준으로 맞추기</h2><p>입력·비교·계산·공공 참고값 네 경로만 먼저 보여주고, 운영·수집 도구는 데이터 허브로 분리했습니다.</p></div><nav class="v13-launch-grid" aria-label="핵심 기능"><a href="${BASE}/quote-check/"><span>CHECK</span><strong>견적 검사</strong><em>VAT · 폐기물 · 창호 · 공사범위</em></a><a href="${BASE}/quote-compare/"><span>COMPARE</span><strong>3견적 비교</strong><em>A/B/C 조건과 공종을 같은 표로</em></a><a href="${BASE}/calculator/"><span>CALCULATE</span><strong>예산·단가 계산</strong><em>입력값과 공식 지수는 분리</em></a><a href="${BASE}/data/public-unit-cost/topics/"><span>REFERENCE</span><strong>공공단가 65개</strong><em>민간 시장평균이 아닌 예정가격 참고</em></a></nav><div class="v13-status"><div><span>공사비지수</span><strong>${official.value??'—'}</strong></div><div><span>건설업 일평균</span><strong>${wage.daily_average?Number(wage.daily_average).toLocaleString('ko-KR')+'원':'—'}</strong></div><div><span>실제 견적</span><strong>N=${quoteN}</strong></div><div><span>공식 출처</span><strong>${sourceCurrent?'현재 반영':'갱신 확인'}</strong></div><div><span>현재 상태</span><strong>PREVIEW · NOINDEX</strong></div></div></div></section>`;

for(const rel of htmlFiles()){
  let h=read(rel);if(!/\bv13-ui\b/.test(h))h=h.replace(/<body([^>]*)class="([^"]*)"/,'<body$1class="$2 v13-ui"').replace(/<body(?![^>]*class=)([^>]*)>/,'<body$1 class="v13-ui">');
  h=h.replace(/데이터 v12\.0\.0/g,'데이터 v13.0.0');
  if(!h.includes('site-v13.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v13.css"></head>`);
  if(!h.includes('app-v13.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v13.js" defer></script></body>`);
  if(rel==='index.html'){h=removeLegacyHome(h);if(!h.includes('class="v13-launch"'))h=h.replace('<main>','<main>'+launch)}
  if(rel==='data/index.html'&&!h.includes('v13-prelaunch-link'))h=h.replace('</main>',`<section class="v13-section v13-prelaunch-link"><div class="site-shell"><h2>운영 전 최종 감사</h2><p>검색 역할, 링크 그래프, 구조화데이터, 성능 번들, 접근성, 운영 sitemap 분할을 한 번에 확인합니다.</p><nav class="v10-actions"><a href="${BASE}/data/prelaunch-v13/">v13 프리런치 감사</a><a href="${BASE}/data/search-purpose-v13/">검색 역할</a><a href="${BASE}/data/performance-v13/">성능 예산</a></nav></div></section></main>`);
  write(rel,h);
}

const baseTemplate=read('data/index.html'),header=baseTemplate.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=baseTemplate.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',styleRefs=[...baseTemplate.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scriptRefs=[...baseTemplate.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const pageHead=(title,desc,canonical)=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${canonical}">${styleRefs}</head><body class="v13-ui">`;
const shell=(title,kicker,lead,body,canonical)=>`${pageHead(title,lead,canonical)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">${kicker}</p><h1>${title.replace(/ \|.*$/,'')}</h1><p>${lead}</p></div></section>${body}</main>${footer}${scriptRefs}</body></html>`;
const placeholders={
 'data/prelaunch-v13/index.html':['v13 프리런치 감사 | 검색·링크·성능·접근성','PRELAUNCH V13','운영 배포 전 검색 역할·링크·스키마·성능·접근성·sitemap을 한 화면에서 점검합니다.'],
 'data/search-purpose-v13/index.html':['검색 역할·카니발리제이션 감사 | 페이지 목적 맵','SEARCH PURPOSE','각 페이지의 검색 역할과 운영 색인 상태를 분리해 유사 페이지가 같은 의도를 경쟁하지 않도록 점검합니다.'],
 'data/link-audit-v13/index.html':['내부링크 감사 | 깨진 링크·고립 페이지·링크 밀도','LINK GRAPH','프리뷰 HTML의 내부 링크를 실제 파일 경로와 대조하고 운영 색인 후보의 고립 여부를 확인합니다.'],
 'data/schema-audit-v13/index.html':['구조화데이터 감사 | WebPage·Breadcrumb·FAQ','SCHEMA COVERAGE','각 페이지의 JSON-LD 존재 여부와 기본 WebPage·Breadcrumb 보강 상태를 확인합니다.'],
 'data/performance-v13/index.html':['성능 예산 | CSS·JS 요청 통합','PERFORMANCE BUDGET','누적 버전별 CSS·JS 요청을 하나의 번들로 통합하고 정적 자산 크기와 요청 수를 점검합니다.'],
 'data/accessibility-v13/index.html':['접근성 정적 감사 | H1·이미지·버튼·표','ACCESSIBILITY','정적 HTML에서 확인할 수 있는 H1, 이미지 대체텍스트, 빈 버튼, 표 헤더의 치명적 누락을 점검합니다.'],
 'data/sitemaps-v13/index.html':['운영 sitemap 분할 시뮬레이션 | core·tool·content·data','SITEMAP PARTITIONS','실제 루트 sitemap을 바꾸지 않고 운영 색인 후보를 페이지 역할별 sitemap으로 분할해 검수합니다.']
};
for(const [rel,[title,kicker,lead]] of Object.entries(placeholders))write(rel,shell(title,kicker,lead,`<section class="v13-section"><div class="site-shell"><p>최종 생성 단계에서 실제 감사 결과로 채워집니다. 현재 프리뷰의 robots·sitemap·광고 설정은 변경하지 않습니다.</p></div></section>`,url(rel)));

function injectSchema(){for(const rel of htmlFiles()){if(rel==='404.html'||rel.startsWith('search/'))continue;let h=read(rel);if(h.includes('data-v13-schema'))continue;const h1=(h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||h.match(/<title>(.*?)<\/title>/i)?.[1]||rel).replace(/<[^>]+>/g,'').trim(),segments=route(rel).split('/').filter(Boolean),crumb=[{'@type':'ListItem',position:1,name:'홈',item:SITE+'/'}];if(segments.length)crumb.push({'@type':'ListItem',position:2,name:h1,item:url(rel)});const schema={'@context':'https://schema.org','@graph':[{'@type':'WebPage',name:h1,url:url(rel),dateModified:reviewed,isPartOf:{'@type':'WebSite',name:'견적검수실',url:SITE+'/'}},{'@type':'BreadcrumbList',itemListElement:crumb}]};h=h.replace('</head>',`<script type="application/ld+json" data-v13-schema>${JSON.stringify(schema)}</script></head>`);write(rel,h)}}
injectSchema();

function titleOf(h){return (h.match(/<title>(.*?)<\/title>/i)?.[1]||'').replace(/<[^>]+>/g,'').trim()}
function h1Of(h){return (h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||'').replace(/<[^>]+>/g,'').trim()}
function baseAudit(){
  const files=htmlFiles(),set=new Set(files),rows=[],inbound=new Map(files.map(f=>[f,0])),broken=[];
  for(const rel of files){const h=read(rel),hrefs=[...h.matchAll(/href="([^"]+)"/g)].map(x=>x[1]),targets=[];for(const href of hrefs){const t=internalTarget(href);if(!t||t.asset)continue;targets.push(t.path);if(set.has(t.path))inbound.set(t.path,(inbound.get(t.path)||0)+1);else broken.push({from:rel,href,target:t.path})}const prod=prodByPath.get(rel);rows.push({path:rel,url:url(rel),kind:kindFor(rel),title:titleOf(h),h1:h1Of(h),intent:intentFor(rel,titleOf(h)),preview_noindex:/<meta name="robots" content="[^"]*noindex/i.test(h),canonical:/<link rel="canonical" href="[^"]+"/i.test(h),structured:(h.match(/application\/ld\+json/g)||[]).length,internal_links:targets.length,production_indexable:prod?.indexable??false,production_reason:prod?.reason||'v13 audit page / preview-only'})}
  const orphans=rows.filter(x=>x.path!=='index.html'&&x.production_indexable&&(inbound.get(x.path)||0)===0).map(x=>x.path);return {files,rows,inbound,broken,orphans};
}
let audit=baseAudit();
if(audit.orphans.length){for(const rel of audit.orphans){let h=read(rel);if(h.includes('class="v13-related"'))continue;const k=kindFor(rel),links=k==='pyeong'?[['평수별','/interior-cost/'],['견적 비교','/quote-compare/'],['예산 계산','/calculator/']]:k==='trade'?[['공사별','/cost/'],['공공단가','/data/public-unit-cost/topics/'],['견적 비교','/quote-compare/']]:[['홈','/'],['데이터','/data/'],['산출 원칙','/data/methodology/']];h=h.replace('</main>',`<section class="v13-related"><div class="site-shell"><strong>관련 경로</strong><nav>${links.map(([n,p])=>`<a href="${BASE}${p}">${n}</a>`).join('')}</nav></div></section></main>`);write(rel,h)}audit=baseAudit()}

function bundleAssets(){
  const home=read('index.html'),cssHrefs=[...home.matchAll(/<link rel="stylesheet" href="([^"]+\.css(?:\?[^\"]*)?)">/g)].map(x=>x[1]).filter(x=>x.startsWith(BASE+'/assets/')),jsHrefs=[...home.matchAll(/<script src="([^"]+\.js(?:\?[^\"]*)?)" defer><\/script>/g)].map(x=>x[1]).filter(x=>x.startsWith(BASE+'/assets/'));
  const uniq=a=>[...new Set(a)],cssFiles=uniq(cssHrefs).map(x=>x.split('/').pop().split('?')[0]),jsFiles=uniq(jsHrefs).map(x=>x.split('/').pop().split('?')[0]);
  const cssBundle=cssFiles.map(f=>`/* ${f} */\n${read('assets/'+f)}`).join('\n'),jsBundle=jsFiles.map(f=>`/* ${f} */\n${read('assets/'+f)}`).join('\n');
  const hash=crypto.createHash('sha1').update(cssBundle+'\n'+jsBundle).digest('hex').slice(0,10),cssName=`site-v13-bundle.css`,jsName=`app-v13-bundle.js`;write('assets/'+cssName,cssBundle);write('assets/'+jsName,jsBundle);
  const cssLink=`<link rel="stylesheet" href="${BASE}/assets/${cssName}?v=${hash}">`,jsTag=`<script src="${BASE}/assets/${jsName}?v=${hash}" defer></script>`;
  for(const rel of htmlFiles()){let h=read(rel),seen=false;h=h.replace(new RegExp(`<link rel="stylesheet" href="${BASE.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\/assets\/[^\"]+\\.css(?:\\?[^\"]*)?">`,'g'),()=>{if(seen)return '';seen=true;return cssLink});seen=false;h=h.replace(new RegExp(`<script src="${BASE.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\/assets\/[^\"]+\\.js(?:\\?[^\"]*)?" defer><\\/script>`,'g'),()=>{if(seen)return '';seen=true;return jsTag});write(rel,h)}
  return {hash,cssFiles,jsFiles,cssBytes:Buffer.byteLength(cssBundle),jsBytes:Buffer.byteLength(jsBundle),beforeRequests:cssFiles.length+jsFiles.length,afterRequests:2};
}
const perf=bundleAssets();audit=baseAudit();

const purposes=audit.rows.map(x=>({...x,inbound:audit.inbound.get(x.path)||0}));
const normalizeTitle=s=>String(s).toLowerCase().replace(/견적검수실|인테리어|2026|데이터|비용|가이드/g,' ').replace(/[^가-힣a-z0-9]+/g,' ').trim().split(/\s+/).filter(x=>x.length>1);
const sim=(a,b)=>{const A=new Set(normalizeTitle(a)),B=new Set(normalizeTitle(b));if(!A.size||!B.size)return 0;const inter=[...A].filter(x=>B.has(x)).length,union=new Set([...A,...B]).size;return inter/union};
const cann=[];const idxRows=purposes.filter(x=>x.production_indexable);for(let i=0;i<idxRows.length;i++)for(let j=i+1;j<idxRows.length;j++){const a=idxRows[i],b=idxRows[j],s=sim(a.title,b.title),family=a.kind===b.kind&&['pyeong','region','region_pyeong','public_reference'].includes(a.kind);if(s>=.72&&!family)cann.push({a:a.path,b:b.path,similarity:Number(s.toFixed(2)),review:true})}
write('data/search-purpose-map-v13.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,pages:purposes.length,indexable:idxRows.length,pages_map:purposes,cannibalization_review:cann},null,2));
write('data/link-audit-v13.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,pages:audit.rows.length,broken_count:audit.broken.length,broken:audit.broken.slice(0,100),indexable_orphan_count:audit.orphans.length,indexable_orphans:audit.orphans,average_internal_links:Number((audit.rows.reduce((s,x)=>s+x.internal_links,0)/Math.max(1,audit.rows.length)).toFixed(1)),high_link_pages:audit.rows.filter(x=>x.internal_links>60).map(x=>({path:x.path,links:x.internal_links}))},null,2));

const schemaRows=audit.rows.map(x=>({path:x.path,kind:x.kind,scripts:x.structured,has_v13_schema:read(x.path).includes('data-v13-schema')})),schemaAudit={version:VERSION,reviewed_on:reviewed,pages:schemaRows.length,structured_pages:schemaRows.filter(x=>x.scripts>0).length,coverage:Number((schemaRows.filter(x=>x.scripts>0).length/schemaRows.length).toFixed(3)),v13_webpage_breadcrumb:schemaRows.filter(x=>x.has_v13_schema).length,excluded_error_search:schemaRows.filter(x=>['error_search'].includes(x.kind)).length,rows:schemaRows};write('data/schema-audit-v13.json',JSON.stringify(schemaAudit,null,2));

const accessRows=[];for(const rel of audit.files){const h=read(rel),imgs=[...h.matchAll(/<img\b[^>]*>/gi)].map(x=>x[0]),buttons=[...h.matchAll(/<button\b[^>]*>([\s\S]*?)<\/button>/gi)].map(x=>strip(x[1])),tables=(h.match(/<table\b/gi)||[]).length,tablesWithTh=(h.match(/<table\b[\s\S]*?<th\b/gi)||[]).length,h1s=(h.match(/<h1\b/gi)||[]).length;accessRows.push({path:rel,h1_count:h1s,images:imgs.length,images_missing_alt:imgs.filter(x=>!/\balt=/i.test(x)).length,empty_buttons:buttons.filter(x=>!x).length,tables,tables_without_header:Math.max(0,tables-tablesWithTh)})}
const access={version:VERSION,reviewed_on:reviewed,pages:accessRows.length,critical:{h1_issues:accessRows.filter(x=>x.h1_count!==1).length,images_missing_alt:accessRows.reduce((s,x)=>s+x.images_missing_alt,0),empty_buttons:accessRows.reduce((s,x)=>s+x.empty_buttons,0),tables_without_header:accessRows.reduce((s,x)=>s+x.tables_without_header,0)},rows:accessRows.filter(x=>x.h1_count!==1||x.images_missing_alt||x.empty_buttons||x.tables_without_header)};write('data/accessibility-audit-v13.json',JSON.stringify(access,null,2));

const perfAudit={version:VERSION,reviewed_on:reviewed,bundle_hash:perf.hash,source_css_files:perf.cssFiles.length,source_js_files:perf.jsFiles.length,requests_before_bundle:perf.beforeRequests,requests_after_bundle:perf.afterRequests,css_bytes:perf.cssBytes,js_bytes:perf.jsBytes,css_kb:Number((perf.cssBytes/1024).toFixed(1)),js_kb:Number((perf.jsBytes/1024).toFixed(1)),budgets:{css_kb:300,js_kb:350,asset_requests:2},passes:{css:perf.cssBytes<=300*1024,js:perf.jsBytes<=350*1024,requests:perf.afterRequests<=2},note:'정적 파일 크기/요청 수 감사이며 실제 Core Web Vitals 측정값이 아님.'};write('data/performance-budget-v13.json',JSON.stringify(perfAudit,null,2));

const partitions={core:[],tools:[],content:[],data:[]};for(const x of idxRows){if(x.kind==='tool')partitions.tools.push(x.url);else if(['data','public_reference'].includes(x.kind))partitions.data.push(x.url);else if(['guide','pyeong','trade','region','region_pyeong','content'].includes(x.kind))partitions.content.push(x.url);else partitions.core.push(x.url)}
for(const [name,urls] of Object.entries(partitions))write(`data/sitemap-${name}-v13-preview.xml`,`<?xml version="1.0" encoding="UTF-8"?>\n<!-- SIMULATION ONLY: not the live root sitemap -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url>`).join('\n')}\n</urlset>\n`);
write('data/sitemap-partitions-v13.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,simulation_only:true,actual_root_sitemap_changed:false,total_index_candidates:idxRows.length,partitions:Object.fromEntries(Object.entries(partitions).map(([k,v])=>[k,{count:v.length,file:`data/sitemap-${k}-v13-preview.xml`}]))},null,2));

const extraAnswers=[
 ['v13-home','운영','왜 메인 기능 블록을 줄였나요?','버전별 기능 레일을 겹쳐 두지 않고 견적 검사·비교·계산·공공 참고값 네 경로만 먼저 보여주도록 통합했습니다.',`${BASE}/data/prelaunch-v13/`],
 ['v13-cannibal','SEO','검색 카니발리제이션은 어떻게 점검하나요?','운영 색인 후보의 title·페이지 역할을 함께 비교하고 평수·지역처럼 의도적으로 반복되는 패턴은 같은 family로 분리합니다.',`${BASE}/data/search-purpose-v13/`],
 ['v13-orphan','SEO','고립된 운영 색인 후보는 어떻게 찾나요?','생성된 HTML 링크 그래프에서 production index 후보의 inbound link가 0인지 검사하고 필요한 경우 관련 경로를 자동 보강합니다.',`${BASE}/data/link-audit-v13/`],
 ['v13-broken','SEO','깨진 내부링크도 빌드에서 확인하나요?','내부 HTML href를 실제 생성 파일과 대조해 존재하지 않는 페이지 링크를 broken으로 기록합니다.',`${BASE}/data/link-audit-v13/`],
 ['v13-schema','AEO','구조화데이터가 없는 페이지는 어떻게 처리하나요?','오류·검색 페이지를 제외한 문서에는 기본 WebPage와 BreadcrumbList JSON-LD를 보강하고 기존 FAQ·Dataset 스키마는 유지합니다.',`${BASE}/data/schema-audit-v13/`],
 ['v13-bundle','성능','CSS와 JavaScript 파일이 너무 많지 않나요?','프리뷰 생성 시 누적 버전 CSS·JS를 각각 하나의 정적 번들로 합쳐 페이지당 로컬 스타일·스크립트 요청을 줄입니다.',`${BASE}/data/performance-v13/`],
 ['v13-cwv','성능','성능 예산은 Core Web Vitals 점수인가요?','아닙니다. 정적 자산 크기와 요청 수를 보는 사전 게이트이며 실제 LCP·INP·CLS는 운영 환경에서 별도 측정해야 합니다.',`${BASE}/data/performance-v13/`],
 ['v13-a11y','접근성','접근성은 무엇을 자동 검사하나요?','정적 HTML에서 H1 개수, 이미지 alt, 빈 버튼, 표 헤더처럼 빌드 단계에서 확인 가능한 치명적 누락을 검사합니다.',`${BASE}/data/accessibility-v13/`],
 ['v13-sitemap','SEO','운영 sitemap은 하나만 쓰나요?','프리뷰에서는 실제 sitemap을 바꾸지 않고 core·tools·content·data 네 묶음으로 분할한 시뮬레이션을 만들어 검수합니다.',`${BASE}/data/sitemaps-v13/`],
 ['v13-canonical','SEO','canonical과 sitemap 역할은 같은가요?','canonical은 페이지의 대표 URL을 선언하고 sitemap은 색인 후보 URL 발견을 돕습니다. v13 감사에서는 둘을 별도로 검사합니다.',`${BASE}/data/prelaunch-v13/`],
 ['v13-evidence','AEO','AI 답변 근거 링크는 어디를 사용하나요?','답변 레코드의 source 또는 evidence URL을 실제 도구·데이터·방법론 페이지에 연결하고 빈 근거 링크가 남지 않도록 검사합니다.',`${BASE}/data/answers-v13/`],
 ['v13-ads','광고','v13에서 광고를 실제로 켜나요?','아니요. v12 광고 슬롯 계획은 유지하지만 실제 광고 스크립트와 운영 활성화는 사용자 승인 전까지 하지 않습니다.',`${BASE}/data/prelaunch-v13/`],
 ['v13-region','SEO','표본 없는 지역 페이지가 sitemap에 들어가나요?','운영 시뮬레이션에서 지역 N 기준을 통과하지 못한 지역·지역×평수 페이지는 index 후보와 sitemap 분할에서 제외합니다.',`${BASE}/data/sitemaps-v13/`],
 ['v13-launch','운영','v13 통과 후 바로 운영 배포되나요?','아니요. v13은 프리런치 감사이며 robots·sitemap·광고·운영 도메인 변경은 사용자 승인 후 별도 작업입니다.',`${BASE}/data/prelaunch-v13/`]
].map(([id,category,question,answer,source])=>({id,category,question,answer,source,url:source,status:'published',evidence_fallback:false}));
const answers=[...(answers12.answers||[]).map(x=>({...x,source:x.source||x.url||`${BASE}/data/methodology/`,url:x.source||x.url||`${BASE}/data/methodology/`})),...extraAnswers];write('data/answer-index-v13.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,count:answers.length,answers},null,2));

function auditBody(){const q=json('data/site-quality-v13.json',{}),link=json('data/link-audit-v13.json',{}),perf=json('data/performance-budget-v13.json',{}),sch=json('data/schema-audit-v13.json',{});return `<section class="v13-section"><div class="site-shell"><div class="v13-audit-kpis"><div><span>HTML</span><strong>${q.pages||audit.rows.length}</strong></div><div><span>Thin</span><strong>${q.thin_under_500??0}</strong></div><div><span>Broken</span><strong>${link.broken_count??audit.broken.length}</strong></div><div><span>Orphan</span><strong>${link.indexable_orphan_count??audit.orphans.length}</strong></div><div><span>Schema</span><strong>${sch.structured_pages||schemaAudit.structured_pages}</strong></div><div><span>Asset req</span><strong>${perf.requests_after_bundle??2}</strong></div></div><p>이 감사는 운영 전 정적 프리뷰를 대상으로 합니다. Google 색인·AdSense 승인·Core Web Vitals 결과를 보장하지 않으며 실제 production switch는 수행하지 않습니다.</p><nav class="v10-actions"><a href="${BASE}/data/search-purpose-v13/">검색 역할</a><a href="${BASE}/data/link-audit-v13/">링크 감사</a><a href="${BASE}/data/schema-audit-v13/">스키마</a><a href="${BASE}/data/performance-v13/">성능</a><a href="${BASE}/data/accessibility-v13/">접근성</a><a href="${BASE}/data/sitemaps-v13/">sitemap</a></nav></div></section>`}
function tablePage(rel,title,kicker,lead,inner){write(rel,shell(title,kicker,lead,`<section class="v13-section"><div class="site-shell">${inner}</div></section>`,url(rel)).replace(styleRefs,`<link rel="stylesheet" href="${BASE}/assets/site-v13-bundle.css?v=${perf.hash}">`).replace(scriptRefs,`<script src="${BASE}/assets/app-v13-bundle.js?v=${perf.hash}" defer></script>`))}
tablePage('data/prelaunch-v13/index.html','v13 프리런치 감사 | 검색·링크·성능·접근성','PRELAUNCH V13','운영 배포 전 검색 역할·링크·스키마·성능·접근성·sitemap을 한 화면에서 점검합니다.',auditBody().replace(/^<section[^>]*><div class="site-shell">|<\/div><\/section>$/g,''));
tablePage('data/search-purpose-v13/index.html','검색 역할·카니발리제이션 감사 | 페이지 목적 맵','SEARCH PURPOSE','각 페이지의 검색 역할과 운영 색인 상태를 분리해 유사 페이지가 같은 의도를 경쟁하지 않도록 점검합니다.',`<div data-v13-filter-root><div class="v13-filter"><input data-v13-q placeholder="페이지·의도 검색"><select data-v13-kind><option value="">전체 역할</option>${[...new Set(purposes.map(x=>x.kind))].map(k=>`<option>${k}</option>`).join('')}</select></div><div class="table-wrap"><table class="v13-audit-table"><thead><tr><th>페이지</th><th>역할</th><th>검색 의도</th><th>운영</th></tr></thead><tbody>${purposes.map(x=>`<tr data-v13-row data-kind="${x.kind}" data-search="${esc(x.path+' '+x.title+' '+x.intent)}"><td>${esc(x.path)}</td><td>${x.kind}</td><td>${esc(x.intent)}</td><td>${x.production_indexable?'INDEX 후보':'NOINDEX'}</td></tr>`).join('')}</tbody></table></div></div><p>고유 family를 제외한 title 유사도 검토 후보 ${cann.length}쌍. 실제 canonical 변경은 이 감사만으로 자동 수행하지 않습니다.</p>`);
tablePage('data/link-audit-v13/index.html','내부링크 감사 | 깨진 링크·고립 페이지·링크 밀도','LINK GRAPH','프리뷰 HTML의 내부 링크를 실제 파일 경로와 대조하고 운영 색인 후보의 고립 여부를 확인합니다.',`<div class="v13-audit-kpis"><div><span>Broken</span><strong>${audit.broken.length}</strong></div><div><span>Index orphan</span><strong>${audit.orphans.length}</strong></div><div><span>평균 링크</span><strong>${json('data/link-audit-v13.json',{}).average_internal_links||'—'}</strong></div></div><p>헤더·푸터 같은 공통 탐색 링크와 본문 링크를 모두 포함한 정적 수치입니다. 링크 수 자체를 순위 신호로 보지 않고 깨진 경로·고립된 색인 후보·과도한 중복 탐색을 찾는 용도로 사용합니다.</p>${audit.broken.length?`<div class="table-wrap"><table class="v13-audit-table"><thead><tr><th>출발</th><th>href</th><th>대상</th></tr></thead><tbody>${audit.broken.slice(0,50).map(x=>`<tr><td>${x.from}</td><td>${esc(x.href)}</td><td>${x.target}</td></tr>`).join('')}</tbody></table></div>`:'<p class="v13-pass">깨진 내부 HTML 링크 없음</p>'}`);
tablePage('data/schema-audit-v13/index.html','구조화데이터 감사 | WebPage·Breadcrumb·FAQ','SCHEMA COVERAGE','각 페이지의 JSON-LD 존재 여부와 기본 WebPage·Breadcrumb 보강 상태를 확인합니다.',`<div class="v13-audit-kpis"><div><span>HTML</span><strong>${schemaAudit.pages}</strong></div><div><span>Structured</span><strong>${schemaAudit.structured_pages}</strong></div><div><span>v13 WebPage</span><strong>${schemaAudit.v13_webpage_breadcrumb}</strong></div></div><p>기존 FAQPage·Dataset·WebApplication 구조화데이터를 유지하면서 오류·검색 페이지를 제외한 문서에 WebPage와 BreadcrumbList를 보강합니다. 보이지 않는 FAQ를 새로 만들지는 않습니다.</p>`);
tablePage('data/performance-v13/index.html','성능 예산 | CSS·JS 요청 통합','PERFORMANCE BUDGET','누적 버전별 CSS·JS 요청을 하나의 번들로 통합하고 정적 자산 크기와 요청 수를 점검합니다.',`<div class="v13-budget"><div class="v13-budget-box"><h2>요청 수</h2><dl><div><dt>번들 전 로컬 CSS+JS</dt><dd>${perf.beforeRequests}</dd></div><div><dt>번들 후</dt><dd>${perf.afterRequests}</dd></div><div><dt>감소</dt><dd>${Math.max(0,perf.beforeRequests-perf.afterRequests)}</dd></div></dl></div><div class="v13-budget-box"><h2>번들 크기</h2><dl><div><dt>CSS</dt><dd>${perfAudit.css_kb}KB</dd></div><div><dt>JS</dt><dd>${perfAudit.js_kb}KB</dd></div><div><dt>예산</dt><dd>${Object.values(perfAudit.passes).every(Boolean)?'PASS':'REVIEW'}</dd></div></dl></div></div><p>정적 파일 수와 크기를 줄이는 사전 작업이며 실제 LCP·INP·CLS는 운영 CDN·기기·네트워크에서 별도로 측정해야 합니다.</p>`);
tablePage('data/accessibility-v13/index.html','접근성 정적 감사 | H1·이미지·버튼·표','ACCESSIBILITY','정적 HTML에서 확인할 수 있는 H1, 이미지 대체텍스트, 빈 버튼, 표 헤더의 치명적 누락을 점검합니다.',`<div class="v13-audit-kpis"><div><span>H1 issue</span><strong>${access.critical.h1_issues}</strong></div><div><span>Missing alt</span><strong>${access.critical.images_missing_alt}</strong></div><div><span>Empty button</span><strong>${access.critical.empty_buttons}</strong></div><div><span>Table header</span><strong>${access.critical.tables_without_header}</strong></div></div><p>브라우저·스크린리더 실제 사용성 전체를 대신하는 감사가 아닙니다. 빌드 시점에 자동 확인 가능한 치명적 정적 누락만 대상으로 합니다.</p>`);
tablePage('data/sitemaps-v13/index.html','운영 sitemap 분할 시뮬레이션 | core·tool·content·data','SITEMAP PARTITIONS','실제 루트 sitemap을 바꾸지 않고 운영 색인 후보를 페이지 역할별 sitemap으로 분할해 검수합니다.',`<div class="v13-purpose-grid">${Object.entries(partitions).map(([k,v])=>`<article class="v13-purpose-card"><span>${k.toUpperCase()}</span><strong>${v.length} URL</strong><p>data/sitemap-${k}-v13-preview.xml</p></article>`).join('')}</div><p>SIMULATION ONLY. 현재 프리뷰의 루트 sitemap과 noindex 설정은 변경하지 않습니다.</p>`);

const renderAnswers=answers.map(x=>`<article class="v10-answer-card" data-v10-answer-card data-category="${esc(x.category)}" data-search="${esc(x.question+' '+x.answer)}"><span>${esc(x.category)} · ${x.status==='withheld'?'WITHHELD':'GUIDE'}</span><h3>${esc(x.question)}</h3><p>${esc(x.answer)}</p><a href="${esc(x.source)}">근거/도구</a></article>`).join('');tablePage('data/answers-v13/index.html','인테리어 견적 질문 120개 | 검색·데이터·운영 근거 허브','ANSWER INDEX v13',`${answers.length}개 질문 · 모든 답변에 근거 경로 연결 · 표본 미달 가격 생성 없음`,`<div data-v10-answer-hub><div class="v10-answer-controls"><input data-v10-answer-q placeholder="견적 · 지역 · CSV · SEO · 성능"><select data-v10-answer-category><option value="">전체 분류</option>${[...new Set(answers.map(x=>x.category))].sort().map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div class="v10-answer-grid">${renderAnswers}</div></div>`);

// Re-apply generated WebPage/Breadcrumb schema to the final audit pages, then bundle refs again.
injectSchema();
const all=htmlFiles(),texts=all.map(rel=>({rel,h:read(rel)})),titles=texts.map(x=>titleOf(x.h)),h1s=texts.map(x=>h1Of(x.h)),dups=a=>[...new Set(a.filter((v,i)=>v&&a.indexOf(v)!==i))],thin=texts.filter(x=>strip(x.h).length<500).map(x=>x.rel),noindex=texts.filter(x=>/<meta name="robots" content="[^"]*noindex/i.test(x.h)).length,canon=texts.filter(x=>/<link rel="canonical" href="[^"]+"/i.test(x.h)).length,structured=texts.filter(x=>/application\/ld\+json/.test(x.h)).length;
const quality={version:VERSION,reviewed_on:reviewed,pages:all.length,thin_under_500:thin.length,duplicate_titles:dups(titles).length,duplicate_h1:dups(h1s).length,noindex_pages:noindex,canonical_pages:canon,structured_pages:structured,structured_ratio:Number((structured/all.length).toFixed(3)),average_text_chars:Number((texts.reduce((s,x)=>s+strip(x.h).length,0)/all.length).toFixed(0)),average_internal_links:Number((baseAudit().rows.reduce((s,x)=>s+x.internal_links,0)/all.length).toFixed(1)),broken_internal_links:baseAudit().broken.length,indexable_orphans:baseAudit().orphans.length,answer_records:answers.length,bundle_requests:2,actual_production_switch:false,actual_ads_injected:false};write('data/site-quality-v13.json',JSON.stringify(quality,null,2));
const gate={version:VERSION,reviewed_on:reviewed,status:'preview_review',checks:{thin_zero:quality.thin_under_500===0,unique_titles:quality.duplicate_titles===0,unique_h1:quality.duplicate_h1===0,noindex_all:quality.noindex_pages===quality.pages,canonical_all:quality.canonical_pages===quality.pages,broken_links_zero:quality.broken_internal_links===0,indexable_orphans_zero:quality.indexable_orphans===0,structured_coverage:quality.structured_ratio>=.95,bundle_requests_two:quality.bundle_requests===2,answer_evidence:answers.every(x=>Boolean(x.source)),actual_production_switch:false},approval:{production_requires_owner:true,robots_requires_owner:true,sitemap_requires_owner:true,ads_requires_owner:true}};write('data/launch-gate-v13.json',JSON.stringify(gate,null,2));
let r=json('data/v6-report.json',{});Object.assign(r,{version:VERSION,v13_bulk_batch:true,v13_home_consolidated:true,v13_search_purpose:true,v13_link_graph:true,v13_schema_coverage:true,v13_asset_bundling:true,v13_accessibility_audit:true,v13_sitemap_partitions:true,v13_answer_hub:true,v13_answer_count:answers.length,v13_page_count:quality.pages,v13_thin_zero:gate.checks.thin_zero,v13_unique_titles:gate.checks.unique_titles,v13_unique_h1:gate.checks.unique_h1,v13_noindex_all:gate.checks.noindex_all,v13_canonical_all:gate.checks.canonical_all,v13_broken_links_zero:gate.checks.broken_links_zero,v13_indexable_orphans_zero:gate.checks.indexable_orphans_zero,v13_structured_coverage:gate.checks.structured_coverage,v13_bundle_requests_two:gate.checks.bundle_requests_two,v13_answer_evidence:gate.checks.answer_evidence});write('data/v6-report.json',JSON.stringify(r,null,2));
let ll=read('llms.txt');if(!ll.includes('v13 prelaunch hardening'))ll+=`\n\n## v13 prelaunch hardening\n- Search purpose map: ${BASE}/data/search-purpose-map-v13.json\n- Link audit: ${BASE}/data/link-audit-v13.json\n- Schema audit: ${BASE}/data/schema-audit-v13.json\n- Performance budget: ${BASE}/data/performance-budget-v13.json\n- Accessibility audit: ${BASE}/data/accessibility-audit-v13.json\n- Sitemap partitions are simulation only; preview remains noindex.\n`;write('llms.txt',ll);
const failed=Object.entries(gate.checks).filter(([k,v])=>k!=='actual_production_switch'&&v!==true).map(([k])=>k);if(failed.length)throw new Error(`v13 quality gate failed ${JSON.stringify({failed,quality})}`);
console.log(JSON.stringify({version:VERSION,pages:quality.pages,answers:answers.length,structured:quality.structured_ratio,broken:quality.broken_internal_links,orphans:quality.indexable_orphans,bundle:[perfAudit.css_kb,perfAudit.js_kb]},null,2));
