import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='8.0.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8');
const write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)};
const json=(r,fallback={})=>{try{return JSON.parse(read(r))}catch{return fallback}};
const reviewed=json('data/v5-report.json',{}).reviewed_on||new Date().toISOString().slice(0,10);
const quoteStats=json('data/quote-statistics.json',{sample_count:0,status:'withheld'}),index=json('data/construction-cost-index.json',{}),wage=json('data/construction-wage-2026-h2.json',{}),baseUnit=json('data/public-unit-cost-2026-h2.json',{items:[]});
const css=fs.readFileSync(path.join(CORE,'site-v8.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v8.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v8.css',css);write('assets/app-v8.js',js);
const official='https://www.codil.or.kr/helpdesk/read.do?bbsId=BBSMSTR_900000000204&nttId=13281';
const mirror='https://it7.kr/solutions/public-cost/items/';
const detail=code=>`https://it7.kr/solutions/public-cost/item/${code}/`;
const u=(code,group,name,spec,unit,price,match=[])=>({code,group,name,spec,unit,price,match,detail_level:'catalog',official_source:official,reference_source:detail(code),warning:'공공 건설 예정가격 참고용. 민간 인테리어 시장가·적정가 판정용 아님'});
const extras=[
 u('GF000.01000','바탕·미장','모르타르 타설','바닥 미장면','㎥',19554,['floor']),u('GF000.02100','바탕·미장','표면마무리','인력마감','㎡',943,['floor']),u('GH110.10000','창호','시멘트모르타르 충전','창호주위','m',3763,['window']),u('GJ000.01000','수장·마감','비드 설치','-','m',4829,['carpentry']),
 u('HB001.10000','방수','시트방수/접착식','바닥','㎡',9903,['bathroom']),u('HB001.20000','방수','시트방수/접착식','수직부','㎡',13878,['bathroom']),u('HB002.10000','방수','시트방수/자착식','바닥','㎡',6629,['bathroom']),u('HB002.20000','방수','시트방수/자착식','수직부','㎡',9513,['bathroom']),
 u('HC001.10000','방수','도막방수/도막바름','바닥/1층','㎡',3985,['bathroom']),u('HC001.20000','방수','도막방수/도막바름','수직부/1층','㎡',5639,['bathroom']),u('HC002.10000','방수','도막방수/보강포','바닥/1층','㎡',2281,['bathroom']),u('HC002.20000','방수','도막방수/보강포','수직부/1층','㎡',3420,['bathroom']),u('HC003.10000','방수','도막방수/마감도료','바닥/1층','㎡',2859,['bathroom']),u('HC003.20000','방수','도막방수/마감도료','수직부/1층','㎡',3683,['bathroom']),
 u('HF201.00015','실링·창호','수밀코킹','삼각 / 폭 15mm이하','m',3713,['window']),u('HF202.00015','실링·창호','수밀코킹','사각 / 폭 15mm이하','m',4136,['window']),u('HF202.00025','실링·창호','수밀코킹','사각 / 폭 15~25mm이하','m',4345,['window']),u('HF240.10000','실링·창호','우레탄충전','양면','m',2121,['window']),u('HF240.20000','실링·창호','우레탄충전','일면','m',1021,['window']),
 u('HG022.01000','방수','폴리머 시멘트 모르타르 방수','1종','㎡',15760,['bathroom']),u('HG022.02000','방수','폴리머 시멘트 모르타르 방수','2종','㎡',10413,['bathroom']),u('HS110.10000','방수','방수 바탕처리','바닥','㎡',8341,['bathroom']),u('HS110.20000','방수','방수 바탕처리','수직부','㎡',10371,['bathroom']),u('HS120.10000','방수','방수 프라이머','1회바름','㎡',2573,['bathroom']),u('HS131.10000','방수','방수층 보호재 / PE필름 설치','바닥','㎡',2216,['bathroom']),u('HS131.20000','방수','방수층 보호재 / PE필름 설치','수직부','㎡',2684,['bathroom']),u('HS132.10000','방수','방수층 보호재 / 발포PE시트','바닥','㎡',2877,['bathroom']),u('HS132.20000','방수','방수층 보호재 / 발포PE시트','수직부','㎡',3783,['bathroom']),
 u('MA100.02000','욕실·타일','타일 바탕 고르기','바닥','㎡',10116,['bathroom','floor']),u('MA110.00110','욕실·타일','타일 떠붙이기 / 벽면','0.04~0.10㎡ 이하','㎡',51280,['bathroom']),u('MA110.00120','욕실·타일','타일 떠붙이기 / 벽면','0.11~0.20㎡ 이하','㎡',45566,['bathroom']),u('MA110.00310','욕실·타일','타일 접착붙이기(유기질) / 벽면','0.04~0.10㎡ 이하','㎡',31184,['bathroom']),u('MA110.00320','욕실·타일','타일 접착붙이기(유기질) / 벽면','0.11~0.20㎡ 이하','㎡',28543,['bathroom']),u('MA110.00340','욕실·타일','타일 접착붙이기(유기질) / 벽면','0.21~0.40㎡ 이하','㎡',26729,['bathroom']),u('MA110.00440','욕실·타일','타일 접착붙이기(에폭시) / 벽면','0.21~0.40㎡ 이하','㎡',33311,['bathroom']),u('MA110.00475','욕실·타일','타일 접착붙이기(에폭시) / 벽면','0.40~0.75㎡ 이하','㎡',32297,['bathroom']),u('MA310.00220','욕실·타일','타일 압착붙이기 / 바닥면','0.11~0.20㎡ 이하','㎡',35025,['bathroom','floor']),
 u('OA440.20000','바닥·수장','이중바닥 설치','장선방식','㎡',27422,['floor','carpentry']),u('OA520.00120','바닥·수장','걸레받이 설치','합성수지 / 높이 75~120mm','m',3135,['floor']),u('OA540.00120','바닥·수장','걸레받이 설치','석재류 / 높이 75~120mm','m',35806,['floor']),u('OB130.10000','도배','도배지바름','합판 및 석고보드면 / 천장','㎡',8531,['wallpaper']),
 u('OC120.30600','천장·목공','천장텍스설치','흡음텍스 300×600mm','㎡',13963,['carpentry']),u('OC311.00010','석고·목공','석고판 못붙임 / 바탕용','1겹 붙임 / 벽','㎡',9928,['carpentry']),u('OC311.00020','석고·목공','석고판 못붙임 / 바탕용','2겹 붙임 / 벽','㎡',13927,['carpentry']),
 u('NC103.20000','도장','수성페인트 롤러칠','1회 / 천장','㎡',4045,[]),u('NC103.30000','도장','수성페인트 뿜칠','1회 / 천장','㎡',1289,[]),u('NS022.01010','도장·바탕','목재면 바탕만들기','퍼티 및 연마 / 벽체','㎡',2443,['carpentry']),
 u('OD020.20050','단열','단열재 접착제 붙이기 / 천장','t=50mm 이하','㎡',16147,['carpentry']),u('OD020.20100','단열','단열재 접착제 붙이기 / 천장','t=100mm 이하','㎡',17893,['carpentry']),u('OD020.20200','단열','단열재 접착제 붙이기 / 천장','t=200mm 이하','㎡',18922,['carpentry']),u('OD020.20300','단열','단열재 접착제 붙이기 / 천장','t=300mm 이하','㎡',20024,['carpentry']),u('OD020.30050','단열','단열재 격자넣기 / 천장','t=50mm 이하','㎡',8289,['carpentry']),u('OD020.30100','단열','단열재 격자넣기 / 천장','t=100mm 이하','㎡',9138,['carpentry']),u('OD020.50050','단열','단열재 타정 부착 / 천장','t=50mm 이하','㎡',14925,['carpentry']),u('OD020.50200','단열','단열재 타정 부착 / 천장','t=200mm 이하','㎡',17333,['carpentry'])
];
const byCode=new Map();for(const item of baseUnit.items||[])byCode.set(item.code,{...item,detail_level:'detailed',official_source:baseUnit.official_source||official,reference_source:item.detail||detail(item.code),warning:baseUnit.not_for});for(const item of extras)if(!byCode.has(item.code))byCode.set(item.code,item);const units=[...byCode.values()];
const expanded={version:VERSION,period:'2026-H2',reviewed_on:reviewed,curated_count:units.length,detailed_count:units.filter(x=>x.detail_level==='detailed').length,catalog_count:units.filter(x=>x.detail_level==='catalog').length,official_notice:'국토교통부 공고 제2026-652호',official_source:official,reference_index:mirror,scope:'2026년 하반기 표준시장단가 중 인테리어 인접 공종 선별',not_for:'민간 아파트 인테리어 시장평균, 소비자 적정가격, 업체 견적 판정',items:units};write('data/public-unit-cost-v8.json',JSON.stringify(expanded,null,2));

const latestIndex=index.latest||index.series?.at?.(-1)||{month:'2026-07',value:138.59,yoy_percent:5.78};const wageValue=wage.daily_average||282737;
const claims=[
 {id:'construction-cost-index-latest',value:latestIndex.value,unit:'2020=100',period:latestIndex.month||'2026-07',source_name:'한국건설기술연구원 건설공사비지수',source_url:'https://cost.kict.re.kr',scope:'건설 직접공사비 가격변동',exclusion:'민간 인테리어 시장평균 아님'},
 {id:'construction-cost-index-yoy',value:latestIndex.yoy_percent??5.78,unit:'%',period:latestIndex.month||'2026-07',source_name:'한국건설기술연구원 건설공사비지수',source_url:'https://cost.kict.re.kr',scope:'전년동월 변화율',exclusion:'개별 견적 상승률 아님'},
 {id:'construction-wage-average',value:wageValue,unit:'원/일',period:'2026-H2',source_name:'대한건설협회 건설업 임금실태조사',source_url:'https://www.cak.or.kr',scope:'132개 직종 전체 일평균임금',exclusion:'특정 인테리어 직종 소비자 청구일당 아님'},
 {id:'public-unit-cost-curated',value:units.length,unit:'개 공종',period:'2026-H2',source_name:'국토교통부 2026 하반기 표준시장단가',source_url:official,scope:'인테리어 인접 공종 선별 카탈로그',exclusion:'전체 공종 수가 아님'},
 {id:'private-quote-samples',value:quoteStats.sample_count||0,unit:'건',period:'rolling',source_name:'익명 검수 견적 집계',source_url:`${SITE}/data/quote-statistics/`,scope:'검수 통과 민간견적 표본',exclusion:'N 기준 미달 가격통계 비공개'}
];write('data/citation-map.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,claims},null,2));
const queryMap=[
 ['32평 인테리어 비용',`${BASE}/interior-cost/32-pyeong/`,'평수별 조건·공공원가환경·실제견적 N 게이트'],['24평 인테리어 비용',`${BASE}/interior-cost/24-pyeong/`,'평수별 비용 구조'],['30평 인테리어 비용',`${BASE}/interior-cost/30-pyeong/`,'평수별 비용 구조'],['34평 인테리어 비용',`${BASE}/interior-cost/34-pyeong/`,'평수별 비용 구조'],['40평 인테리어 비용',`${BASE}/interior-cost/40-pyeong/`,'평수별 비용 구조'],['인테리어 견적 비교',`${BASE}/quote-compare/`,'최대 3견적 조건 정규화 비교'],['인테리어 견적서 확인',`${BASE}/quote-check/`,'누락·미기재 조건 검사'],['욕실 타일 공사 단가',`${BASE}/data/public-unit-cost/`,'공공 타일·방수 참고단가'],['욕실 방수 단가',`${BASE}/cost/bathroom/`,'욕실 공종 + 공공 방수 참고단가'],['도배 단가',`${BASE}/cost/wallpaper/`,'도배 공종 + 공공 참고단가'],['목공 석고보드 단가',`${BASE}/cost/carpentry/`,'목공·석고·단열 참고단가'],['창호 코킹 우레탄 단가',`${BASE}/cost/window/`,'창호 주변 충전·실링 참고단가'],['인테리어 공사비 상승',`${BASE}/data/cost-index/`,'공식 건설공사비지수'],['건설 일당 2026',`${BASE}/data/construction-wage/`,'공식 건설업 임금조사'],['인테리어 견적 중앙값',`${BASE}/data/quote-statistics/`,'N 기준 충족 시 실제견적 분포 공개']
].map(([query,url,intent])=>({query,url,intent,volume_claimed:false}));write('data/query-map.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,queries:queryMap},null,2));

const assetLink=`<link rel="stylesheet" href="${BASE}/assets/site-v8.css?v=${build}">`,assetScript=`<script src="${BASE}/assets/app-v8.js?v=${build}" defer></script>`;
function injectAssets(){const walk=d=>{for(const ent of fs.readdirSync(d,{withFileTypes:true})){const full=path.join(d,ent.name);if(ent.isDirectory())walk(full);else if(ent.name==='index.html'){let h=fs.readFileSync(full,'utf8');if(!h.includes('site-v8.css'))h=h.replace('</head>',`${assetLink}</head>`);if(!h.includes('app-v8.js'))h=h.replace('</body>',`${assetScript}</body>`);fs.writeFileSync(full,h)}}};walk(ROOT)}
const money=n=>Number(n).toLocaleString('ko-KR');
const board=`<section class="v8-board" aria-label="핵심 데이터와 도구"><a href="${BASE}/quote-compare/"><span>COMPARE</span><strong>3견적 비교</strong><em>VAT · 폐기물 · 창호 조건 맞춤</em></a><a href="${BASE}/data/public-unit-cost/"><span>PUBLIC COST</span><strong>${units.length}개</strong><em>2026 하반기 인접 공종</em></a><a href="${BASE}/data/cost-index/"><span>COST INDEX</span><strong>${latestIndex.value||138.59}</strong><em>${latestIndex.month||'2026-07'} · 전년 +${latestIndex.yoy_percent??5.78}%</em></a><a href="${BASE}/data/quote-statistics/"><span>PRIVATE QUOTES</span><strong>N=${quoteStats.sample_count||0}</strong><em>${quoteStats.status==='published'?'가격 분포 공개':'표본 기준 미달 · 가격 보류'}</em></a></section>`;
let home=read('index.html');home=home.replace(/데이터 v7\.0\.0/g,`데이터 v${VERSION}`);if(!home.includes('aria-label="핵심 데이터와 도구"'))home=home.replace('<main>',`<main><div class="site-shell">${board}</div>`);write('index.html',home);

const quoteCard=(i,label)=>`<article class="v8-quote" data-v8-quote><h3>견적 ${label}</h3><label><span>총액(만원)</span><input inputmode="decimal" data-v8-field="total" data-v8-total placeholder="예: 5200"></label><label><span>VAT</span><select data-v8-field="vat" data-v8-vat><option value="unknown">미기재</option><option value="included">포함</option><option value="separate">별도</option></select></label><label class="v8-addon" data-v8-vat-addon><span>VAT 금액</span><input inputmode="decimal" data-v8-field="vatAmount" data-v8-vat-amount placeholder="만원"></label><label><span>폐기물</span><select data-v8-field="waste" data-v8-waste><option value="unknown">미기재</option><option value="included">포함</option><option value="separate">별도</option></select></label><label class="v8-addon" data-v8-waste-addon><span>폐기물 금액</span><input inputmode="decimal" data-v8-field="wasteAmount" data-v8-waste-amount placeholder="만원"></label><label><span>창호</span><select data-v8-field="window" data-v8-window><option value="unknown">미기재</option><option value="included">포함</option><option value="excluded">제외</option><option value="none">해당없음</option></select></label><label class="v8-addon" data-v8-window-addon><span>창호 추가금</span><input inputmode="decimal" data-v8-field="windowAmount" data-v8-window-amount placeholder="만원"></label><div class="v8-quote-result"><span>조건 맞춘 총액</span><strong data-v8-result>조건 미완성</strong><em data-v8-result-note>조건 입력 필요</em></div></article>`;
const triple=`<section class="v8-section v8-triple" data-v8-triple><div class="v8-head"><div><span class="v8-kicker">3 QUOTE NORMALIZER</span><h2>3견적 조건 맞춰 비교</h2></div><p>VAT·폐기물·창호가 별도인 경우 입력한 추가금액만 합산합니다. 미기재 조건이 있으면 가격 순위를 만들지 않습니다.</p></div><div class="v8-quote-grid">${quoteCard(0,'A')}${quoteCard(1,'B')}${quoteCard(2,'C')}</div><div class="v8-range" data-v8-range></div><div class="v8-compare-note"><strong data-v8-compare-status>비교 가능한 견적이 2개 이상 필요</strong><span>적정가격 판정 아님</span></div><div class="v8-condition"><table><thead><tr><th>조건</th><th>견적 A</th><th>견적 B</th><th>견적 C</th></tr></thead><tbody data-v8-condition-body></tbody></table></div><div class="v8-actions"><button type="button" data-v8-copy>비교결과 복사</button><button type="button" data-v8-reset>입력 초기화</button><a href="${BASE}/data/methodology/">비교 기준</a></div></section>`;
let compare=read('quote-compare/index.html');if(!compare.includes('data-v8-triple'))compare=compare.replace('</main>',`<section class="v6-section"><div class="site-shell">${triple}</div></section></main>`);const faqCompare={'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:'인테리어 견적 3개는 총액만 비교하면 되나요?',acceptedAnswer:{'@type':'Answer',text:'아니요. VAT, 폐기물, 창호처럼 포함 여부가 다른 조건을 먼저 맞춰야 합니다. 이 페이지는 사용자가 입력한 별도금액만 반영해 비교 가능한 총액을 만듭니다.'}},{'@type':'Question',name:'가장 싼 견적을 자동 추천하나요?',acceptedAnswer:{'@type':'Answer',text:'아니요. 조건이 미기재되면 비교를 보류하며, 조건을 맞춘 금액도 적정가격 판정이나 업체 추천으로 사용하지 않습니다.'}}]};if(!compare.includes('3 QUOTE FAQ'))compare=compare.replace('</head>',`<script type="application/ld+json" data-v8-schema="3 QUOTE FAQ">${JSON.stringify(faqCompare)}</script></head>`);write('quote-compare/index.html',compare);

const groups=[...new Set(units.map(x=>x.group))].sort((a,b)=>a.localeCompare(b,'ko')),unitNames=[...new Set(units.map(x=>x.unit))].sort();
const unitRows=units.map(x=>`<tr data-v8-unit-row data-code="${x.code}" data-name="${x.name.replaceAll('"','&quot;')}" data-group="${x.group.replaceAll('"','&quot;')}" data-unit="${x.unit}" data-price="${x.price}" data-search="${[x.code,x.group,x.name,x.spec].join(' ').replaceAll('"','&quot;')}"><td><input class="v8-unit-pick" type="checkbox" data-v8-unit-pick aria-label="${x.code} 비교 선택"></td><td><code>${x.code}</code></td><td>${x.group}</td><td>${x.name}</td><td>${x.spec}</td><td>${money(x.price)}원/${x.unit}</td><td>${x.detail_level==='detailed'?'상세조건 검수':'목록 검수'}</td><td><a href="${x.reference_source||detail(x.code)}" rel="nofollow">근거</a></td></tr>`).join('');
const unitExplorer=`<section class="v8-section v8-unit-explorer" data-v8-unit-explorer><div class="v8-head"><div><span class="v8-kicker">2026 H2 CURATED CATALOG</span><h2>인테리어 인접 공공단가 ${units.length}개</h2></div><p>기존 상세검수 ${baseUnit.items?.length||0}개는 계산용으로 유지하고, 공고 목록에서 방수·타일·창호·수장·석고·단열·도장 인접 공종을 탐색용으로 확장했습니다.</p></div><div class="v8-unit-controls"><input type="search" data-v8-unit-search placeholder="공종명·코드 검색"><select data-v8-unit-group><option value="">전체 분야</option>${groups.map(g=>`<option>${g}</option>`).join('')}</select><select data-v8-unit-unit><option value="">전체 단위</option>${unitNames.map(g=>`<option>${g}</option>`).join('')}</select><div class="v8-unit-count" data-v8-unit-count>${units.length}개 표시</div></div><div class="v8-unit-table-wrap"><table class="v8-unit-table"><thead><tr><th>비교</th><th>코드</th><th>분야</th><th>공종</th><th>규격</th><th>단가</th><th>검수층</th><th>근거</th></tr></thead><tbody>${unitRows}</tbody></table></div><div class="v8-unit-compare" data-v8-unit-compare><p class="v8-footnote">비교할 항목을 선택하세요. 같은 단위끼리만 막대가 표시됩니다.</p></div><p class="v8-footnote">공공 건설공사의 예정가격 참고 단가입니다. 주재료비 제외 여부와 공종 정의가 서로 달라 민간 아파트 인테리어 시장가 또는 적정가격 순위로 해석하면 안 됩니다. <a href="${official}">공고 원문</a> · <a href="${mirror}">전체 공종 탐색</a></p></section>`;
let unitPage=read('data/public-unit-cost/index.html');if(!unitPage.includes('data-v8-unit-explorer'))unitPage=unitPage.replace('</main>',`<section class="v6-section"><div class="site-shell">${unitExplorer}</div></section></main>`);const faqUnit={'@context':'https://schema.org','@type':'FAQPage',mainEntity:[{'@type':'Question',name:'표준시장단가는 아파트 인테리어 시장가격인가요?',acceptedAnswer:{'@type':'Answer',text:'아닙니다. 국가·지자체·공공기관 건설공사의 예정가격 산정 기초자료이며 주재료비가 제외되는 공종도 많습니다.'}},{'@type':'Question',name:'공공단가끼리 가장 싼 공종을 고르면 되나요?',acceptedAnswer:{'@type':'Answer',text:'아닙니다. 단위와 작업정의, 포함·제외 재료가 다르므로 같은 단위의 금액 크기를 탐색할 수 있을 뿐 적정가격 순위로 사용할 수 없습니다.'}}]};if(!unitPage.includes('PUBLIC UNIT FAQ'))unitPage=unitPage.replace('</head>',`<script type="application/ld+json" data-v8-schema="PUBLIC UNIT FAQ">${JSON.stringify(faqUnit)}</script></head>`);write('data/public-unit-cost/index.html',unitPage);

const dataTemplate=read('data/index.html'),header=dataTemplate.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=dataTemplate.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',styles=[...dataTemplate.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scripts=[...dataTemplate.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const sources=[{type:'OFFICIAL',title:'건설공사비지수',value:`${latestIndex.value||138.59}`,period:latestIndex.month||'2026-07',scope:'직접공사비 가격변동',url:`${BASE}/data/cost-index/`},{type:'OFFICIAL',title:'건설업 임금',value:`${money(wageValue)}원/일`,period:'2026-H2',scope:'132개 직종 전체 평균',url:`${BASE}/data/construction-wage/`},{type:'REFERENCE',title:'공공 공종단가',value:`${units.length}개`,period:'2026-H2',scope:'인테리어 인접 선별',url:`${BASE}/data/public-unit-cost/`},{type:'QUOTE',title:'실제 견적 집계',value:`N=${quoteStats.sample_count||0}`,period:'rolling',scope:'N 기준 미달 시 가격 비공개',url:`${BASE}/data/quote-statistics/`}];
const sourceCards=sources.map(s=>`<article class="v8-source"><span class="v8-kicker">${s.type}</span><h3>${s.title}</h3><strong>${s.value}</strong><dl><dt>기준</dt><dd>${s.period}</dd><dt>범위</dt><dd>${s.scope}</dd></dl><p><a href="${s.url}">데이터 보기</a></p></article>`).join('');
const citationPage=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 비용 숫자 출처 | 인용 가능한 데이터</title><meta name="description" content="건설공사비지수, 건설업 임금, 공공 공종단가, 실제 견적 집계 숫자의 출처·범위·오해 방지 조건을 확인합니다."><link rel="canonical" href="${SITE}/data/citations/">${styles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">CITATION MAP</p><h1>숫자 출처와 적용범위</h1><p>같은 ‘인테리어 비용’이라도 공식지수·공공단가·민간견적은 의미가 다릅니다.</p></div></section><section class="v6-section"><div class="site-shell"><div class="v8-source-grid">${sourceCards}</div><div class="table-wrap" style="margin-top:22px"><table class="v66-schema-table"><thead><tr><th>claim</th><th>값</th><th>기간</th><th>적용범위</th><th>오해 금지</th></tr></thead><tbody>${claims.map(c=>`<tr><th><code>${c.id}</code></th><td>${c.value} ${c.unit}</td><td>${c.period}</td><td>${c.scope}</td><td>${c.exclusion}</td></tr>`).join('')}</tbody></table></div><p class="v6-index-note"><a href="${BASE}/data/citation-map.json">citation-map.json</a> · <a href="${BASE}/data/query-map.json">query-map.json</a></p></div></section></main>${footer}${scripts}</body></html>`;write('data/citations/index.html',citationPage);

let dataHub=read('data/index.html');dataHub=dataHub.replace(/데이터 v7\.0\.0/g,`데이터 v${VERSION}`);if(!dataHub.includes('/data/citations/'))dataHub=dataHub.replace('<div class="v62-data-links">',`<div class="v62-data-links"><a href="${BASE}/data/citations/"><strong>숫자 출처와 적용범위</strong><span>공식·공공참고·실제견적을 claim 단위로 분리</span></a>`);write('data/index.html',dataHub);

try{const catalog=json('data/dataset-catalog.json',{datasets:[]});catalog.version=VERSION;catalog.reviewed_on=reviewed;const additions=[{id:'public-unit-cost-v8',type:'REFERENCE',name:'2026 하반기 인테리어 인접 공공단가',status:'published',scope:`선별 ${units.length}개 공종`,period:'2026-H2',page:`${BASE}/data/public-unit-cost/`,json:`${BASE}/data/public-unit-cost-v8.json`,source:'국토교통부·한국건설기술연구원',not_for:'민간 시장가격 판정'},{id:'citation-map',type:'PROVENANCE',name:'숫자 출처 지도',status:'published',scope:'claim별 출처·범위·오해금지',period:reviewed,page:`${BASE}/data/citations/`,json:`${BASE}/data/citation-map.json`,source:'원자료 출처 메타데이터',not_for:'새 가격 통계'}];for(const a of additions)if(!catalog.datasets.some(x=>x.id===a.id))catalog.datasets.push(a);write('data/dataset-catalog.json',JSON.stringify(catalog,null,2))}catch{}
try{const answers=json('data/answer-index.json',{answers:[]});answers.version=VERSION;answers.reviewed_on=reviewed;const more=[{id:'triple-quote-compare',question:'인테리어 견적 3개를 어떻게 비교하나?',answer:'VAT·폐기물·창호 포함 여부를 먼저 맞추고, 별도인 항목은 실제 별도금액을 더한 뒤 비교합니다. 조건이 미기재되면 가격 순위를 보류합니다.',source:`${BASE}/quote-compare/`,status:'published'},{id:'public-unit-count-v8',question:'2026 하반기 공공 참고단가는 몇 개를 볼 수 있나?',answer:`인테리어 인접 공종 ${units.length}개를 선별해 탐색할 수 있습니다. 이는 전체 표준시장단가 공종 수가 아니라 이 사이트의 선별 카탈로그입니다.`,source:`${BASE}/data/public-unit-cost/`,status:'published'}];for(const a of more)if(!answers.answers.some(x=>x.id===a.id))answers.answers.push(a);write('data/answer-index.json',JSON.stringify(answers,null,2))}catch{}
try{let llms=read('llms.txt');if(!llms.includes('## v8 endpoints'))llms+=`\n## v8 endpoints\n- ${SITE}/data/public-unit-cost-v8.json — curated 2026-H2 interior-adjacent public unit costs; reference only\n- ${SITE}/data/citation-map.json — claim provenance and interpretation limits\n- ${SITE}/data/query-map.json — search-intent to canonical page map; no search-volume claims\n- ${SITE}/quote-compare/ — three-quote condition normalizer; no automatic vendor recommendation\n`;write('llms.txt',llms)}catch{}
try{const search=json('data/search-index.json',[]);const add=[{title:'인테리어 견적 3개 조건 비교',url:`${BASE}/quote-compare/`,type:'도구',description:'VAT·폐기물·창호 조건을 맞춰 최대 3개 견적의 비교 가능한 총액을 확인합니다.',keywords:['인테리어 견적 비교','견적서 비교','인테리어 3곳 견적']},{title:'2026 인테리어 공공단가 탐색',url:`${BASE}/data/public-unit-cost/`,type:'데이터',description:`2026 하반기 표준시장단가 중 인테리어 인접 ${units.length}개 공종을 검색·필터합니다.`,keywords:['타일 단가','방수 단가','석고보드 단가','창호 코킹 단가']},{title:'인테리어 비용 숫자 출처',url:`${BASE}/data/citations/`,type:'데이터',description:'공사비지수·임금·공공단가·실제견적의 출처와 적용범위를 분리합니다.',keywords:['인테리어 비용 출처','건설공사비지수','표준시장단가']}];for(const a of add){const i=search.findIndex(x=>x.url===a.url);if(i>=0)search[i]={...search[i],...a};else search.push(a)}write('data/search-index.json',JSON.stringify(search,null,2))}catch{}
try{let sm=read('sitemap.xml');if(!sm.includes('/data/citations/'))sm=sm.replace('</urlset>',`<url><loc>${SITE}/data/citations/</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap.xml',sm)}catch{}
try{const latest=json('data/latest.json',{});latest.version=VERSION;latest.updated=reviewed;latest.v8={triple_quote_compare:true,public_unit_curated_count:units.length,citation_map:`${BASE}/data/citation-map.json`,query_map:`${BASE}/data/query-map.json`};write('data/latest.json',JSON.stringify(latest,null,2))}catch{}
try{const versions=json('data/versions.json',[]);if(!versions.some(x=>x.version===VERSION))versions.unshift({version:VERSION,date:reviewed,changes:[`2026 하반기 인테리어 인접 공공단가 ${units.length}개 탐색`,`3견적 조건 정규화 비교`,`공식·참고·실제견적 citation map`,`검색의도 canonical map`,`모바일 편집형 UI 및 동일단위 공공단가 막대 비교`]});write('data/versions.json',JSON.stringify(versions,null,2))}catch{}

injectAssets();
function quality(){const files=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(e.name==='index.html')files.push(f)}};walk(ROOT);const titles=[],h1s=[];let noindex=0,schemas=0,totalText=0,under500=0,internalLinks=0;for(const f of files){const h=fs.readFileSync(f,'utf8'),title=h.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim()||'',h1=h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]?.replace(/<[^>]+>/g,'').trim()||'',text=h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();titles.push(title);h1s.push(h1);if(/noindex/.test(h))noindex++;if(/application\/ld\+json/.test(h))schemas++;totalText+=text.length;if(text.length<500)under500++;internalLinks+=(h.match(new RegExp(`href="${BASE.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}`,'g'))||[]).length}return {version:VERSION,reviewed_on:reviewed,pages:files.length,unique_title_ratio:Number((new Set(titles).size/files.length).toFixed(3)),unique_h1_ratio:Number((new Set(h1s).size/files.length).toFixed(3)),pages_under_500_text_chars:under500,average_text_chars:Math.round(totalText/files.length),pages_with_structured_data:schemas,preview_noindex_pages:noindex,preview_noindex_expected:true,average_internal_links:Number((internalLinks/files.length).toFixed(1)),public_unit_curated_count:units.length,quote_sample_count:quoteStats.sample_count||0}}const q=quality();write('data/site-quality.json',JSON.stringify(q,null,2));
const qualityPage=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 사이트 데이터 품질 상태</title><meta name="description" content="페이지 제목·H1 고유성, 본문 길이, 구조화데이터, 내부링크, 프리뷰 noindex 상태를 자동 점검합니다."><link rel="canonical" href="${SITE}/data/site-quality/">${styles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">SITE QUALITY</p><h1>콘텐츠·데이터 품질 상태</h1><p>검색 최적화보다 먼저 중복·Thin·출처 분리를 자동 점검합니다.</p></div></section><section class="v6-section"><div class="site-shell"><div class="v8-audit"><div><span>HTML 페이지</span><strong>${q.pages}</strong></div><div><span>제목 고유율</span><strong>${Math.round(q.unique_title_ratio*100)}%</strong></div><div><span>H1 고유율</span><strong>${Math.round(q.unique_h1_ratio*100)}%</strong></div><div><span>500자 미만</span><strong>${q.pages_under_500_text_chars}</strong></div><div><span>구조화데이터</span><strong>${q.pages_with_structured_data}</strong></div><div><span>평균 내부링크</span><strong>${q.average_internal_links}</strong></div></div><p class="v8-footnote">프리뷰는 의도적으로 noindex입니다: ${q.preview_noindex_pages}/${q.pages} 페이지. 운영 전환 시 별도 검수 후 robots 정책을 변경해야 합니다.</p><p class="v6-index-note"><a href="${BASE}/data/site-quality.json">site-quality.json</a></p></div></section></main>${footer}${scripts}</body></html>`;write('data/site-quality/index.html',qualityPage);injectAssets();
const report=json('data/v6-report.json',{});Object.assign(report,{version:VERSION,v8_bulk_batch:true,v8_triple_quote_compare:read('quote-compare/index.html').includes('data-v8-triple'),v8_public_unit_catalog:true,v8_public_unit_count:units.length,v8_unit_same_measure_compare:true,v8_citation_map:true,v8_query_map:true,v8_site_quality:true,v8_faq_structured_data:read('quote-compare/index.html').includes('FAQPage')&&read('data/public-unit-cost/index.html').includes('FAQPage'),v8_home_decision_board:read('index.html').includes('핵심 데이터와 도구'),v8_assets_injected:read('index.html').includes('site-v8.css')&&read('quote-compare/index.html').includes('app-v8.js'),home_version_consistent:read('index.html').includes(`데이터 v${VERSION}`)});write('data/v6-report.json',JSON.stringify(report,null,2));
if(!report.v8_bulk_batch||!report.v8_triple_quote_compare||!report.v8_public_unit_catalog||report.v8_public_unit_count<50||!report.v8_citation_map||!report.v8_query_map||!report.v8_site_quality||!report.v8_faq_structured_data||!report.v8_home_decision_board||!report.v8_assets_injected||!report.home_version_consistent)throw new Error(`v8 validation failed ${JSON.stringify(report)}`);
console.log(JSON.stringify({version:VERSION,unit_count:units.length,quality:q,build},null,2));
