import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='10.0.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8');
const write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)};
const json=(r,fallback={})=>{try{return JSON.parse(read(r))}catch{return fallback}};
const reviewed=json('data/v5-report.json',{}).reviewed_on||new Date().toISOString().slice(0,10);
const quote=json('data/quote-statistics.json',{sample_count:0,status:'withheld',segment_threshold:20,segments:{}}),index=json('data/construction-cost-index.json',{series:[]}),wage=json('data/construction-wage-2026-h2.json',{}),unit=json('data/public-unit-cost-v8.json',{items:[]}),groupData=json('data/public-unit-groups.json',{groups:[]});
const css=fs.readFileSync(path.join(CORE,'site-v10.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v10.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v10.css',css);write('assets/app-v10.js',js);
const fmt=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:1});
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const strip=s=>String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim();
const regions=[
 ['seoul','서울'],['busan','부산'],['daegu','대구'],['incheon','인천'],['gwangju','광주'],['daejeon','대전'],['ulsan','울산'],['sejong','세종'],['gyeonggi','경기'],['gangwon','강원'],['chungbuk','충북'],['chungnam','충남'],['jeonbuk','전북'],['jeonnam','전남'],['gyeongbuk','경북'],['gyeongnam','경남'],['jeju','제주']
].map(([slug,name])=>({slug,name}));
const pyeongs=[24,30,32,34,40],segmentN=quote.segment_threshold||20;
const cell=(dim,key)=>(quote.segments?.[dim]||[]).find(x=>x.key===key)||null;
const regionInfo=r=>cell('region_level1',r.name);
const routeInfo=(r,p)=>cell('region_pyeong_rounded',`${r.name} · ${p}평`);
const priceText=c=>c?.status==='published'&&c.distribution?.total_amount_manwon?`P25 ${fmt(c.distribution.total_amount_manwon.p25)}만원 · 중앙값 ${fmt(c.distribution.total_amount_manwon.median)}만원 · P75 ${fmt(c.distribution.total_amount_manwon.p75)}만원`:`가격통계 보류`;

// Extend the aggregate contract so future private imports publish region × pyeong only through the same N gate.
try{const c=json('data/quote-aggregate-contract.json',{});c.extension_version=VERSION;c.dimensions=[...new Set([...(c.dimensions||[]),'region_pyeong_rounded','region_pyeong_band'])];write('data/quote-aggregate-contract.json',JSON.stringify(c,null,2))}catch{}

const routes=[];
for(const r of regions)for(const p of pyeongs){const c=routeInfo(r,p),published=c?.status==='published';routes.push({region:r.name,region_slug:r.slug,pyeong:p,key:`${r.name} · ${p}평`,sample_count:c?.n||0,status:published?'published':'withheld',indexable:published,price_distribution:published?c.distribution?.total_amount_manwon||null:null,region_url:`${BASE}/region/${r.slug}/`,pyeong_url:`${BASE}/interior-cost/${p}-pyeong/`,combination_url:published?`${BASE}/region/${r.slug}/${p}-pyeong/`:null,reason:published?`N>=${segmentN}`:`지역×평수 셀 N=${c?.n||0}, 공개 기준 N>=${segmentN} 미달`})}
write('data/region-pyeong-map.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,segment_threshold:segmentN,regions:regions.length,pyeongs,route_count:routes.length,production_rule:'지역×평수 가격 페이지는 해당 셀 N 기준 충족 시에만 생성·색인 후보가 된다.',routes},null,2));

const template=read('data/index.html'),header=template.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=template.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',baseStyles=[...template.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),baseScripts=[...template.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const regionFaq=r=>[
 {q:`${r.name} 인테리어 견적 평균을 지금 볼 수 있나요?`,a:`현재 ${r.name} 검수 표본은 N=${regionInfo(r)?.n||0}입니다. 사이트는 지역 세그먼트 N≥${segmentN}에서만 가격분포를 공개하므로 기준 미달이면 평균·중앙값을 만들지 않습니다.`},
 {q:`${r.name} 32평 견적은 전국 32평 통계와 같은가요?`,a:'같은 값으로 취급하지 않습니다. 지역×평수 셀은 별도 집계하며 해당 셀 자체가 N 기준을 통과해야 가격분포를 공개합니다.'},
 {q:'지역 견적을 비교할 때 무엇을 먼저 맞추나요?',a:'지역보다 먼저 VAT, 폐기물, 창호, 욕실 수, 공사범위처럼 견적 포함조건을 맞춥니다. 지역명만으로 가격을 보정하지 않습니다.'}
];
function regionPage(r){
 const rc=regionInfo(r),rr=routes.filter(x=>x.region_slug===r.slug),rows=rr.map(x=>`<tr><th>${x.pyeong}평</th><td>N=${x.sample_count}</td><td class="${x.status==='published'?'v10-status-published':'v10-status-withheld'}">${x.status==='published'?priceText(routeInfo(r,x.pyeong)):`N<${segmentN} · 가격통계 보류`}</td><td><a href="${x.pyeong_url}">${x.pyeong}평 조건 보기</a></td></tr>`).join(''),faq=regionFaq(r);
 const schema={'@context':'https://schema.org','@graph':[{'@type':'CollectionPage',name:`${r.name} 인테리어 견적 데이터`,url:`${SITE}/region/${r.slug}/`,description:`${r.name} 익명 견적의 공개 상태와 24·30·32·34·40평 데이터 슬롯을 확인합니다.`,dateModified:reviewed},{'@type':'FAQPage',mainEntity:faq.map(x=>({'@type':'Question',name:x.q,acceptedAnswer:{'@type':'Answer',text:x.a}}))}]};
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>${r.name} 인테리어 견적 데이터 | 24·30·32·34·40평 공개 상태</title><meta name="description" content="${r.name} 인테리어 실제 견적 표본 상태와 24평·30평·32평·34평·40평 지역×평수 통계 공개 여부를 확인합니다. 표본 기준 미달 가격은 만들지 않습니다."><link rel="canonical" href="${SITE}/region/${r.slug}/">${baseStyles}<script type="application/ld+json">${JSON.stringify(schema)}</script></head><body><header>${header.replace(/^<header[^>]*>|<\/header>$/g,'')}</header><main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">REGION QUOTE STATUS</p><h1>${r.name} 인테리어 견적 데이터</h1><p>지역명으로 가격을 추정하지 않고 실제 익명 견적 표본이 쌓인 경우에만 지역 통계를 엽니다.</p></div></section><section class="v10-section"><div class="site-shell"><div class="v10-section-head"><div><h2>${r.name} 공개 상태</h2><p>QUOTE · 시도 단위만 사용 · 상세주소·업체명 미수집</p></div></div><div class="v10-launch-audit"><div><span>지역 표본</span><strong>N=${rc?.n||0}</strong></div><div><span>지역 가격통계</span><strong>${rc?.status==='published'?'공개':'보류'}</strong></div><div><span>세그먼트 기준</span><strong>N≥${segmentN}</strong></div><div><span>평수 슬롯</span><strong>${pyeongs.length}개</strong></div><div><span>상세주소</span><strong>미수집</strong></div><div><span>민간 평균 추정</span><strong>안 함</strong></div></div><p>이 페이지의 역할은 ${r.name} 가격을 임의로 만드는 것이 아니라 데이터가 실제로 쌓였는지 보여 주는 것입니다. 지역 통계와 24·30·32·34·40평 조합 통계는 각각 별도 셀로 집계합니다. 전국 또는 다른 지역의 값을 ${r.name}에 대입하지 않으며, 표본이 적은 상태에서는 건수만 공개하고 가격분포를 숨깁니다.</p></div></section><section class="v10-section"><div class="site-shell"><div class="v10-section-head"><div><h2>${r.name} × 평수</h2><p>조합별 N 게이트 · 현재 셀 자체가 기준을 넘어야 가격 표시</p></div></div><div class="table-wrap"><table class="v10-route-table"><thead><tr><th>평수</th><th>표본</th><th>가격 상태</th><th>평수 페이지</th></tr></thead><tbody>${rows}</tbody></table></div><p>평수 페이지는 욕실 수, 창호 포함 여부, 철거·폐기물, VAT 등 견적 조건을 정리하는 용도입니다. 지역×평수 통계가 보류된 상태에서 평수 페이지의 공식 공사비지수나 공공단가를 ${r.name} 시장 평균으로 해석하지 않습니다.</p></div></section><section class="v10-section"><div class="site-shell"><h2>비교 순서</h2><p>${r.name} 견적도 먼저 A/B/C 견적의 공종명과 포함조건을 같은 기준으로 맞춥니다. 견적서 문장을 복사할 수 있다면 붙여넣기 분류 도구로 철거·방수·욕실·주방·도배·바닥·목공·전기·창호 항목을 정리한 뒤 비교표로 넘길 수 있습니다. 공공 표준시장단가는 시공 범위를 확인하는 참고자료일 뿐 업체 견적의 적정가격을 판정하는 기준으로 사용하지 않습니다.</p><nav class="v10-actions"><a href="${BASE}/quote-paste/">견적 항목 붙여넣기</a><a href="${BASE}/quote-compare/">A/B/C 비교</a><a href="${BASE}/data/public-unit-cost/topics/">공종별 공공단가</a><a href="${BASE}/data/quote-statistics/">실제견적 집계 기준</a></nav></div></section><section class="v10-section"><div class="site-shell"><h2>질문</h2>${faq.map(x=>`<details><summary>${x.q}</summary><p>${x.a}</p></details>`).join('')}</div></section></main>${footer}${baseScripts}</body></html>`;
}
for(const r of regions)write(`region/${r.slug}/index.html`,regionPage(r));

// Generate combination pages only when the exact region × rounded-pyeong cell passes the publication gate.
for(const x of routes.filter(x=>x.indexable)){
 const d=x.price_distribution||{};write(`region/${x.region_slug}/${x.pyeong}-pyeong/index.html`,`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${x.region} ${x.pyeong}평 인테리어 실제 견적 통계</title><meta name="description" content="${x.region} ${x.pyeong}평 익명 검수 견적 N=${x.sample_count}의 P25·중앙값·P75를 공개 기준 충족 시 제공합니다."><link rel="canonical" href="${SITE}/region/${x.region_slug}/${x.pyeong}-pyeong/">${baseStyles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><h1>${x.region} ${x.pyeong}평 실제 견적 통계</h1><p>QUOTE · 지역×반올림 공급평수 · N=${x.sample_count}</p></div></section><section class="v10-section"><div class="site-shell"><div class="v10-launch-audit"><div><span>P25</span><strong>${fmt(d.p25)}만원</strong></div><div><span>중앙값</span><strong>${fmt(d.median)}만원</strong></div><div><span>P75</span><strong>${fmt(d.p75)}만원</strong></div></div><p>표본 기준을 통과한 익명 견적 분포이며 평균값은 공개하지 않습니다. 동일 지역·평수라도 공사범위, 욕실 수, 창호, VAT와 폐기물 조건이 다르면 직접 비교할 수 없습니다.</p></div></section></main>${footer}${baseScripts}</body></html>`)}

const regionCards=regions.map(r=>{const c=regionInfo(r);return `<a class="v10-region" data-v10-region-card data-search="${r.name} ${r.slug}" href="${BASE}/region/${r.slug}/"><span>REGION · N=${c?.n||0}</span><strong>${r.name}</strong><p>${c?.status==='published'?priceText(c):`지역 가격통계 N<${segmentN} 보류`}</p><div class="v10-region-status"><b>24·30·32·34·40평</b><b>시도 단위</b></div></a>`}).join('');
write('region/index.html',`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>지역별 인테리어 견적 데이터 | 17개 시도 표본 상태</title><meta name="description" content="서울·부산·대구·인천·경기 등 17개 시도의 익명 인테리어 견적 표본 상태와 지역×평수 통계 공개 여부를 확인합니다."><link rel="canonical" href="${SITE}/region/">${baseStyles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">REGION DATA</p><h1>지역별 인테리어 견적 데이터</h1><p>17개 시도 · 가격은 각 지역 또는 지역×평수 셀이 N 기준을 넘을 때만 공개</p></div></section><section class="v10-section"><div class="site-shell" data-v10-region-index><div class="v10-section-head"><div><h2>17개 시도</h2><p>상세주소를 수집하지 않고 시도 단위만 사용합니다.</p></div><div class="v10-answer-tools"><input data-v10-region-q placeholder="지역 검색"></div></div><div class="v10-region-grid">${regionCards}</div><p>현재 지역별 표본이 충분하지 않으면 가격 대신 N만 보여 줍니다. 전국 통계나 공공단가를 특정 지역 민간시장 가격으로 환산하지 않습니다. 지역×평수 조합 85개는 기계가독 라우팅 맵으로 준비되어 있으며, 각 셀 N≥${segmentN}일 때만 조합 가격 페이지를 생성할 수 있습니다.</p><p class="v6-index-note"><a href="${BASE}/data/region-pyeong-map.json">region-pyeong-map.json</a> · <a href="${BASE}/data/quote-statistics/">표본 기준</a></p></div></section></main>${footer}${baseScripts}</body></html>`);

// Quote text paste classifier.
write('quote-paste/index.html',`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 견적 항목 붙여넣기 | 텍스트 자동 분류</title><meta name="description" content="견적서에서 복사한 텍스트를 철거·폐기물·방수·욕실·주방·도배·바닥·목공·전기·창호 등으로 브라우저에서 분류합니다."><link rel="canonical" href="${SITE}/quote-paste/">${baseStyles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">QUOTE TEXT CLASSIFIER</p><h1>견적 항목 붙여넣기</h1><p>텍스트만 로컬에서 분류 · OCR 없음 · 서버 전송 없음 · 애매한 줄은 검토 필요로 유지</p></div></section><section class="v10-section"><div class="site-shell" data-v10-paste-tool><div class="v10-paste-wrap"><div class="v10-paste-panel"><label for="v10-paste"><strong>견적서 텍스트</strong></label><textarea id="v10-paste" data-v10-paste placeholder="예: 욕실 2개 860만원&#10;도배 310만원&#10;샷시 1450만원"></textarea><div class="v10-actions"><button type="button" data-v10-run>분류</button><button type="button" data-v10-example>예시</button><button type="button" data-v10-send-a disabled>A업체 비교표로 보내기</button><button type="button" data-v10-export disabled>JSON 저장</button></div><p>숫자 뒤에 단위가 없으면 만원으로 해석합니다. 자동 분류는 계약서 해석이 아니라 입력 보조 기능이므로 원문과 반드시 대조하세요.</p></div><aside class="v10-parser-summary"><div><span>입력 줄</span><strong data-v10-lines>0줄</strong></div><div><span>공종 매칭</span><strong data-v10-matched>0줄</strong></div><div><span>검토 필요</span><strong data-v10-review>0줄</strong></div><div><span>매칭 금액 합계</span><strong data-v10-sum>0만원</strong></div></aside></div><div class="table-wrap"><table class="v10-parser-table"><thead><tr><th>#</th><th>원문</th><th>분류</th><th>금액</th><th>상태</th></tr></thead><tbody data-v10-paste-body><tr><td colspan="5">분석 전</td></tr></tbody></table></div></div></section><section class="v10-section"><div class="site-shell"><h2>분류 원칙</h2><p>철거·폐기물·방수·욕실·주방·도배·바닥·목공·전기·창호·관리비·VAT 키워드를 사용합니다. 한 줄에서 여러 공종 키워드가 겹치거나 어느 공종에도 맞지 않으면 자동 확정하지 않습니다. 개인정보, 업체명, 상세주소를 통계 데이터로 저장하지 않으며 이 도구의 붙여넣기 내용은 브라우저 안에서만 처리합니다.</p></div></section></main>${footer}${baseScripts}</body></html>`);

// Scope combination tool: coverage only, no invalid arithmetic across incompatible units.
const comboItems=(groupData.groups||[]).map(g=>`<div class="v10-combo-item"><label><input type="checkbox" data-v10-combo data-label="${esc(g.name)}" data-note="${g.item_count}개 참고항목 · ${(g.units||[]).join(' / ')}"><span>${esc(g.name)}</span></label><p>${g.item_count}개 항목 · <a href="${g.url}">공공 참고범위</a></p></div>`).join('');
write('cost-combination/index.html',`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 공종 조합 점검 | 견적 범위 체크</title><meta name="description" content="방수·타일·창호·도배·목공·바닥·도장·단열·바탕 공종을 조합해 견적 범위 누락을 확인합니다. 서로 다른 공공단가를 억지로 합산하지 않습니다."><link rel="canonical" href="${SITE}/cost-combination/">${baseStyles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">SCOPE COMBINATION</p><h1>공종 조합 점검</h1><p>포함할 공종군을 선택해 견적 범위를 정리 · 단가 합산 없음</p></div></section><section class="v10-section"><div class="site-shell" data-v10-combo-tool><div class="v10-combo-grid">${comboItems}</div><div class="v10-combo-result"><strong data-v10-combo-count>0개 공종군 선택</strong><div data-v10-combo-output></div></div><p>표준시장단가는 규격·단위·재료 포함조건이 서로 다르므로 공종군 선택값을 총공사비로 합산하지 않습니다. 실제 업체 견적은 A/B/C 비교에서 같은 포함조건을 맞춘 뒤 확인합니다.</p></div></section></main>${footer}${baseScripts}</body></html>`);

// Construction cost-index period calculator.
const series=index.series||[],options=series.map(x=>`<option value="${x.month}">${x.month} · ${x.value}</option>`).join('');
try{let h=read('data/cost-index/index.html');if(!h.includes('data-v10-index-tool')){const tool=`<section class="v10-section"><div class="site-shell" data-v10-index-tool><div class="v10-section-head"><div><h2>기간 변화 계산</h2><p>OFFICIAL INDEX · 두 달의 지수 변화만 계산</p></div></div><div class="v10-index-controls"><label>시작월<select data-v10-index-start>${options}</select></label><label>종료월<select data-v10-index-end>${options}</select></label><div class="v10-index-result"><span>변화율</span><strong data-v10-index-result>—</strong></div></div><p data-v10-index-note>월을 선택하세요.</p><script type="application/json" data-v10-index-series>${JSON.stringify(series)}</script><p>이 계산은 건설 직접공사비 지수의 기간 변화입니다. 특정 아파트 인테리어 견적이나 업체 가격의 인상률로 환산하지 않습니다.</p></div></section>`;h=h.replace('</main>',`${tool}</main>`);write('data/cost-index/index.html',h)}}catch{}

// AEO answer index: official, tools, methods, public cost, pyeong, region and region×32 status.
const answers=[],add=(category,q,a,source,status='published')=>answers.push({id:`a${String(answers.length+1).padStart(3,'0')}`,category,question:q,answer:a,source,status});
const latest=index.series?.at?.(-1)||{month:index.latest_month||'2026-07',value:index.latest_value||138.59};
add('공식데이터','현재 건설공사비지수는?',`${latest.month} 건설공사비지수는 ${latest.value}입니다. 2020=100 기준이며 민간 인테리어 시장평균이 아닙니다.`,`${BASE}/data/cost-index/`);
add('공식데이터','건설공사비지수 기간 변화는 어떻게 계산하나요?','공사비지수 페이지의 기간 변화 계산에서 시작월과 종료월을 선택합니다. 결과는 지수 변화율이며 개별 견적 상승률이 아닙니다.',`${BASE}/data/cost-index/`);
add('공식데이터','2026 하반기 건설업 일평균임금은?',`132개 직종 일평균임금은 ${Number(wage.daily_average||282737).toLocaleString('ko-KR')}원입니다. 특정 인테리어 직종 소비자 청구 일당이 아닙니다.`,`${BASE}/data/construction-wage/`);
add('공식데이터','공공 표준시장단가는 민간 인테리어 시세인가요?','아닙니다. 공공 건설 예정가격 참고자료이며 주재료 제외 등 조건이 있어 민간 시장가나 적정가격 판정으로 사용하지 않습니다.',`${BASE}/data/public-unit-cost/`);
add('공식데이터','실제 민간 견적 표본은 몇 건인가?',`현재 검수 통과 표본은 ${quote.sample_count||0}건입니다. 전체 분포 N≥${quote.publication_threshold||30}, 세그먼트 N≥${segmentN}에서만 가격통계를 공개합니다.`,`${BASE}/data/quote-statistics/`,quote.status||'withheld');
add('공식데이터','실제 견적 원본 행을 공개하나요?','아니요. 원본 견적 행은 공개 저장하지 않고 표본 기준을 통과한 집계값만 공개합니다.',`${BASE}/data/quote-pipeline/`);
const toolQ=[
 ['견적도구','견적서 텍스트를 자동으로 공종별 분류할 수 있나요?','견적 항목 붙여넣기에서 복사한 텍스트를 철거·방수·욕실·주방·도배·바닥·목공·전기·창호 등으로 로컬 분류합니다.',`${BASE}/quote-paste/`],
 ['견적도구','견적서 이미지를 OCR로 읽나요?','아니요. 현재 붙여넣기 도구는 텍스트만 처리하며 OCR을 사용하지 않습니다.',`${BASE}/quote-paste/`],
 ['견적도구','분류한 견적을 A/B/C 비교로 넘길 수 있나요?','공종 매칭 금액을 A업체 입력칸으로 넘길 수 있습니다. 자동 분류 결과는 원문과 다시 대조해야 합니다.',`${BASE}/quote-paste/`],
 ['견적도구','인테리어 견적 3개는 총액만 비교하면 되나요?','아니요. VAT·폐기물·창호 등 포함조건을 먼저 맞춘 뒤 비교해야 합니다.',`${BASE}/quote-compare/`],
 ['견적도구','가장 싼 업체를 자동 추천하나요?','아니요. 조건 미기재 시 비교를 보류하며 적정가격이나 업체 추천을 자동 판정하지 않습니다.',`${BASE}/quote-compare/`],
 ['견적도구','공종 조합 금액을 자동 합산하나요?','아니요. 서로 다른 단위와 규격의 공공단가를 합산하지 않고 견적 범위 누락을 점검하는 용도로만 사용합니다.',`${BASE}/cost-combination/`],
 ['견적도구','공공단가와 내 견적 단가 차이를 볼 수 있나요?','공공단가 계산기와 단가 역산 기능에서 동일 공정·제외조건을 확인한 뒤 산술 차이를 볼 수 있습니다. 적정가격 판정은 아닙니다.',`${BASE}/calculator/`],
 ['견적도구','견적에 VAT가 미기재면 어떻게 하나요?','포함 또는 별도 여부를 확인하기 전까지 조건 맞춘 총액 비교를 보류합니다.',`${BASE}/quote-compare/`],
 ['견적도구','폐기물 비용이 별도면 어떻게 비교하나요?','별도 폐기물 금액을 확인해 비교 기준에 반영하거나 모든 견적에서 같은 방식으로 분리합니다.',`${BASE}/quote-compare/`],
 ['견적도구','창호 제외 견적은 어떻게 비교하나요?','다른 견적도 창호를 제외하거나 별도 항목으로 분리해 같은 범위를 맞춥니다.',`${BASE}/quote-compare/`],
 ['견적도구','견적 항목 이름이 업체마다 다르면 어떻게 하나요?','표준 공종으로 재분류한 뒤 철거·방수·욕실·주방·도배·바닥·목공·전기·창호 등 같은 범주끼리 비교합니다.',`${BASE}/quote-check/`],
 ['견적도구','브라우저에 붙여넣은 견적 내용이 서버로 전송되나요?','견적 붙여넣기와 로컬 탐색기는 브라우저 안에서 처리하며 서버 업로드 기능을 사용하지 않습니다.',`${BASE}/quote-paste/`]
];for(const x of toolQ)add(...x);
const methodQ=[
 ['방법론','왜 평균값을 공개하지 않나요?','소수의 큰 견적에 결과가 끌리는 영향을 줄이고 분포 폭을 함께 보여주기 위해 중앙값·P25·P75를 사용합니다.','/data/quote-pipeline/'],
 ['방법론','지역 통계는 몇 건부터 공개하나요?',`각 지역 셀 N≥${segmentN}에서만 가격분포를 공개합니다.`,'/region/'],
 ['방법론','지역×평수 통계도 같은 N 기준을 쓰나요?',`네. 지역×반올림 공급평수 셀도 독립적으로 N≥${segmentN}을 충족해야 가격을 표시합니다.`,'/region/'],
 ['방법론','상세주소를 수집하나요?','아니요. 지역 필드는 17개 시도 약칭만 허용하고 상세주소는 스키마에서 받지 않습니다.','/data/quote-pipeline/'],
 ['방법론','업체명을 수집하나요?','아니요. 익명 견적 스키마는 업체명과 개인 식별정보 열을 허용하지 않습니다.','/data/quote-pipeline/'],
 ['방법론','공급평당 견적은 어떻게 계산하나요?','견적 총액을 공급평수로 나눈 계산값이며 표본 기준을 통과한 집계에서만 분포를 공개합니다.','/data/quote-statistics/'],
 ['방법론','공공단가 최저값을 싼 시공 기준으로 볼 수 있나요?','아니요. 같은 단위라도 규격과 공법, 재료 포함조건이 달라 최저·최고 순위를 적정가격으로 해석하지 않습니다.','/data/public-unit-cost/'],
 ['방법론','공사비지수 138.59는 38.59% 비싸졌다는 뜻인가요?','2020년 평균을 100으로 둔 지수 수준을 뜻합니다. 개별 인테리어 견적이 정확히 38.59% 상승했다는 뜻은 아닙니다.','/data/cost-index/'],
 ['방법론','공식 데이터와 민간 견적을 합쳐 평균을 만드나요?','아니요. OFFICIAL, REFERENCE, QUOTE, CALCULATED를 분리하고 서로 다른 데이터 종류를 하나의 시장평균으로 합치지 않습니다.','/data/catalog/'],
 ['방법론','표본이 N 기준에 못 미치면 어떻게 표시하나요?','건수와 보류 상태만 표시하고 P25·중앙값·P75 가격값은 숨깁니다.','/data/quote-statistics/'],
 ['방법론','지역×평수 조합 페이지는 언제 만들어지나요?',`해당 지역×평수 셀이 N≥${segmentN}을 통과했을 때만 가격 페이지 생성 후보가 됩니다.`,'/region/'],
 ['방법론','검색량 수치를 임의 추정해 쓰나요?','아니요. 검색 의도 맵은 질의와 canonical 역할만 관리하고 검색량 추정값을 사실처럼 표시하지 않습니다.','/data/']
];for(const [c,q,a,s] of methodQ)add(c,q,a,`${BASE}${s}`);
for(const g of groupData.groups||[])add('공공단가',`${g.name}를 민간 인테리어 시세로 봐도 되나요?`,`아닙니다. ${g.item_count}개 관련 공공 표준시장단가를 묶은 참고 페이지이며 규격·단위·재료조건을 확인해야 합니다.`,g.url);
for(const p of pyeongs){const c=cell('supply_pyeong_rounded',`${p}평`);add('평수',`${p}평 인테리어 실제 견적 중앙값은?`,c?.status==='published'?`${p}평 검수 표본 N=${c.n}의 중앙값은 ${fmt(c.distribution.total_amount_manwon.median)}만원입니다. P25·P75와 포함조건을 함께 확인하세요.`:`현재 ${p}평 표본 N=${c?.n||0}으로 세그먼트 기준 N≥${segmentN} 미달이라 가격통계를 공개하지 않습니다.`,`${BASE}/interior-cost/${p}-pyeong/`,c?.status||'withheld')}
for(const r of regions){const c=regionInfo(r);add('지역',`${r.name} 인테리어 실제 견적 통계는?`,c?.status==='published'?`${r.name} 검수 표본 N=${c.n}이 공개 기준을 충족했습니다. 상세 분포는 지역 페이지에서 확인합니다.`:`현재 ${r.name} 검수 표본 N=${c?.n||0}으로 지역 가격통계를 보류합니다. 다른 지역 값을 ${r.name} 평균으로 대입하지 않습니다.`,`${BASE}/region/${r.slug}/`,c?.status||'withheld')}
for(const r of regions){const c=routeInfo(r,32);add('지역×평수',`${r.name} 32평 인테리어 실제 견적 중앙값은?`,c?.status==='published'?`${r.name} 32평 검수 표본 N=${c.n}의 중앙값은 ${fmt(c.distribution.total_amount_manwon.median)}만원입니다.`:`현재 ${r.name} 32평 셀 N=${c?.n||0}으로 공개 기준 N≥${segmentN} 미달이라 가격을 표시하지 않습니다.`,`${BASE}/region/${r.slug}/`,c?.status||'withheld')}
write('data/answer-index-v10.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,count:answers.length,answers},null,2));write('data/answer-index.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,answers},null,2));
const cats=[...new Set(answers.map(x=>x.category))],answerCards=answers.map(x=>`<article class="v10-answer-card" data-v10-answer-card data-category="${esc(x.category)}" data-search="${esc(`${x.question} ${x.answer} ${x.category}`)}"><span>${esc(x.category)} · ${esc(x.status)}</span><strong>${esc(x.question)}</strong><p>${esc(x.answer)}</p><em><a href="${x.source}">근거 페이지</a></em></article>`).join('');
write('data/answers-v10/index.html',`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 비용 질문 답변 허브 | 견적·평수·지역·공공단가</title><meta name="description" content="인테리어 견적 비교, 24·30·32·34·40평, 17개 지역, 공공단가와 공식지표 질문을 근거 페이지와 함께 검색합니다."><link rel="canonical" href="${SITE}/data/answers-v10/">${baseStyles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">ANSWER HUB</p><h1>인테리어 비용 질문 답변 허브</h1><p>${answers.length}개 질문 · 근거 URL · 공개/보류 상태 포함</p></div></section><section class="v10-section"><div class="site-shell" data-v10-answer-hub><div class="v10-answer-tools"><input data-v10-answer-q placeholder="질문 검색"><select data-v10-answer-category><option value="">전체 분류</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div class="v10-answer-grid">${answerCards}</div><p>답변은 사이트 데이터의 현재 공개 상태를 반영합니다. 실제 견적 N 기준을 충족하지 않은 지역·평수 질문에는 가격을 만들어 답하지 않습니다.</p><p class="v6-index-note"><a href="${BASE}/data/answer-index-v10.json">answer-index-v10.json</a></p></div></section></main>${footer}${baseScripts}</body></html>`);

// Search intent routing, including 85 region × pyeong queries without pretending search volume.
const qm=json('data/query-map.json',{queries:[]});qm.version=VERSION;qm.reviewed_on=reviewed;qm.queries=qm.queries||[];const existing=new Set(qm.queries.map(x=>x.query));
const addQuery=x=>{if(!existing.has(x.query)){qm.queries.push({...x,volume_claimed:false});existing.add(x.query)}};
for(const x of routes)addQuery({query:`${x.region} ${x.pyeong}평 인테리어 비용`,intent:'region-pyeong',canonical:x.indexable?x.combination_url:x.region_url,secondary:x.pyeong_url,publication:x.indexable?'published-cell':'withheld-until-N-gate'});
[['인테리어 견적서 항목 분류',`${BASE}/quote-paste/`],['인테리어 견적 붙여넣기',`${BASE}/quote-paste/`],['인테리어 공종 조합',`${BASE}/cost-combination/`],['건설공사비지수 기간 변화',`${BASE}/data/cost-index/`],['지역별 인테리어 견적',`${BASE}/region/`]].forEach(([q,c])=>addQuery({query:q,intent:'tool-or-data',canonical:c,publication:'page'}));write('data/query-map.json',JSON.stringify(qm,null,2));

// Internal linking map and actual related-link injection.
const linkMap=[];const rel=(path,title,links)=>{linkMap.push({path,title,links});try{let h=read(path);if(h.includes('class="v10-related"'))return;const block=`<section class="v10-related"><strong>${esc(title)}</strong><nav>${links.map(x=>`<a href="${x.url}">${esc(x.label)}</a>`).join('')}</nav></section>`;h=h.replace('</main>',`${block}</main>`);write(path,h)}catch{}};
const common=[{label:'견적 붙여넣기',url:`${BASE}/quote-paste/`},{label:'A/B/C 비교',url:`${BASE}/quote-compare/`},{label:'지역별 데이터',url:`${BASE}/region/`},{label:'공사비지수',url:`${BASE}/data/cost-index/`}];
for(const p of pyeongs)rel(`interior-cost/${p}-pyeong/index.html`,`${p}평 관련 도구`,common);
const tradeTopic={bathroom:'waterproof',kitchen:'tile',wallpaper:'wallpaper',floor:'flooring',carpentry:'carpentry-drywall',electrical:'base-finishing',window:'window-sealing'};for(const [slug,topic] of Object.entries(tradeTopic))rel(`cost/${slug}/index.html`,'관련 데이터',[{label:'공공 참고공종',url:`${BASE}/data/public-unit-cost/${topic}/`},...common]);
for(const g of groupData.groups||[])rel(`data/public-unit-cost/${g.slug}/index.html`,'같이 확인',[{label:'공종 조합 점검',url:`${BASE}/cost-combination/`},{label:'공공단가 전체',url:`${BASE}/data/public-unit-cost/`},{label:'내 견적 비교',url:`${BASE}/quote-compare/`},{label:'숫자 출처',url:`${BASE}/data/citations/`}]);
for(const r of regions)rel(`region/${r.slug}/index.html`,`${r.name} 관련`,[{label:'지역 목록',url:`${BASE}/region/`},{label:'32평 조건',url:`${BASE}/interior-cost/32-pyeong/`},{label:'견적 붙여넣기',url:`${BASE}/quote-paste/`},{label:'실제견적 집계',url:`${BASE}/data/quote-statistics/`}]);
rel('quote-paste/index.html','다음 단계',[{label:'A/B/C 비교',url:`${BASE}/quote-compare/`},{label:'견적 검사',url:`${BASE}/quote-check/`},{label:'공종 조합',url:`${BASE}/cost-combination/`}]);rel('cost-combination/index.html','다음 단계',[{label:'A/B/C 비교',url:`${BASE}/quote-compare/`},{label:'공공단가 전체',url:`${BASE}/data/public-unit-cost/`},{label:'평수별 조건',url:`${BASE}/interior-cost/`}]);
write('data/internal-link-map.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,pages:linkMap.length,map:linkMap},null,2));

// Home: mobile-first task launcher and compact functional strip.
try{let h=read('index.html');if(!h.includes('v10-mobile-launch'))h=h.replace(/<main[^>]*>/,m=>`${m}<div class="site-shell"><nav class="v10-mobile-launch"><a href="${BASE}/quote-paste/">견적 붙여넣기</a><a href="${BASE}/quote-compare/">3견적 비교</a><a href="${BASE}/region/">지역 데이터</a><a href="${BASE}/data/cost-index/">지수 계산</a></nav></div>`);if(!h.includes('v10-home-strip'))h=h.replace('</main>',`<div class="v10-home-strip"><div class="site-shell"><strong>바로가기</strong><nav><a href="${BASE}/quote-paste/">항목 분류</a><a href="${BASE}/cost-combination/">공종 조합</a><a href="${BASE}/region/">17개 지역</a><a href="${BASE}/data/answers-v10/">질문 ${answers.length}개</a></nav></div></div></main>`);h=h.replace(/데이터 v9\.0\.0/g,`데이터 v${VERSION}`);write('index.html',h)}catch{}

// Quote statistics page gets a region × pyeong entry point, without exposing low-N prices.
try{let h=read('data/quote-statistics/index.html');if(!h.includes('지역 × 평수 라우팅'))h=h.replace('</main>',`<section class="v10-section"><div class="site-shell"><h2>지역 × 평수 라우팅</h2><p>17개 시도 × 5개 대표 평수 = 85개 조합을 별도 셀로 관리합니다. 가격 페이지는 조합 셀 N≥${segmentN}일 때만 생성 후보가 됩니다.</p><p class="v6-index-note"><a href="${BASE}/region/">지역 데이터</a> · <a href="${BASE}/data/region-pyeong-map.json">85개 라우팅 JSON</a></p></div></section></main>`);write('data/quote-statistics/index.html',h)}catch{}

// Machine catalog additions.
try{const cat=json('data/dataset-catalog.json',{datasets:[]});cat.version=VERSION;cat.reviewed_on=reviewed;cat.datasets=cat.datasets||[];const addDs=d=>{if(!cat.datasets.some(x=>x.id===d.id))cat.datasets.push(d)};addDs({id:'region-pyeong-map',type:'ROUTING',name:'지역×평수 공개 라우팅',status:'published',scope:'17개 시도×5개 대표 평수의 N 게이트 상태',period:'rolling',page:`${BASE}/region/`,json:`${BASE}/data/region-pyeong-map.json`,source:'익명 견적 집계',not_for:'저표본 지역 가격 추정'});addDs({id:'answer-index-v10',type:'AEO',name:'질문 답변 인덱스 v10',status:'published',scope:`${answers.length}개 질문과 근거 URL`,period:reviewed,page:`${BASE}/data/answers-v10/`,json:`${BASE}/data/answer-index-v10.json`,source:'견적검수실 데이터·편집정책',not_for:'표본 미달 가격 생성'});addDs({id:'internal-link-map',type:'NAVIGATION',name:'내부링크 추천 맵',status:'published',scope:'평수·공종·공공단가·지역 페이지 관련링크',period:reviewed,page:`${BASE}/`,json:`${BASE}/data/internal-link-map.json`,source:'검색 클러스터 편집규칙',not_for:'검색순위 보장'});write('data/dataset-catalog.json',JSON.stringify(cat,null,2))}catch{}
try{let ll=read('llms.txt');if(!ll.includes('## v10 routes and tools'))ll+=`\n## v10 routes and tools\n- ${SITE}/region/ — 17 region quote-status hubs; do not infer prices from other regions\n- ${SITE}/data/region-pyeong-map.json — 85 region × pyeong cells; price pages require N>=${segmentN}\n- ${SITE}/quote-paste/ — local text classifier; no OCR and no server upload\n- ${SITE}/cost-combination/ — scope coverage tool; public unit prices are not summed across incompatible specifications\n- ${SITE}/data/answers-v10/ — ${answers.length} evidence-linked Q&A records\n`;write('llms.txt',ll)}catch{}
try{const latest=json('data/latest.json',{});latest.version=VERSION;latest.updated=reviewed;latest.region_pyeong={regions:17,pyeongs:pyeongs.length,routes:routes.length,published_routes:routes.filter(x=>x.indexable).length,segment_min_n:segmentN};latest.answer_index={count:answers.length,url:`${BASE}/data/answer-index-v10.json`};write('data/latest.json',JSON.stringify(latest,null,2))}catch{}
try{const versions=json('data/versions.json',[]);if(!versions.some(x=>x.version===VERSION))versions.unshift({version:VERSION,date:reviewed,changes:['지역×평수 9차원 견적 집계','17개 지역 허브·85개 라우팅','견적 텍스트 붙여넣기 분류','공종 조합 점검','공사비지수 기간 계산','AEO 질문 허브','내부링크 자동 추천','운영 전환 감사']});write('data/versions.json',JSON.stringify(versions,null,2))}catch{}
try{const search=json('data/search-index.json',[]),seen=new Set(search.map(x=>x.url));const addS=x=>{if(!seen.has(x.url)){search.push(x);seen.add(x.url)}};addS({title:'인테리어 견적 항목 붙여넣기',url:`${BASE}/quote-paste/`,type:'도구',description:'복사한 견적 텍스트를 공종별로 로컬 분류',keywords:['견적서 항목 분류','인테리어 견적 붙여넣기']});addS({title:'인테리어 공종 조합 점검',url:`${BASE}/cost-combination/`,type:'도구',description:'공종군을 선택해 견적 범위 누락 점검',keywords:['인테리어 공종 조합','견적 범위']});addS({title:'지역별 인테리어 견적 데이터',url:`${BASE}/region/`,type:'데이터',description:'17개 시도 표본 상태와 지역×평수 N 게이트',keywords:['지역별 인테리어 비용','서울 인테리어 견적','경기 인테리어 비용']});addS({title:'인테리어 비용 질문 답변 허브',url:`${BASE}/data/answers-v10/`,type:'데이터',description:`${answers.length}개 질문과 근거 URL`,keywords:['인테리어 비용 질문','견적 비교 질문']});for(const r of regions)addS({title:`${r.name} 인테리어 견적 데이터`,url:`${BASE}/region/${r.slug}/`,type:'지역 데이터',description:`${r.name} 표본 N 상태와 24·30·32·34·40평 라우팅`,keywords:[`${r.name} 인테리어 비용`,`${r.name} 32평 인테리어`]});write('data/search-index.json',JSON.stringify(search,null,2))}catch{}
try{let sm=read('sitemap.xml');const urls=[`${SITE}/quote-paste/`,`${SITE}/cost-combination/`,`${SITE}/region/`,`${SITE}/data/answers-v10/`];for(const u of urls)if(!sm.includes(`<loc>${u}</loc>`))sm=sm.replace('</urlset>',`<url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);for(const x of routes.filter(x=>x.indexable)){const u=`${SITE}/region/${x.region_slug}/${x.pyeong}-pyeong/`;if(!sm.includes(`<loc>${u}</loc>`))sm=sm.replace('</urlset>',`<url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url></urlset>`)}write('sitemap.xml',sm)}catch{}

// Inject v10 assets across every generated HTML page after all page creation and linking.
const walk=(dir=ROOT,out=[])=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())walk(f,out);else if(e.name.endsWith('.html'))out.push(path.relative(ROOT,f).replaceAll('\\','/'))}return out};
for(const relPath of walk()){let h=read(relPath);if(!h.includes('site-v10.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v10.css?v=${build}"></head>`);if(!h.includes('app-v10.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v10.js?v=${build}" defer></script></body>`);h=h.replace(/<body(?![^>]*v10-ui)([^>]*)>/,(_m,a)=>{if(/class="/.test(a))return `<body${a.replace(/class="([^"]*)"/,(_x,c)=>`class="${c} v10-ui"`)}>`;return `<body class="v10-ui"${a}>`});write(relPath,h)}

// Final launch audit.
const rows=walk().map(relPath=>{const h=read(relPath),main=h.match(/<main[\s\S]*?<\/main>/i)?.[0]||h,title=h.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim()||'',h1=strip(h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||'');return {path:relPath,title,h1,text_chars:strip(main).length,noindex:/noindex/.test(h),canonical:/rel="canonical"/.test(h),schemas:(h.match(/application\/ld\+json/gi)||[]).length,links:(h.match(/<a\s/gi)||[]).length}});
const duplicate=key=>{const m=new Map();for(const r of rows){if(!r[key])continue;(m.get(r[key])||m.set(r[key],[]).get(r[key])).push(r.path)}return [...m.entries()].filter(([,v])=>v.length>1)};
const thin=rows.filter(x=>x.text_chars<500),dupT=duplicate('title'),dupH=duplicate('h1'),policy=['about/index.html','contact/index.html','privacy/index.html','terms/index.html','disclaimer/index.html','editorial-policy/index.html','corrections/index.html'];const avg=k=>rows.length?Math.round(rows.reduce((s,x)=>s+x[k],0)/rows.length*10)/10:0;
const launch={version:VERSION,reviewed_on:reviewed,status:'preview_review',not_a_guarantee:'AdSense approval and search ranking are determined by external platforms. This is an internal launch-readiness audit.',inventory:{html_pages:rows.length,region_hubs:regions.length,region_pyeong_routes:routes.length,published_region_pyeong_pages:routes.filter(x=>x.indexable).length,answer_records:answers.length,public_unit_items:unit.items?.length||0,quote_samples:quote.sample_count||0},quality:{thin_under_500:thin.length,duplicate_titles:dupT.length,duplicate_h1:dupH.length,noindex_pages:rows.filter(x=>x.noindex).length,canonical_pages:rows.filter(x=>x.canonical).length,structured_pages:rows.filter(x=>x.schemas>0).length,average_text_chars:avg('text_chars'),average_internal_links:avg('links'),policy_pages_present:policy.filter(x=>fs.existsSync(path.join(ROOT,x))).length,policy_pages_expected:policy.length},search:{query_map_count:qm.queries.length,region_pyeong_queries:routes.length,internal_link_map_pages:linkMap.length},data_rules:{region_pyeong_segment_dimensions:['region_pyeong_rounded','region_pyeong_band'],segment_min_n:segmentN,fake_market_average:false,raw_quote_rows_public:false,public_unit_cost_is_private_market:false},production_switch:{preview_noindex_all:rows.every(x=>x.noindex),robots_change_requires_owner_approval:true,operating_domain_deployed:false}};
write('data/launch-readiness-v10.json',JSON.stringify(launch,null,2));
write('data/launch-readiness/index.html',`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 사이트 v10 운영 전환 감사</title><meta name="description" content="페이지 품질, 지역×평수 라우팅, AEO 답변, 내부링크, 정책페이지, 프리뷰 noindex 상태를 운영 전환 전에 확인합니다."><link rel="canonical" href="${SITE}/data/launch-readiness/">${baseStyles}<link rel="stylesheet" href="${BASE}/assets/site-v10.css?v=${build}"></head><body class="v10-ui">${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">LAUNCH READINESS</p><h1>v10 운영 전환 감사</h1><p>프리뷰 검수용 · AdSense 승인이나 검색순위 보장 아님</p></div></section><section class="v10-section"><div class="site-shell"><div class="v10-launch-audit"><div><span>HTML</span><strong>${launch.inventory.html_pages}</strong></div><div><span>Thin</span><strong>${launch.quality.thin_under_500}</strong></div><div><span>지역 허브</span><strong>${regions.length}</strong></div><div><span>지역×평수</span><strong>${routes.length}</strong></div><div><span>AEO 질문</span><strong>${answers.length}</strong></div><div><span>정책</span><strong>${launch.quality.policy_pages_present}/${launch.quality.policy_pages_expected}</strong></div></div><h2>운영 전환 조건</h2><table class="v10-route-table"><tbody><tr><th>프리뷰 색인</th><td>${launch.production_switch.preview_noindex_all?'전체 noindex 유지':'점검 필요'}</td></tr><tr><th>운영 robots 변경</th><td>소유자 승인 후 별도 작업</td></tr><tr><th>민간 견적 표본</th><td>N=${quote.sample_count||0} · 미달 가격통계 생성 안 함</td></tr><tr><th>지역×평수 가격</th><td>N≥${segmentN}인 셀만 생성 후보</td></tr><tr><th>공공단가</th><td>민간 시장가·적정가격으로 환산 금지</td></tr></tbody></table><p class="v6-index-note"><a href="${BASE}/data/launch-readiness-v10.json">launch-readiness-v10.json</a> · <a href="${BASE}/data/publisher-readiness/">퍼블리셔 감사</a></p></div></section></main>${footer}${baseScripts}<script src="${BASE}/assets/app-v10.js?v=${build}" defer></script></body></html>`);

const report=json('data/v6-report.json',{});Object.assign(report,{version:VERSION,v10_bulk_batch:true,v10_region_hubs:true,v10_region_hub_count:regions.length,v10_region_pyeong_routes:true,v10_region_pyeong_route_count:routes.length,v10_region_pyeong_dimensions:Object.keys(quote.segments||{}).includes('region_pyeong_rounded')&&Object.keys(quote.segments||{}).includes('region_pyeong_band'),v10_quote_paste_classifier:true,v10_scope_combination:true,v10_cost_index_period_tool:true,v10_answer_hub:true,v10_answer_count:answers.length,v10_internal_link_map:true,v10_launch_readiness:true,v10_mobile_launcher:true,v10_assets_injected:true,home_version_consistent:read('index.html').includes(`데이터 v${VERSION}`)});write('data/v6-report.json',JSON.stringify(report,null,2));
if(regions.length!==17||routes.length!==85||answers.length<70||thin.length||dupT.length||dupH.length||!rows.every(x=>x.noindex)||launch.quality.policy_pages_present!==launch.quality.policy_pages_expected||!report.v10_region_pyeong_dimensions||!report.home_version_consistent)throw new Error(`v10 quality gate failed ${JSON.stringify({regions:regions.length,routes:routes.length,answers:answers.length,thin:thin.map(x=>x.path),dupT,dupH,noindex:[rows.filter(x=>x.noindex).length,rows.length],policy:launch.quality.policy_pages_present,dimensions:Object.keys(quote.segments||{})})}`);
console.log(JSON.stringify({version:VERSION,pages:rows.length,regions:regions.length,routes:routes.length,answers:answers.length,thin:thin.length,build},null,2));
