import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='9.0.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8');
const write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)};
const json=(r,fallback={})=>{try{return JSON.parse(read(r))}catch{return fallback}};
const reviewed=json('data/v5-report.json',{}).reviewed_on||new Date().toISOString().slice(0,10);
const unit=json('data/public-unit-cost-v8.json',{items:[]}),quote=json('data/quote-statistics.json',{sample_count:0,status:'withheld',segments:{}}),index=json('data/construction-cost-index.json',{series:[]}),wage=json('data/construction-wage-2026-h2.json',{});
const css=fs.readFileSync(path.join(CORE,'site-v9.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v9.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v9.css',css);write('assets/app-v9.js',js);
const fmt=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:1});
const htmlEscape=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const strip=s=>String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim();
const items=unit.items||[];

const groups=[
 {slug:'waterproof',name:'방수 단가',label:'방수',keywords:['방수','시멘트액체방수'],desc:'시트·도막·폴리머 시멘트·바탕처리 등 방수 관련 공공 표준시장단가를 공법과 부위별로 구분합니다.',test:i=>/방수/.test(`${i.group} ${i.name}`)},
 {slug:'tile',name:'타일 시공 단가',label:'타일',keywords:['타일','압착붙이기','떠붙이기'],desc:'벽·바닥 타일의 압착붙이기·떠붙이기·접착붙이기 항목을 규격과 단위 기준으로 확인합니다.',test:i=>/타일/.test(`${i.group} ${i.name}`)},
 {slug:'window-sealing',name:'창호·실링 단가',label:'창호·실링',keywords:['창호','코킹','우레탄폼'],desc:'창호 주위 충전·코킹·실링처럼 창호 본체 가격과 분리해야 하는 시공 항목을 모읍니다.',test:i=>/창호|실링|코킹|우레탄/.test(`${i.group} ${i.name}`)},
 {slug:'wallpaper',name:'도배 단가',label:'도배',keywords:['도배','벽지','천장 도배'],desc:'벽·천장 도배지 바름 항목을 바탕면 조건과 함께 확인합니다. 주재료 도배지 포함 여부를 별도로 봅니다.',test:i=>/도배/.test(`${i.group} ${i.name}`)},
 {slug:'carpentry-drywall',name:'목공·석고·천장 단가',label:'목공·석고',keywords:['목공','석고보드','천장','띠장'],desc:'벽체 띠장·석고판·천장 마감 등 목공과 건식 수장에 가까운 공종을 한 묶음으로 비교합니다.',test:i=>/목공|석고|천장|띠장|수장/.test(`${i.group} ${i.name}`)},
 {slug:'flooring',name:'바닥·걸레받이 단가',label:'바닥',keywords:['바닥','마루','걸레받이','이중바닥'],desc:'바닥 바탕·마루·걸레받이·이중바닥 등 서로 다른 시공 단위를 분리해 확인합니다.',test:i=>/바닥|마루|걸레받이/.test(`${i.group} ${i.name}`)},
 {slug:'paint',name:'도장 단가',label:'도장',keywords:['도장','수성페인트','바탕만들기'],desc:'수성페인트 롤러·뿜칠과 목재 바탕처리 등 도장 전후 공정을 구분합니다.',test:i=>/도장|페인트|바탕만들기/.test(`${i.group} ${i.name}`)},
 {slug:'insulation',name:'단열 시공 단가',label:'단열',keywords:['단열','단열재','천장 단열'],desc:'단열재 두께와 부착 방식에 따라 달라지는 공공 표준시장단가 항목을 구분합니다.',test:i=>/단열/.test(`${i.group} ${i.name}`)},
 {slug:'base-finishing',name:'바탕·미장 단가',label:'바탕·미장',keywords:['미장','모르타르','바탕','표면마무리'],desc:'모르타르·표면마무리·타일 바탕고르기처럼 최종 마감 전에 필요한 바탕 공정을 분리합니다.',test:i=>/바탕|미장|모르타르|표면마무리/.test(`${i.group} ${i.name}`)}
].map(g=>({...g,items:items.filter(g.test)}));

const groupData={version:VERSION,reviewed_on:reviewed,source:unit.official_source,warning:unit.not_for,groups:groups.map(g=>({slug:g.slug,name:g.name,keywords:g.keywords,item_count:g.items.length,units:[...new Set(g.items.map(i=>i.unit))],url:`${BASE}/data/public-unit-cost/${g.slug}/`,codes:g.items.map(i=>i.code)}))};
write('data/public-unit-groups.json',JSON.stringify(groupData,null,2));

const template=read('data/index.html'),header=template.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=template.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',baseStyles=[...template.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),baseScripts=[...template.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
function groupRange(g){const by={};for(const i of g.items){if(!Number.isFinite(Number(i.price)))continue;(by[i.unit]??=[]).push(Number(i.price))}return Object.entries(by).map(([u,v])=>({unit:u,min:Math.min(...v),max:Math.max(...v),n:v.length}))}
function groupPage(g){
 const ranges=groupRange(g);const rows=g.items.map(i=>`<tr><th><code>${htmlEscape(i.code)}</code><br>${htmlEscape(i.name)}</th><td>${htmlEscape(i.spec||'—')}</td><td>${fmt(i.price)}원/${htmlEscape(i.unit)}</td><td>${i.detail_level==='detailed'?'상세검수':'카탈로그'}</td></tr>`).join('');
 const rangeHtml=ranges.map(r=>`<div><span>${htmlEscape(r.unit)} 항목</span><strong>${r.n}개</strong><em>${fmt(r.min)}~${fmt(r.max)}원 · 규격 서로 다름</em></div>`).join('');
 const faq=[{q:`${g.name}를 민간 인테리어 시세로 봐도 되나요?`,a:'아닙니다. 이 페이지는 공공 건설 예정가격 참고용 표준시장단가를 공종별로 분류한 자료입니다. 주재료비 제외 여부와 규격이 서로 달라 민간 소비자 견적의 적정가격 판정에 사용할 수 없습니다.'},{q:`${g.name} 항목은 무엇을 먼저 비교해야 하나요?`,a:'같은 단위인지 확인한 뒤 공법·부위·규격·포함재료를 맞춰야 합니다. 단위가 같아도 규격이 다르면 단순 가격순위로 해석하지 않습니다.'},{q:'실제 인테리어 견적과 어떻게 같이 보나요?',a:`공공 단가는 작업 범위를 확인하는 참고축으로 쓰고, 실제 민간 견적은 견적 비교 도구에서 VAT·폐기물·창호 등 포함조건을 먼저 맞춥니다. 현재 민간 가격 통계는 표본 기준을 충족할 때만 공개합니다.`}];
 const schema={'@context':'https://schema.org','@graph':[{'@type':'CollectionPage',name:g.name,url:`${SITE}/data/public-unit-cost/${g.slug}/`,description:g.desc,dateModified:reviewed},{'@type':'ItemList',name:`${g.name} 공공 참고항목`,numberOfItems:g.items.length,itemListElement:g.items.slice(0,30).map((i,n)=>({'@type':'ListItem',position:n+1,name:`${i.name} ${i.spec||''}`.trim()}))},{'@type':'FAQPage',mainEntity:faq.map(x=>({'@type':'Question',name:x.q,acceptedAnswer:{'@type':'Answer',text:x.a}}))}]};
 return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>${g.name} | 2026 하반기 공공 표준시장단가 참고</title><meta name="description" content="${g.desc} 민간 시장가가 아닌 2026 하반기 공공 표준시장단가 참고자료입니다."><link rel="canonical" href="${SITE}/data/public-unit-cost/${g.slug}/">${baseStyles}<script type="application/ld+json">${JSON.stringify(schema)}</script></head><body><header>${header.replace(/^<header[^>]*>|<\/header>$/g,'')}</header><main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">PUBLIC COST TOPIC</p><h1>${g.name}</h1><p>${g.desc}</p></div></section><section class="v6-section"><div class="site-shell"><div class="v9-reference-summary">${rangeHtml||'<div><span>항목</span><strong>0개</strong></div>'}</div><div class="v9-scope-grid"><div class="v9-scope-note"><h3>REFERENCE · 공공 예정가격 참고</h3><p>국토교통부 2026년 하반기 표준시장단가 중 관련 공종 ${g.items.length}개를 선별했습니다. 같은 단위라도 규격·공법·주재료 포함 여부가 다릅니다. 이 페이지의 최저·최고값은 시장가격 범위가 아니라 카탈로그 내부 값입니다.</p></div><div class="v9-scope-note"><h3>민간 견적 비교</h3><p>업체 견적은 <a href="${BASE}/quote-compare/">A/B/C 비교</a>에서 포함조건을 먼저 맞추고, 실제 견적 통계는 <a href="${BASE}/data/quote-statistics/">표본 공개 기준</a>을 충족한 경우에만 가격분포를 사용합니다.</p></div></div><div class="table-wrap"><table class="v9-link-table"><thead><tr><th>공종</th><th>규격</th><th>참고단가</th><th>검수수준</th></tr></thead><tbody>${rows||'<tr><td colspan="4">선별 항목 없음</td></tr>'}</tbody></table></div><p class="v6-index-note"><a href="${unit.official_source}">공식 공고</a> · <a href="${BASE}/data/public-unit-cost/">65개 전체 탐색</a> · <a href="${BASE}/data/public-unit-cost/topics/">공종군 목록</a></p></div></section><section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>질문</h2><p>적용범위 확인</p></div>${faq.map(x=>`<details><summary>${x.q}</summary><p>${x.a}</p></details>`).join('')}</div></section></main>${footer}${baseScripts}</body></html>`;
}
for(const g of groups)write(`data/public-unit-cost/${g.slug}/index.html`,groupPage(g));
const topicCards=groups.map(g=>`<a class="v9-topic-card" data-v9-topic-item="${htmlEscape([g.name,...g.keywords].join(' '))}" href="${BASE}/data/public-unit-cost/${g.slug}/"><span>${g.items.length} ITEMS · ${[...new Set(g.items.map(i=>i.unit))].join(' · ')||'—'}</span><strong>${g.name}</strong><p>${g.desc}</p></a>`).join('');
const topicSchema={'@context':'https://schema.org','@type':'CollectionPage',name:'인테리어 공공단가 공종별 탐색',dateModified:reviewed,url:`${SITE}/data/public-unit-cost/topics/`,hasPart:groups.map(g=>({'@type':'CollectionPage',name:g.name,url:`${SITE}/data/public-unit-cost/${g.slug}/`}))};
write('data/public-unit-cost/topics/index.html',`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 공공단가 공종별 탐색 | 방수·타일·창호·도배·목공</title><meta name="description" content="2026 하반기 공공 표준시장단가 65개 선별항목을 방수, 타일, 창호, 도배, 목공, 바닥, 도장, 단열, 바탕 공종별로 탐색합니다."><link rel="canonical" href="${SITE}/data/public-unit-cost/topics/">${baseStyles}<script type="application/ld+json">${JSON.stringify(topicSchema)}</script></head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">PUBLIC COST TOPICS</p><h1>공공단가 공종별 탐색</h1><p>65개 선별항목을 공종군으로 나눕니다. 시장가 순위가 아니라 공법·규격·단위 확인용입니다.</p></div></section><section class="v6-section"><div class="site-shell"><label>공종 찾기<input data-v9-topic-search type="search" placeholder="방수 · 타일 · 창호 · 도배 · 단열" style="display:block;width:100%;max-width:520px;margin:10px 0 18px;padding:12px;border:1px solid #9ca3ad"></label><div class="v9-topic-index">${topicCards}</div><p class="v6-index-note"><a href="${BASE}/data/public-unit-cost/">65개 전체 표</a> · <a href="${BASE}/data/citations/">출처 지도</a></p></div></section></main>${footer}${baseScripts}</body></html>`);

const series=index.series||[];const minIndex=Math.min(...series.map(x=>Number(x.value)).filter(Number.isFinite),0),maxIndex=Math.max(...series.map(x=>Number(x.value)).filter(Number.isFinite),1);function indexChart(){return `<div class="v9-index-chart" aria-label="2026 건설공사비지수 월별 추이">${series.map(x=>{const h=maxIndex===minIndex?50:18+((x.value-minIndex)/(maxIndex-minIndex))*65;return `<div class="v9-index-bar"><b>${fmt(x.value)}</b><i style="height:${h}%"></i><span>${x.month.slice(5)}월</span></div>`}).join('')}</div>`}
const refCounts={bathroom:items.filter(i=>(i.match||[]).includes('bathroom')).length,kitchen:items.filter(i=>(i.match||[]).includes('kitchen')).length,wallpaper:items.filter(i=>(i.match||[]).includes('wallpaper')).length,floor:items.filter(i=>(i.match||[]).includes('floor')).length,carpentry:items.filter(i=>(i.match||[]).includes('carpentry')).length,electrical:items.filter(i=>(i.match||[]).includes('electrical')).length,window:items.filter(i=>(i.match||[]).includes('window')).length};
const pyeongs=[24,30,32,34,40];
for(const p of pyeongs){const rel=`interior-cost/${p}-pyeong/index.html`;if(!fs.existsSync(path.join(ROOT,rel)))continue;let h=read(rel);const cell=(quote.segments?.supply_pyeong_rounded||[]).find(x=>x.key===`${p}평`);const qStatus=cell?.status==='published'?`N=${cell.n} · 가격분포 공개`:`N=${cell?.n||0} · 가격통계 보류`;const rows=[['욕실·방수',refCounts.bathroom,`${BASE}/cost/bathroom/`],['도배',refCounts.wallpaper,`${BASE}/cost/wallpaper/`],['바닥',refCounts.floor,`${BASE}/cost/floor/`],['목공',refCounts.carpentry,`${BASE}/cost/carpentry/`],['창호',refCounts.window,`${BASE}/cost/window/`]].map(r=>`<tr><th>${r[0]}</th><td>공공 참고 ${r[1]}개</td><td><a href="${r[2]}">공종 보기</a></td></tr>`).join('');const block=`<section class="v9-pyeong-board"><div class="v9-board-head"><h2>${p}평 데이터 보드</h2><p>OFFICIAL + REFERENCE + QUOTE · 서로 다른 데이터 종류를 합치지 않음</p></div><div class="v9-metric-strip"><div><span>건설공사비지수</span><strong>${index.latest_value||138.59}</strong></div><div><span>전년동월</span><strong>+${index.latest_yoy_percent||5.78}%</strong></div><div><span>건설업 일평균임금</span><strong>${Number(wage.daily_average||282737).toLocaleString('ko-KR')}원</strong></div><div><span>${p}평 실제견적</span><strong>${qStatus}</strong></div></div>${indexChart()}<div class="table-wrap"><table class="v9-link-table"><thead><tr><th>공종</th><th>참고 데이터</th><th>페이지</th></tr></thead><tbody>${rows}</tbody></table></div><p class="v8-footnote">공사비지수와 건설업 임금은 거시 지표이며 ${p}평 민간 인테리어 견적 평균으로 환산하지 않습니다.</p></section>`;if(!h.includes('v9-pyeong-board'))h=h.replace('</main>',`${block}</main>`);write(rel,h)}

const tradeNames={bathroom:'욕실',kitchen:'주방',wallpaper:'도배',floor:'바닥',carpentry:'목공',electrical:'전기',window:'창호'};
for(const [slug,name] of Object.entries(tradeNames)){const rel=`cost/${slug}/index.html`;if(!fs.existsSync(path.join(ROOT,rel)))continue;let h=read(rel);const matched=items.filter(i=>(i.match||[]).includes(slug));const unitGroups={};for(const i of matched)(unitGroups[i.unit]??=[]).push(i);const rows=matched.slice(0,10).map(i=>`<tr><th>${htmlEscape(i.name)}</th><td>${htmlEscape(i.spec||'—')}</td><td>${fmt(i.price)}원/${htmlEscape(i.unit)}</td><td>${i.detail_level==='detailed'?'상세검수':'카탈로그'}</td></tr>`).join('');const quoteTrade=(quote.overall?.distribution?.trade_amounts||{})[`${slug}_manwon`];const block=`<section class="v9-trade-board"><div class="v9-board-head"><h2>${name} 데이터 보드</h2><p>직접 매칭 공공단가 ${matched.length}개 · 실제 견적 공종통계 ${quoteTrade?'공개':'보류'}</p></div><div class="v9-reference-summary"><div><span>공공 참고 직접매칭</span><strong>${matched.length}개</strong></div><div><span>사용 단위</span><strong>${Object.keys(unitGroups).join(' · ')||'없음'}</strong></div><div><span>민간 공종 통계</span><strong>${quoteTrade?`N≥${quote.segment_threshold||20}`:'표본 기준 미달'}</strong></div></div>${matched.length?`<div class="table-wrap"><table class="v9-link-table"><thead><tr><th>공종</th><th>규격</th><th>참고단가</th><th>수준</th></tr></thead><tbody>${rows}</tbody></table></div>`:`<div class="v9-scope-note"><h3>직접 매칭 공공 공종 없음</h3><p>${name} 전체 공사와 의미가 같은 공공 단가를 억지로 연결하지 않습니다. 관련 공공 공종이 확인될 때만 직접 매칭에 추가합니다.</p></div>`}<p class="v6-index-note"><a href="${BASE}/data/public-unit-cost/topics/">공공단가 공종군</a> · <a href="${BASE}/quote-compare/">A/B/C 견적 비교</a> · <a href="${BASE}/data/quote-statistics/">실제 견적 집계</a></p></section>`;if(!h.includes('v9-trade-board'))h=h.replace('</main>',`${block}</main>`);write(rel,h)}

let compare=read('quote-compare/index.html');const matrix=`<section class="v9-compare-matrix site-shell" data-v9-compare-matrix><div class="v9-board-head"><h2>공종별 비교 요약</h2><p data-v9-condition-gate>미기재 조건 있음 · 최저가/적정가 판단 보류</p></div><div class="v9-matrix-status">${['a','b','c'].map((v,i)=>`<div data-v9-summary="${v}"><span>${String.fromCharCode(65+i)} 견적 상태</span><strong data-v9-summary-main>검토 전</strong><em data-v9-summary-sub>입력금액 합계 —</em></div>`).join('')}</div><div class="table-wrap"><table class="v9-matrix-table"><thead><tr><th>공종</th><th>A</th><th>B</th><th>C</th></tr></thead><tbody data-v9-matrix-body><tr><td colspan="4">입력 대기</td></tr></tbody></table></div><p class="v8-footnote">위 표는 기존 A/B/C 입력을 그대로 요약합니다. 포함·별도·미기재 상태와 사용자가 입력한 금액만 표시하며 누락값을 시장가로 채우지 않습니다.</p></section>`;if(!compare.includes('data-v9-compare-matrix'))compare=compare.replace('</main>',`${matrix}</main>`);write('quote-compare/index.html',compare);

let home=read('index.html');const command=`<section class="v6-section v9-command-wrap"><div class="site-shell"><div class="v9-command"><div class="v9-command-head"><h2>견적 비교 · 공공단가 · 실제표본</h2><p>총액보다 조건을 먼저 맞추고, 공공 참고값과 민간 견적 통계를 분리해서 확인합니다.</p></div><div class="v9-command-grid"><a href="${BASE}/quote-compare/"><span>TOOL</span><strong>A/B/C 견적 비교</strong><em>포함 · 별도 · 미기재</em></a><a href="${BASE}/data/public-unit-cost/topics/"><span>REFERENCE</span><strong>공종 9개 묶음</strong><em>공공단가 ${items.length}개</em></a><a href="${BASE}/interior-cost/32-pyeong/"><span>PYEONG</span><strong>평수 데이터</strong><em>24 · 30 · 32 · 34 · 40평</em></a><a href="${BASE}/data/quote-statistics/"><span>QUOTE</span><strong>실제표본 N=${quote.sample_count||0}</strong><em>${quote.status==='published'?'가격통계 공개':'가격통계 보류'}</em></a></div></div></div></section>`;if(!home.includes('v9-command-wrap'))home=home.replace('<main>',`<main>${command}`);write('index.html',home);

const clusterData={version:VERSION,reviewed_on:reviewed,clusters:[
 {id:'quote-tools',intent:'견적 검수·비교',canonical:`${BASE}/quote-compare/`,pages:[`${BASE}/quote-check/`,`${BASE}/quote-compare/`,`${BASE}/calculator/`,`${BASE}/quote-market/`],queries:['인테리어 견적 비교','인테리어 견적서 보는법','인테리어 VAT 별도','폐기물 별도 견적']},
 {id:'pyeong-cost',intent:'평수별 비용 조건',canonical:`${BASE}/interior-cost/`,pages:pyeongs.map(p=>`${BASE}/interior-cost/${p}-pyeong/`),queries:pyeongs.flatMap(p=>[`${p}평 인테리어 비용`,`${p}평 리모델링 견적`])},
 {id:'trade-cost',intent:'공사별 비용·조건',canonical:`${BASE}/cost/`,pages:Object.keys(tradeNames).map(s=>`${BASE}/cost/${s}/`),queries:['욕실 인테리어 비용','도배 비용','마루 시공 비용','목공 비용','샷시 비용','전기 공사 비용']},
 {id:'public-unit-cost',intent:'공공 공종 단가 참고',canonical:`${BASE}/data/public-unit-cost/`,pages:groups.map(g=>`${BASE}/data/public-unit-cost/${g.slug}/`),queries:groups.flatMap(g=>g.keywords.map(k=>`${k} 단가`))},
 {id:'evidence',intent:'데이터 출처·방법론',canonical:`${BASE}/data/`,pages:[`${BASE}/data/cost-index/`,`${BASE}/data/construction-wage/`,`${BASE}/data/citations/`,`${BASE}/data/quote-statistics/`,`${BASE}/data/catalog/`],queries:['건설공사비지수','건설업 임금','인테리어 데이터 출처','인테리어 견적 통계']}
],note:'검색량 추정값을 만들지 않고 검색 의도와 canonical 역할만 관리'};write('data/search-clusters.json',JSON.stringify(clusterData,null,2));

try{const q=json('data/query-map.json',{version:'8.0.0',queries:[]});q.version=VERSION;q.reviewed_on=reviewed;const existing=new Set((q.queries||[]).map(x=>x.query));for(const g of groups)for(const k of g.keywords){const queryText=`${k} 단가`;if(!existing.has(queryText))q.queries.push({query:queryText,intent:'public-reference',target:`${BASE}/data/public-unit-cost/${g.slug}/`,evidence:'2026-H2 public standard market unit cost; not private market average'})}q.note='검색량·순위를 추정하지 않고 검색 의도와 canonical 타깃만 관리';write('data/query-map.json',JSON.stringify(q,null,2))}catch{}
try{const s=json('data/search-index.json',[]);const seen=new Set(s.map(x=>x.url));const add=(x)=>{if(!seen.has(x.url)){s.push(x);seen.add(x.url)}};add({title:'공공단가 공종별 탐색',url:`${BASE}/data/public-unit-cost/topics/`,type:'데이터',description:'65개 공공 표준시장단가 선별항목을 9개 공종군으로 탐색',keywords:['방수 단가','타일 단가','창호 단가','도배 단가','목공 단가','단열 단가']});for(const g of groups)add({title:g.name,url:`${BASE}/data/public-unit-cost/${g.slug}/`,type:'공공단가',description:g.desc,keywords:g.keywords});write('data/search-index.json',JSON.stringify(s,null,2))}catch{}
try{let sm=read('sitemap.xml');const urls=[`${SITE}/data/public-unit-cost/topics/`,...groups.map(g=>`${SITE}/data/public-unit-cost/${g.slug}/`)];for(const u of urls)if(!sm.includes(`<loc>${u}</loc>`))sm=sm.replace('</urlset>',`<url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap.xml',sm)}catch{}
try{let l=read('llms.txt');if(!l.includes('Public unit-cost topic pages'))l+=`\n## Public unit-cost topic pages\n${groups.map(g=>`- ${SITE}/data/public-unit-cost/${g.slug}/ — ${g.name}; ${g.items.length} selected items; public construction reference, not private market price`).join('\n')}\n`;write('llms.txt',l)}catch{}

function injectAssets(rel){let h=read(rel);if(!h.includes('site-v9.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v9.css?v=${build}"></head>`);if(!h.includes('app-v9.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v9.js?v=${build}" defer></script></body>`);if(/<body(?![^>]*v9-ui)/.test(h))h=h.replace(/<body([^>]*)>/,`<body$1 class="${rel==='index.html'?'v9-ui v9-home':'v9-ui'}">`);else if(rel==='index.html'&&!h.includes('v9-home'))h=h.replace('class="v9-ui"','class="v9-ui v9-home"');write(rel,h)}
const walkHtml=(dir=ROOT,out=[])=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())walkHtml(f,out);else if(e.name.endsWith('.html'))out.push(path.relative(ROOT,f).replaceAll('\\','/'))}return out};
let htmlFiles=walkHtml();for(const rel of htmlFiles)injectAssets(rel);

function contextFor(rel,title){const isPolicy=/about|contact|privacy|terms|disclaimer|editorial-policy|corrections/.test(rel),isData=rel.startsWith('data/');const role=isPolicy?'운영·검수 정책 페이지':isData?'데이터 정의·출처 페이지':'견적 판단 보조 페이지';return `<section class="v9-quality-context"><div class="site-shell"><h2>${htmlEscape(title)} · 사용 기준</h2><p>이 페이지는 ${role}입니다. 견적검수실은 공식 통계(OFFICIAL), 공공 예정가격 참고값(REFERENCE), 사용자가 입력한 계산값(CALCULATED), 익명 민간견적 집계(QUOTE)를 서로 다른 데이터 종류로 표시합니다. 공공 표준시장단가는 민간 아파트 인테리어 시장평균이나 적정가격 판정값으로 바꾸지 않으며, 실제 견적 가격분포는 정해진 표본 기준을 충족한 경우에만 공개합니다. 프리뷰의 모든 페이지는 검수 중이므로 검색 색인을 막아 두었고 운영 전환은 별도 승인 후 진행합니다.</p><nav><a href="${BASE}/data/citations/">숫자 출처</a><a href="${BASE}/data/methodology/">산출 원칙</a><a href="${BASE}/data/public-unit-cost/topics/">공공단가 공종군</a><a href="${BASE}/quote-compare/">견적 비교</a></nav></div></section>`}
function audit(files){const rows=files.map(rel=>{const h=read(rel),title=h.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim()||'',h1=h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||'',chars=strip(h.match(/<main[\s\S]*?<\/main>/i)?.[0]||h).length,links=(h.match(/<a\s/gi)||[]).length,schemas=(h.match(/application\/ld\+json/gi)||[]).length,noindex=/noindex/.test(h);return {rel,title,h1:strip(h1),chars,links,schemas,noindex}});const dup=(key)=>{const m=new Map();for(const r of rows){if(!r[key])continue;(m.get(r[key])||m.set(r[key],[]).get(r[key])).push(r.rel)}return [...m.entries()].filter(([,v])=>v.length>1)};return {rows,thin:rows.filter(r=>r.chars<500),duplicate_titles:dup('title'),duplicate_h1:dup('h1')}}
let firstAudit=audit(htmlFiles);for(const r of firstAudit.thin){let h=read(r.rel);const title=r.h1||r.title||'페이지';if(!h.includes('v9-quality-context'))h=h.replace('</main>',`${contextFor(r.rel,title)}</main>`);write(r.rel,h)}
htmlFiles=walkHtml();const a=audit(htmlFiles);const avg=k=>a.rows.length?Math.round(a.rows.reduce((s,r)=>s+r[k],0)/a.rows.length*10)/10:0;const policyPaths=['about/index.html','contact/index.html','privacy/index.html','terms/index.html','disclaimer/index.html','editorial-policy/index.html','corrections/index.html'];const structured=a.rows.filter(r=>r.schemas>0).length;const quality={version:VERSION,reviewed_on:reviewed,pages:a.rows.length,unique_title_ratio:a.rows.length?(a.rows.length-a.duplicate_titles.reduce((s,x)=>s+x[1].length,0))/a.rows.length:1,unique_h1_ratio:a.rows.length?(a.rows.length-a.duplicate_h1.reduce((s,x)=>s+x[1].length,0))/a.rows.length:1,thin_before:firstAudit.thin.map(x=>x.rel),pages_under_500_text_chars:a.thin.length,average_text_chars:avg('chars'),pages_with_structured_data:structured,structured_data_ratio:a.rows.length?Number((structured/a.rows.length).toFixed(3)):0,preview_noindex_pages:a.rows.filter(r=>r.noindex).length,preview_noindex_expected:true,average_internal_links:avg('links'),policy_pages_present:policyPaths.filter(p=>fs.existsSync(path.join(ROOT,p))).length,policy_pages_expected:policyPaths.length,public_unit_curated_count:items.length,public_unit_topic_pages:groups.length,quote_sample_count:quote.sample_count||0};write('data/site-quality-v9.json',JSON.stringify(quality,null,2));
const readiness={version:VERSION,reviewed_on:reviewed,status:'preview_review',not_a_guarantee:'AdSense approval is determined by Google; this is an internal publisher-readiness audit only.',checks:{unique_titles:a.duplicate_titles.length===0,unique_h1:a.duplicate_h1.length===0,thin_pages_zero:a.thin.length===0,policy_pages_complete:quality.policy_pages_present===quality.policy_pages_expected,preview_noindex_all:quality.preview_noindex_pages===quality.pages,structured_data_coverage:quality.structured_data_ratio,average_text_chars:quality.average_text_chars,average_internal_links:quality.average_internal_links,official_reference_quote_separated:true,fake_market_average:false,raw_quote_rows_public:false},content_inventory:{html_pages:quality.pages,pyeong_pages:pyeongs.length,trade_pages:Object.keys(tradeNames).length,public_unit_topic_pages:groups.length,public_unit_items:items.length,quote_samples:quote.sample_count||0}};write('data/publisher-readiness.json',JSON.stringify(readiness,null,2));
const readinessPage=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 사이트 퍼블리셔 준비도 | 콘텐츠·출처·Thin 감사</title><meta name="description" content="정책 페이지, Thin 콘텐츠, 제목/H1 중복, 구조화데이터, 내부링크, 데이터 출처 분리를 자동 점검합니다."><link rel="canonical" href="${SITE}/data/publisher-readiness/">${baseStyles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">PUBLISHER READINESS</p><h1>퍼블리셔 준비도</h1><p>승인 보장이 아니라 콘텐츠·출처·운영정보 누락을 찾는 내부 감사입니다.</p></div></section><section class="v6-section"><div class="site-shell"><div class="v9-quality-strip"><div><span>HTML</span><strong>${quality.pages}</strong></div><div><span>500자 미만</span><strong>${quality.pages_under_500_text_chars}</strong></div><div><span>정책 페이지</span><strong>${quality.policy_pages_present}/${quality.policy_pages_expected}</strong></div><div><span>구조화데이터</span><strong>${Math.round(quality.structured_data_ratio*100)}%</strong></div><div><span>평균 내부링크</span><strong>${quality.average_internal_links}</strong></div></div><div class="v9-scope-grid"><div class="v9-scope-note"><h3>콘텐츠 구조</h3><p>평수 ${pyeongs.length}개, 공종 ${Object.keys(tradeNames).length}개, 공공단가 공종군 ${groups.length}개, 선별 공공단가 ${items.length}개를 도구·데이터·출처 페이지와 연결했습니다. 실제 민간견적 N=${quote.sample_count||0}은 표본 기준 미달이면 가격통계를 만들지 않습니다.</p></div><div class="v9-scope-note"><h3>프리뷰 상태</h3><p>${quality.preview_noindex_pages}/${quality.pages} 페이지 noindex. 운영 검색 노출 전환은 별도 승인 후 robots·canonical·사이트맵을 재검수해야 합니다. 이 내부 감사 결과는 광고 승인 결과를 보장하지 않습니다.</p></div></div><p class="v6-index-note"><a href="${BASE}/data/publisher-readiness.json">publisher-readiness.json</a> · <a href="${BASE}/data/site-quality-v9.json">site-quality-v9.json</a> · <a href="${BASE}/data/search-clusters.json">search-clusters.json</a></p></div></section></main>${footer}${baseScripts}</body></html>`;write('data/publisher-readiness/index.html',readinessPage);injectAssets('data/publisher-readiness/index.html');

try{let data=read('data/index.html');if(!data.includes('/data/publisher-readiness/'))data=data.replace('<div class="v62-data-links">',`<div class="v62-data-links"><a href="${BASE}/data/public-unit-cost/topics/"><strong>공공단가 공종별 탐색</strong><span>방수·타일·창호·도배·목공·바닥·도장·단열·바탕</span></a><a href="${BASE}/data/publisher-readiness/"><strong>퍼블리셔 준비도</strong><span>Thin · 출처 · 정책 · 구조화데이터 자동감사</span></a>`);write('data/index.html',data);injectAssets('data/index.html')}catch{}
try{const s=json('data/search-index.json',[]);if(!s.some(x=>x.url===`${BASE}/data/publisher-readiness/`))s.push({title:'퍼블리셔 준비도',url:`${BASE}/data/publisher-readiness/`,type:'데이터',description:'Thin 콘텐츠, 정책 페이지, 출처 분리, 내부링크, 구조화데이터 상태 감사',keywords:['애드센스 콘텐츠 품질','사이트 품질 점검','thin content 점검']});write('data/search-index.json',JSON.stringify(s,null,2))}catch{}
try{let sm=read('sitemap.xml');const u=`${SITE}/data/publisher-readiness/`;if(!sm.includes(`<loc>${u}</loc>`))sm=sm.replace('</urlset>',`<url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap.xml',sm)}catch{}

const report=json('data/v6-report.json',{});Object.assign(report,{version:VERSION,v9_bulk_batch:true,v9_editorial_redesign:true,v9_public_unit_topics:true,v9_public_unit_topic_count:groups.length,v9_pyeong_data_boards:true,v9_trade_data_boards:true,v9_compare_matrix:true,v9_search_clusters:true,v9_thin_zero:a.thin.length===0,v9_publisher_readiness:true,v9_policy_pages_complete:quality.policy_pages_present===quality.policy_pages_expected,v9_preview_noindex_all:quality.preview_noindex_pages===quality.pages,v9_assets_injected:true,home_version_consistent:true});write('data/v6-report.json',JSON.stringify(report,null,2));
if(groups.length<9||items.length<60||a.thin.length!==0||a.duplicate_titles.length||a.duplicate_h1.length||quality.policy_pages_present!==quality.policy_pages_expected||quality.preview_noindex_pages!==quality.pages)throw new Error(`v9 quality gate failed ${JSON.stringify({groups:groups.length,items:items.length,thin:a.thin.map(x=>x.rel),titles:a.duplicate_titles,h1:a.duplicate_h1,policy:quality.policy_pages_present,noindex:[quality.preview_noindex_pages,quality.pages]})}`);
console.log(JSON.stringify({version:VERSION,build,groups:groups.length,items:items.length,pages:quality.pages,thin_before:quality.thin_before,thin_after:quality.pages_under_500_text_chars,structured:quality.structured_data_ratio,internal_links:quality.average_internal_links},null,2));
