import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='6.2.0';
const cost={month:'2026-07',value:138.59,yoy:5.78,published:'2026-08-28',source:'KICT'};
const wage={period:'2026-H2',daily_average:282737,yoy:1.40,half_change:0.98,occupations:132,published:'2026-09-01',source:'대한건설협회'};
const repair=[{scope:'경보수',amount:590,cycle:'3년'},{scope:'중보수',amount:1095,cycle:'5년'},{scope:'대보수',amount:1601,cycle:'7년'}];
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)},json=r=>JSON.parse(read(r)),fmt=n=>Number(n).toLocaleString('ko-KR');
const reviewed=(()=>{try{return json('data/v5-report.json').reviewed_on}catch{return new Date().toISOString().slice(0,10)}})();
const quoteCount=(()=>{try{return json('data/quote-samples.json').length}catch{return 0}})();
const css=fs.readFileSync(path.join(CORE,'site-v6-2.css'),'utf8'),cssHash=crypto.createHash('sha1').update(css).digest('hex').slice(0,10);write('assets/site-v6-2.css',css);

const snapshot=`<section class="v62-snapshot"><div class="v62-snapshot-head"><strong>현재 원가 환경</strong><span>OFFICIAL + QUOTE STATUS · ${reviewed}</span></div><div class="v62-snapshot-grid"><div><span>건설공사비지수</span><b>${cost.value}</b><em>${cost.month} · 2020=100</em></div><div><span>공사비 전년동월</span><b>+${cost.yoy.toFixed(2)}%</b><em>${cost.source}</em></div><div><span>건설업 일평균임금</span><b>${fmt(wage.daily_average)}원</b><em>${wage.period} · ${wage.occupations}개 직종</em></div><div><span>실제 견적 표본</span><b>${quoteCount}건</b><em>시장 통계 비노출</em></div></div><div class="v62-snapshot-foot"><span>공식 원가 지표와 민간 인테리어 견적은 같은 데이터가 아닙니다.</span><span><a href="${BASE}/data/">데이터 허브</a> · <a href="${BASE}/quote-compare/">내 견적 비교</a></span></div></section>`;
for(const size of [24,30,32,34,40]){const r=`interior-cost/${size}-pyeong/index.html`;let h=read(r);if(!h.includes('v62-snapshot'))h=h.replace('<article class="article-body">',`<article class="article-body">${snapshot}`);write(r,h)}

const template=read('data/construction-wage/index.html'),header=template.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=template.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',styles=[...template.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scripts=[...template.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const desc='건설공사비지수, 건설업 임금, 2026 공공 수선기준, 실제 견적 표본 상태를 한 화면에서 확인하는 인테리어 비용 데이터 허브입니다.';
const schema={'@context':'https://schema.org','@type':'Dataset',name:'인테리어 비용 공식 데이터 스냅샷',description:desc,dateModified:reviewed,distribution:{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE}/data/official-snapshot.json`}};
const dataPage=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 비용 데이터 | 공사비·임금·수선 기준</title><meta name="description" content="${desc}"><link rel="canonical" href="${SITE}/data/">${styles}<script type="application/ld+json">${JSON.stringify(schema)}</script></head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">DATA HUB</p><h1>인테리어 비용 데이터</h1><p>시장평균처럼 섞지 않고 공식 원가 지표, 공공 수선 기준, 사용자 견적 표본 상태를 데이터 종류별로 분리합니다.</p></div></section><section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>현재 스냅샷</h2><p>검수 ${reviewed} · 데이터 v${VERSION}</p></div><table class="v62-data-table"><thead><tr><th>데이터</th><th>현재 값</th><th>기준</th><th>사용 범위</th></tr></thead><tbody><tr><th>건설공사비지수</th><td><b>${cost.value}</b><small>전년동월 +${cost.yoy.toFixed(2)}%</small></td><td>${cost.month}<small>2020=100</small></td><td>건설 직접공사비 가격변동</td></tr><tr><th>건설업 평균임금</th><td><b>${fmt(wage.daily_average)}원/일</b><small>전년동기 +${wage.yoy.toFixed(2)}%</small></td><td>${wage.period}<small>${wage.occupations}개 직종</small></td><td>건설업 전체 임금 수준</td></tr><tr><th>공공 수선 기준</th><td><b>590 · 1,095 · 1,601만원</b><small>경·중·대보수</small></td><td>2026<small>3 · 5 · 7년</small></td><td>주거급여 수선유지급여</td></tr><tr><th>실제 견적 표본</th><td><b>${quoteCount}건</b><small>시장 통계 비노출</small></td><td>현재</td><td>표준화 표본 확보 전 평균 미표시</td></tr></tbody></table><p class="v6-index-note"><a class="v62-json" href="${BASE}/data/official-snapshot.json">official-snapshot.json</a></p></div></section><section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>세부 데이터</h2><p>독립 URL · 출처 · 적용범위</p></div><div class="v62-data-links"><a href="${BASE}/data/cost-index/"><strong>건설공사비지수</strong><span>2026년 1~7월 월별 추이</span></a><a href="${BASE}/data/construction-wage/"><strong>건설업 임금</strong><span>132개 직종 일평균임금</span></a><a href="${BASE}/data/sources/"><strong>출처 레지스트리</strong><span>기관·게시일·적용/제외 범위</span></a><a href="${BASE}/data/methodology/"><strong>산출 기준</strong><span>OFFICIAL / QUOTE / CALCULATED</span></a><a href="${BASE}/quote-items/"><strong>견적 항목 사전</strong><span>22개 공종·별칭·확인조건</span></a><a href="${BASE}/calculator/"><strong>예산·지수 환산</strong><span>사용자 입력 기반 계산</span></a></div></div></section></main>${footer}${scripts}</body></html>`;write('data/index.html',dataPage);
write('data/official-snapshot.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,official:{construction_cost_index:cost,construction_wage:wage,repair_support:{year:2026,unit:'만원',standards:repair}},quote_data:{sample_count:quoteCount,statistics_visible:false,reason:'표준화된 실제 견적 표본 부족'},rules:['공식 원가 지표를 민간 인테리어 시장평균으로 표시하지 않는다','표본 없는 평균·중앙값·P25/P75를 생성하지 않는다']},null,2));

let home=read('index.html');home=home.replace(/데이터 v6\.0\.0/g,`데이터 v${VERSION}`).replace(/데이터 v6\.1\.0/g,`데이터 v${VERSION}`);write('index.html',home);
try{const latest=json('data/latest.json');latest.version=VERSION;latest.updated=reviewed;latest.official_snapshot=`${BASE}/data/official-snapshot.json`;write('data/latest.json',JSON.stringify(latest,null,2))}catch{}
try{const versions=json('data/versions.json');if(!versions.some(x=>x.version===VERSION))versions.unshift({version:VERSION,date:reviewed,changes:['데이터 허브 추가','공식 스냅샷 JSON 추가','평수별 공식 원가환경 스냅샷','홈 버전 표기 정합성 수정']});write('data/versions.json',JSON.stringify(versions,null,2))}catch{}
try{const s=json('data/search-index.json');if(!s.some(x=>x.url===`${BASE}/data/`))s.push({title:'인테리어 비용 데이터',url:`${BASE}/data/`,type:'데이터',description:desc,keywords:['인테리어 비용 데이터','공사비지수','건설업 임금','수선 기준']});write('data/search-index.json',JSON.stringify(s,null,2))}catch{}
try{let s=read('sitemap-production.xml'),u=`${SITE}/data/`;if(!s.includes(u))s=s.replace('</urlset>',`<url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap-production.xml',s)}catch{}

const html=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);e.isDirectory()?walk(f):e.name.endsWith('.html')&&html.push(f)}};walk(ROOT);
for(const f of html){let h=fs.readFileSync(f,'utf8');if(!h.includes('site-v6-2.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v6-2.css?v=${cssHash}"></head>`);const guide=`<a href="${BASE}/guides/">가이드</a>`;const data=`<a href="${BASE}/data/">데이터</a>`;if(h.includes(guide)&&!h.includes(data))h=h.split(guide).join(guide+data);fs.writeFileSync(f,h)}
const report=json('data/v6-report.json');Object.assign(report,{version:VERSION,data_hub_page:fs.existsSync(path.join(ROOT,'data/index.html')),official_snapshot_json:fs.existsSync(path.join(ROOT,'data/official-snapshot.json')),pyeong_snapshots:[24,30,32,34,40].every(x=>read(`interior-cost/${x}-pyeong/index.html`).includes('v62-snapshot')),home_version_consistent:read('index.html').includes(`데이터 v${VERSION}`),v62_assets_injected:html.every(f=>fs.readFileSync(f,'utf8').includes('site-v6-2.css'))});write('data/v6-report.json',JSON.stringify(report,null,2));if(!report.data_hub_page||!report.official_snapshot_json||!report.pyeong_snapshots||!report.home_version_consistent||!report.v62_assets_injected)throw new Error(`v6.2 validation failed ${JSON.stringify(report)}`);console.log(JSON.stringify(report,null,2));
