import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='6.6.0';
const PUBLIC_N=30,SEGMENT_N=20;
const required=['sample_id','quote_month','region_level1','supply_pyeong','building_type','scope','bathroom_count','window_scope','vat_state','waste_state','total_amount_manwon'];
const optional=['exclusive_pyeong','demolition_manwon','waste_manwon','waterproof_manwon','bathroom_manwon','kitchen_manwon','wallpaper_manwon','flooring_manwon','carpentry_manwon','electrical_manwon','window_manwon','management_manwon'];
const headers=[...required,...optional];
const fieldRows=[
 ['sample_id','필수','영문·숫자·_- 3~40자','익명 표본 ID. 이름·업체명 금지'],['quote_month','필수','YYYY-MM','정확한 계약일 대신 월 단위'],['region_level1','필수','17개 시도 약칭','상세 주소 수집 금지'],['supply_pyeong','필수','5~100','공급면적 평'],['exclusive_pyeong','선택','0~100','전용면적 평'],['building_type','필수','아파트 / 빌라 / 주택','건물 유형'],['scope','필수','올수리 / 부분','공사 범위'],['bathroom_count','필수','0~5 정수','욕실 개수'],['window_scope','필수','전체 / 부분 / 제외 / 미기재','샷시 범위'],['vat_state','필수','포함 / 별도 / 미기재','VAT 조건'],['waste_state','필수','포함 / 별도 / 미기재','폐기물 조건'],['total_amount_manwon','필수','0 초과','견적 총액, 만원'],['*_manwon','선택','0 이상','공종별 금액. 미기재면 공란']
];
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)},json=r=>JSON.parse(read(r));
const reviewed=(()=>{try{return json('data/v5-report.json').reviewed_on}catch{return new Date().toISOString().slice(0,10)}})();
const quoteCount=(()=>{try{return json('data/quote-samples.json').length}catch{return 0}})();
const css=fs.readFileSync(path.join(CORE,'site-v6-6.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v6-6.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v6-6.css',css);write('assets/app-v6-6.js',js);

const schema={
 '$schema':'https://json-schema.org/draft/2020-12/schema',
 '$id':`${SITE}/data/quote-sample-schema.json`,
 title:'Anonymized interior quote sample',type:'object',additionalProperties:false,required,
 properties:{
  sample_id:{type:'string',pattern:'^[A-Za-z0-9_-]{3,40}$'},quote_month:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'},
  region_level1:{enum:['서울','부산','대구','인천','광주','대전','울산','세종','경기','강원','충북','충남','전북','전남','경북','경남','제주']},
  supply_pyeong:{type:'number',minimum:5,maximum:100},exclusive_pyeong:{type:['number','null'],minimum:0,maximum:100},building_type:{enum:['아파트','빌라','주택']},scope:{enum:['올수리','부분']},bathroom_count:{type:'integer',minimum:0,maximum:5},window_scope:{enum:['전체','부분','제외','미기재']},vat_state:{enum:['포함','별도','미기재']},waste_state:{enum:['포함','별도','미기재']},total_amount_manwon:{type:'number',exclusiveMinimum:0,maximum:100000}
 }
};
for(const f of optional.filter(x=>x.endsWith('_manwon')))schema.properties[f]={type:['number','null'],minimum:0,maximum:100000};
write('data/quote-sample-schema.json',JSON.stringify(schema,null,2));
const template=[headers.join(','),['Q0001','2026-08','서울','32','25.7','아파트','올수리','2','제외','포함','포함','5200','','','','900','850','320','450','','','','','',''].slice(0,headers.length).join(',')].join('\n');write('data/quote-sample-template.csv','\ufeff'+template+'\n');
const policy={version:VERSION,reviewed_on:reviewed,publication:{distribution_min_n:PUBLIC_N,segment_min_n:SEGMENT_N,metrics:['median','p25','p75'],mean_published:false},privacy:{allowed_geography:'시도만',forbidden_fields:['이름','전화번호','이메일','상세주소','업체명','사업자번호','계좌','서명'],server_upload:false},validation:{unknown_columns:'reject',duplicate_sample_id:'reject',invalid_enum:'reject'},note:'N 기준은 사이트의 보수적 편집 공개 정책이며 통계학적 보편 기준을 뜻하지 않는다.'};write('data/quote-publication-policy.json',JSON.stringify(policy,null,2));
const stats={version:VERSION,reviewed_on:reviewed,sample_count:quoteCount,status:quoteCount>=PUBLIC_N?'eligible_for_distribution':'withheld',publication_threshold:PUBLIC_N,segment_threshold:SEGMENT_N,metrics_visible:quoteCount>=PUBLIC_N?['median','p25','p75']:[],reason:quoteCount>=PUBLIC_N?'검수 통과 표본 수 기준 충족':'검수 통과 실제 견적 표본 수가 공개 기준 미만',statistics:{}};write('data/quote-statistics.json',JSON.stringify(stats,null,2));

const templatePage=read('data/index.html'),header=templatePage.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=templatePage.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',styles=[...templatePage.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scripts=[...templatePage.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const desc='익명 인테리어 견적 CSV를 브라우저에서 검증·표준화하고, 표본 공개 기준을 충족할 때만 중앙값·P25·P75 통계를 여는 데이터 파이프라인입니다.';
const datasetSchema={'@context':'https://schema.org','@type':'Dataset',name:'인테리어 익명 견적 표본 스키마',description:desc,dateModified:reviewed,distribution:[{'@type':'DataDownload',encodingFormat:'application/schema+json',contentUrl:`${SITE}/data/quote-sample-schema.json`},{'@type':'DataDownload',encodingFormat:'text/csv',contentUrl:`${SITE}/data/quote-sample-template.csv`},{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE}/data/quote-statistics.json`}],measurementTechnique:'표준 공종·포함조건 정규화 후 검수'};
const fieldTable=fieldRows.map(r=>`<tr><th><code>${r[0]}</code></th><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('');
const pipeline=`<section class="v66-pipeline" data-v66-pipeline><div class="v66-pipeline-head"><h2>CSV 검증 · 표준화</h2><p>LOCAL ONLY · 붙여넣은 데이터는 서버로 전송하지 않습니다. 허용 헤더 외 열은 거부해 개인정보·업체 식별정보가 섞이는 것을 막습니다.</p></div><div class="v66-policy"><div><span>현재 공개 표본</span><strong>${quoteCount}건</strong><em>현재 통계 ${quoteCount>=PUBLIC_N?'공개 가능':'보류'}</em></div><div><span>전체 분포 공개</span><strong>N ≥ ${PUBLIC_N}</strong><em>중앙값 · P25 · P75</em></div><div><span>세그먼트 공개</span><strong>N ≥ ${SEGMENT_N}</strong><em>시도·평수·범위별 각 셀</em></div></div><div class="v66-upload-grid"><div class="v66-csv-area"><label for="v66-csv">CSV 붙여넣기</label><textarea id="v66-csv" data-v66-csv spellcheck="false" placeholder="quote-sample-template.csv 형식으로 붙여넣기"></textarea><div class="v66-actions"><button type="button" data-v66-validate>검증</button><button type="button" data-v66-example>예시 넣기</button><button type="button" data-v66-export disabled>검증 행 JSON 저장</button><a href="${BASE}/data/quote-sample-template.csv">CSV 템플릿</a><a href="${BASE}/data/quote-sample-schema.json">JSON Schema</a></div></div><aside class="v66-result"><div><span>검수 통과</span><strong data-v66-valid>0건</strong></div><div><span>오류 행</span><strong data-v66-invalid>0건</strong></div><div><span>통계 상태</span><strong data-v66-status>통계 보류</strong><p data-v66-status-note>검증 전입니다.</p></div></aside></div><div class="v66-errors"><h3>검증 메시지</h3><ul data-v66-errors></ul></div><section class="v66-stat-preview" data-v66-stat-preview hidden><h3>로컬 통계 미리보기</h3><div class="v66-stat-grid"><div><span>N</span><strong data-v66-n>—</strong></div><div><span>P25</span><strong data-v66-p25>—</strong></div><div><span>중앙값</span><strong data-v66-median>—</strong></div><div><span>P75</span><strong data-v66-p75>—</strong></div></div><p class="v66-withheld">이 미리보기는 사용자의 브라우저 안에서만 계산되며 사이트의 공개 통계로 저장되지 않습니다.</p></section></section>`;
const page=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 견적 데이터 파이프라인 | 익명 CSV 검증</title><meta name="description" content="${desc}"><link rel="canonical" href="${SITE}/data/quote-pipeline/">${styles}<script type="application/ld+json">${JSON.stringify(datasetSchema)}</script></head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">QUOTE DATA PIPELINE</p><h1>익명 견적 데이터 파이프라인</h1><p>실제 민간 견적 통계를 만들기 전에 입력 형식·개인정보·포함조건부터 고정합니다. 표본이 부족한 동안 공개 통계는 계속 숨깁니다.</p></div></section><section class="v6-section"><div class="site-shell">${pipeline}</div></section><section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>표본 스키마</h2><p>상세 주소·업체명·연락처 열은 허용하지 않음</p></div><div class="table-wrap"><table class="v66-schema-table"><thead><tr><th>필드</th><th>필수</th><th>형식</th><th>설명</th></tr></thead><tbody>${fieldTable}</tbody></table></div></div></section><section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>공개 규칙</h2><p>사이트 편집 정책 · 통계학적 보편 기준 아님</p></div><table class="v6-status-table"><tbody><tr><td class="v6-status-ok">N ≥ ${PUBLIC_N}</td><td>전체 유효 표본의 중앙값·P25·P75 공개 가능</td></tr><tr><td class="v6-status-ok">N ≥ ${SEGMENT_N}</td><td>시도·평수·공사범위 등 각 세그먼트 셀 공개 가능</td></tr><tr><td class="v6-status-empty">N 미달</td><td>건수만 표시하고 가격 통계는 보류</td></tr><tr><td class="v6-status-empty">항상 제외</td><td>평균값, 업체명 순위, 상세주소, 개인 식별정보</td></tr></tbody></table><p class="v6-index-note"><a href="${BASE}/data/quote-publication-policy.json">공개 정책 JSON</a> · <a href="${BASE}/data/quote-statistics.json">현재 통계 상태 JSON</a></p></div></section></main>${footer}${scripts}</body></html>`;write('data/quote-pipeline/index.html',page);

let data=read('data/index.html');data=data.replace(/데이터 v6\.5\.0/g,`데이터 v${VERSION}`);if(!data.includes('/data/quote-pipeline/'))data=data.replace('<div class="v62-data-links">',`<div class="v62-data-links"><a href="${BASE}/data/quote-pipeline/"><strong>실제 견적 데이터 파이프라인</strong><span>익명 CSV 검증 · 표본 공개 기준 · N=${quoteCount}</span></a>`);write('data/index.html',data);
let home=read('index.html');home=home.replace(/데이터 v6\.5\.0/g,`데이터 v${VERSION}`);write('index.html',home);
try{const latest=json('data/latest.json');latest.version=VERSION;latest.updated=reviewed;latest.quote_pipeline={sample_count:quoteCount,distribution_min_n:PUBLIC_N,segment_min_n:SEGMENT_N,statistics_status:stats.status,schema:`${BASE}/data/quote-sample-schema.json`};write('data/latest.json',JSON.stringify(latest,null,2))}catch{}
try{const versions=json('data/versions.json');if(!versions.some(x=>x.version===VERSION))versions.unshift({version:VERSION,date:reviewed,changes:['익명 견적 CSV 스키마','브라우저 로컬 검증기','개인정보 열 거부','표본 N 기준 공개 게이트','중앙값·P25·P75 로컬 미리보기']});write('data/versions.json',JSON.stringify(versions,null,2))}catch{}
try{const search=json('data/search-index.json');if(!search.some(x=>x.url===`${BASE}/data/quote-pipeline/`))search.push({title:'인테리어 견적 데이터 파이프라인',url:`${BASE}/data/quote-pipeline/`,type:'데이터',description:desc,keywords:['인테리어 견적 데이터','견적 평균 데이터','인테리어 견적 통계','견적 CSV','견적 중앙값']});write('data/search-index.json',JSON.stringify(search,null,2))}catch{}
try{let s=read('sitemap-production.xml'),u=`${SITE}/data/quote-pipeline/`;if(!s.includes(u))s=s.replace('</urlset>',`<url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap-production.xml',s)}catch{}

const html=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);e.isDirectory()?walk(f):e.name.endsWith('.html')&&html.push(f)}};walk(ROOT);for(const f of html){let h=fs.readFileSync(f,'utf8');if(!h.includes('site-v6-6.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v6-6.css?v=${build}"></head>`);if(!h.includes('app-v6-6.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v6-6.js?v=${build}" defer></script></body>`);fs.writeFileSync(f,h)}
const report=json('data/v6-report.json');Object.assign(report,{version:VERSION,quote_pipeline_page:fs.existsSync(path.join(ROOT,'data/quote-pipeline/index.html')),quote_schema_json:fs.existsSync(path.join(ROOT,'data/quote-sample-schema.json')),quote_template_csv:fs.existsSync(path.join(ROOT,'data/quote-sample-template.csv')),quote_publication_policy:fs.existsSync(path.join(ROOT,'data/quote-publication-policy.json')),quote_statistics_gate:stats.status==='withheld'&&stats.sample_count===quoteCount,privacy_column_rejection:js.includes('허용하지 않는 열')&&js.includes('개인정보/업체명 열'),local_stat_threshold:js.includes('PUBLIC_N=30')&&js.includes('SEGMENT_N=20'),home_version_consistent:read('index.html').includes(`데이터 v${VERSION}`),v66_assets_injected:html.every(f=>{const h=fs.readFileSync(f,'utf8');return h.includes('site-v6-6.css')&&h.includes('app-v6-6.js')})});write('data/v6-report.json',JSON.stringify(report,null,2));if(!report.quote_pipeline_page||!report.quote_schema_json||!report.quote_template_csv||!report.quote_publication_policy||!report.quote_statistics_gate||!report.privacy_column_rejection||!report.local_stat_threshold||!report.home_version_consistent||!report.v66_assets_injected)throw new Error(`v6.6 validation failed ${JSON.stringify(report)}`);console.log(JSON.stringify(report,null,2));
