import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',VERSION='6.4.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)},json=r=>JSON.parse(read(r));
const reviewed=(()=>{try{return json('data/v5-report.json').reviewed_on}catch{return new Date().toISOString().slice(0,10)}})();
const unitData=json('data/public-unit-cost-2026-h2.json');
const css=fs.readFileSync(path.join(CORE,'site-v6-4.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v6-4.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v6-4.css',css);write('assets/app-v6-4.js',js);

function refCalculator({saved=true}={}){return `<section class="v64-refcalc" id="public-reference" data-v64-unit-ref><div class="v64-refcalc-head"><h2>공공 공종 참고 계산</h2><p>REFERENCE · 2026 하반기 표준시장단가 × 직접 입력 수량. 민간 아파트 시장가격이나 적정견적 판정값이 아닙니다.</p></div><div class="v64-refcalc-grid"><label>공종<select data-v64-item aria-label="공공 참고 공종"></select></label><label>수량<input data-v64-qty type="number" min="0" step="0.1" inputmode="decimal" placeholder="10"></label><label>기준 단가<input data-v64-unit-price readonly aria-label="기준 단가"></label></div><dl class="v64-ref-meta"><dt>세부코드</dt><dd><span class="v64-ref-code" data-v64-code>—</span></dd><dt>규격</dt><dd data-v64-spec>—</dd><dt>포함 작업</dt><dd data-v64-scope>—</dd><dt>제외 조건</dt><dd data-v64-exclude>—</dd><dt>노무비율</dt><dd data-v64-labor>—</dd></dl><div class="v64-ref-result"><div><span>공공 기준 소계</span><strong data-v64-result>수량 입력</strong><em><span data-v64-result-won>공공 기준 단가 × 수량</span> · 단위 <span data-v64-unit>—</span></em></div><div class="v64-ref-actions">${saved?'<button type="button" data-v64-add>참고합계에 추가</button>':''}<button type="button" data-v64-copy>계산근거 복사</button><a href="#" data-v64-source rel="noopener">원 항목 조건</a></div></div>${saved?'<div class="v64-ref-saved"><h3>REFERENCE 참고합계</h3><div class="v64-ref-saved-list" data-v64-saved-list></div><div class="v64-ref-saved-total"><span>저장한 공공 참고계산 합계</span><strong data-v64-saved-total>0만원</strong></div><p class="v64-ref-warning">이 합계는 위의 사용자 예산 합계와 분리됩니다. 서로 다른 세부 공정을 중복 저장하면 중복 합산될 수 있습니다.</p></div>':'<p class="v64-ref-warning">공공 건설 예정가격 참고용 단가입니다. 현장 최소작업량·철거·양중·보양·관리비·주재료비가 별도일 수 있습니다.</p>'}</section>`}

let calc=read('calculator/index.html');if(!calc.includes('data-v64-unit-ref'))calc=calc.replace('<article class="tool-article">',`${refCalculator({saved:true})}<article class="tool-article">`);calc=calc.replace('수량 × 입력 단가 · VAT · 공식 공사비지수 환산','수량 × 입력 단가 · VAT · 공사비지수 · 공공 공종 참고계산');write('calculator/index.html',calc);
let unit=read('data/public-unit-cost/index.html');if(!unit.includes('data-v64-unit-ref'))unit=unit.replace('<section class="v6-section">',`<section class="v6-section"><div class="site-shell">${refCalculator({saved:false})}</div></section><section class="v6-section">`);for(const item of unitData.items||[]){const old=`<a href="${item.detail}" rel="noopener">조건</a>`;const next=`<a href="${item.detail}" rel="noopener">조건</a><br><a href="${BASE}/calculator/?ref=${encodeURIComponent(item.code)}#public-reference">계산</a>`;unit=unit.split(old).join(next)}write('data/public-unit-cost/index.html',unit);

let data=read('data/index.html');data=data.replace(/데이터 v6\.3\.0/g,`데이터 v${VERSION}`);if(!data.includes('공공단가 × 수량'))data=data.replace(`<a href="${BASE}/calculator/"><strong>예산·지수 환산</strong><span>사용자 입력 기반 계산</span></a>`,`<a href="${BASE}/calculator/"><strong>예산·지수·공공단가 계산</strong><span>사용자 입력 · 공사비지수 · 공공단가 × 수량</span></a>`);write('data/index.html',data);
let home=read('index.html');home=home.replace(/데이터 v6\.3\.0/g,`데이터 v${VERSION}`);write('index.html',home);
try{const latest=json('data/latest.json');latest.version=VERSION;latest.updated=reviewed;latest.reference_calculator={source:`${BASE}/data/public-unit-cost-2026-h2.json`,mode:'quantity_x_public_unit_cost',included_in_budget_total:false};write('data/latest.json',JSON.stringify(latest,null,2))}catch{}
try{const versions=json('data/versions.json');if(!versions.some(x=>x.version===VERSION))versions.unshift({version:VERSION,date:reviewed,changes:['공공 공종 참고계산기','단가 JSON 직접 로딩','REFERENCE 참고합계 분리 저장','공종 단가→계산기 딥링크']});write('data/versions.json',JSON.stringify(versions,null,2))}catch{}
try{const search=json('data/search-index.json');const row=search.find(x=>x.url===`${BASE}/calculator/`);if(row){row.keywords=[...(row.keywords||[]),'타일 단가 계산','방수 단가 계산','도배 단가 계산','공공 공종 단가 계산'];row.description='사용자 입력 예산, 공사비지수 환산, 2026 하반기 공공 공종 단가 × 수량 참고계산을 제공합니다.'}write('data/search-index.json',JSON.stringify(search,null,2))}catch{}

const html=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);e.isDirectory()?walk(f):e.name.endsWith('.html')&&html.push(f)}};walk(ROOT);for(const f of html){let h=fs.readFileSync(f,'utf8');if(!h.includes('site-v6-4.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v6-4.css?v=${build}"></head>`);if(!h.includes('app-v6-4.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v6-4.js?v=${build}" defer></script></body>`);fs.writeFileSync(f,h)}
const report=json('data/v6-report.json');Object.assign(report,{version:VERSION,public_reference_calculator:read('calculator/index.html').includes('data-v64-unit-ref'),public_reference_json_fetch:js.includes('public-unit-cost-2026-h2.json'),reference_total_separate:read('calculator/index.html').includes('REFERENCE 참고합계'),unit_cost_deep_links:read('data/public-unit-cost/index.html').includes('/calculator/?ref='),home_version_consistent:read('index.html').includes(`데이터 v${VERSION}`),v64_assets_injected:html.every(f=>{const h=fs.readFileSync(f,'utf8');return h.includes('site-v6-4.css')&&h.includes('app-v6-4.js')})});write('data/v6-report.json',JSON.stringify(report,null,2));if(!report.public_reference_calculator||!report.public_reference_json_fetch||!report.reference_total_separate||!report.unit_cost_deep_links||!report.home_version_consistent||!report.v64_assets_injected)throw new Error(`v6.4 validation failed ${JSON.stringify(report)}`);console.log(JSON.stringify(report,null,2));
