import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='12.0.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8');
const write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)};
const json=(r,fallback={})=>{try{return JSON.parse(read(r))}catch{return fallback}};
const reviewed=json('data/v5-report.json',{}).reviewed_on||new Date().toISOString().slice(0,10);
const quote=json('data/quote-statistics.json',{sample_count:0,publication_threshold:30,segment_threshold:20,segments:{}}),health=json('data/quote-data-health.json',{trade_field_counts:{}}),coverage=json('data/quote-coverage-v11.json',{region_pyeong:{cells:[]},trade_fields:{cells:[]},regions:{cells:[]},pyeongs:{cells:[]}}),regionMap=json('data/region-pyeong-map.json',{routes:[]}),baseAnswers=json('data/answer-index-v11.json',{answers:[]}),queryMap=json('data/query-map.json',{queries:[]}),sourceFresh=json('data/source-freshness-v11.json',{update_required:false,sources:[]});
const css=fs.readFileSync(path.join(CORE,'site-v12.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v12.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v12.css',css);write('assets/app-v12.js',js);
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const strip=s=>String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[^;]+;/g,' ').replace(/\s+/g,' ').trim();
const fmt=n=>Number(n||0).toLocaleString('ko-KR',{maximumFractionDigits:1});
const overallN=quote.publication_threshold||30,segmentN=quote.segment_threshold||20;
const months=(quote.segments?.quote_month||[]).map(x=>({month:x.key,n:x.n})).sort((a,b)=>a.month.localeCompare(b.month));let cum=0;const growthRows=months.map(x=>({...x,cumulative:(cum+=x.n)}));
const sampleGrowth={version:VERSION,reviewed_on:reviewed,total_samples:quote.sample_count||0,publication_threshold:overallN,monthly:growthRows,latest_month:growthRows.at(-1)?.month||null,latest_cumulative:growthRows.at(-1)?.cumulative||0,raw_rows_public:false};write('data/sample-growth-v12.json',JSON.stringify(sampleGrowth,null,2));

const routeCells=(coverage.region_pyeong?.cells||[]).length?coverage.region_pyeong.cells:(regionMap.routes||[]).map(x=>({...x,n:x.sample_count||0,needed:Math.max(0,segmentN-(x.sample_count||0)),published:x.status==='published'}));
const targetRows=[...routeCells.map(x=>({type:'region_pyeong',key:x.key||`${x.region} · ${x.pyeong}평`,region:x.region,pyeong:x.pyeong,n:x.n||0,needed:x.needed??Math.max(0,segmentN-(x.n||0)),threshold:segmentN,status:x.published?'published':'withheld',url:`${BASE}/region/${x.region_slug||''}/`})),...(coverage.trade_fields?.cells||[]).map(x=>({type:'trade',key:`${x.label} 공종`,n:x.n||0,needed:x.needed??Math.max(0,segmentN-(x.n||0)),threshold:segmentN,status:x.published?'published':'withheld',url:`${BASE}/data/coverage/`}))].sort((a,b)=>a.status==='published'&&b.status!=='published'?1:b.status==='published'&&a.status!=='published'?-1:a.needed-b.needed||b.n-a.n||a.key.localeCompare(b.key,'ko'));
write('data/coverage-targets-v12.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,rule:'공개 기준까지 남은 표본 수 기준. 지역×평수와 공종 필드의 실측 N만 사용.',items:targetRows},null,2));

const batchContract={version:VERSION,reviewed_on:reviewed,client:{file_or_paste:true,server_upload:false,schema:`${BASE}/data/quote-sample-schema.json`,clean_export:'quote-batch-clean.csv'},validation:{blocking:['schema violation','unknown/privacy column','duplicate sample_id'],review_only:['potential duplicate signature','exclusive_pyeong > supply_pyeong','trade sum > total × 1.05','single trade > total','3×IQR per-pyeong outlier when N>=8'],market_price_rule:false},private_cli:'node interior-cost-core/audit-quote-batch-v12.mjs --input PRIVATE.csv --output /tmp/batch-audit.json',raw_rows_public:false};write('data/quote-batch-contract-v12.json',JSON.stringify(batchContract,null,2));
const contribution={version:VERSION,reviewed_on:reviewed,public_upload_endpoint:false,accepted_format:'anonymous CSV matching quote-sample-schema.json',forbidden_fields:['name','vendor_name','phone','email','detailed_address','business_number','account','signature'],workflow:['브라우저 로컬 입력 또는 CSV 정리','로컬/비공개 검증','중복·이상치 검토','비공개 원본 보관','집계만 public docs 생성','N 기준 통과 셀만 가격 공개'],publication:{overall_n:overallN,segment_n:segmentN,mean:false,raw_rows:false}};write('data/data-contribution-contract-v12.json',JSON.stringify(contribution,null,2));

const template=read('data/index.html'),header=template.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=template.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',styles=[...template.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scripts=[...template.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const head=(title,desc,url,schemaObj=null)=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${url}">${styles}${schemaObj?`<script type="application/ld+json">${JSON.stringify(schemaObj)}</script>`:''}</head><body>`;

const schemaProps=json('data/quote-sample-schema.json',{properties:{}}).properties||{},batchSchema={'@context':'https://schema.org','@type':'WebApplication',name:'인테리어 익명 견적 CSV 대량 검수',applicationCategory:'BusinessApplication',operatingSystem:'Web',description:'익명 견적 CSV를 브라우저에서 검증하고 중복·구조적 이상치를 분리한 뒤 정상 행만 다시 내보내는 도구',url:`${SITE}/quote-batch/`};
const exampleHeader=Object.keys(schemaProps).join(','),exampleRow=Object.keys(schemaProps).map(k=>({sample_id:'EXAMPLE_001',quote_month:'2026-09',region_level1:'서울',supply_pyeong:'32',exclusive_pyeong:'25.7',building_type:'아파트',scope:'올수리',bathroom_count:'2',window_scope:'제외',vat_state:'포함',waste_state:'포함',total_amount_manwon:'4500',bathroom_manwon:'850',kitchen_manwon:'780',wallpaper_manwon:'320',flooring_manwon:'430'}[k]??'')).join(',');
write('quote-batch/index.html',`${head('인테리어 견적 CSV 대량 검수 | 중복·이상치 확인','익명 견적 CSV를 브라우저에서 검증하고 개인정보 열·필수값·중복·구조적 이상치를 확인한 뒤 정상 행만 다시 내보냅니다.',`${SITE}/quote-batch/`,batchSchema)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">LOCAL BATCH QA</p><h1>견적 CSV 대량 검수</h1><p>서버 업로드 없음 · 개인정보 열 차단 · 정상/검토/차단 분리 · 정상 행만 재내보내기</p></div></section><section class="v12-section"><div class="site-shell"><div class="v12-section-head"><div><h2>CSV 불러오기</h2><p>공개 스키마와 같은 열만 허용합니다. 이상치 검토는 시장가 판정이 아니라 데이터셋 내부·구조적 모순 확인입니다.</p></div></div><div class="v12-batch" data-v12-batch><div class="v12-batch-input"><textarea data-v12-batch-text spellcheck="false" placeholder="${esc(exampleHeader+'\n'+exampleRow)}"></textarea><div class="v12-batch-actions"><input data-v12-batch-file type="file" accept=".csv,text/csv"><button type="button" data-v12-batch-run>검증</button><button type="button" class="secondary" data-v12-batch-export disabled>정상 행 CSV</button></div></div><p class="v12-batch-msg" data-v12-batch-msg>CSV를 붙여넣거나 파일을 선택하세요.</p><div class="table-wrap"><table class="v12-batch-table"><thead><tr><th>행</th><th>sample_id</th><th>상태</th><th>사유</th><th>조건</th></tr></thead><tbody data-v12-batch-body><tr><td colspan="5">검증 전</td></tr></tbody></table></div></div><p>동일 sample_id는 차단합니다. 다른 ID라도 월·지역·평수·주택유형·범위·욕실·창호·VAT·폐기물·총액 조합이 같으면 중복 의심으로 검토합니다. 전용평수가 공급평수보다 큰 경우, 공종별 금액 합이 총액보다 큰 경우도 검토 대상으로 표시합니다. 이 상태만으로 행을 자동 삭제하거나 시장에서 비싸고 싸다고 판단하지 않습니다.</p></div></section><section class="v12-section"><div class="site-shell"><h2>운영자 비공개 검사</h2><p>브라우저 도구는 1차 정리용입니다. 실제 집계 전에는 비공개 환경에서 <code>audit-quote-batch-v12.mjs</code>를 실행해 스키마, 잠재 중복, 구조적 검토 항목과 데이터셋 내부 3×IQR 이상치를 확인합니다. 감사 결과에는 검토용 sample_id가 포함될 수 있으므로 public docs에 저장하지 않습니다.</p><nav class="v10-actions"><a href="${BASE}/quote-intake/">익명 행 만들기</a><a href="${BASE}/data/contribute/">데이터 준비 기준</a><a href="${BASE}/data/coverage-targets/">표본 목표</a></nav></div></section></main>${footer}${scripts}</body></html>`);

const growthMax=Math.max(1,...growthRows.map(x=>x.n));const growthBars=growthRows.length?growthRows.map(x=>`<div class="v12-growth-col"><b>${x.n}</b><i style="height:${Math.max(2,Math.round(x.n/growthMax*120))}px"></i><span>${esc(x.month)}</span></div>`).join(''):`<div class="v12-growth-col"><b>0</b><i style="height:2px"></i><span>표본 없음</span></div>`;
write('data/sample-growth/index.html',`${head('인테리어 실제 견적 표본 증가 | 월별 데이터 현황','익명 검수 견적 표본이 월별로 얼마나 누적됐는지 확인합니다. 가격통계와 별개로 데이터 수집량을 공개합니다.',`${SITE}/data/sample-growth/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">SAMPLE GROWTH</p><h1>실제 견적 표본 증가</h1><p>QUOTE COUNT · 원본 행 비공개 · 월별 유효표본 수와 누적량</p></div></section><section class="v12-section"><div class="site-shell"><div class="v12-kpis"><div><span>현재 표본</span><strong>N=${quote.sample_count||0}</strong><em>검수 통과</em></div><div><span>전체 공개 기준</span><strong>N≥${overallN}</strong><em>가격 분포</em></div><div><span>남은 표본</span><strong>${Math.max(0,overallN-(quote.sample_count||0))}</strong><em>전체 분포 기준</em></div><div><span>기록 월</span><strong>${growthRows.length}</strong><em>quote_month</em></div><div><span>원본 공개</span><strong>안 함</strong><em>집계만 공개</em></div></div><div class="v12-growth" aria-label="월별 유효 견적 표본 수">${growthBars}</div><p>월별 막대는 가격이 아니라 검수 통과 견적 건수입니다. 표본이 늘어도 전체 N≥${overallN}, 지역·평수·공종 등 세부 셀 N≥${segmentN} 조건은 각각 별도로 적용합니다. 월별 건수가 많다는 이유만으로 특정 월 가격을 대표값으로 사용하지 않습니다.</p></div></section><section class="v12-section"><div class="site-shell"><h2>데이터가 쌓이면 바뀌는 것</h2><div class="v12-pipeline"><div><span>01</span><strong>행 검증</strong><p>익명 스키마와 중복을 확인</p></div><div><span>02</span><strong>집계</strong><p>원본 대신 N과 분포 생성</p></div><div><span>03</span><strong>N 게이트</strong><p>전체 30 · 세부 20</p></div><div><span>04</span><strong>커버리지</strong><p>지역×평수·공종 상태 갱신</p></div><div><span>05</span><strong>검색 후보</strong><p>N 충족 페이지만 운영 색인 후보</p></div><div><span>06</span><strong>AEO</strong><p>가격 질문 답변도 같은 게이트 사용</p></div></div></div></section></main>${footer}${scripts}</body></html>`);

const heatHead=`<div class="head">지역</div>${[24,30,32,34,40].map(p=>`<div class="head">${p}평</div>`).join('')}`;const regions=[...new Set(routeCells.map(x=>x.region))];const heatRows=regions.map(r=>`<div class="head">${esc(r)}</div>${[24,30,32,34,40].map(p=>{const x=routeCells.find(c=>c.region===r&&Number(c.pyeong)===p)||{n:0,needed:segmentN,published:false};return `<div class="cell"><span>N</span><strong>${x.n||0}</strong><em>${x.published?'공개 가능':`${x.needed??segmentN}건 필요`}</em></div>`}).join('')}`).join('');
const targetTable=targetRows.map(x=>`<tr data-v12-target-row data-search="${esc(x.key)}" data-state="${x.status}"><th>${esc(x.key)}</th><td>${x.type==='trade'?'공종':'지역×평수'}</td><td>${x.n}</td><td>${x.threshold}</td><td>${x.needed}</td><td class="${x.status==='published'?'v12-state-published':'v12-state-withheld'}">${x.status==='published'?'공개 가능':'보류'}</td></tr>`).join('');
write('data/coverage-targets/index.html',`${head('인테리어 견적 표본 목표 | 지역×평수·공종 공개까지 남은 N','지역×평수 85셀과 공종별 금액 필드가 공개 기준까지 몇 건 남았는지 실제 표본 N으로 확인합니다.',`${SITE}/data/coverage-targets/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">COVERAGE TARGETS</p><h1>표본 목표 보드</h1><p>지역×평수 85셀 · 공종 11필드 · 공개까지 남은 실제 N</p></div></section><section class="v12-section"><div class="site-shell"><div class="v12-section-head"><div><h2>17 × 5 커버리지</h2><p>각 셀 자체가 N≥${segmentN}이어야 가격분포를 공개할 수 있습니다.</p></div></div><div class="v12-heatmap">${heatHead}${heatRows}</div></div></section><section class="v12-section"><div class="site-shell" data-v12-targets><div class="v12-section-head"><div><h2>남은 표본 순</h2><p>검색량 추정이 아니라 공개 기준까지 남은 N으로 정렬합니다.</p></div></div><div class="v12-target-controls"><input data-v12-target-q placeholder="서울 32평 · 욕실"><select data-v12-target-state><option value="">전체</option><option value="withheld">보류</option><option value="published">공개 가능</option></select></div><div class="table-wrap"><table class="v12-targets"><thead><tr><th>셀</th><th>유형</th><th>N</th><th>기준</th><th>남음</th><th>상태</th></tr></thead><tbody>${targetTable}</tbody></table></div></div></section></main>${footer}${scripts}</body></html>`);

write('data/contribute/index.html',`${head('인테리어 견적 데이터 기여 준비 | 익명 CSV 기준','인테리어 실제 견적 데이터를 개인정보 없이 정리하고 비공개 검수 후 집계에 반영하는 절차와 필드 기준을 안내합니다.',`${SITE}/data/contribute/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">DATA CONTRIBUTION</p><h1>견적 데이터 준비 기준</h1><p>공개 업로드 엔드포인트 없음 · 익명 CSV · 원본 행 비공개 · 집계만 공개</p></div></section><section class="v12-section"><div class="site-shell"><div class="v12-contrib-grid"><article><h3>받는 정보</h3><p>견적 월, 시도, 공급·전용 평수, 주택유형, 올수리/부분, 욕실 수, 창호 범위, VAT·폐기물 상태, 총액과 선택적인 공종별 금액입니다. 실제 가격분포를 같은 조건으로 집계하는 데 필요한 최소 범위만 사용합니다.</p></article><article><h3>받지 않는 정보</h3><p>성명, 업체명, 전화번호, 이메일, 상세주소, 사업자번호, 계좌, 서명, 계약서 원본 식별정보는 스키마에 넣지 않습니다. 해당 열이 CSV에 있으면 비공개 감사 단계에서 차단합니다.</p></article><article><h3>현재 프리뷰에서의 전달</h3><p>공개 사이트에는 서버 제출 기능을 두지 않았습니다. <a href="${BASE}/quote-intake/">익명 행 만들기</a> 또는 <a href="${BASE}/quote-batch/">CSV 대량 검수</a>로 정리한 후 운영자가 승인한 비공개 수집 경로에서만 원본 CSV를 취급합니다.</p></article><article><h3>공개되는 것</h3><p>원본 행이 아니라 N, P25, 중앙값, P75와 커버리지 상태만 공개합니다. 전체 N≥${overallN}, 세부 셀 N≥${segmentN} 미만이면 가격은 보류합니다. 평균값과 업체 순위는 공개하지 않습니다.</p></article></div><nav class="v10-actions"><a href="${BASE}/data/quote-sample-template.csv">CSV 템플릿</a><a href="${BASE}/data/quote-sample-schema.json">JSON Schema</a><a href="${BASE}/data/coverage-targets/">필요 표본 보기</a><a href="${BASE}/data/quote-operations/">운영 절차</a></nav></div></section></main>${footer}${scripts}</body></html>`);

const walk=(dir=ROOT,out=[])=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())walk(f,out);else if(e.name.endsWith('.html'))out.push(path.relative(ROOT,f).replaceAll('\\','/'))}return out};
const regionPublished=new Set((coverage.regions?.cells||[]).filter(x=>x.published).map(x=>x.slug));
const operatorPrefixes=['quote-intake/','quote-batch/','data/coverage/','data/coverage-targets/','data/data-gaps/','data/quote-operations/','data/launch-readiness/','data/launch-gate-v11/','data/launch-gate-v12/','data/publisher-readiness/','data/source-freshness/','data/production-simulator/','data/ad-layout/'];
function prodDecision(rel){if(rel==='404.html'||rel==='search/index.html')return {indexable:false,reason:'오류/검색 내부 페이지'};if(operatorPrefixes.some(p=>rel.startsWith(p)))return {indexable:false,reason:'수집·운영·감사 내부 페이지'};const rm=rel.match(/^region\/([^/]+)\/index\.html$/);if(rm&&!regionPublished.has(rm[1]))return {indexable:false,reason:`지역 표본 N<${segmentN}`};if(rel.startsWith('region/')&&rel.split('/').length>3)return {indexable:true,reason:'지역×평수 셀 N 기준 통과로 생성된 페이지'};return {indexable:true,reason:'고유 도구·가이드·검증 데이터 페이지'}}
let allPages=walk();const prodRows=allPages.map(rel=>({path:rel,url:`${SITE}/${rel==='index.html'?'':rel.replace(/index\.html$/,'')}`,...prodDecision(rel)}));const indexable=prodRows.filter(x=>x.indexable);const productionPlan={version:VERSION,reviewed_on:reviewed,simulation_only:true,actual_preview_noindex_unchanged:true,total_pages:prodRows.length,indexable_count:indexable.length,noindex_count:prodRows.length-indexable.length,rules:{region_hub:`region N>=${segmentN}`,region_pyeong:`exact cell N>=${segmentN}`,operator_pages:false,error_search:false},pages:prodRows};write('data/production-index-plan-v12.json',JSON.stringify(productionPlan,null,2));
const robots=`# SIMULATION ONLY - not deployed as /robots.txt\nUser-agent: *\nAllow: /\nDisallow: ${BASE}/search/\nSitemap: ${SITE}/sitemap.xml\n`;write('data/robots-production-preview.txt',robots);const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${indexable.map(x=>`  <url><loc>${x.url}</loc><lastmod>${reviewed}</lastmod></url>`).join('\n')}\n</urlset>`;write('data/sitemap-production-preview.xml',sitemap);
const prodRowsHtml=prodRows.map(x=>`<tr data-v12-prod-row data-state="${x.indexable?'index':'noindex'}"><td><code>${esc(x.path)}</code></td><td class="${x.indexable?'v12-index-yes':'v12-index-no'}">${x.indexable?'INDEX':'NOINDEX'}</td><td>${esc(x.reason)}</td></tr>`).join('');
write('data/production-simulator/index.html',`${head('운영 색인 시뮬레이터 | robots·sitemap 전환 계획','현재 프리뷰의 noindex를 유지한 채 운영 전환 시 색인할 페이지와 제외할 페이지, robots·sitemap 결과를 미리 계산합니다.',`${SITE}/data/production-simulator/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">PRODUCTION SIMULATOR</p><h1>운영 색인 시뮬레이터</h1><p>실제 robots·sitemap 변경 없음 · 프리뷰 noindex 유지 · 운영 승인 전 계획만 생성</p></div></section><section class="v12-section"><div class="site-shell"><div class="v12-kpis"><div><span>전체 HTML</span><strong>${prodRows.length}</strong><em>현재 preview</em></div><div><span>운영 INDEX 후보</span><strong>${indexable.length}</strong><em>simulation</em></div><div><span>운영 NOINDEX</span><strong>${prodRows.length-indexable.length}</strong><em>ops/low-N</em></div><div><span>지역 공개 허브</span><strong>${regionPublished.size}</strong><em>N≥${segmentN}</em></div><div><span>실제 전환</span><strong>안 함</strong><em>승인 필요</em></div></div><div data-v12-prod-sim><div class="v12-prod-toolbar"><button data-v12-prod-filter="all">전체</button><button data-v12-prod-filter="index">INDEX</button><button data-v12-prod-filter="noindex">NOINDEX</button></div><div class="table-wrap"><table class="v12-prod-table"><thead><tr><th>페이지</th><th>운영 계획</th><th>이유</th></tr></thead><tbody>${prodRowsHtml}</tbody></table></div></div><p><a href="${BASE}/data/robots-production-preview.txt">robots 시뮬레이션</a> · <a href="${BASE}/data/sitemap-production-preview.xml">sitemap 시뮬레이션</a>. 이 두 파일은 <code>/data/</code> 아래 참고 산출물이며 실제 루트 robots.txt나 실제 sitemap.xml을 교체하지 않습니다.</p></div></section></main>${footer}${scripts}</body></html>`);

const adPlan={version:VERSION,reviewed_on:reviewed,actual_ads_injected:false,principles:['주요 입력·공식 출처·결과보다 광고 우선 금지','도구 입력 위/결과 사이 광고 금지','본문 흐름을 끊는 과도한 슬롯 금지','운영·정책·오류·수집 페이지 광고 제외','실제 광고 코드는 운영 승인 후 별도'],page_types:{tool:{max_slots:1,placements:['결과/설명 블록 이후'],blocked:['첫 화면','입력 폼 내부','결과 숫자 직전']},article_data:{max_slots:2,placements:['첫 핵심 데이터 블록 이후','본문 하단'],blocked:['제목 직후','출처와 숫자 사이']},policy_ops:{max_slots:0,placements:[],blocked:['전체']},region_low_n:{max_slots:0,placements:[],blocked:['표본 미달 상태 페이지']}}};write('data/ad-slot-plan-v12.json',JSON.stringify(adPlan,null,2));
const adCards=[['도구','최대 1','결과·설명 이후','입력 폼 위 / 결과 숫자 직전'],['평수·공종·데이터','최대 2','첫 핵심 데이터 이후 / 본문 하단','제목 직후 / 숫자와 출처 사이'],['정책·운영·수집','0','없음','전체'],['지역 표본 미달','0','없음','가격 데이터가 없는 상태에서 광고 우선 금지'],['공식 출처 블록','0','없음','출처 링크와 숫자 사이'],['모바일','동일 상한','콘텐츠 흐름 이후','고정 하단·전면·입력 방해']];
write('data/ad-layout/index.html',`${head('AdSense 광고 위치 설계 | 도구·데이터 페이지 슬롯 원칙','인테리어 데이터 사이트의 광고 위치를 페이지 유형별로 설계합니다. 현재 프리뷰에는 실제 광고 코드를 넣지 않습니다.',`${SITE}/data/ad-layout/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">AD LAYOUT PLAN</p><h1>광고 슬롯 설계</h1><p>실제 광고 미삽입 · 도구/데이터 우선 · 운영 승인 후 별도 적용</p></div></section><section class="v12-section"><div class="site-shell"><div class="v12-ad-plan">${adCards.map(x=>`<article class="v12-ad-card"><span>${x[0]}</span><strong>${x[1]}</strong><p>허용: ${x[2]}<br><span class="blocked">금지: ${x[3]}</span></p></article>`).join('')}</div><p>애드센스 승인 자체는 Google 판단이며 이 설계가 승인을 보장하지 않습니다. 프리뷰에서는 광고 스크립트와 광고 단위를 삽입하지 않습니다. 운영 전환 시 실제 콘텐츠 밀도와 모바일 레이아웃을 다시 확인한 뒤 슬롯 수를 줄이는 방향을 우선합니다.</p></div></section></main>${footer}${scripts}</body></html>`);

const extraAnswers=[
 ['대량 CSV는 어디서 검수하나요?',`${BASE}/quote-batch/`,'브라우저에서 CSV를 붙여넣거나 파일로 불러와 필수열·허용값·sample_id 중복과 구조적 이상치를 확인합니다. 서버로 업로드하지 않습니다.','도구'],
 ['중복 견적은 어떻게 찾나요?',`${BASE}/quote-batch/`,'같은 sample_id는 차단하고, 다른 ID라도 월·지역·평수·범위·총액 등 핵심 조건 조합이 같으면 중복 의심으로 검토합니다.','데이터 검수'],
 ['이상치 견적은 자동 삭제하나요?',`${BASE}/quote-batch/`,'아닙니다. 구조적 모순과 데이터셋 내부 3×IQR 이탈은 검토 표시만 하며 비싸거나 싸다는 이유로 자동 삭제하지 않습니다.','데이터 검수'],
 ['월별 견적 표본 수는 어디서 보나요?',`${BASE}/data/sample-growth/`,'월별 검수 통과 N과 누적 표본을 확인할 수 있습니다. 가격 변화 그래프가 아니라 표본 수 그래프입니다.','표본'],
 ['서울 32평 통계를 열려면 몇 건이 필요한가요?',`${BASE}/data/coverage-targets/`,`서울×32평 셀 자체가 N≥${segmentN}이어야 하며 현재 N과 남은 건수를 목표 보드에서 확인합니다.`,'지역×평수'],
 ['공종별 데이터는 몇 건부터 공개하나요?',`${BASE}/data/coverage-targets/`,`공종별 가격분포도 해당 공종 금액이 입력된 유효 표본 N≥${segmentN}일 때만 공개합니다.`,'공종'],
 ['데이터를 제공할 때 업체명을 넣어도 되나요?',`${BASE}/data/contribute/`,'넣지 않습니다. 업체명·성명·전화번호·이메일·상세주소 등 식별정보는 허용 스키마 밖이며 검수에서 차단합니다.','개인정보'],
 ['공개 업로드 폼이 있나요?',`${BASE}/data/contribute/`,'현재 프리뷰에는 서버 업로드 엔드포인트가 없습니다. 로컬에서 익명 CSV를 만들고 운영자가 승인한 비공개 수집 경로만 사용합니다.','개인정보'],
 ['운영 전환 시 모든 페이지를 색인하나요?',`${BASE}/data/production-simulator/`,'아닙니다. 내부 운영 페이지와 표본 미달 지역 페이지는 noindex 계획이며 고유 도구·가이드·검증 데이터 중심으로 색인 후보를 계산합니다.','SEO'],
 ['지역 페이지는 언제 색인 후보가 되나요?',`${BASE}/data/production-simulator/`,`해당 지역 실제 견적 셀이 N≥${segmentN}일 때 운영 색인 후보가 됩니다. 전국값으로 지역가격을 추정해 열지 않습니다.`,'SEO'],
 ['robots.txt가 지금 바뀌었나요?',`${BASE}/data/production-simulator/`,'아닙니다. /data 아래 시뮬레이션 파일만 만들었고 실제 프리뷰 robots·noindex 정책은 유지합니다.','SEO'],
 ['AdSense 광고는 지금 들어갔나요?',`${BASE}/data/ad-layout/`,'아닙니다. 페이지 유형별 슬롯 원칙만 설계했고 실제 광고 스크립트와 단위는 운영 승인 전까지 넣지 않습니다.','광고'],
 ['도구 페이지에는 광고를 어디에 둘 계획인가요?',`${BASE}/data/ad-layout/`,'첫 입력이나 결과보다 앞에 두지 않고 결과·설명 이후 최대 1개를 기본 상한으로 계획합니다.','광고'],
 ['표본 미달 지역 페이지에도 광고를 넣나요?',`${BASE}/data/ad-layout/`,'계획상 넣지 않습니다. 실질 가격 데이터가 없는 지역 상태 페이지에서 광고를 콘텐츠보다 우선하지 않습니다.','광고'],
 ['정상 행 CSV는 무엇인가요?',`${BASE}/quote-batch/`,'브라우저 1차 검수에서 차단·검토 상태가 없는 행만 다시 묶은 로컬 다운로드 파일입니다. 공개 업로드나 자동 집계를 의미하지 않습니다.','도구'],
 ['검색 랜딩은 표본이 쌓이면 자동 생성되나요?',`${BASE}/data/production-simulator/`,`지역×평수 정확한 셀이 N≥${segmentN}을 넘으면 기존 생성기가 해당 조합 페이지를 만들고 v12 운영 manifest가 색인 후보로 분류합니다.`,'SEO']
];
const answers=[...(baseAnswers.answers||[]),...extraAnswers.map((x,i)=>({id:`v12-${String(i+1).padStart(2,'0')}`,question:x[0],answer:x[2],category:x[3],url:x[1],data_type:/광고|SEO|도구/.test(x[3])?'GUIDE':'QUOTE',status:'current'}))];write('data/answer-index-v12.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,count:answers.length,answers},null,2));
const cats=[...new Set(answers.map(x=>x.category))];const answerCards=answers.map(x=>`<article class="v10-answer-card" data-v10-answer-card data-category="${esc(x.category)}" data-search="${esc(x.question+' '+x.answer)}"><span>${esc(x.category)} · ${esc(x.data_type||'GUIDE')}</span><h3>${esc(x.question)}</h3><p>${esc(x.answer)}</p><a href="${esc(x.url)}">근거/도구</a></article>`).join('');
write('data/answers-v12/index.html',`${head('인테리어 견적 질문 100+ | 데이터·표본·SEO·광고 답변 허브','인테리어 견적 비교, 지역×평수 표본, CSV 검수, 데이터 수집, 운영 색인과 광고 설계 질문을 근거 페이지와 연결합니다.',`${SITE}/data/answers-v12/`)}${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">ANSWER INDEX v12</p><h1>질문 답변 허브</h1><p>${answers.length}개 · 데이터 상태와 도구 근거 연결 · 가짜 시장평균 없음</p></div></section><section class="v10-section"><div class="site-shell" data-v10-answer-hub><div class="v10-answer-controls"><input data-v10-answer-q placeholder="32평 · CSV · 광고 · 지역"><select data-v10-answer-category><option value="">전체 분류</option>${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div class="v10-answer-grid">${answerCards}</div></div></section></main>${footer}${scripts}</body></html>`);

try{const q=json('data/query-map.json',{queries:[]});q.version=VERSION;const additions=[['인테리어 견적 CSV 검수',`${BASE}/quote-batch/`],['인테리어 견적 중복 확인',`${BASE}/quote-batch/`],['인테리어 견적 이상치',`${BASE}/quote-batch/`],['인테리어 견적 표본 수',`${BASE}/data/sample-growth/`],['인테리어 견적 데이터 제공',`${BASE}/data/contribute/`],['지역별 인테리어 데이터 표본',`${BASE}/data/coverage-targets/`],['32평 인테리어 표본 수',`${BASE}/data/coverage-targets/`],['인테리어 사이트 robots',`${BASE}/data/production-simulator/`],['인테리어 사이트 sitemap',`${BASE}/data/production-simulator/`],['인테리어 계산기 애드센스 위치',`${BASE}/data/ad-layout/`]];const existing=new Set((q.queries||[]).map(x=>x.query));for(const [query,canonical] of additions)if(!existing.has(query))q.queries.push({query,intent:'qa',canonical,volume_claimed:false});write('data/query-map.json',JSON.stringify(q,null,2))}catch{}
try{let ll=read('llms.txt');if(!ll.includes('# v12 growth engine'))ll+=`\n# v12 growth engine\n- Batch quote QA: ${SITE}/quote-batch/\n- Sample growth: ${SITE}/data/sample-growth/\n- Coverage targets: ${SITE}/data/coverage-targets/\n- Data contribution rules: ${SITE}/data/contribute/\n- Production index simulation: ${SITE}/data/production-simulator/\n- Ad slot plan: ${SITE}/data/ad-layout/\n- Answer index v12: ${SITE}/data/answer-index-v12.json\n- Preview remains noindex; production switching requires owner approval.\n`;write('llms.txt',ll)}catch{}

// Home + data hub entry points.
let home=read('index.html');home=home.replace(/데이터 v\d+\.\d+\.\d+/g,'데이터 v12.0.0');if(!home.includes('v12-home-rail'))home=home.replace('<main>',`<main><div class="site-shell"><nav class="v12-home-rail"><a href="${BASE}/quote-batch/"><span>BATCH QA</span><strong>CSV 대량 검수</strong></a><a href="${BASE}/data/sample-growth/"><span>GROWTH</span><strong>표본 증가</strong></a><a href="${BASE}/data/coverage-targets/"><span>COVERAGE</span><strong>공개까지 남은 N</strong></a><a href="${BASE}/data/production-simulator/"><span>LAUNCH</span><strong>운영 색인 시뮬레이터</strong></a></nav></div>`);write('index.html',home);
try{let d=read('data/index.html');if(!d.includes('/data/sample-growth/'))d=d.replace('<main>',`<main><section class="v12-section"><div class="site-shell"><div class="v12-section-head"><div><h2>수집·성장·운영</h2><p>실제 견적 데이터가 쌓일 때 공개 가능한 범위와 운영 전환 대상을 관리합니다.</p></div></div><nav class="v10-actions"><a href="${BASE}/quote-batch/">CSV 대량 검수</a><a href="${BASE}/data/sample-growth/">표본 증가</a><a href="${BASE}/data/coverage-targets/">표본 목표</a><a href="${BASE}/data/contribute/">데이터 준비</a><a href="${BASE}/data/production-simulator/">운영 시뮬레이터</a><a href="${BASE}/data/ad-layout/">광고 설계</a></nav></div></section>`);write('data/index.html',d)}catch{}

// Inject v12 assets into every HTML generated so far.
allPages=walk();for(const rel of allPages){let h=read(rel);if(!h.includes('site-v12.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v12.css?v=${build}"></head>`);if(!h.includes('app-v12.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v12.js?v=${build}" defer></script></body>`);if(/<body/.test(h)&&!/<body[^>]*\bv12-ui\b/.test(h))h=h.replace(/<body([^>]*)class="([^"]*)"/,`<body$1class="$2 v12-ui"`).replace(/<body(?![^>]*class=)([^>]*)>/,`<body class="v12-ui"$1>`);write(rel,h)}

allPages=walk();const auditRows=allPages.map(rel=>{const h=read(rel),title=h.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim()||'',h1=strip(h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||''),chars=strip(h.match(/<main[\s\S]*?<\/main>/i)?.[0]||h).length,noindex=/noindex/.test(h),canonical=/<link rel="canonical"/.test(h),schemas=(h.match(/application\/ld\+json/gi)||[]).length,links=(h.match(/<a\s/gi)||[]).length;return {rel,title,h1,chars,noindex,canonical,schemas,links}});const duplicates=key=>{const m=new Map();for(const r of auditRows){if(!r[key])continue;if(!m.has(r[key]))m.set(r[key],[]);m.get(r[key]).push(r.rel)}return [...m.values()].filter(x=>x.length>1)};const policy=['about/index.html','contact/index.html','privacy/index.html','terms/index.html','disclaimer/index.html','editorial-policy/index.html','corrections/index.html'];const quality={version:VERSION,reviewed_on:reviewed,pages:auditRows.length,thin_under_500:auditRows.filter(x=>x.chars<500).length,duplicate_titles:duplicates('title').length,duplicate_h1:duplicates('h1').length,noindex_pages:auditRows.filter(x=>x.noindex).length,canonical_pages:auditRows.filter(x=>x.canonical).length,structured_pages:auditRows.filter(x=>x.schemas>0).length,structured_ratio:Number((auditRows.filter(x=>x.schemas>0).length/auditRows.length).toFixed(3)),average_text_chars:Math.round(auditRows.reduce((s,x)=>s+x.chars,0)/auditRows.length),average_internal_links:Number((auditRows.reduce((s,x)=>s+x.links,0)/auditRows.length).toFixed(1)),policy_pages_present:policy.filter(x=>fs.existsSync(path.join(ROOT,x))).length,policy_pages_expected:policy.length,quote_samples:quote.sample_count||0,answer_records:answers.length,region_pyeong_cells:routeCells.length,production_index_candidates:indexable.length,actual_ads_injected:false,actual_production_robots_changed:false,raw_rows_public:false,fake_market_average:false,preview_noindex_expected:true};write('data/site-quality-v12.json',JSON.stringify(quality,null,2));const launch={version:VERSION,reviewed_on:reviewed,status:'preview_review',checks:{thin_zero:quality.thin_under_500===0,unique_titles:quality.duplicate_titles===0,unique_h1:quality.duplicate_h1===0,noindex_all:quality.noindex_pages===quality.pages,canonical_all:quality.canonical_pages===quality.pages,policy_complete:quality.policy_pages_present===quality.policy_pages_expected,batch_contract:true,sample_growth:true,coverage_targets:routeCells.length===85,production_simulation:true,actual_production_switch:false,ad_plan_only:true,raw_rows_public:false,fake_market_average:false,source_update_required:sourceFresh.update_required===true},inventory:{html_pages:quality.pages,answers:answers.length,region_pyeong_cells:routeCells.length,production_index_candidates:indexable.length,quote_samples:quote.sample_count||0},approval:{robots_change_requires_owner:true,sitemap_switch_requires_owner:true,ads_activation_requires_owner:true}};write('data/launch-gate-v12.json',JSON.stringify(launch,null,2));
const report=json('data/v6-report.json',{});Object.assign(report,{version:VERSION,home_version_consistent:read('index.html').includes('데이터 v12.0.0'),v12_bulk_batch:true,v12_batch_import:true,v12_duplicate_outlier_review:true,v12_sample_growth:true,v12_contribution_guide:true,v12_coverage_targets:true,v12_publication_manifest:true,v12_production_simulator:true,v12_ad_slot_plan:true,v12_answer_hub:true,v12_answer_count:answers.length,v12_assets_injected:true,v12_page_count:quality.pages,v12_thin_zero:quality.thin_under_500===0,v12_unique_titles:quality.duplicate_titles===0,v12_unique_h1:quality.duplicate_h1===0,v12_preview_noindex_all:quality.noindex_pages===quality.pages,v12_canonical_all:quality.canonical_pages===quality.pages});write('data/v6-report.json',JSON.stringify(report,null,2));
const publication={version:VERSION,reviewed_on:reviewed,segment_threshold:segmentN,published_region_pyeong:(regionMap.routes||[]).filter(x=>x.status==='published').map(x=>({key:x.key,url:x.combination_url,sample_count:x.sample_count})),candidate_count:(regionMap.routes||[]).filter(x=>x.status==='published').length,withheld_count:(regionMap.routes||[]).filter(x=>x.status!=='published').length,production_index_candidates:indexable.length};write('data/publication-manifest-v12.json',JSON.stringify(publication,null,2));
if(routeCells.length!==85||answers.length<100||quality.duplicate_titles||quality.duplicate_h1||quality.noindex_pages!==quality.pages||quality.canonical_pages!==quality.pages||quality.policy_pages_present!==quality.policy_pages_expected||!report.home_version_consistent)throw new Error(`v12 quality gate failed ${JSON.stringify({cells:routeCells.length,answers:answers.length,thin:quality.thin_under_500,titles:quality.duplicate_titles,h1:quality.duplicate_h1,noindex:[quality.noindex_pages,quality.pages],canonical:[quality.canonical_pages,quality.pages],policy:quality.policy_pages_present,home:report.home_version_consistent})}`);
console.log(JSON.stringify({version:VERSION,pages:quality.pages,answers:answers.length,thin:quality.thin_under_500,indexCandidates:indexable.length,quoteN:quote.sample_count||0},null,2));
