import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='6.1.0';
const series=[{month:'2026-01',value:133.28},{month:'2026-02',value:133.69},{month:'2026-03',value:134.42},{month:'2026-04',value:136.88},{month:'2026-05',value:137.67},{month:'2026-06',value:138.22},{month:'2026-07',value:138.59}];
const cost={month:'2026-07',value:138.59,yoy:5.78,published:'2026-08-28'};
const wage={period:'2026-H2',occupations:132,daily_average:282737,half_change:0.98,yoy:1.40,published:'2026-09-01'};
const sources={cost:{source_id:'KICT-COST-INDEX-2026-07',agency:'한국건설기술연구원 공사비원가관리센터',title:'2026년 7월 건설공사비지수 (2020=100)',url:'https://cost.kict.re.kr/index.html'},wage:{source_id:'CAK-WAGE-2026H2',agency:'대한건설협회',title:'2026년 하반기 적용 건설업 임금실태조사',url:'https://www.cak.or.kr/lay1/bbs/S1T823C828/A/2/view.do?article_seq=160600'}};
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)},json=r=>JSON.parse(read(r));
const reviewed=(()=>{try{return json('data/v5-report.json').reviewed_on}catch{return new Date().toISOString().slice(0,10)}})();
const css=fs.readFileSync(path.join(CORE,'site-v6-1.css'),'utf8'),cssHash=crypto.createHash('sha1').update(css).digest('hex').slice(0,10);write('assets/site-v6-1.css',css);
const fmt=n=>Number(n).toLocaleString('ko-KR');
function replaceOrThrow(text,re,replacement,label){if(!re.test(text))throw new Error(`v6.1 patch target missing: ${label}`);return text.replace(re,replacement)}
function chart(){const W=760,H=238,L=42,R=24,T=18,B=36,v=series.map(x=>x.value),min=Math.floor((Math.min(...v)-.7)*2)/2,max=Math.ceil((Math.max(...v)+.5)*2)/2,x=i=>L+(W-L-R)*(i/(series.length-1)),y=n=>T+(H-T-B)*(1-(n-min)/(max-min));const d=series.map((p,i)=>`${i?'L':'M'}${x(i).toFixed(1)} ${y(p.value).toFixed(1)}`).join(' '),grids=[0,.25,.5,.75,1].map(t=>{const gy=T+(H-T-B)*t,val=(max-(max-min)*t).toFixed(1);return `<line class="v6-chart-grid" x1="${L}" x2="${W-R}" y1="${gy}" y2="${gy}"/><text class="v6-chart-label" x="0" y="${gy+3}">${val}</text>`}).join(''),labels=series.map((p,i)=>`<text class="v6-chart-label" x="${x(i)}" y="${H-10}" text-anchor="middle">${p.month.slice(5)}월</text>`).join(''),e=series.length-1;return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="2026년 1월부터 7월 건설공사비지수 추이">${grids}<path class="v6-chart-line" d="${d}"/><circle class="v6-chart-point" cx="${x(e)}" cy="${y(series[e].value)}" r="4"/><text class="v6-chart-value" x="${x(e)-8}" y="${y(series[e].value)-10}" text-anchor="end">${series[e].value}</text>${labels}</svg>`}
const svg=chart(),options=series.map(x=>`<option value="${x.month}"${x.month==='2026-01'?' selected':''}>${x.month} · ${x.value}</option>`).join(''),targets=series.map(x=>`<option value="${x.month}"${x.month==='2026-07'?' selected':''}>${x.month} · ${x.value}</option>`).join('');
const kpis=`<div class="v6-kpi-strip"><div class="v6-kpi"><span>건설공사비지수</span><strong>${cost.value}</strong><em>${cost.month} · 2020=100</em></div><div class="v6-kpi"><span>공사비 전년동월</span><strong>+${cost.yoy.toFixed(2)}%</strong><em>KICT · 잠정치</em></div><div class="v6-kpi"><span>건설업 일평균임금</span><strong>${fmt(wage.daily_average)}원</strong><em>${wage.occupations}개 직종 · 2026 하반기</em></div><div class="v6-kpi"><span>임금 전년동기</span><strong>+${wage.yoy.toFixed(2)}%</strong><em>직전 반기 +${wage.half_change.toFixed(2)}%</em></div></div><form class="v6-search"`;
const indexSection=`<section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>건설공사비지수</h2><p>OFFICIAL · 한국건설기술연구원 · 민간 인테리어 시장평균 아님</p></div><div class="v6-index-layout"><div class="v6-index-panel"><div class="v6-index-current"><strong>${cost.value}</strong><span>${cost.month} · 전년 동월 +${cost.yoy.toFixed(2)}% · 2020=100</span></div><div class="v6-chart-frame">${svg}</div><p class="v6-index-note">재료·노무·장비 등 건설 직접공사비의 가격 변동을 보는 공식 지수입니다. 특정 평수나 인테리어 업체의 견적 평균이 아닙니다. <a class="v6-source-link" href="${BASE}/data/cost-index/">2026 월별 데이터</a></p></div><div><table class="v6-index-table"><thead><tr><th>월</th><th>지수</th></tr></thead><tbody>${series.slice().reverse().map(x=>`<tr><th>${x.month}</th><td>${x.value}</td></tr>`).join('')}</tbody></table><p class="v6-index-note">공표 ${cost.published}<br><a href="${sources.cost.url}" rel="noopener">KICT 원출처</a></p></div></div></div></section>`;
const pressureSection=`<section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>공사비 · 건설임금 변화폭</h2><p>서로 다른 통계를 전년 대비 증감률로만 나란히 비교</p></div><div class="v61-pressure"><div><div class="v61-pressure-chart"><div class="v61-pressure-row"><div class="v61-pressure-label"><strong>건설공사비지수</strong><span>2026-07 · 전년동월</span></div><div class="v61-pressure-track"><div class="v61-pressure-fill" style="width:96.3%"></div></div><div class="v61-pressure-value">+${cost.yoy.toFixed(2)}%</div></div><div class="v61-pressure-row"><div class="v61-pressure-label"><strong>건설업 평균임금</strong><span>2026 하반기 · 전년동기</span></div><div class="v61-pressure-track"><div class="v61-pressure-fill" style="width:23.3%"></div></div><div class="v61-pressure-value">+${wage.yoy.toFixed(2)}%</div></div></div><p class="v61-pressure-note">두 지표의 조사대상과 산식은 다릅니다. 같은 단가로 합산하지 않고, 같은 ‘전년 대비 변화율’ 축에서 원가 환경을 읽는 참고 비교만 제공합니다.</p></div><aside class="v61-wage-card"><div class="v61-wage-main"><span>건설업 ${wage.occupations}개 직종 일평균임금</span><strong>${fmt(wage.daily_average)}원</strong><em>2026년 하반기 적용 · 지정통계</em></div><div class="v61-wage-mini"><div><span>직전 반기 대비</span><strong>+${wage.half_change.toFixed(2)}%</strong></div><div><span>전년 동기 대비</span><strong>+${wage.yoy.toFixed(2)}%</strong></div></div><p class="v6-index-note"><a class="v6-source-link" href="${BASE}/data/construction-wage/">임금 데이터 보기</a></p></aside></div></div></section>`;

let home=read('index.html');home=replaceOrThrow(home,/<div class="v6-kpi-strip">[\s\S]*?<\/div><form class="v6-search"/,kpis,'home KPI');home=replaceOrThrow(home,/<section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>건설공사비지수<\/h2>[\s\S]*?<\/section>/,indexSection+pressureSection,'home cost-index section');home=home.replace('공사비지수 · 수선유지급여','공사비지수 · 건설업 임금 · 수선유지급여');write('index.html',home);

let calc=read('calculator/index.html');calc=replaceOrThrow(calc,/<select data-v6-index-from>[\s\S]*?<\/select>/,`<select data-v6-index-from>${options}</select>`,'calculator from');calc=replaceOrThrow(calc,/<select data-v6-index-to>[\s\S]*?<\/select>/,`<select data-v6-index-to>${targets}</select>`,'calculator to');write('calculator/index.html',calc);

let ci=read('data/cost-index/index.html');const indexKpis=`<div class="v61-page-kpis"><div><span>2026-07 지수</span><strong>${cost.value}</strong></div><div><span>전년 동월</span><strong>+${cost.yoy.toFixed(2)}%</strong></div><div><span>2026-01</span><strong>${series[0].value}</strong></div><div><span>공표일</span><strong>${cost.published.slice(5)}</strong></div></div>`;ci=replaceOrThrow(ci,/<aside class="v6-benchmark">[\s\S]*?<\/aside>/,indexKpis,'cost index KPI');ci=replaceOrThrow(ci,/<section class="content-section"><h2>최근 12개월<\/h2>[\s\S]*?<\/section>/,`<section class="content-section"><h2>2026 월별 추이</h2><div class="v6-chart-frame">${svg}</div><p class="v6-index-note">1월 ${series[0].value} → 7월 ${cost.value}. 7월은 전년 동월 대비 +${cost.yoy.toFixed(2)}%입니다.</p></section>`,'cost index chart');ci=replaceOrThrow(ci,/<section class="content-section"><h2>월별 값<\/h2>[\s\S]*?<\/section>/,`<section class="content-section"><h2>월별 값</h2><table class="v6-index-table"><thead><tr><th>기준월</th><th>지수</th></tr></thead><tbody>${series.slice().reverse().map(x=>`<tr><th>${x.month}</th><td>${x.value}</td></tr>`).join('')}</tbody></table><p class="v6-index-note"><a href="${BASE}/data/construction-cost-index.json">JSON 데이터</a></p></section>`,'cost index table');write('data/cost-index/index.html',ci);

const template=read('data/cost-index/index.html'),header=template.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=template.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',cssLinks=[...template.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scripts=[...template.matchAll(/<script src="[^"]*app-v[56]\.js[^"]*" defer><\/script>/g)].map(x=>x[0]).join('');
const wageDesc='2026년 하반기 적용 건설업 132개 직종 일평균임금과 직전 반기·전년 동기 증감률을 확인합니다.';const wageSchema={'@context':'https://schema.org','@type':'Dataset',name:'2026년 하반기 건설업 임금실태조사 요약',description:wageDesc,temporalCoverage:'2026-H2',creator:{'@type':'Organization',name:sources.wage.agency},isBasedOn:sources.wage.url};
const wagePage=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>2026 건설업 임금 | 일평균 282,737원</title><meta name="description" content="${wageDesc}"><link rel="canonical" href="${SITE}/data/construction-wage/">${cssLinks}<script type="application/ld+json">${JSON.stringify(wageSchema)}</script></head><body>${header}<main><section class="article-hero"><div class="article-shell"><nav class="breadcrumbs"><a href="${BASE}/">홈</a><span>/</span><a href="${BASE}/data/sources/">데이터</a><span>/</span><span>건설업 임금</span></nav><p class="kicker">OFFICIAL DATA</p><h1>2026 하반기 건설업 임금</h1><div class="page-meta"><span>공표 ${wage.published}</span><span>${wage.occupations}개 직종</span><span>지정통계</span></div></div></section><div class="article-layout"><article class="article-body"><div class="v61-page-kpis"><div><span>일평균임금</span><strong>${fmt(wage.daily_average)}원</strong></div><div><span>직전 반기 대비</span><strong>+${wage.half_change.toFixed(2)}%</strong></div><div><span>전년 동기 대비</span><strong>+${wage.yoy.toFixed(2)}%</strong></div><div><span>조사 직종</span><strong>${wage.occupations}개</strong></div></div><section class="content-section"><h2>어디에 쓰는 숫자인가</h2><p>대한건설협회가 2026년 5월 건설업 임금을 조사해 9월 1일 공표한 전체 ${wage.occupations}개 직종의 일 평균임금입니다. 건설공사 원가계산에 적용할 수 있는 지정통계입니다.</p></section><section class="content-section"><h2>인테리어 견적과의 관계</h2><table class="v6-status-table"><tbody><tr><td class="v6-status-ok">가능</td><td>건설 인건비의 전반적인 변화 방향 확인</td></tr><tr><td class="v6-status-ok">가능</td><td>공사비지수와 전년 대비 변화폭 비교</td></tr><tr><td class="v6-status-empty">불가</td><td>도배·타일·목공 등 특정 인테리어 직종의 일당으로 직접 대체</td></tr><tr><td class="v6-status-empty">불가</td><td>아파트 인테리어 총견적의 평균 산정</td></tr></tbody></table></section><section class="content-section"><h2>출처</h2><p><a href="${sources.wage.url}" rel="noopener">${sources.wage.agency} · ${sources.wage.title}</a></p><p>확인일 ${reviewed}</p></section></article><aside class="side-rail"><strong>같이 확인</strong><a href="${BASE}/data/cost-index/">공사비지수</a><a href="${BASE}/calculator/">예산 계산</a><a href="${BASE}/data/methodology/">산출 기준</a></aside></div></main>${footer}${scripts}</body></html>`;write('data/construction-wage/index.html',wagePage);

write('data/construction-cost-index.json',JSON.stringify({version:VERSION,base_year:2020,unit:'index',latest_month:cost.month,latest_value:cost.value,latest_yoy_percent:cost.yoy,published:cost.published,checked:reviewed,source:sources.cost,series,note:'2026 월별 건설공사비지수. 민간 아파트 인테리어 시장평균이 아님.'},null,2));write('data/construction-wage-2026-h2.json',JSON.stringify({version:VERSION,period:wage.period,unit:'원/일',occupations:wage.occupations,daily_average:wage.daily_average,half_change_percent:wage.half_change,yoy_percent:wage.yoy,published:wage.published,checked:reviewed,source:sources.wage,note:'전체 건설업 직종 평균이며 특정 인테리어 직종 일당이나 소비자 견적 평균이 아님.'},null,2));
try{const a=json('data/public-sources.json'),i=a.findIndex(x=>x.source_id===sources.wage.source_id);const row={...sources.wage,published:wage.published,checked:reviewed,applies:'건설업 전체 직종 임금 수준·변화 참고',does_not_apply:'특정 인테리어 직종 일당 또는 민간 견적 평균',processed:true};if(i>=0)a[i]={...a[i],...row};else a.push(row);write('data/public-sources.json',JSON.stringify(a,null,2))}catch{}
try{const l=json('data/latest.json');Object.assign(l,{version:VERSION,updated:reviewed,official_cost_index:{month:cost.month,value:cost.value,yoy_percent:cost.yoy,base_year:2020},official_construction_wage:{period:wage.period,daily_average:wage.daily_average,yoy_percent:wage.yoy,half_change_percent:wage.half_change,occupations:wage.occupations}});write('data/latest.json',JSON.stringify(l,null,2))}catch{}
try{const v=json('data/versions.json');if(!v.some(x=>x.version===VERSION))v.unshift({version:VERSION,date:reviewed,changes:['공사비 공식 전년동월 증감률 적용','건설업 일평균임금 추가','공사비·임금 변화폭 비교','2026 검증 월별 지수로 환산 범위 정리']});write('data/versions.json',JSON.stringify(v,null,2))}catch{}
try{const s=json('data/search-index.json');if(!s.some(x=>x.url===`${BASE}/data/construction-wage/`))s.push({title:'2026 하반기 건설업 임금',url:`${BASE}/data/construction-wage/`,type:'데이터',description:'건설업 132개 직종 일평균임금과 직전 반기·전년 동기 증감률',keywords:['건설업 임금','건설 일당','건설 인건비','인테리어 인건비 참고']});write('data/search-index.json',JSON.stringify(s,null,2))}catch{}
try{let s=read('sitemap-production.xml'),u=`${SITE}/data/construction-wage/`;if(!s.includes(u))s=s.replace('</urlset>',`<url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap-production.xml',s)}catch{}
let src=read('data/sources/index.html');if(!src.includes(sources.wage.source_id)){src=src.replace('</article>',`<section class="content-section v6-source-register"><h2>건설업 임금</h2><dl><div><dt>${sources.wage.source_id}</dt><dd><a href="${sources.wage.url}" rel="noopener">${sources.wage.agency} · ${sources.wage.title}</a><br>일평균 ${fmt(wage.daily_average)}원 · 전년 동기 +${wage.yoy.toFixed(2)}% · 특정 인테리어 직종 일당 아님</dd></div></dl></section></article>`);write('data/sources/index.html',src)}
const html=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);e.isDirectory()?walk(f):e.name.endsWith('.html')&&html.push(f)}};walk(ROOT);for(const f of html){let x=fs.readFileSync(f,'utf8');if(!x.includes('site-v6-1.css'))x=x.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v6-1.css?v=${cssHash}"></head>`);fs.writeFileSync(f,x)}
const report=json('data/v6-report.json');Object.assign(report,{version:VERSION,official_index_latest:{month:cost.month,value:cost.value,yoy_percent:cost.yoy},official_wage:{period:wage.period,daily_average:wage.daily_average,yoy_percent:wage.yoy},verified_2026_index_series:true,official_wage_page:fs.existsSync(path.join(ROOT,'data/construction-wage/index.html')),cost_wage_comparison:read('index.html').includes('공사비 · 건설임금 변화폭'),v61_assets_injected:html.every(f=>fs.readFileSync(f,'utf8').includes('site-v6-1.css'))});write('data/v6-report.json',JSON.stringify(report,null,2));if(!report.verified_2026_index_series||!report.official_wage_page||!report.cost_wage_comparison||!report.v61_assets_injected)throw new Error(`v6.1 validation failed ${JSON.stringify(report)}`);console.log(JSON.stringify(report,null,2));
