import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='7.0.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)},json=(r,fallback={})=>{try{return JSON.parse(read(r))}catch{return fallback}};
const reviewed=json('data/v5-report.json',{}).reviewed_on||new Date().toISOString().slice(0,10);
const stats=json('data/quote-statistics.json',{sample_count:0,status:'withheld',segments:{}}),health=json('data/quote-data-health.json',{}),costIndex=json('data/construction-cost-index.json',{}),wage=json('data/construction-wage-2026-h2.json',{}),repair=json('data/repair-support-2026.json',{}),unit=json('data/public-unit-cost-2026-h2.json',{items:[]});
const css=fs.readFileSync(path.join(CORE,'site-v7.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v7.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v7.css',css);write('assets/app-v7.js',js);
const fmt=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:1});
const latestCost=costIndex.latest||costIndex.series?.at?.(-1)||{month:'2026-07',value:138.59,yoy_percent:5.78};
const wageValue=wage.daily_average||282737;
const quoteState=stats.status==='published'?'published':'withheld';
const publishedCells=Object.fromEntries(Object.entries(stats.segments||{}).map(([k,v])=>[k,(v||[]).filter(x=>x.status==='published').length]));
const datasets=[
 {id:'construction-cost-index',type:'OFFICIAL',name:'건설공사비지수',status:'published',scope:'건설 직접공사비 가격변동',period:latestCost.month||'2026-07',page:`${BASE}/data/cost-index/`,json:`${BASE}/data/construction-cost-index.json`,source:'한국건설기술연구원',not_for:'민간 아파트 인테리어 시장평균'},
 {id:'construction-wage',type:'OFFICIAL',name:'건설업 임금',status:'published',scope:'건설업 132개 직종 일평균임금',period:'2026-H2',page:`${BASE}/data/construction-wage/`,json:`${BASE}/data/construction-wage-2026-h2.json`,source:'대한건설협회',not_for:'특정 인테리어 직종 일당'},
 {id:'repair-support',type:'OFFICIAL',name:'공공 수선 기준',status:'published',scope:'주거급여 수선유지급여',period:'2026',page:`${BASE}/data/`,json:`${BASE}/data/repair-support-2026.json`,source:'국토교통부',not_for:'민간 인테리어 견적 평균'},
 {id:'public-unit-cost',type:'REFERENCE',name:'공공 공종 단가',status:'published',scope:`표준시장단가 중 인테리어 관련 ${unit.items?.length||0}개 공종`,period:'2026-H2',page:`${BASE}/data/public-unit-cost/`,json:`${BASE}/data/public-unit-cost-2026-h2.json`,source:'국토교통부·한국건설기술연구원',not_for:'민간 시장가격 또는 적정가격 판정'},
 {id:'quote-statistics',type:'QUOTE',name:'실제 견적 집계',status:quoteState,scope:'익명 검수 견적의 중앙값·P25·P75',period:'rolling',page:`${BASE}/data/quote-statistics/`,json:`${BASE}/data/quote-statistics.json`,source:'익명 검수 표본',not_for:'표본 기준 미달 시 가격통계 비공개'},
 {id:'quote-schema',type:'SCHEMA',name:'익명 견적 스키마',status:'published',scope:'민간 견적 입력·검증 계약',period:'v7',page:`${BASE}/data/quote-pipeline/`,json:`${BASE}/data/quote-sample-schema.json`,source:'견적검수실 편집정책',not_for:'개인정보·업체 식별정보 수집'}
];
write('data/dataset-catalog.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,datasets},null,2));
const intelligence={version:VERSION,reviewed_on:reviewed,quote:{sample_count:stats.sample_count||0,status:quoteState,overall_min_n:stats.publication_threshold||30,segment_min_n:stats.segment_threshold||20,published_segment_cells:publishedCells,raw_rows_public:false},quality:{valid_rows:health.valid_rows||0,invalid_messages:health.invalid_messages||0,trade_field_completion_percent:health.trade_field_completion_percent||{}},official:{construction_cost_index:{month:latestCost.month||'2026-07',value:latestCost.value||138.59,yoy_percent:latestCost.yoy_percent??5.78},construction_wage:{period:'2026-H2',daily_average:wageValue},public_unit_cost_items:unit.items?.length||0},endpoints:{catalog:`${BASE}/data/dataset-catalog.json`,answers:`${BASE}/data/answer-index.json`,quote_statistics:`${BASE}/data/quote-statistics.json`,quote_health:`${BASE}/data/quote-data-health.json`}};
write('data/quote-intelligence.json',JSON.stringify(intelligence,null,2));
function roundedCell(p){return (stats.segments?.supply_pyeong_rounded||[]).find(x=>x.key===`${p}평`)||null}
function answer32(){const c=roundedCell(32);if(c?.status==='published'){const d=c.distribution?.total_amount_manwon;return d?`검수 표본 N=${c.n}에서 32평 견적 중앙값은 ${fmt(d.median)}만원, P25 ${fmt(d.p25)}만원, P75 ${fmt(d.p75)}만원입니다.`:`32평 셀은 공개 상태지만 분포값을 확인할 수 없습니다.`}return `32평 실제 견적 가격 통계는 현재 공개하지 않습니다. 유효 표본 N=${c?.n||0}으로 세그먼트 공개 기준 N≥${stats.segment_threshold||20} 미달입니다.`}
const answers=[
 {id:'cost-index-latest',question:'현재 건설공사비지수는?',answer:`${latestCost.month||'2026-07'} 건설공사비지수는 ${latestCost.value||138.59}입니다. 2020=100 기준이며 민간 인테리어 시장평균이 아닙니다.`,source:`${BASE}/data/cost-index/`,status:'published'},
 {id:'construction-wage-latest',question:'2026 하반기 건설업 일평균임금은?',answer:`132개 직종 일평균임금은 ${Number(wageValue).toLocaleString('ko-KR')}원입니다. 특정 인테리어 직종의 소비자 청구 일당을 뜻하지 않습니다.`,source:`${BASE}/data/construction-wage/`,status:'published'},
 {id:'public-unit-cost-scope',question:'공공 공종 단가를 인테리어 시장가로 봐도 되나?',answer:`아닙니다. 현재 ${unit.items?.length||0}개 항목은 공공 건설 예정가격 참고용 표준시장단가이며 주재료비 제외 항목이 많습니다.`,source:`${BASE}/data/public-unit-cost/`,status:'published'},
 {id:'quote-sample-count',question:'실제 인테리어 견적 표본은 몇 건인가?',answer:`현재 검수 통과 공개 집계 표본은 ${stats.sample_count||0}건입니다. 전체 분포는 N≥${stats.publication_threshold||30}, 세그먼트는 각 셀 N≥${stats.segment_threshold||20}에서만 가격 통계를 공개합니다.`,source:`${BASE}/data/quote-statistics/`,status:quoteState},
 {id:'32p-market',question:'32평 인테리어 실제 견적 중앙값은?',answer:answer32(),source:`${BASE}/interior-cost/32-pyeong/`,status:roundedCell(32)?.status||'withheld'},
 {id:'why-no-mean',question:'왜 평균값 대신 중앙값과 P25·P75를 쓰나?',answer:'소수의 매우 큰 견적에 결과가 끌리는 것을 줄이고 분포 폭을 함께 보여주기 위해 평균값은 공개하지 않는 편집정책을 사용합니다.',source:`${BASE}/data/quote-pipeline/`,status:'published'}
];
write('data/answer-index.json',JSON.stringify({version:VERSION,reviewed_on:reviewed,answers},null,2));
const llms=`# 견적검수실 데이터\n\nUpdated: ${reviewed}\n\nThis preview separates OFFICIAL, REFERENCE, QUOTE and CALCULATED data. Do not treat public construction standards as private apartment market averages.\n\n## Primary datasets\n- ${SITE}/data/cost-index/ — official construction cost index\n- ${SITE}/data/construction-wage/ — official construction wage survey\n- ${SITE}/data/public-unit-cost/ — public construction unit-cost references; not private market prices\n- ${SITE}/data/quote-statistics/ — anonymized quote aggregates; prices withheld below N thresholds\n- ${SITE}/data/catalog/ — dataset catalog and scopes\n- ${SITE}/data/answers/ — concise answer index for common questions\n- ${SITE}/data/dataset-catalog.json — machine-readable dataset catalog\n- ${SITE}/data/answer-index.json — machine-readable answer index\n- ${SITE}/data/quote-intelligence.json — quote coverage and publication status\n\n## Quote publication policy\nOverall distribution requires N>=${stats.publication_threshold||30}. Segment price distributions require N>=${stats.segment_threshold||20}. Raw quote rows are not published. Mean is not published.\n`;
write('llms.txt',llms);

const dataTemplate=read('data/index.html'),header=dataTemplate.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=dataTemplate.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',styles=[...dataTemplate.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scripts=[...dataTemplate.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const catalogCards=datasets.map(d=>`<article class="v7-dataset"><span class="tag">${d.type} · ${d.status.toUpperCase()}</span><h3>${d.name}</h3><p>${d.scope}</p><dl><dt>기준</dt><dd>${d.period}</dd><dt>출처</dt><dd>${d.source}</dd><dt>제외</dt><dd>${d.not_for}</dd></dl><nav><a href="${d.page}">페이지</a><a href="${d.json}">JSON</a></nav></article>`).join('');
const catalogSchema={'@context':'https://schema.org','@type':'DataCatalog',name:'견적검수실 인테리어 비용 데이터 카탈로그',dateModified:reviewed,url:`${SITE}/data/catalog/`,dataset:datasets.map(d=>({'@type':'Dataset',name:d.name,url:`${SITE}${d.page.replace(BASE,'')}`,description:d.scope,temporalCoverage:d.period}))};
const catalogPage=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 비용 데이터 카탈로그 | 공식·견적·참고 데이터</title><meta name="description" content="공식 공사비지수·건설업 임금·공공 공종 단가·실제 견적 집계의 출처와 적용범위를 데이터셋 단위로 확인합니다."><link rel="canonical" href="${SITE}/data/catalog/">${styles}<script type="application/ld+json">${JSON.stringify(catalogSchema)}</script></head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">DATA CATALOG</p><h1>인테리어 비용 데이터 카탈로그</h1><p>숫자의 종류·출처·적용범위·금지 해석을 데이터셋마다 분리합니다.</p></div></section><section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>데이터셋 ${datasets.length}개</h2><p>검수 ${reviewed} · v${VERSION}</p></div><div class="v7-catalog">${catalogCards}</div><p class="v6-index-note"><a href="${BASE}/data/dataset-catalog.json">dataset-catalog.json</a> · <a href="${BASE}/llms.txt">llms.txt</a></p></div></section></main>${footer}${scripts}</body></html>`;write('data/catalog/index.html',catalogPage);
const answerRows=answers.map(a=>`<tr><th>${a.question}</th><td>${a.answer}<br><a href="${a.source}">근거 페이지</a></td><td><code>${a.status}</code></td></tr>`).join('');
const answerPage=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 비용 질문 답변 데이터 | AEO 인덱스</title><meta name="description" content="공사비지수, 건설업 임금, 공공 공종 단가, 32평 실제 견적 통계 등 자주 묻는 질문을 출처와 공개상태와 함께 제공합니다."><link rel="canonical" href="${SITE}/data/answers/">${styles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">ANSWER INDEX</p><h1>인테리어 비용 답변 데이터</h1><p>질문마다 현재 답변·근거 URL·통계 공개상태를 함께 둡니다.</p></div></section><section class="v6-section"><div class="site-shell"><table class="v7-aeo"><thead><tr><th>질문</th><th>답변</th><th>상태</th></tr></thead><tbody>${answerRows}</tbody></table><p class="v6-index-note"><a href="${BASE}/data/answer-index.json">answer-index.json</a></p></div></section></main>${footer}${scripts}</body></html>`;write('data/answers/index.html',answerPage);
const market=`<section class="v7-market" data-v7-market><div class="v7-market-head"><h2>견적 데이터 로컬 탐색기</h2><p>CSV를 업로드하거나 붙여넣어 브라우저 안에서만 검증·필터·정규화합니다. 서버 전송 없음.</p></div><div class="v7-filebox"><div><div class="v7-drop" data-v7-drop><div><strong>CSV 파일 끌어놓기</strong><span>또는 파일 선택</span><input type="file" accept=".csv,text/csv" data-v7-file></div></div><label class="sr-only" for="v7-paste">CSV 붙여넣기</label><textarea id="v7-paste" data-v7-paste style="width:100%;min-height:140px;margin-top:10px;border:1px solid var(--v6-line);border-radius:0;padding:10px;font:11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace" placeholder="CSV 붙여넣기"></textarea><div class="v7-actions"><button type="button" data-v7-run>검증·분석</button><button type="button" data-v7-example>템플릿 예시</button><button type="button" data-v7-export-json disabled>정규화 JSON</button><button type="button" data-v7-export-csv disabled>정규화 CSV</button><a href="${BASE}/data/quote-sample-template.csv">CSV 템플릿</a></div></div><aside class="v7-quality"><div class="v7-quality-row"><span>검수 통과</span><strong data-v7-valid>0건</strong></div><div class="v7-quality-row"><span>검증 메시지</span><strong data-v7-invalid>0건</strong></div><div class="v7-quality-row"><span>유효행 비율</span><strong data-v7-valid-ratio>—</strong></div><div class="v7-quality-row"><span>VAT 상태 기재율</span><strong data-v7-vat-known>—</strong></div><div class="v7-quality-row"><span>공종금액 입력률</span><strong data-v7-trade-cover>—</strong></div></aside></div><div class="v7-filterbar"><label>지역<select data-v7-region><option value="">전체 지역</option></select></label><label>평수<select data-v7-band><option value="">전체 평수</option></select></label><label>공사범위<select data-v7-scope><option value="">전체 범위</option></select></label><label>건물유형<select data-v7-building><option value="">전체 건물</option></select></label></div><div class="v7-statline"><div class="v7-stat"><span>N</span><strong data-v7-n>0건</strong><em data-v7-gate-note>N 기준 확인</em></div><div class="v7-stat"><span>P25</span><strong data-v7-p25>보류</strong></div><div class="v7-stat"><span>중앙값</span><strong data-v7-median>보류</strong></div><div class="v7-stat"><span>P75</span><strong data-v7-p75>보류</strong></div><div class="v7-stat"><span>평당 중앙값</span><strong data-v7-per>보류</strong></div></div><details class="v7-errors"><summary>행별 검증 메시지</summary><table><thead><tr><th>행</th><th>필드</th><th>메시지</th></tr></thead><tbody data-v7-error-body><tr><td colspan="3">검증 전</td></tr></tbody></table></details></section>`;
const marketPage=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>인테리어 견적 데이터 탐색기 | CSV 검증·필터·중앙값</title><meta name="description" content="익명 견적 CSV를 로컬에서 검증하고 지역·평수·공사범위로 필터해 N 기준 충족 시 중앙값·P25·P75를 확인합니다."><link rel="canonical" href="${SITE}/quote-market/">${styles}</head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">LOCAL QUOTE EXPLORER</p><h1>견적 데이터 탐색기</h1><p>원본 견적을 서버에 올리지 않고 검증·정규화·필터 통계를 확인합니다.</p></div></section><section class="v6-section"><div class="site-shell">${market}</div></section></main>${footer}${scripts}</body></html>`;write('quote-market/index.html',marketPage);

function pyeongBlock(p){const c=roundedCell(p),published=c?.status==='published',d=c?.distribution?.total_amount_manwon,per=c?.distribution?.per_supply_pyeong_manwon;return `<section class="v7-pyeong-stat"><div class="v7-pyeong-stat-head"><strong>${p}평 실제 견적 표본</strong><span>QUOTE · 동일 반올림 공급평수 · N 기준 적용</span></div><div class="v7-pyeong-stat-grid"><div><span>N</span><strong>${c?.n||0}건</strong></div><div><span>P25</span><strong>${published&&d?fmt(d.p25)+'만원':'보류'}</strong></div><div><span>중앙값</span><strong>${published&&d?fmt(d.median)+'만원':'보류'}</strong></div><div><span>평당 중앙값</span><strong>${published&&per?fmt(per.median)+'만원/평':'보류'}</strong></div></div><p class="v7-withheld">${published?'P75 '+fmt(d?.p75)+'만원 · 실제 검수 표본 분포':'가격 통계는 세그먼트 N≥'+(stats.segment_threshold||20)+'일 때만 공개'} · <a href="${BASE}/data/quote-statistics/">집계 기준</a></p></section>`}
for(const p of [24,30,32,34,40]){const rel=`interior-cost/${p}-pyeong/index.html`;if(!fs.existsSync(path.join(ROOT,rel)))continue;let h=read(rel);if(!h.includes('v7-pyeong-stat'))h=h.replace('<article class="article-body">',`<article class="article-body">${pyeongBlock(p)}`);write(rel,h)}
const tradeMap={bathroom:'bathroom_manwon',kitchen:'kitchen_manwon',wallpaper:'wallpaper_manwon',floor:'flooring_manwon',carpentry:'carpentry_manwon',electrical:'electrical_manwon',window:'window_manwon'};
for(const [slug,field] of Object.entries(tradeMap)){const rel=`cost/${slug}/index.html`;if(!fs.existsSync(path.join(ROOT,rel)))continue;const t=stats.overall?.distribution?.trade_amounts?.[field];let h=read(rel);const block=`<section class="v7-trade-stat"><div class="v7-trade-stat-head"><strong>실제 견적 공종 금액 표본</strong><span>QUOTE · ${field}</span></div><div class="v7-trade-stat-grid"><div><span>N</span><strong>${t?.n||0}건</strong></div><div><span>P25</span><strong>${t?fmt(t.p25)+'만원':'보류'}</strong></div><div><span>중앙값</span><strong>${t?fmt(t.median)+'만원':'보류'}</strong></div><div><span>P75</span><strong>${t?fmt(t.p75)+'만원':'보류'}</strong></div></div><p class="v7-withheld">${t?'공종별 금액 기재 표본에서 계산':'공종별 유효 표본 N≥'+(stats.segment_threshold||20)+' 전까지 가격통계 보류'} · 전체 견적 포함조건과 별도 확인</p></section>`;if(!h.includes('v7-trade-stat'))h=h.replace('<article class="article-body">',`<article class="article-body">${block}`);write(rel,h)}

const rail=`<section class="v7-rail"><div class="site-shell"><div class="v7-rail-grid"><a href="${BASE}/quote-market/"><span>LOCAL TOOL</span><strong>견적 데이터 탐색기</strong><em>CSV · 필터 · N gate</em></a><a href="${BASE}/data/quote-statistics/"><span>QUOTE</span><strong>실제 견적 집계</strong><em>N=${stats.sample_count||0} · ${quoteState}</em></a><a href="${BASE}/data/public-unit-cost/"><span>REFERENCE</span><strong>공공 공종 단가</strong><em>${unit.items?.length||0} items · 2026-H2</em></a><a href="${BASE}/data/catalog/"><span>CATALOG</span><strong>데이터 출처·범위</strong><em>${datasets.length} datasets</em></a></div></div></section>`;
let home=read('index.html');home=home.replace(/데이터 v6\.7\.0/g,`데이터 v${VERSION}`);if(!home.includes('v7-rail'))home=home.replace('</section>\n<section class="v6-section">',`</section>${rail}<section class="v6-section">`);write('index.html',home);
let data=read('data/index.html');data=data.replace(/데이터 v6\.7\.0/g,`데이터 v${VERSION}`);if(!data.includes('/data/catalog/'))data=data.replace('<div class="v62-data-links">',`<div class="v62-data-links"><a href="${BASE}/data/catalog/"><strong>데이터 카탈로그</strong><span>출처 · 적용범위 · JSON 엔드포인트</span></a><a href="${BASE}/data/answers/"><strong>답변 데이터</strong><span>AEO 질문 · 답변 · 근거 URL</span></a><a href="${BASE}/quote-market/"><strong>견적 데이터 탐색기</strong><span>로컬 CSV · 필터 · 중앙값 게이트</span></a>`);write('data/index.html',data);
try{const latest=json('data/latest.json',{});latest.version=VERSION;latest.updated=reviewed;latest.v7={dataset_catalog:`${BASE}/data/dataset-catalog.json`,answer_index:`${BASE}/data/answer-index.json`,quote_intelligence:`${BASE}/data/quote-intelligence.json`,local_explorer:`${BASE}/quote-market/`,llms:`${BASE}/llms.txt`};write('data/latest.json',JSON.stringify(latest,null,2))}catch{}
try{const versions=json('data/versions.json',[]);if(!versions.some(x=>x.version===VERSION))versions.unshift({version:VERSION,date:reviewed,changes:['대형 배치: 로컬 견적 탐색기','CSV 파일 업로드·드래그앤드롭·행별 검증','VAT 정규화·공종합계 이상 검증','지역·평수·범위 필터 통계','평수/공종 페이지 실제 견적 집계 자동 연결','데이터 카탈로그·AEO 답변 인덱스·llms.txt','기계가독 quote-intelligence.json']});write('data/versions.json',JSON.stringify(versions,null,2))}catch{}
try{const search=json('data/search-index.json',[]);for(const row of [{title:'견적 데이터 탐색기',url:`${BASE}/quote-market/`,type:'도구',description:'익명 견적 CSV를 로컬 검증하고 지역·평수·공사범위 필터 통계를 계산합니다.',keywords:['인테리어 견적 csv','인테리어 견적 중앙값 계산','32평 인테리어 견적 데이터']},{title:'인테리어 비용 데이터 카탈로그',url:`${BASE}/data/catalog/`,type:'데이터',description:'공식·참고·실제견적 데이터의 출처와 적용범위를 데이터셋별로 확인합니다.',keywords:['인테리어 비용 데이터','인테리어 공사비 출처']},{title:'인테리어 비용 답변 데이터',url:`${BASE}/data/answers/`,type:'데이터',description:'주요 인테리어 비용 질문의 현재 답변과 근거 URL을 제공합니다.',keywords:['32평 인테리어 비용','건설공사비지수','인테리어 견적 중앙값']}])if(!search.some(x=>x.url===row.url))search.push(row);write('data/search-index.json',JSON.stringify(search,null,2))}catch{}
try{let sm=read('sitemap.xml');for(const p of ['quote-market/','data/catalog/','data/answers/'])if(!sm.includes(`/${p}`))sm=sm.replace('</urlset>',`<url><loc>${SITE}/${p}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap.xml',sm)}catch{}
const html=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);e.isDirectory()?walk(f):e.name.endsWith('.html')&&html.push(f)}};walk(ROOT);for(const f of html){let h=fs.readFileSync(f,'utf8');if(!h.includes('site-v7.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v7.css?v=${build}"></head>`);if(!h.includes('app-v7.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v7.js?v=${build}" defer></script></body>`);fs.writeFileSync(f,h)}
const report=json('data/v6-report.json',{});Object.assign(report,{version:VERSION,v7_bulk_batch:true,v7_local_quote_explorer:fs.existsSync(path.join(ROOT,'quote-market/index.html')),v7_dataset_catalog:fs.existsSync(path.join(ROOT,'data/catalog/index.html')),v7_answer_index:fs.existsSync(path.join(ROOT,'data/answers/index.html')),v7_machine_catalog:fs.existsSync(path.join(ROOT,'data/dataset-catalog.json')),v7_quote_intelligence:fs.existsSync(path.join(ROOT,'data/quote-intelligence.json')),v7_llms_txt:fs.existsSync(path.join(ROOT,'llms.txt')),v7_pyeong_integration:[24,30,32,34,40].every(p=>read(`interior-cost/${p}-pyeong/index.html`).includes('v7-pyeong-stat')),v7_trade_integration:Object.keys(tradeMap).every(s=>read(`cost/${s}/index.html`).includes('v7-trade-stat')),v7_assets_injected:html.every(f=>{const h=fs.readFileSync(f,'utf8');return h.includes('site-v7.css')&&h.includes('app-v7.js')}),home_version_consistent:read('index.html').includes(`데이터 v${VERSION}`)});write('data/v6-report.json',JSON.stringify(report,null,2));if(!report.v7_bulk_batch||!report.v7_local_quote_explorer||!report.v7_dataset_catalog||!report.v7_answer_index||!report.v7_machine_catalog||!report.v7_quote_intelligence||!report.v7_llms_txt||!report.v7_pyeong_integration||!report.v7_trade_integration||!report.v7_assets_injected||!report.home_version_consistent)throw new Error(`v7 validation failed ${JSON.stringify(report)}`);console.log(JSON.stringify(report,null,2));
