import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',VERSION='6.5.0';
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)},json=r=>JSON.parse(read(r));
const reviewed=(()=>{try{return json('data/v5-report.json').reviewed_on}catch{return new Date().toISOString().slice(0,10)}})();
const css=fs.readFileSync(path.join(CORE,'site-v6-5.css'),'utf8'),js=fs.readFileSync(path.join(CORE,'app-v6-5.js'),'utf8'),build=crypto.createHash('sha1').update(css+'\n'+js).digest('hex').slice(0,10);write('assets/site-v6-5.css',css);write('assets/app-v6-5.js',js);

function normalizer(){return `<section class="v65-normalizer" id="unit-normalizer" data-v65-normalizer><div class="v65-head"><h2>내 견적 단가 역산</h2><p>COMPARE · 견적금액 ÷ 수량으로 내 단가를 구한 뒤 같은 공공 세부공종과 나란히 봅니다. 조건이 맞기 전에는 차이율을 숨깁니다.</p></div><div class="v65-fields"><label>비교 공종<select data-v65-item aria-label="비교 공종"></select></label><label>내 견적 금액(만원)<input data-v65-amount type="number" min="0" step="0.1" inputmode="decimal" placeholder="120"></label><label>수량<input data-v65-qty type="number" min="0" step="0.1" inputmode="decimal" placeholder="30"></label></div><div class="v65-condition"><label><input type="checkbox" data-v65-scope-match><span>공정 범위가 동일함<small>시공방법·규격·포함 작업이 선택한 공공 세부공종과 같은지 확인</small></span></label><label><input type="checkbox" data-v65-exclude-match><span>제외 조건을 맞췄음<small>주재료비·바탕작업·보양 등 공공 단가에서 빠진 비용을 같은 기준으로 제외</small></span></label></div><div class="v65-comparison"><div class="v65-metric"><span>내 견적 역산 단가</span><strong data-v65-user-unit>금액·수량 입력</strong><em>입력한 견적금액 ÷ 수량</em></div><div class="v65-metric"><span>공공 참고 단가</span><strong data-v65-ref-unit>—</strong><em>2026 하반기 표준시장단가</em></div><div class="v65-metric v65-delta" data-state="blocked"><span>단순 차이율</span><strong data-v65-delta>조건 미확인</strong><em data-v65-delta-note>공정범위와 제외조건을 확인해야 표시합니다.</em></div></div><p class="v65-item-note" data-v65-item-note>세부코드·규격·제외조건을 불러오는 중입니다.</p><p class="v65-rule"><b>판정하지 않음:</b> 차이율은 같은 조건으로 정규화됐을 때 두 숫자의 산술 차이만 보여줍니다. 업체 마진·현장 난이도·최소작업량·관리비 등을 반영한 적정가격 판정이 아닙니다.</p></section>`}

let calc=read('calculator/index.html');if(!calc.includes('data-v65-normalizer'))calc=calc.replace('<article class="tool-article">',`${normalizer()}<article class="tool-article">`);calc=calc.replace('수량 × 입력 단가 · VAT · 공사비지수 · 공공 공종 참고계산','수량 × 입력 단가 · 공사비지수 · 공공단가 · 내 견적 단가 역산');write('calculator/index.html',calc);
let unit=read('data/public-unit-cost/index.html');if(!unit.includes('data-v65-normalizer'))unit=unit.replace('</main>',`<section class="v6-section"><div class="site-shell">${normalizer()}</div></section></main>`);
const unitData=json('data/public-unit-cost-2026-h2.json');for(const item of unitData.items||[]){const old=`<a href="${BASE}/calculator/?ref=${encodeURIComponent(item.code)}#public-reference">계산</a>`;const next=`<a href="${BASE}/calculator/?ref=${encodeURIComponent(item.code)}#public-reference">계산</a><br><a href="${BASE}/calculator/?ref=${encodeURIComponent(item.code)}#unit-normalizer">내 단가 비교</a>`;unit=unit.split(old).join(next)}write('data/public-unit-cost/index.html',unit);

let data=read('data/index.html');data=data.replace(/데이터 v6\.4\.0/g,`데이터 v${VERSION}`);data=data.replace('사용자 입력 · 공사비지수 · 공공단가 × 수량','사용자 입력 · 공사비지수 · 공공단가 × 수량 · 내 단가 역산');write('data/index.html',data);
let home=read('index.html');home=home.replace(/데이터 v6\.4\.0/g,`데이터 v${VERSION}`);write('index.html',home);
try{const latest=json('data/latest.json');latest.version=VERSION;latest.updated=reviewed;latest.unit_normalizer={formula:'user_quote_amount / quantity',comparison_gate:['same_scope','same_exclusions'],verdict:false};write('data/latest.json',JSON.stringify(latest,null,2))}catch{}
try{const versions=json('data/versions.json');if(!versions.some(x=>x.version===VERSION))versions.unshift({version:VERSION,date:reviewed,changes:['내 견적 단가 역산','공정범위·제외조건 비교 게이트','조건 일치 시 공공 참고단가 차이율','적정가격 판정 금지']});write('data/versions.json',JSON.stringify(versions,null,2))}catch{}
try{const search=json('data/search-index.json');const row=search.find(x=>x.url===`${BASE}/calculator/`);if(row){row.keywords=[...(row.keywords||[]),'견적 단가 역산','타일 견적 단가 비교','도배 견적 단가 비교','방수 견적 단가 비교'];row.description='인테리어 예산, 공사비지수 환산, 공공단가 × 수량 계산과 내 견적의 단위당 금액 역산 비교를 제공합니다.'}write('data/search-index.json',JSON.stringify(search,null,2))}catch{}

const html=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);e.isDirectory()?walk(f):e.name.endsWith('.html')&&html.push(f)}};walk(ROOT);for(const f of html){let h=fs.readFileSync(f,'utf8');if(!h.includes('site-v6-5.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v6-5.css?v=${build}"></head>`);if(!h.includes('app-v6-5.js'))h=h.replace('</body>',`<script src="${BASE}/assets/app-v6-5.js?v=${build}" defer></script></body>`);fs.writeFileSync(f,h)}
const report=json('data/v6-report.json');Object.assign(report,{version:VERSION,unit_normalizer:read('calculator/index.html').includes('data-v65-normalizer'),comparison_gate:read('calculator/index.html').includes('data-v65-scope-match')&&read('calculator/index.html').includes('data-v65-exclude-match'),difference_hidden_until_match:js.includes("delta.dataset.state='blocked'")&&js.includes('!scopeOk||!excludeOk'),unit_normalizer_on_public_data:read('data/public-unit-cost/index.html').includes('data-v65-normalizer'),unit_compare_deep_links:read('data/public-unit-cost/index.html').includes('#unit-normalizer'),home_version_consistent:read('index.html').includes(`데이터 v${VERSION}`),v65_assets_injected:html.every(f=>{const h=fs.readFileSync(f,'utf8');return h.includes('site-v6-5.css')&&h.includes('app-v6-5.js')})});write('data/v6-report.json',JSON.stringify(report,null,2));if(!report.unit_normalizer||!report.comparison_gate||!report.difference_hidden_until_match||!report.unit_normalizer_on_public_data||!report.unit_compare_deep_links||!report.home_version_consistent||!report.v65_assets_injected)throw new Error(`v6.5 validation failed ${JSON.stringify(report)}`);console.log(JSON.stringify(report,null,2));
