import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT=path.resolve('docs/interior-cost-preview'),CORE=path.resolve('interior-cost-core');
const BASE='/pm-lab/interior-cost-preview',SITE='https://5ggul.github.io/pm-lab/interior-cost-preview',VERSION='6.3.0';
const officialNotice='https://www.codil.or.kr/helpdesk/read.do?bbsId=BBSMSTR_900000000204&nttId=13281';
const items=[
 {code:'MA110.20040',group:'욕실·타일',name:'타일 압착붙이기 / 벽면',spec:'0.21~0.40㎡ 이하',unit:'㎡',price:38903,labor:97,scope:'모르타르 비빔·타일붙임·줄눈·마무리',exclude:'타일·모르타르·줄눈 재료비 제외',match:['bathroom'],detail:'https://it7.kr/solutions/public-cost/item/MA110.20040/'},
 {code:'MA310.00240',group:'욕실·타일',name:'타일 압착붙이기 / 바닥면',spec:'0.21~0.40㎡ 이하',unit:'㎡',price:31822,labor:97,scope:'모르타르 압착붙이기·줄눈·마무리',exclude:'타일·모르타르·줄눈 재료비 제외',match:['bathroom','floor'],detail:'https://it7.kr/solutions/public-cost/items/'},
 {code:'HI000.20000',group:'욕실·방수',name:'시멘트액체방수 / 벽',spec:'수직부',unit:'㎡',price:16226,labor:97,scope:'바탕청소·방수작업·담수시험',exclude:'재료비 제외',match:['bathroom'],detail:'https://it7.kr/solutions/public-cost/item/HI000.20000/'},
 {code:'HI000.30000',group:'욕실·방수',name:'시멘트액체방수 / 바닥',spec:'바닥',unit:'㎡',price:18961,labor:97,scope:'바탕청소·방수작업·담수시험',exclude:'재료비 제외',match:['bathroom'],detail:'https://it7.kr/solutions/public-cost/item/HI000.30000/'},
 {code:'OB110.20000',group:'도배',name:'도배지바름 / 벽',spec:'콘크리트·모르타르면',unit:'㎡',price:5993,labor:96,scope:'풀먹임·절단·초배·정배',exclude:'주재료 도배지 제외, 풀 등 잡재료 포함',match:['wallpaper'],detail:'https://it7.kr/solutions/public-cost/item/OB110.20000/'},
 {code:'OB130.20000',group:'도배',name:'도배지바름 / 천장',spec:'콘크리트·모르타르면',unit:'㎡',price:7737,labor:96,scope:'풀먹임·절단·초배·정배',exclude:'주재료 도배지 제외, 풀 등 잡재료 포함',match:['wallpaper'],detail:'https://it7.kr/solutions/public-cost/item/OB130.20000/'},
 {code:'NC102.20000',group:'도장',name:'수성페인트 롤러칠 / 벽체',spec:'1회',unit:'㎡',price:3380,labor:98,scope:'롤러칠·보조 붓칠·공구손료',exclude:'페인트 재료비·바탕만들기·보양 별도',match:[],detail:'https://it7.kr/solutions/public-cost/item/NC102.20000/'},
 {code:'IB310.00600',group:'목공',name:'벽체 띠장 설치',spec:'틀간격 45~60㎝',unit:'㎡',price:9184,labor:96,scope:'목조 벽체틀 절단·설치',exclude:'주재료 각재 제외, 못 등 잡재료 포함',match:['carpentry'],detail:'https://it7.kr/solutions/public-cost/item/IB310.00600/'},
 {code:'IA400.10000',group:'목공·바닥',name:'목조 마루 설치',spec:'마루틀·바탕·마루널',unit:'㎡',price:42993,labor:95,scope:'마루틀·합판 바탕·목조 마루널 설치',exclude:'목재·합판 등 주재료 제외, 일반 강마루/장판과 다른 공종',match:['floor','carpentry'],detail:'https://it7.kr/solutions/public-cost/item/IA400.10000/'},
 {code:'GH120.01000',group:'창호',name:'우레탄폼 충전 / 창호주위',spec:'창호틀 주위',unit:'m',price:2335,labor:98,scope:'바탕정리·우레탄 충전·마무리',exclude:'재료비·방수코킹 제외',match:['window'],detail:'https://it7.kr/solutions/public-cost/item/GH120.01000/'}
];
const read=r=>fs.readFileSync(path.join(ROOT,r),'utf8'),write=(r,c)=>{const f=path.join(ROOT,r);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)},json=r=>JSON.parse(read(r)),fmt=n=>Number(n).toLocaleString('ko-KR');
const reviewed=(()=>{try{return json('data/v5-report.json').reviewed_on}catch{return new Date().toISOString().slice(0,10)}})();
const css=fs.readFileSync(path.join(CORE,'site-v6-3.css'),'utf8'),cssHash=crypto.createHash('sha1').update(css).digest('hex').slice(0,10);write('assets/site-v6-3.css',css);
const card=i=>`<article class="v63-unit-card"><span class="code">${i.code}</span><h3>${i.name}</h3><div class="v63-unit-price"><b>${fmt(i.price)}원</b><span>/${i.unit}</span></div><p>${i.spec} · 노무비율 ${i.labor}%<br>${i.exclude}</p><a href="${i.detail}" rel="noopener">항목 조건 확인</a></article>`;
const block=(title,rows)=>`<section class="v63-unit-section"><div class="v63-unit-head"><strong>${title}</strong><span>2026 하반기 표준시장단가 · 공공 건설 예정가격 참고</span></div><div class="v63-unit-list">${rows.map(card).join('')}</div><div class="v63-unit-warning">이 숫자는 아파트 인테리어 소비자 시장가가 아닙니다. 표시된 공정·규격의 공공 건설 기준 단가이며, 주재료비 제외 항목이 많습니다. <a href="${BASE}/data/public-unit-cost/">적용범위 전체 보기</a></div></section>`;
for(const slug of ['bathroom','wallpaper','carpentry','floor','window']){const rows=items.filter(i=>i.match.includes(slug));if(!rows.length)continue;const rel=`cost/${slug}/index.html`;let h=read(rel);if(!h.includes('v63-unit-section'))h=h.replace('<article class="article-body">',`<article class="article-body">${block('공공 공종 단가 참고',rows)}`);write(rel,h)}
let hub=read('cost/index.html');if(!hub.includes('/data/public-unit-cost/'))hub=hub.replace('<article class="article-body">',`<article class="article-body"><section class="v63-unit-section"><div class="v63-unit-head"><strong>2026 하반기 공공 공종 단가</strong><span>타일 · 방수 · 도배 · 도장 · 목공 · 창호</span></div><div class="v63-unit-warning">공공 건설 예정가격용 표준시장단가에서 인테리어와 가까운 공종만 별도 정리했습니다. <a href="${BASE}/data/public-unit-cost/">단가 데이터 보기</a></div></section>`);write('cost/index.html',hub);

const template=read('data/index.html'),header=template.match(/<header[\s\S]*?<\/header>/)?.[0]||'',footer=template.match(/<footer[\s\S]*?<\/footer>/)?.[0]||'',styles=[...template.matchAll(/<link rel="stylesheet" href="[^"]+">/g)].map(x=>x[0]).join(''),scripts=[...template.matchAll(/<script src="[^"]+" defer><\/script>/g)].map(x=>x[0]).join('');
const desc='국토교통부 2026년 하반기 건설공사 표준시장단가 중 타일·방수·도배·도장·목공·창호 등 인테리어 관련 공종을 적용조건과 함께 확인합니다.';
const schema={'@context':'https://schema.org','@type':'Dataset',name:'2026년 하반기 인테리어 관련 공공 공종 단가',description:desc,dateModified:reviewed,creator:{'@type':'Organization',name:'국토교통부·한국건설기술연구원'},isBasedOn:officialNotice,distribution:{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:`${SITE}/data/public-unit-cost-2026-h2.json`}};
const rows=items.map(i=>`<tr><th><span class="code">${i.code}</span><br>${i.name}<small>${i.spec}</small></th><td class="money">${fmt(i.price)}원/${i.unit}<small>노무 ${i.labor}%</small></td><td>${i.scope}<small>${i.exclude}</small></td><td><a href="${i.detail}" rel="noopener">조건</a></td></tr>`).join('');
const page=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><title>2026 인테리어 공종 단가 | 타일·방수·도배·도장</title><meta name="description" content="${desc}"><link rel="canonical" href="${SITE}/data/public-unit-cost/">${styles}<script type="application/ld+json">${JSON.stringify(schema)}</script></head><body>${header}<main><section class="v62-data-hero"><div class="site-shell"><p class="kicker">OFFICIAL REFERENCE</p><h1>2026 하반기 공공 공종 단가</h1><p>민간 아파트 인테리어 평균 견적이 아니라 공공 건설 예정가격 작성용 표준시장단가입니다. 단가 숫자만 떼지 않고 규격·재료비 제외·노무비율을 함께 표시합니다.</p></div></section><section class="v6-section"><div class="site-shell"><div class="v6-section-head"><h2>인테리어 관련 공종 ${items.length}개</h2><p>국토교통부 공고 제2026-652호 · 2026-05-08</p></div><div class="v63-filter-links"><a href="#bath">욕실·타일·방수</a><a href="#finish">도배·도장</a><a href="#wood">목공·바닥</a><a href="#window">창호</a></div><div class="table-wrap"><table class="v63-unit-table"><thead><tr><th>공종·규격</th><th>단가</th><th>포함·제외 조건</th><th>상세</th></tr></thead><tbody>${rows}</tbody></table></div><p class="v63-unit-warning">표준시장단가는 국가·지자체·공공기관 등의 건설공사 예정가격을 위한 기초자료입니다. 실제 아파트 리모델링 견적은 현장조건, 최소작업량, 자재, 철거·양중·보양·관리비 등에 따라 달라집니다.</p><p class="v6-index-note"><a href="${officialNotice}" rel="noopener">CODIL 공식 공고</a> · <a class="v62-json" href="${BASE}/data/public-unit-cost-2026-h2.json">JSON 데이터</a></p></div></section></main>${footer}${scripts}</body></html>`;write('data/public-unit-cost/index.html',page);
write('data/public-unit-cost-2026-h2.json',JSON.stringify({version:VERSION,period:'2026-H2',published:'2026-05-08',checked:reviewed,notice:'국토교통부 공고 제2026-652호',official_source:officialNotice,scope:'공공 건설공사 예정가격 참고',not_for:'민간 아파트 인테리어 시장평균 또는 적정가격 판정',items},null,2));
let data=read('data/index.html');if(!data.includes('/data/public-unit-cost/'))data=data.replace('<div class="v62-data-links">',`<div class="v62-data-links"><a href="${BASE}/data/public-unit-cost/"><strong>공공 공종 단가</strong><span>타일·방수·도배·도장·목공·창호</span></a>`);write('data/index.html',data);
try{const s=json('data/search-index.json');if(!s.some(x=>x.url===`${BASE}/data/public-unit-cost/`))s.push({title:'2026 하반기 공공 공종 단가',url:`${BASE}/data/public-unit-cost/`,type:'데이터',description:desc,keywords:['타일 시공 단가','방수 단가','도배 단가','페인트 단가','목공 단가','창호 우레탄폼']});write('data/search-index.json',JSON.stringify(s,null,2))}catch{}
try{const v=json('data/versions.json');if(!v.some(x=>x.version===VERSION))v.unshift({version:VERSION,date:reviewed,changes:['2026 하반기 공공 공종 단가 10개','욕실·도배·목공·바닥·창호 페이지 단가 매칭','공종 단가 JSON 데이터']});write('data/versions.json',JSON.stringify(v,null,2))}catch{}
try{const l=json('data/latest.json');l.version=VERSION;l.updated=reviewed;l.public_unit_cost={period:'2026-H2',item_count:items.length,url:`${BASE}/data/public-unit-cost/`};write('data/latest.json',JSON.stringify(l,null,2))}catch{}
try{let s=read('sitemap-production.xml'),u=`${SITE}/data/public-unit-cost/`;if(!s.includes(u))s=s.replace('</urlset>',`<url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url></urlset>`);write('sitemap-production.xml',s)}catch{}
let home=read('index.html');home=home.replace(/데이터 v6\.2\.0/g,`데이터 v${VERSION}`);write('index.html',home);
const html=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);e.isDirectory()?walk(f):e.name.endsWith('.html')&&html.push(f)}};walk(ROOT);for(const f of html){let h=fs.readFileSync(f,'utf8');if(!h.includes('site-v6-3.css'))h=h.replace('</head>',`<link rel="stylesheet" href="${BASE}/assets/site-v6-3.css?v=${cssHash}"></head>`);fs.writeFileSync(f,h)}
const report=json('data/v6-report.json');Object.assign(report,{version:VERSION,public_unit_cost_page:fs.existsSync(path.join(ROOT,'data/public-unit-cost/index.html')),public_unit_cost_json:fs.existsSync(path.join(ROOT,'data/public-unit-cost-2026-h2.json')),public_unit_cost_count:items.length,unit_cost_mapped_pages:['bathroom','wallpaper','carpentry','floor','window'].every(x=>read(`cost/${x}/index.html`).includes('v63-unit-section')),home_version_consistent:read('index.html').includes(`데이터 v${VERSION}`),v63_assets_injected:html.every(f=>fs.readFileSync(f,'utf8').includes('site-v6-3.css'))});write('data/v6-report.json',JSON.stringify(report,null,2));if(!report.public_unit_cost_page||!report.public_unit_cost_json||report.public_unit_cost_count!==10||!report.unit_cost_mapped_pages||!report.home_version_consistent||!report.v63_assets_injected)throw new Error(`v6.3 validation failed ${JSON.stringify(report)}`);console.log(JSON.stringify(report,null,2));
