import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {BASE,SITE,UPDATED,nav,coreItems,itemDictionary,aliases,publicSources,quoteSamples,methodology,versions,sizes,works,guides} from './data-v5.mjs';

const ROOT=path.resolve('docs/interior-cost-preview');
const CORE=path.resolve('interior-cost-core');
const BUILD=crypto.createHash('sha1').update(fs.readFileSync(path.join(CORE,'site-v5.css'))).digest('hex').slice(0,10);
fs.rmSync(ROOT,{recursive:true,force:true});
fs.mkdirSync(path.join(ROOT,'assets'),{recursive:true});
fs.mkdirSync(path.join(ROOT,'data'),{recursive:true});
fs.copyFileSync(path.join(CORE,'site-v5.css'),path.join(ROOT,'assets','site-v5.css'));
fs.copyFileSync(path.join(CORE,'app-v5.js'),path.join(ROOT,'assets','app-v5.js'));

const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const write=(rel,content)=>{const f=path.join(ROOT,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,content)};
const asset=n=>`${BASE}/assets/${n}?v=${BUILD}`;
const itemBy=id=>itemDictionary.find(x=>x.id===id);

function header(){return `<header class="site-header"><div class="site-shell header-row"><a class="wordmark" href="${BASE}/">견적검수실</a><nav class="desktop-nav" aria-label="주요 메뉴">${nav.map(([n,u])=>`<a href="${BASE}${u}">${n}</a>`).join('')}</nav><form class="header-search" data-site-search><label class="sr-only" for="site-search">사이트 검색</label><input id="site-search" name="q" placeholder="32평 · 욕실 · VAT · 폐기물"><button>검색</button></form><button class="menu-btn" type="button" data-menu-btn aria-expanded="false" aria-controls="mobile-drawer">메뉴</button></div><div id="mobile-drawer" class="mobile-drawer" data-mobile-drawer hidden>${nav.map(([n,u])=>`<a href="${BASE}${u}">${n}</a>`).join('')}<a href="${BASE}/data/methodology/">데이터 기준</a></div></header>`}
function footer(){return `<footer class="site-footer"><div class="site-shell footer-grid"><div><strong>견적검수실</strong><p>인테리어 견적 항목·조건 표준화 도구.</p></div><nav aria-label="사이트 안내"><a href="${BASE}/about/">소개</a><a href="${BASE}/contact/">연락</a><a href="${BASE}/privacy/">개인정보</a><a href="${BASE}/terms/">이용약관</a><a href="${BASE}/disclaimer/">면책</a><a href="${BASE}/editorial-policy/">검수 기준</a><a href="${BASE}/corrections/">정정 요청</a></nav><nav aria-label="데이터 안내"><a href="${BASE}/data/methodology/">산출 원칙</a><a href="${BASE}/data/sources/">출처</a><a href="${BASE}/data/changelog/">변경이력</a><a href="${BASE}/quote-items/">견적 항목 사전</a></nav></div></footer>`}
function meta({title,desc,path:'/',type='website',schema=[]}){const url=`${SITE}${path==='/'?'':path}`;return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><meta name="googlebot" content="noindex,nofollow,noarchive,nosnippet"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${url}"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${url}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="${asset('site-v5.css')}">${schema.map(x=>`<script type="application/ld+json">${JSON.stringify(x)}</script>`).join('')}`}
function layout(o,body){return `<!doctype html><html lang="ko"><head>${meta(o)}</head><body>${header()}<main>${body}</main>${footer()}<div id="site-toast" hidden></div><script src="${asset('app-v5.js')}" defer></script></body></html>`}
function crumb(items){return `<nav class="breadcrumbs" aria-label="현재 위치">${items.map(([n,u],i)=>i===items.length-1?`<span aria-current="page">${esc(n)}</span>`:`<a href="${BASE}${u}">${esc(n)}</a><span aria-hidden="true">/</span>`).join('')}</nav>`}
function table(headers,rows,caption=''){return `<div class="table-wrap"><table class="data-table">${caption?`<caption>${esc(caption)}</caption>`:''}<thead><tr>${headers.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<${i?'td':'th'}${i?'':' scope="row"'}>${x}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function faq(rows){return `<section class="content-section faq"><h2>자주 묻는 질문</h2>${rows.map(([q,a])=>`<article><h3>${esc(q)}</h3><p>${esc(a)}</p></article>`).join('')}</section>`}
function sideLinks(rows){return `<aside class="side-rail"><strong>같이 확인</strong>${rows.map(([n,u])=>`<a href="${BASE}${u}">${esc(n)}</a>`).join('')}</aside>`}
function schemaBreadcrumb(items){return {'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':items.map(([n,u],i)=>({'@type':'ListItem',position:i+1,name:n,item:`${SITE}${u==='/'?'':u}`}))}}
function docPage({path,title,desc,h1,kicker='실무 가이드',answer,sections=[],faqs=[],links=[]}){const bc=[['홈','/'],[h1,path]], schema=[schemaBreadcrumb(bc),{'@context':'https://schema.org','@type':'Article',headline:h1,dateModified:UPDATED,author:{'@type':'Organization',name:'견적검수실'}}];const body=`<section class="article-hero"><div class="article-shell">${crumb(bc)}<p class="kicker">${esc(kicker)}</p><h1>${esc(h1)}</h1><p class="lead">${esc(answer)}</p><div class="page-meta"><span>최종 검수 ${UPDATED}</span><span>자료 유형 편집 가이드</span></div></div></section><div class="article-layout"><article class="article-body"><section class="direct-answer"><h2>${esc(h1)}에서 먼저 볼 것</h2><p>${esc(answer)}</p></section>${sections.join('')}${faqs.length?faq(faqs):''}<section class="content-section source-note"><h2>데이터와 한계</h2><p>이 페이지는 견적 항목을 같은 기준으로 읽기 위한 편집 가이드입니다. 실제 계약금액이나 시장평균을 단정하지 않습니다. 숫자를 표시할 때는 표본 수·기간·지역·포함조건을 함께 공개합니다.</p><a href="${BASE}/data/methodology/">숫자 표시 기준 보기</a></section></article>${sideLinks(links)}</div>`;write(path==='/'?'index.html':`${path.slice(1)}index.html`,layout({title,desc,path,schema},body))}
function toolSchema(name,path,desc){return [{'@context':'https://schema.org','@type':'WebApplication',name,applicationCategory:'BusinessApplication',operatingSystem:'Web',description:desc,url:`${SITE}${path}`},schemaBreadcrumb([['홈','/'],[name,path]])]}
function toolPage({path,title,desc,h1,lead,toolHtml,after=[],faqs=[]}){const body=`<section class="tool-hero"><div class="site-shell">${crumb([['홈','/'],[h1,path]])}<p class="kicker">견적 도구</p><h1>${esc(h1)}</h1><p class="lead">${esc(lead)}</p><div class="page-meta"><span>서버 전송 없음</span><span>브라우저 저장</span><span>최종 검수 ${UPDATED}</span></div></div></section><div class="tool-page site-shell"><section class="tool-stage">${toolHtml}</section><article class="tool-article">${after.join('')}${faqs.length?faq(faqs):''}<section class="content-section source-note"><h2>해석할 때 주의</h2><p>결과는 견적 조건을 같은 기준으로 읽기 위한 참고입니다. 계약·하자·세무 자문이 아니며 실제 계약 문서와 현장 조건이 우선합니다.</p><a href="${BASE}/data/methodology/">데이터 기준</a></section></article></div>`;write(`${path.slice(1)}index.html`,layout({title,desc,path,schema:toolSchema(h1,path,desc)},body))}

const homeSchema=[{'@context':'https://schema.org','@type':'WebSite',name:'견적검수실',url:SITE},{'@context':'https://schema.org','@type':'Organization',name:'견적검수실',url:SITE}];
const home=`<section class="masthead"><div class="site-shell masthead-grid"><div><p class="kicker">인테리어 견적 표준화</p><h1>아파트 인테리어 견적,<br>총액보다 먼저 조건을 맞춥니다.</h1><p class="masthead-copy">폐기물·VAT·샷시·방수처럼 포함조건이 다르면 총액을 바로 비교할 수 없습니다. 견적서를 표준 공종으로 옮기고 차이를 먼저 확인합니다.</p><form class="mast-search" data-site-search><label for="home-search">평수·공사·견적 항목 검색</label><div><input id="home-search" placeholder="32평 비용 · 욕실 방수 · VAT · 폐기물 · 1식"><button>검색</button></div></form></div><div class="register"><div><span>데이터 버전</span><strong>v5.0.0</strong></div><div><span>마지막 검수</span><strong>${UPDATED}</strong></div><div><span>실제 견적 표본</span><strong>${quoteSamples.length}건</strong></div><div><span>표준 항목 사전</span><strong>${itemDictionary.length}개</strong></div></div></div></section>
<section class="site-shell command-section"><h2>작업 시작</h2><div class="command-list"><a href="${BASE}/quote-check/"><span>01</span><strong>받은 견적 검사</strong><em>누락·별도·사양 확인</em></a><a href="${BASE}/quote-compare/"><span>02</span><strong>업체 3곳 비교</strong><em>VAT·폐기물·샷시 조건 맞추기</em></a><a href="${BASE}/checklist/"><span>03</span><strong>계약 전 항목 확인</strong><em>12개 핵심 항목 저장·인쇄</em></a></div></section>
<section class="site-shell home-section"><div class="section-head"><h2>비용 탐색</h2><a href="${BASE}/interior-cost/">평수별 보기</a></div><div class="facet-root"><div class="facet-tabs" role="tablist"><button role="tab" aria-selected="true" data-panel="facet-size">평수별</button><button role="tab" aria-selected="false" data-panel="facet-work">공사별</button><button role="tab" aria-selected="false" data-panel="facet-situation">상황별</button></div><div id="facet-size" class="facet-panel">${Object.keys(sizes).map(s=>`<a href="${BASE}/interior-cost/${s}-pyeong/">${s}평</a>`).join('')}</div><div id="facet-work" class="facet-panel" hidden>${Object.entries(works).map(([s,w])=>`<a href="${BASE}/cost/${s}/">${esc(w.name)}</a>`).join('')}</div><div id="facet-situation" class="facet-panel" hidden><a href="${BASE}/guides/partial-vs-full/">올수리 / 부분수리</a><a href="${BASE}/guides/old-apartment/">구축</a><a href="${BASE}/guides/window-impact/">샷시 제외</a><a href="${BASE}/guides/vat/">VAT 별도</a></div></div></section>
<section class="site-shell home-section"><div class="section-head"><h2>총액 비교가 틀리는 예</h2><a href="${BASE}/quote-compare/">직접 비교</a></div>${table(['조건','A 업체','B 업체','C 업체'],[['표시 총액','예시 5,000','예시 5,500','예시 5,200'],['VAT','포함','별도','미기재'],['폐기물','포함','포함','별도'],['욕실','1식','세부 기재','1식'],['샷시','제외','제외','포함']],'예시 견적 — 실제 시장 통계가 아님')}<p class="matrix-conclusion warning">현재 조건에서는 단순 총액 비교 불가</p></section>
<section class="site-shell home-section"><div class="section-head"><h2>견적 구조 사전</h2><a href="${BASE}/quote-items/">전체 ${itemDictionary.length}개</a></div>${table(['표준 항목','견적서 표현','비교 전에 확인'],itemDictionary.slice(0,10).map(x=>[x.name,esc(x.aliases.join(' · ')),esc(x.compare_before.join(' · '))]),'견적서 표준화 편집 사전')}</section>
<section class="site-shell home-section methodology-preview"><h2>숫자를 표시하는 기준</h2><div class="rule-columns"><div><strong>표시하는 것</strong><p>출처·기준일·조건이 확인되는 공공 원자료와 사용자가 직접 입력한 예산 시나리오.</p></div><div><strong>숨기는 것</strong><p>표본 수 없는 평균, 가상의 지역 보정률, 실제 견적이 없는 중앙값/P25/P75.</p></div><div><strong>현재 실제 견적 표본</strong><p>${quoteSamples.length}건. 표본 통계 UI는 노출하지 않습니다.</p></div></div><a class="text-link" href="${BASE}/data/methodology/">산출 원칙 전체 보기</a></section>`;
write('index.html',layout({title:'인테리어 견적 검사·비교 | 견적검수실',desc:'인테리어 견적서를 표준 공종으로 옮겨 누락·별도비용·사양 차이를 확인하고 업체별 조건을 맞춰 비교합니다.',path:'/',schema:homeSchema},home));

const stateRadios=id=>`<div class="state-radios" role="radiogroup" aria-label="${id} 상태"><label><input type="radio" name="state-${id}" value="included" checked>기재</label><label><input type="radio" name="state-${id}" value="separate">별도</label><label><input type="radio" name="state-${id}" value="missing">미기재</label></div>`;
const qRows=coreItems.map(([id,name],i)=>`<section class="qrow" data-qrow="${id}"><div class="qrow-title"><span>${String(i+1).padStart(2,'0')}</span><strong>${name}</strong></div>${stateRadios(id)}<div class="q-fields"><label>금액 <input data-q-amount inputmode="numeric" type="number" min="0" placeholder="만원"></label><label>수량 <input data-q-qty inputmode="decimal"></label><label>단위 <input data-q-unit placeholder="㎡ · 개 · 식"></label><label>사양 <input data-q-spec placeholder="규격·범위"></label><label class="wide">메모 <input data-q-memo placeholder="견적서 표현 그대로"></label></div></section>`).join('');
toolPage({path:'/quote-check/',title:'인테리어 견적서 검사 | 누락·별도비용 확인',desc:'철거·폐기물·방수·욕실·주방·VAT 등 12개 표준 항목으로 받은 인테리어 견적의 누락과 별도비용, 사양 부족을 확인합니다.',h1:'인테리어 견적서 검사',lead:'총액보다 먼저 12개 항목의 포함·별도·미기재와 수량·사양을 확인합니다.',toolHtml:`<form data-quote-form><fieldset class="context-grid"><legend>견적 조건</legend><label>공급평수<input data-context="supply" inputmode="decimal" placeholder="32"></label><label>전용평수<input data-context="exclusive" inputmode="decimal"></label><label>건물유형<select data-context="building"><option>아파트</option><option>빌라</option><option>주택</option></select></label><label>지역<input data-context="region" placeholder="서울"></label><label>공사범위<select data-context="scope"><option>올수리</option><option>부분</option></select></label><label>욕실 수<input data-context="bathrooms" inputmode="numeric" placeholder="2"></label></fieldset><div class="wizard-head"><strong data-wizard-counter>1 / 12</strong><span data-wizard-label>철거</span></div><div class="quote-check-table">${qRows}</div><div class="wizard-actions"><button type="button" data-prev>이전</button><button type="button" data-next>다음</button></div><div class="tool-actions"><button type="button" data-save-quote>저장</button><button type="button" data-copy-report>결과 복사</button><button type="button" data-export-csv>CSV</button><button type="button" data-print>인쇄</button><button type="button" data-reset-quote>초기화</button></div></form><section class="quote-report" data-quote-report><h2>검수 결과</h2><div class="report-stats"><div><span>기재</span><strong data-stat-included>0</strong></div><div><span>별도</span><strong data-stat-separate>0</strong></div><div><span>미기재</span><strong data-stat-missing>0</strong></div><div><span>사양 확인</span><strong data-stat-unclear>0</strong></div></div><p>입력 금액 합계 <strong data-quote-total>0만원</strong></p><p class="matrix-conclusion warning" data-comparable>단순 총액 비교 불가</p><h3>업체에 확인할 질문</h3><div data-question-list></div></section>`,after:[`<section class="content-section"><h2>왜 12개 항목으로 나누나</h2><p>업체마다 “욕실공사 1식”, “철거 일체”, “현장경비”처럼 묶는 방식이 다릅니다. 같은 총액이라도 폐기물·방수·샷시·VAT가 빠져 있으면 실제 지급조건은 다릅니다. 먼저 표준 항목으로 옮겨야 비교가 시작됩니다.</p>${table(['항목','확인 이유'],coreItems.map(([id,n])=>[n,esc(itemBy(id)?.details.join(' · ')||'포함조건 확인')]),'견적 검사 12개 핵심 항목')}</section>`,`<section class="content-section"><h2>1식 표기의 함정</h2><p>“욕실공사 1식 850만원”은 금액은 있지만 방수 범위, 타일 규격, 폐기물, 배관 이동 여부를 알 수 없습니다.</p><a href="${BASE}/one-set/">1식 해체 도구</a></section>`],faqs:[['견적서에 없는 항목은 무조건 추가비인가요?','아닙니다. 다른 항목에 포함됐을 수 있으므로 포함인지 별도인지 확인해야 합니다.'],['VAT가 미기재면 어떻게 하나요?','표시 총액에 포함된 금액인지 별도인지 먼저 확인합니다.'],['폐기물 별도는 이상한 견적인가요?','별도 자체보다 추가금 산정 기준과 반출 조건이 명확한지가 중요합니다.'],['욕실 1식이면 비교가 불가능한가요?','세부 범위와 사양을 확인하기 전에는 다른 견적의 세분화 금액과 직접 비교하기 어렵습니다.']]});

const compareRows=coreItems.map(([id,n])=>`<section class="compare-row" data-compare-row="${id}"><h3>${n}<span data-diff-flag></span></h3><div class="vendor-grid">${['a','b','c'].map(v=>`<div class="vendor-cell"><strong>${v.toUpperCase()} 업체</strong><select data-vendor="${v}" data-state><option value="included">포함</option><option value="separate">별도</option><option value="missing">미기재</option></select><label>금액<input data-vendor="${v}" data-amount type="number" inputmode="numeric" min="0" placeholder="만원"></label></div>`).join('')}</div></section>`).join('');
toolPage({path:'/quote-compare/',title:'인테리어 견적 비교 | A/B/C 업체 조건 맞추기',desc:'업체 세 곳의 인테리어 견적을 같은 표준 공종으로 재배열하고 VAT·폐기물·샷시·현장관리비 등 포함조건 차이를 먼저 확인합니다.',h1:'인테리어 견적 A/B/C 비교',lead:'싸 보이는 견적을 고르는 도구가 아니라, 서로 다른 포함조건을 같은 기준으로 맞추는 비교표입니다.',toolHtml:`<div data-compare-table><div class="compare-top">${['a','b','c'].map(v=>`<div><span>${v.toUpperCase()} 업체 입력합계</span><strong data-total="${v}">0만원</strong></div>`).join('')}</div><div class="difference-filter"><label><input type="checkbox" data-diff-only> 조건이 다른 항목만 보기</label></div>${compareRows}<div class="notice" data-compare-summary></div><div class="tool-actions"><button data-save-compare type="button">비교 저장</button><button data-reset-compare type="button">초기화</button><button data-print type="button">인쇄</button></div></div>`,after:[`<section class="content-section"><h2>총액보다 먼저 맞출 조건</h2>${table(['조건','왜 맞춰야 하나'],[['VAT','포함/별도에 따라 표시 총액이 다릅니다.'],['폐기물','별도이면 반출·처리 추가금이 생길 수 있습니다.'],['샷시','포함 여부가 전체 공사 범위를 크게 바꿉니다.'],['현장관리비','정액·비율·포함항목이 업체마다 다릅니다.'],['1식','세부 공정과 수량·사양이 보이지 않으면 직접 비교가 어렵습니다.']],'업체 견적 조건 정렬')}</section>`],faqs:[['A업체 총액이 가장 낮으면 더 저렴한가요?','VAT·폐기물·샷시·현장관리비 조건이 같을 때에만 총액 차이를 해석할 수 있습니다.'],['미기재 항목은 0원으로 보면 되나요?','아닙니다. 포함인지 별도인지 모르는 상태이므로 0원으로 계산하면 안 됩니다.']]});

toolPage({path:'/calculator/',title:'인테리어 예산 설계 | 사용자 입력 단가 합산',desc:'시장평균을 만들지 않고 사용자가 공종별 단가와 수량을 직접 입력해 인테리어 예산 시나리오를 구성합니다.',h1:'인테리어 예산 설계',lead:'근거 없는 시장평균 대신 사용자가 입력한 수량·단가로 예산 시나리오를 합산합니다.',toolHtml:`<div class="budget-builder" data-budget-builder>${coreItems.filter(([id])=>id!=='vat').map(([id,n])=>`<section class="budget-row" data-budget-row="${id}"><strong>${n}</strong><label>수량<input data-qty inputmode="decimal" placeholder="1"></label><label>단위<input data-unit placeholder="식"></label><label>단가(만원)<input data-unit-price type="number" inputmode="numeric" min="0"></label><label>포함<select data-included><option value="yes">포함</option><option value="no">제외</option></select></label><span data-line-total>0만원</span></section>`).join('')}<section class="budget-summary"><label>VAT<select data-vat><option value="excluded">별도</option><option value="included">입력 단가에 포함</option><option value="add10">10% 추가 계산</option></select></label><strong>입력 시나리오 합계 <span data-budget-total>0만원</span></strong><p>시장평균이 아니라 사용자가 입력한 조건의 합계입니다.</p></section><div class="tool-actions"><button type="button" data-save-budget>저장</button><button type="button" data-reset-budget>초기화</button><button type="button" data-print>인쇄</button></div></div>`,after:[`<section class="content-section"><h2>금액을 직접 입력하는 이유</h2><p>현재 실제 견적 표본은 ${quoteSamples.length}건입니다. 출처 없는 평당 단가나 가상의 지역·연식 보정률을 시장 평균처럼 만들지 않습니다.</p></section>`],faqs:[['왜 자동으로 평당 가격을 넣어주지 않나요?','검증된 민간 표본이 없는데 자동 단가를 넣으면 가짜 정밀도가 생기기 때문입니다.'],['VAT 10% 추가는 시장 평균인가요?','아닙니다. 선택한 입력금액에 산술적으로 10%를 더하는 기능입니다.']]});

toolPage({path:'/checklist/',title:'인테리어 계약 전 체크리스트 | 12개 항목 저장·인쇄',desc:'철거·폐기물·방수·욕실·주방·전기·샷시·현장관리비·VAT 등 계약 전 확인할 12개 항목을 브라우저에 저장하고 인쇄합니다.',h1:'인테리어 계약 전 체크리스트',lead:'견적서 금액을 확정하기 전에 포함·별도·수량·사양이 적혀 있는지 확인합니다.',toolHtml:`<div class="checklist" data-checklist>${coreItems.map(([id,n],i)=>`<label><input type="checkbox" data-check-id="${id}"><span>${String(i+1).padStart(2,'0')}</span><strong>${n}</strong><em>${esc(itemBy(id)?.details.join(' · ')||'조건 확인')}</em></label>`).join('')}<div class="check-progress"><strong data-check-progress>0 / 12</strong><span>확인 완료</span></div><div class="tool-actions"><button type="button" data-save-check>저장</button><button type="button" data-reset-check>초기화</button><button type="button" data-print>인쇄</button></div></div>`,after:[`<section class="content-section"><h2>체크했다고 끝이 아닌 항목</h2><p>“포함” 표시만으로 충분하지 않은 공종이 있습니다. 욕실은 방수·타일·도기, 샷시는 창 개수·치수·유리, 전기는 회로·증설 범위를 함께 적어야 합니다.</p></section>`],faqs:[['체크리스트는 서버에 저장되나요?','아니요. 현재 프리뷰에서는 브라우저 localStorage만 사용합니다.']]});

toolPage({path:'/one-set/',title:'인테리어 견적 1식 해체 | 욕실·주방·샷시 세부항목',desc:'욕실공사 1식, 주방공사 1식, 샷시 1식처럼 묶인 견적을 세부 공정과 확인 질문으로 풀어봅니다.',h1:'견적서 1식 해체',lead:'“1식” 금액을 쪼개서 가격을 만드는 도구가 아니라, 비교 전에 빠진 수량·사양 질문을 만드는 도구입니다.',toolHtml:`<div class="one-set-tool" data-one-set><label>견적서 항목<select data-one-set-type><option value="bathroom">욕실공사 1식</option><option value="kitchen">주방공사 1식</option><option value="window">샷시 1식</option></select></label><label>표시 금액(만원)<input data-one-set-amount type="number" inputmode="numeric" min="0" placeholder="850"></label><div data-one-set-result></div></div>`,after:[`<section class="content-section"><h2>1식이 위험한 이유가 아니라, 비교정보가 부족한 이유</h2><p>1식은 일괄공사를 묶어 표현하는 방식입니다. 문제는 철거·폐기·방수·자재·수량이 보이지 않으면 다른 업체 견적과 같은 기준으로 맞출 수 없다는 점입니다.</p></section>`],faqs:[['1식 견적은 피해야 하나요?','무조건 피할 표현은 아닙니다. 포함 범위와 사양이 별첨이나 상세내역으로 확인되는지가 중요합니다.'],['1식 금액을 세부 금액으로 자동 배분할 수 있나요?','실제 근거가 없으면 임의 배분하지 않습니다.']]});

const sizeHubRows=Object.entries(sizes).map(([s,v])=>[`<a href="${BASE}/interior-cost/${s}-pyeong/">${s}평</a>`,esc(v.unique.join(' · '))]);
docPage({path:'/interior-cost/',title:'평수별 인테리어 비용 | 견적 조건 비교',desc:'24평·30평·32평·34평·40평 아파트 인테리어 견적을 평당 평균이 아니라 욕실·샷시·철거·VAT 등 조건 중심으로 비교합니다.',h1:'평수별 인테리어 비용',kicker:'비용 허브',answer:'평수는 출발점일 뿐입니다. 같은 평수라도 욕실 수, 샷시, 철거, 주방과 VAT·폐기물 조건을 맞춰야 견적을 비교할 수 있습니다.',sections:[`<section class="content-section"><h2>대표 평수</h2>${table(['평수','먼저 확인'],sizeHubRows,'평수별 견적 비교 출발점')}</section>`],faqs:[['평당 인테리어 비용만 보면 안 되나요?','평당 값은 빠른 비교용이지만 포함 공종과 자재·수량이 다르면 의미가 달라집니다.']],links:[['견적 검사','/quote-check/'],['견적 비교','/quote-compare/']]});
for(const [s,v] of Object.entries(sizes)){docPage({path:`/interior-cost/${s}-pyeong/`,title:`${s}평 아파트 인테리어 비용 | 공종·샷시 조건 비교`,desc:`${s}평 아파트 인테리어 견적에서 욕실·샷시·철거·주방·VAT·폐기물 조건을 맞추는 방법을 설명합니다.`,h1:`${s}평 아파트 인테리어 비용`,kicker:'평수별 견적',answer:v.answer,sections:[`<section class="content-section"><h2>${esc(v.question)}</h2><p>${esc(v.answer)}</p>${table(['변수','확인 내용'],v.unique.map(x=>[esc(x),'견적 A/B/C에서 같은 조건인지 확인']),'이 평수에서 먼저 맞출 조건')}</section>`,`<section class="content-section"><h2>총액을 비교하기 전에</h2>${table(['항목','확인'],[['VAT','포함 / 별도 / 미기재'],['폐기물','포함 / 별도'],['욕실','개수·철거·방수·타일 사양'],['샷시','전체·부분·제외 / 수량'],['주방','길이·상판·배관 이동']],'평수와 무관하게 확인할 공통 조건')}</section>`,`<section class="content-section"><h2>실제 표본 통계</h2><p>현재 조건을 표준화한 실제 견적 표본이 충분하지 않아 평균·중앙값·P25/P75는 표시하지 않습니다.</p></section>`],faqs:[[`${s}평이면 욕실 수를 어떻게 봐야 하나요?`,'실제 평면과 견적서에 적힌 욕실 개수를 기준으로 봅니다. 평수만으로 욕실 수를 가정하지 않습니다.'],['샷시 제외 견적은 어떻게 비교하나요?','비교 대상 견적에서도 샷시를 제외하거나 별도 항목으로 분리한 뒤 총액을 봅니다.'],['VAT가 빠져 있으면 어떻게 하나요?','포함/별도 여부를 확인하고 동일 기준으로 환산한 뒤 비교합니다.']],links:[['견적 검사','/quote-check/'],['A/B/C 비교','/quote-compare/'],['욕실 비용','/cost/bathroom/'],['샷시 조건','/cost/window/']]})}

docPage({path:'/cost/',title:'공사별 인테리어 비용 | 견적 항목 구조',desc:'욕실·주방·샷시·도배·바닥·철거·전기·목공 견적을 공종별 포함항목과 수량·사양 중심으로 확인합니다.',h1:'공사별 인테리어 비용',kicker:'공종 허브',answer:'공사별 페이지는 시장 평균 숫자를 복제하지 않고, 해당 공종의 견적 항목과 비교조건을 분해합니다.',sections:[`<section class="content-section"><h2>공종별 보기</h2>${table(['공종','먼저 확인'],Object.entries(works).map(([s,w])=>[`<a href="${BASE}/cost/${s}/">${esc(w.name)}</a>`,esc(w.answer)]),'공종별 견적 구조')}</section>`],links:[['견적 항목 사전','/quote-items/'],['견적 검사','/quote-check/']]});
for(const [slug,w] of Object.entries(works)){docPage({path:`/cost/${slug}/`,title:w.title,desc:w.answer,h1:`${w.name} 견적`,kicker:'공사별 견적',answer:w.answer,sections:[`<section class="content-section"><h2>${w.name} 견적서에서 확인할 항목</h2>${table(['세부 항목','확인 내용'],w.rows.map(r=>r.map(esc)),`${w.name} 견적 분해표`)}</section>`,`<section class="content-section"><h2>바로 비교하면 안 되는 경우</h2><p>한 업체는 상세공정과 수량이 적혀 있고 다른 업체는 1식만 적혀 있다면 금액 차이보다 조건 차이를 먼저 확인합니다. 미기재 항목을 0원으로 취급하지 않습니다.</p></section>`],faqs:[[`${w.name} 1식은 바로 비교할 수 있나요?`,'세부 범위·수량·사양이 확인되기 전에는 다른 견적의 세분화 금액과 직접 비교하기 어렵습니다.'],['별도 항목은 무조건 추가금인가요?','별도라고 적혀 있으면 추가 금액과 산정 기준을 확인해야 합니다.']],links:[['견적 검사','/quote-check/'],['A/B/C 비교','/quote-compare/'],['1식 해체','/one-set/']]})}

docPage({path:'/guides/',title:'인테리어 견적 가이드 | 누락·VAT·폐기물·1식',desc:'인테리어 견적서 보는 법, 누락항목, 폐기물·VAT·현장관리비, 욕실 1식, 샷시, 추가변경 등 계약 직전 질문을 정리합니다.',h1:'인테리어 견적 가이드',kicker:'가이드 허브',answer:'검색어를 늘리기 위한 글이 아니라 견적을 같은 기준으로 읽는 데 필요한 질문별 문서입니다.',sections:[`<section class="content-section"><h2>가이드 목록</h2><div class="guide-list">${guides.map(([s,t,a])=>`<a href="${BASE}/guides/${s}/"><strong>${esc(t)}</strong><p>${esc(a)}</p></a>`).join('')}</div></section>`],links:[['견적 검사','/quote-check/'],['견적 항목 사전','/quote-items/']]});
for(const [slug,title,answer] of guides){docPage({path:`/guides/${slug}/`,title:`${title} | 견적검수실`,desc:answer,h1:title,kicker:'견적 실무 가이드',answer,sections:[`<section class="content-section"><h2>견적서에서 이렇게 찾습니다</h2><p>${esc(answer)} 견적서에 표현이 없으면 0원이라고 보지 않고 포함·별도 여부를 확인합니다. 한 업체만 세분화돼 있다면 먼저 다른 업체에도 같은 질문을 합니다.</p></section>`,`<section class="content-section"><h2>예시 표기</h2>${table(['표기','해석'],[['욕실공사 1식 850만원','세부공정·사양 확인 필요'],['폐기물 별도','추가금과 산정 기준 확인'],['VAT 미기재','포함/별도 확인 후 총액 비교']],'가상 견적 표기 예시 — 실제 시장 통계가 아님')}</section>`],faqs:[[`${title}에서 가장 먼저 볼 것은?`,answer],['예시 금액을 시장 평균으로 봐도 되나요?','아니요. 예시 금액은 견적 구조를 설명하기 위한 예시이며 시장 통계가 아닙니다.']],links:[['견적 검사','/quote-check/'],['견적 비교','/quote-compare/'],['견적 항목 사전','/quote-items/']]})}

docPage({path:'/quote-items/',title:'인테리어 견적 항목 사전 | 공종·별칭·수량·사양',desc:'업체마다 다른 인테리어 견적 항목명을 표준 공종으로 옮기기 위한 별칭, 포함작업, 수량·사양 확인 기준을 정리합니다.',h1:'인테리어 견적 항목 사전',kicker:'데이터 자산',answer:'가격 사전이 아니라 견적서를 같은 구조로 옮기기 위한 표준 공종 사전입니다.',sections:[`<section class="content-section"><h2>표준 항목 ${itemDictionary.length}개</h2>${table(['표준명','다른 표현','확인할 세부','단위'],itemDictionary.map(x=>[esc(x.name),esc(x.aliases.join(' · ')),esc(x.details.join(' · ')),esc(x.units.join(' · '))]),'견적 항목 표준화 사전')}</section>`],links:[['1식 해체','/one-set/'],['견적 검사','/quote-check/']]});

function simplePage(pathname,title,desc,h1,body){docPage({path:pathname,title,desc,h1,kicker:'사이트 안내',answer:desc,sections:[`<section class="content-section">${body}</section>`]})}
simplePage('/about/','소개 | 견적검수실','인테리어 업체를 중개하지 않고 견적 항목과 조건을 표준화해 비교하는 소비자용 데이터·도구 서비스입니다.','견적검수실 소개',`<h2>하는 일</h2><p>견적서 항목을 표준 공종으로 옮기고 포함·별도·미기재, 수량·사양 차이를 확인할 도구와 해설을 제공합니다.</p><h2>하지 않는 일</h2><p>업체 중개, 시공계약, 법률·세무·하자 판정은 하지 않습니다.</p><h2>데이터 생성</h2><p>공공 원자료는 적용범위를 명시하고, 실제 사용자 견적은 향후 동의·익명화·검수 절차가 마련된 뒤 별도 표본으로 수집합니다. 현재 실제 견적 표본은 ${quoteSamples.length}건입니다.</p>`);
simplePage('/contact/','연락·오류 신고 | 견적검수실','데이터 출처, 견적 항목 분류, 오탈자와 기능 오류를 신고하는 안내 페이지입니다.','연락·오류 신고',`<h2>현재 프리뷰</h2><p>외부 검수 프리뷰 단계라 운영 이메일을 임의로 만들지 않습니다. 운영 도메인 공개 전 실제 수신 주소와 문의 양식을 연결합니다.</p><h2>정정에 필요한 정보</h2><p>문제가 있는 URL, 항목명, 현재 표시내용, 근거가 되는 공식 문서 또는 견적 표기를 함께 보내는 구조로 운영합니다.</p>`);
simplePage('/privacy/','개인정보처리방침 | 견적검수실','현재 도구 입력값의 브라우저 저장, 향후 로그·쿠키·광고 도입 시 고지 원칙을 설명합니다.','개인정보처리방침',`<h2>현재 저장</h2><p>견적 검사·비교·체크리스트 입력은 브라우저 localStorage에 저장되며 현재 서버로 전송하지 않습니다.</p><h2>파일 업로드</h2><p>현재 견적서 이미지·PDF 업로드를 제공하지 않습니다.</p><h2>운영판 광고·쿠키</h2><p>운영판에서 Google AdSense 등 광고 서비스를 도입할 경우 쿠키, 맞춤광고, 선택해제 방법과 관련 정책 링크를 실제 설정에 맞춰 고지합니다.</p>`);
simplePage('/terms/','이용약관 | 견적검수실','견적 검사·비교·예산 설계 결과의 이용 범위와 제한을 설명합니다.','이용약관',`<h2>결과의 성격</h2><p>표시 결과는 견적 조건을 정리하는 참고자료입니다. 실제 공사계약·현장실측·시공사 설명이 우선합니다.</p><h2>예시 데이터</h2><p>“예시”로 표시한 금액과 조건은 시장평균·실제 계약사례 통계가 아닙니다.</p>`);
simplePage('/disclaimer/','면책 | 견적검수실','견적·계약·세무·하자 관련 정보의 참고 범위와 한계를 설명합니다.','면책',`<h2>전문자문 아님</h2><p>이 사이트는 시공계약, 법률, 세무, 하자 판정에 관한 전문자문을 제공하지 않습니다.</p><h2>가격</h2><p>실제 견적은 현장 상태, 수량, 자재, 업체 조건에 따라 달라질 수 있으며 출처와 표본이 없는 시장평균은 표시하지 않습니다.</p>`);
simplePage('/editorial-policy/','편집·검수 기준 | 견적검수실','공공자료와 견적 예시, 표준 공종 사전, 가이드 문서를 작성·검수·수정하는 기준을 공개합니다.','편집·검수 기준',`<h2>작성 기준</h2><p>검색어를 위한 문장 복제보다 실제 견적 질문을 해결하는 표·예시·도구를 우선합니다.</p><h2>숫자 검수</h2><p>출처·기준일·조건이 없으면 평균·중앙값·P25/P75를 만들지 않습니다.</p><h2>수정</h2><p>산식·분류·출처가 바뀌면 변경이력에 기록합니다.</p>`);
simplePage('/corrections/','정정 정책 | 견적검수실','잘못된 출처, 분류, 계산, 문구를 수정하고 변경이력을 남기는 기준입니다.','정정 정책',`<h2>정정 대상</h2><p>원문 출처 오류, 공종 분류 오류, 계산식 오류, 오탈자와 오해를 부르는 문장을 수정합니다.</p><h2>기록</h2><p>데이터나 계산 기준에 영향을 주는 변경은 날짜와 변경 내용을 공개합니다.</p>`);

docPage({path:'/data/methodology/',title:'인테리어 견적 데이터 산출 기준 | 출처·표본·산식',desc:'공공 원자료, 표준 공종 정규화, 실제 익명 견적 표본, 숫자 표시 조건과 산식 버전을 공개합니다.',h1:'데이터 산출 기준',kicker:'방법론',answer:'공공공사 기준과 민간 아파트 계약가격을 구분하고, 실제 표본이 없으면 시장 통계를 만들지 않습니다.',sections:[`<section class="content-section"><h2>숫자 상태</h2>${table(['유형','표시','조건'],[['공공 원자료','공공자료','기관·자료명·기준일·적용범위'],['공식 원자료 환산','산식 추정','원출처·변환식·단위·버전'],['익명 사용자 견적','실제 견적 표본','익명화·조건 정규화·검수'],['충분한 표본 통계','표본 중앙값','N·기간·지역·P25/P75 계산 기준']],'숫자 표시 분류')}</section>`,`<section class="content-section"><h2>현재 상태</h2><p>실제 견적 표본은 ${quoteSamples.length}건입니다. 따라서 민간 시장 평균·중앙값·P25/P75 UI는 생성하지 않습니다.</p></section>`,`<section class="content-section"><h2>공공자료의 한계</h2><p>표준시장단가·표준품셈·건설업 임금은 공공 건설공사 원가와 작업량·노임 참고자료입니다. 일반 아파트 민간 턴키 가격을 직접 대체하지 않습니다.</p></section>`],links:[['데이터 출처','/data/sources/'],['변경이력','/data/changelog/'],['견적 항목 사전','/quote-items/']]});
docPage({path:'/data/sources/',title:'인테리어 비용 데이터 출처 | CODIL·건설임금',desc:'견적 데이터에 사용할 공공 원자료의 기관, 자료명, 게시일, 확인일, 적용범위와 적용불가범위를 공개합니다.',h1:'데이터 출처',kicker:'출처 레지스트리',answer:'출처 이름만 나열하지 않고 숫자와 연결할 수 있는 source_id와 적용범위를 기록합니다.',sections:[`<section class="content-section"><h2>출처 레코드</h2>${table(['source_id','기관·자료','게시·확인','적용','직접 적용하지 않는 범위'],publicSources.map(s=>[esc(s.source_id),`<a href="${esc(s.url)}" rel="noopener">${esc(s.agency)}<br>${esc(s.title)}</a>`,`${esc(s.published)}<br>확인 ${esc(s.checked)}`,esc(s.applies),esc(s.does_not_apply)]),'공공 원자료 출처')}</section>`],links:[['산출 기준','/data/methodology/'],['변경이력','/data/changelog/']]});
docPage({path:'/data/changelog/',title:'데이터·계산식 변경이력 | 견적검수실',desc:'견적 항목 분류, 도구 계산, 데이터 출처, 카피 변경 내용을 버전과 날짜로 공개합니다.',h1:'데이터·계산식 변경이력',kicker:'변경 로그',answer:'숫자와 분류가 바뀌면 왜 바뀌었는지 기록합니다.',sections:[`<section class="content-section"><h2>버전 기록</h2>${table(['버전','날짜','변경'],versions.map(v=>[esc(v.version),esc(v.date),esc(v.changes.join(' · '))]),'변경 이력')}</section>`],links:[['산출 기준','/data/methodology/'],['출처','/data/sources/']]});

write('search/index.html',layout({title:'사이트 검색 | 견적검수실',desc:'평수, 공사, 견적 항목, 도구와 가이드를 검색합니다.',path:'/search/'},`<section class="article-hero"><div class="article-shell">${crumb([['홈','/'],['검색','/search/']])}<h1>사이트 검색</h1><form class="search-page-form" data-search-form><label for="search-input">검색어</label><input id="search-input" data-search-input placeholder="욕실 · 32평 · VAT · 폐기물"><button>검색</button></form></div></section><section class="article-shell search-results" data-search-results></section>`));
write('404.html',`<!doctype html><html lang="ko"><head>${meta({title:'페이지를 찾을 수 없습니다 | 견적검수실',desc:'요청한 페이지를 찾을 수 없습니다.',path:'/404.html'})}</head><body>${header()}<main><section class="article-hero"><div class="article-shell"><h1>페이지를 찾을 수 없습니다</h1><p class="lead">주소가 바뀌었거나 현재 제공하지 않는 문서입니다.</p><a class="primary-link" href="${BASE}/">홈으로</a></div></section></main>${footer()}<script src="${asset('app-v5.js')}" defer></script></body></html>`);

const searchIndex=[];function walk(dir=''){for(const ent of fs.readdirSync(path.join(ROOT,dir),{withFileTypes:true})){const rel=path.join(dir,ent.name);if(ent.isDirectory())walk(rel);else if(ent.name==='index.html'&&!rel.startsWith('search/')){const html=fs.readFileSync(path.join(ROOT,rel),'utf8');const title=(html.match(/<title>(.*?)<\/title>/)||[])[1]||'';const desc=(html.match(/<meta name="description" content="([^"]*)"/)||[])[1]||'';const h1=(html.match(/<h1[^>]*>(.*?)<\/h1>/)||[])[1]?.replace(/<[^>]+>/g,'')||title;const url=rel==='index.html'?`${BASE}/`:`${BASE}/${dir.replaceAll('\\','/')}/`;searchIndex.push({title:h1,url,type:rel.includes('guides/')?'가이드':rel.includes('cost/')?'공사':rel.includes('interior-cost/')?'평수':rel.includes('quote-')||rel.includes('calculator')||rel.includes('checklist')||rel.includes('one-set')?'도구':'문서',description:desc,keywords:[title,h1],aliases:Object.keys(aliases).filter(k=>`${title} ${h1} ${desc}`.includes(aliases[k]))})}}}walk();
write('data/item-dictionary.json',JSON.stringify(itemDictionary,null,2));write('data/item-aliases.json',JSON.stringify(aliases,null,2));write('data/public-sources.json',JSON.stringify(publicSources,null,2));write('data/quote-samples.json',JSON.stringify(quoteSamples,null,2));write('data/methodology.json',JSON.stringify(methodology,null,2));write('data/versions.json',JSON.stringify(versions,null,2));write('data/latest.json',JSON.stringify({version:methodology.version,updated:methodology.updated,quote_sample_count:quoteSamples.length,item_count:itemDictionary.length},null,2));write('data/search-index.json',JSON.stringify(searchIndex,null,2));
const indexable=searchIndex.map(x=>`${SITE}${x.url.replace(BASE,'')}`);write('sitemap-production.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${indexable.map(u=>`<url><loc>${u}</loc><lastmod>${UPDATED}</lastmod></url>`).join('')}</urlset>`);write('robots-production.txt',`User-agent: *\nAllow: /\nSitemap: ${SITE}/sitemap.xml\n\nUser-agent: OAI-SearchBot\nAllow: /\n`);write('robots.txt',`User-agent: *\nDisallow: /\n# Preview only. Production robots template is robots-production.txt\n`);
const htmlFiles=[];function collect(dir=''){for(const ent of fs.readdirSync(path.join(ROOT,dir),{withFileTypes:true})){const rel=path.join(dir,ent.name);if(ent.isDirectory())collect(rel);else if(ent.name.endsWith('.html'))htmlFiles.push(rel.replaceAll('\\','/'))}}collect();
const report={build:BUILD,html_count:htmlFiles.length,quote_sample_count:quoteSamples.length,item_count:itemDictionary.length,v4_asset_references:[],h1_issues:[],meta_issues:[],internal_link_issues:[]};
for(const rel of htmlFiles){const html=fs.readFileSync(path.join(ROOT,rel),'utf8');if(/site-v4\.css|app-v4\.js/.test(html))report.v4_asset_references.push(rel);const h1=(html.match(/<h1\b/g)||[]).length;if(h1!==1)report.h1_issues.push({rel,h1});if(!/<title>.+<\/title>/.test(html)||!/<meta name="description"/.test(html)||!/<link rel="canonical"/.test(html))report.meta_issues.push(rel);for(const m of html.matchAll(/href="(\/pm-lab\/interior-cost-preview\/[^"#?]*)/g)){const href=m[1];const relative=href.replace(BASE,'').replace(/^\//,'');const target=path.join(ROOT,relative,href.endsWith('/')?'index.html':'');if(!fs.existsSync(target)&&!href.startsWith(`${BASE}/search/`))report.internal_link_issues.push({rel,href})}}
write('data/v5-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));